. = PutManaketeBodyIntro2 - 1;
.text.PutManaketeBodyIntro2Old : {*(.text.PutManaketeBodyIntro2Old)}
. = PutManaketeBodyIntro1 - 1;
.text.PutManaketeBodyIntro1Old : {*(.text.PutManaketeBodyIntro1Old)}
. = PutManaketeBodyStd - 1;
.text.PutManaketeBodyStdOld : {*(.text.PutManaketeBodyStdOld)}
. = PutManaketeTotalImg - 1;
.text.PutManaketeTotalImgOld : {*(.text.PutManaketeTotalImgOld)}
. = EkrDragonTmCpyExt - 1;
.text.EkrDragonTmCpyExtOld : {*(.text.EkrDragonTmCpyExtOld)}
