. = GetActiveMapSong - 1;
.text.GetActiveMapSongOld : {*(.text.GetActiveMapSongOld)}
. = BmMain_StartPhase - 1;
.text.BmMain_StartPhaseOld : {*(.text.BmMain_StartPhaseOld)}
. = BmMain_ResumePlayerPhase - 1;
.text.BmMain_ResumePlayerPhaseOld : {*(.text.BmMain_ResumePlayerPhaseOld)}
. = GetPlayerInitialCursorPosition - 1;
.text.GetPlayerInitialCursorPositionOld : {*(.text.GetPlayerInitialCursorPositionOld)}
