. = GetChapterInfo - 1;
.text.GetChapterInfoOld : {*(.text.GetChapterInfoOld)}
. = GetChapterMap - 1;
.text.GetChapterMapOld : {*(.text.GetChapterMapOld)}
. = GetChapterMapChanges - 1;
.text.GetChapterMapChangesOld : {*(.text.GetChapterMapChangesOld)}
. = GetChapterEventInfo - 1;
.text.GetChapterEventInfoOld : {*(.text.GetChapterEventInfoOld)}
. = GetChapterUnk_0802BBD0 - 1;
.text.GetChapterUnk_0802BBD0Old : {*(.text.GetChapterUnk_0802BBD0Old)}
