. = IsUnitMandatoryDeploy - 1;
.text.IsUnitMandatoryDeployOld : {*(.text.IsUnitMandatoryDeployOld)}
. = func_fe6_0807A59C - 1;
.text.func_fe6_0807A59COld : {*(.text.func_fe6_0807A59COld)}
. = PrepMenu_InitExt - 1;
.text.PrepMenu_InitExtOld : {*(.text.PrepMenu_InitExtOld)}
. = func_fe6_0807A67C - 1;
.text.func_fe6_0807A67COld : {*(.text.func_fe6_0807A67COld)}
. = InitPrepScreenMainMenu - 1;
.text.InitPrepScreenMainMenuOld : {*(.text.InitPrepScreenMainMenuOld)}
