. = func_fe6_0808A918 - 1;
.text.func_fe6_0808A918Old : {*(.text.func_fe6_0808A918Old)}
/* . = func_fe6_080898F0 - 1;
.text.func_fe6_080898F0Old : {*(.text.func_fe6_080898F0Old)} */
. = func_fe6_080898F0Ptr;
.rodata.func_fe6_080898F0PtrNew : {*(.rodata.func_fe6_080898F0PtrNew)}
. = func_fe6_08088870Ptr;
.rodata.func_fe6_08088870PtrNew : {*(.rodata.func_fe6_08088870PtrNew)}
. = AddSaveMenuOptions - 1;
.text.AddSaveMenuOptionsOld : {*(.text.AddSaveMenuOptionsOld)}
