#pragma once

// Generic enemies
#define JID_アバター JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_アバター剣 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_アバター槍 JID_SOLDIER // MVID_歩行 WID_槍
#define JID_アバター斧 JID_FIGHTER // MVID_歩行 WID_斧
#define JID_アバター赤魔 JID_MAGE // MVID_歩行 WID_赤魔
#define JID_アバター青魔 JID_MAGE // MVID_歩行 WID_青魔
#define JID_アバター緑魔 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ソードスチーム JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ランススチーム JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_アクススチーム JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ラウアバット JID_MANAKETE_F // MVID_飛行 WID_赤獣
#define JID_ブラーバット JID_MANAKETE_F // MVID_飛行 WID_青獣
#define JID_グルンバット JID_MANAKETE_F // MVID_飛行 WID_緑獣
#define JID_ソードドラゴン JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ランスドラゴン JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_アクスドラゴン JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_ラウアマムクート JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_ブラーマムクート JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_グルンマムクート JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_ボウペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_レッドペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_ブルーペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_グリーンペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_レッドボウ JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_ブルーボウ JID_ARCHER // MVID_歩行 WID_青弓
#define JID_グリーンボウ JID_ARCHER // MVID_歩行 WID_緑弓
#define JID_レッドシーフ JID_THIEF // MVID_歩行 WID_赤暗
#define JID_ブルーシーフ JID_THIEF // MVID_歩行 WID_青暗
#define JID_グリーンシーフ JID_THIEF // MVID_歩行 WID_緑暗
#define JID_ラウアファヴニル JID_MANAKETE_F // MVID_飛行 WID_赤竜
#define JID_ブラーファヴニル JID_MANAKETE_F // MVID_飛行 WID_青竜
#define JID_グルンファヴニル JID_MANAKETE_F // MVID_飛行 WID_緑竜
#define JID_ソードファイター JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ソードアーマー JID_ARMOR // MVID_重装 WID_剣
#define JID_ソードナイト JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ソードペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ランスファイター JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ランスアーマー JID_ARMOR // MVID_重装 WID_槍
#define JID_ランスナイト JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ランスペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_アクスファイター JID_FIGHTER // MVID_歩行 WID_斧
#define JID_アクスアーマー JID_ARMOR // MVID_重装 WID_斧
#define JID_アクスナイト JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_アクスペガサス JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_ボウファイター JID_ARCHER // MVID_歩行 WID_弓
#define JID_ボウナイト JID_NOMAD // MVID_騎馬 WID_弓
#define JID_シーフ JID_THIEF // MVID_歩行 WID_暗
#define JID_レッドマージ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_レッドナイト JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_ブルーマージ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ブルーナイト JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_グリーンマージ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_グリーンナイト JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_シスター JID_PRIEST // MVID_歩行 WID_杖
#define JID_ロッドナイト JID_TROUBADOUR // MVID_騎馬 WID_杖

// Hero enemies
#define JID_マルス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_オグマ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ナバール JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ロイ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_フィル JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_リン JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_クロム JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ルキナ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ロンクー JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_オリヴィエ JID_DANCER // MVID_歩行 WID_剣
#define JID_カムイ男 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_リョウマ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_カザハナ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ヒナタ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ラズワルド JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ルーナ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ドーガ JID_ARMOR // MVID_重装 WID_剣
#define JID_ゼフィール JID_ARMOR // MVID_重装 WID_剣
#define JID_カイン JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_エリウッド JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ソール JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_シーダ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_パオラ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ドニ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_オボロ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_アクア JID_DANCER // MVID_歩行 WID_槍
#define JID_ウェンディ JID_ARMOR // MVID_重装 WID_槍
#define JID_エルフィ JID_ARMOR // MVID_重装 WID_槍
#define JID_ジェイガン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_アベル JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_カミュ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ソワレ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ピエリ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_カチュア JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_エスト JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_シャニー JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_フロリーナ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ティアモ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ヒノカ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ツバキ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_バーツ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_バアトル JID_FIGHTER // MVID_歩行 WID_斧
#define JID_レイヴァン JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ホークアイ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ハロルド JID_FIGHTER // MVID_歩行 WID_斧
#define JID_シーマ JID_ARMOR // MVID_重装 WID_斧
#define JID_ヘクトル JID_ARMOR // MVID_重装 WID_斧
#define JID_フレデリク JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ギュンター JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ミネルバ JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_ミシェイル JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_ナーシェン JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_セルジュ JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_ベルカ JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_ゴードン JID_ARCHER // MVID_歩行 WID_弓
#define JID_ジョルジュ JID_ARCHER // MVID_歩行 WID_弓
#define JID_セツナ JID_ARCHER // MVID_歩行 WID_弓
#define JID_ゼロ JID_ARCHER // MVID_歩行 WID_弓
#define JID_ガイア JID_THIEF // MVID_歩行 WID_暗
#define JID_フェリシア JID_THIEF // MVID_歩行 WID_暗
#define JID_ジョーカー JID_THIEF // MVID_歩行 WID_暗
#define JID_サイゾウ JID_THIEF // MVID_歩行 WID_暗
#define JID_カゲロウ JID_THIEF // MVID_歩行 WID_暗
#define JID_リリーナ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ソフィーヤ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_サーリャ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ヘンリー JID_MAGE // MVID_歩行 WID_赤魔
#define JID_レオン JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_リンダ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ルフレ男 JID_MAGE // MVID_歩行 WID_青魔
#define JID_オーディン JID_MAGE // MVID_歩行 WID_青魔
#define JID_ウルスラ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_マリク JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ニノ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ルフレ女 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_セシリア JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_リフ JID_PRIEST // MVID_歩行 WID_杖
#define JID_マリア JID_PRIEST // MVID_歩行 WID_杖
#define JID_セーラ JID_PRIEST // MVID_歩行 WID_杖
#define JID_リズ JID_PRIEST // MVID_歩行 WID_杖
#define JID_サクラ JID_PRIEST // MVID_歩行 WID_杖
#define JID_アサマ JID_PRIEST // MVID_歩行 WID_杖
#define JID_クラリーネ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_エリーゼ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_チキ JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_チキ覚醒 JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_ノノ JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_カムイ女 JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_ファ JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_エイリーク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_エフラム JID_SOLDIER // MVID_歩行 WID_槍
#define JID_セリス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ユリア JID_MAGE // MVID_歩行 WID_緑魔
#define JID_サナキ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_クレイン JID_ARCHER // MVID_歩行 WID_弓
#define JID_ラインハルト JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_オルエン JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_エルトシャン JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ラケシス JID_PRIEST // MVID_歩行 WID_杖
#define JID_ルセア JID_PRIEST // MVID_歩行 WID_杖
#define JID_ジャファル JID_THIEF // MVID_歩行 WID_暗
#define JID_レベッカ JID_ARCHER // MVID_歩行 WID_弓
#define JID_カレル JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_プリシラ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_ニニアン JID_DANCER // MVID_歩行 WID_青竜
#define JID_春祭クロム JID_FIGHTER // MVID_歩行 WID_斧
#define JID_春祭マークス JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_春祭ルキナ JID_MAGE // MVID_歩行 WID_青魔
#define JID_春祭カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_アルム JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_エフィ JID_ARCHER // MVID_歩行 WID_弓
#define JID_クレア JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ルカ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_アイク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_セネリオ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ミスト JID_PRIEST // MVID_歩行 WID_杖
#define JID_ティアマト JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_セリカ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_メイ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ボーイ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ジェニー JID_PRIEST // MVID_歩行 WID_杖
#define JID_ロイド JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_花嫁シーダ JID_MAGE // MVID_歩行 WID_青魔
#define JID_花嫁リン JID_PRIEST // MVID_歩行 WID_杖
#define JID_花嫁ティアモ JID_ARCHER // MVID_歩行 WID_弓
#define JID_花嫁シャーロッテ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_仮面ルキナ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ルーク JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ロディ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_アテナ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_カタリナ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ローロー JID_FIGHTER // MVID_歩行 WID_斧
#define JID_クライネ JID_ARCHER // MVID_歩行 WID_弓
#define JID_水着ガイア JID_ARCHER // MVID_歩行 WID_弓
#define JID_水着フレデリク JID_THIEF // MVID_歩行 WID_暗
#define JID_水着ルフレ女 JID_SOLDIER // MVID_歩行 WID_槍
#define JID_水着チキ覚醒 JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ロビン JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_デューテ JID_MAGE // MVID_歩行 WID_青魔
#define JID_グレイ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_マチルダ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_クレーベ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_セーバー JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ソニア JID_MAGE // MVID_歩行 WID_緑魔
#define JID_レオ JID_ARCHER // MVID_歩行 WID_弓
#define JID_ベルクト JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_水着レオン JID_MAGE // MVID_歩行 WID_赤魔
#define JID_水着マークス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_水着カムイ女 JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_水着エリーゼ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ゼト JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ヒーニアス JID_ARCHER // MVID_歩行 WID_弓
#define JID_アメリア JID_ARMOR // MVID_重装 WID_斧
#define JID_ターナ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ヴァルター JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_総選挙アイク JID_FIGHTER // MVID_歩行 WID_斧
#define JID_総選挙ロイ JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_総選挙リン JID_NOMAD // MVID_騎馬 WID_弓
#define JID_総選挙ルキナ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_オスカー JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_エリンシア JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ネフェニー JID_SOLDIER // MVID_歩行 WID_槍
#define JID_漆黒の騎士 JID_ARMOR // MVID_重装 WID_剣
#define JID_舞踏祭アズール JID_DANCER // MVID_歩行 WID_緑魔
#define JID_舞踏祭シグレ JID_DANCER // MVID_歩行 WID_青魔
#define JID_舞踏祭オリヴィエ JID_DANCER // MVID_歩行 WID_暗
#define JID_舞踏祭黒アクア JID_DANCER // MVID_歩行 WID_斧
#define JID_シグルド JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_アイラ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ディアドラ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ティルテュ JID_MAGE // MVID_歩行 WID_青魔
#define JID_アーダン JID_ARMOR // MVID_重装 WID_剣
#define JID_アルヴィス JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ハロヘンリー JID_ARMOR // MVID_重装 WID_緑魔
#define JID_ハロノノ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_ハロジョーカー JID_ARMOR // MVID_重装 WID_弓
#define JID_ハロサクラ JID_THIEF // MVID_歩行 WID_暗
#define JID_ドルカス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ルーテ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ワユ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ヨシュア JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_オーシン JID_FIGHTER // MVID_歩行 WID_斧
#define JID_マリータ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_タニア JID_ARCHER // MVID_歩行 WID_弓
#define JID_エーヴェル JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ケンプフ JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_比翼マルス JID_ARMOR // MVID_重装 WID_弓
#define JID_冬祭ニノ JID_ARMOR // MVID_重装 WID_青魔
#define JID_冬祭若ゼフィール JID_ARMOR // MVID_重装 WID_剣
#define JID_冬祭ソティス JID_MANAKETE // MVID_重装 WID_緑竜
#define JID_冬祭ジャファル JID_ARMOR // MVID_重装 WID_緑暗
#define JID_伝承セリカ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_比翼アルフォンス JID_MAGE // MVID_歩行 WID_青魔
#define JID_年明レテ JID_MANAKETE_F // MVID_騎馬 WID_緑獣
#define JID_年明キヌ JID_MANAKETE_F // MVID_騎馬 WID_無獣
#define JID_年明アンナ JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_年明エイル JID_PEGASUSKNIGHT // MVID_飛行 WID_赤暗
#define JID_ラクチェ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_シャナン JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_セティ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_アルテナ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_トラバント JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_つばさ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_まもり JID_ARMOR // MVID_重装 WID_斧
#define JID_霧亜 JID_MAGE // MVID_歩行 WID_赤魔
#define JID_エレオノーラ JID_ARCHER // MVID_歩行 WID_弓
#define JID_樹 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_比翼アルム JID_FIGHTER // MVID_歩行 WID_斧
#define JID_愛の祭ルドルフ JID_ARMOR // MVID_重装 WID_槍
#define JID_愛の祭エフィ JID_ARMOR // MVID_重装 WID_弓
#define JID_愛の祭コンラート JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_愛の祭シルク JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_ニルス JID_DANCER // MVID_歩行 WID_青竜
#define JID_フィオーラ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_レイラ JID_THIEF // MVID_歩行 WID_暗
#define JID_ラス JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_ヒース JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_伝承クロム JID_ARCHER // MVID_歩行 WID_青弓
#define JID_フェルディナント JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_リシテア JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ベルナデッタ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_アネット JID_FIGHTER // MVID_歩行 WID_斧
#define JID_炎帝 JID_ARMOR // MVID_重装 WID_斧
#define JID_比翼イドゥン JID_MANAKETE // MVID_重装 WID_赤竜
#define JID_春祭エスト JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_春祭フィル JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_春祭ナーシェン JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_春祭バアトル JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_神階ブラミモンド JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_リンカ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_フォレオ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_リリス JID_MANAKETE_F // MVID_飛行 WID_青竜
#define JID_ミドリコ JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_マクベス JID_MAGE // MVID_歩行 WID_赤魔
#define JID_比翼パオラ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_幼少マリク JID_MAGE // MVID_歩行 WID_緑魔
#define JID_幼少シーダ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_幼少マルス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_幼少ミネルバ JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_伝承エーデルガルト JID_ARMOR // MVID_重装 WID_斧
#define JID_暴走アイク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_催眠ユリア JID_MAGE // MVID_歩行 WID_赤魔
#define JID_魔王リオン JID_MAGE // MVID_歩行 WID_緑魔
#define JID_暴走カムイ男 JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_暴走アシュナード JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_比翼ミカヤ JID_PEGASUSKNIGHT // MVID_飛行 WID_無魔
#define JID_花嫁オボロ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_花嫁ニケ JID_MANAKETE // MVID_歩行 WID_緑獣
#define JID_花婿ラフィエル JID_DANCER // MVID_歩行 WID_青獣
#define JID_花婿ヒナタ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_神階ミラ JID_MANAKETE // MVID_歩行 WID_無竜
#define JID_覚醒アンナ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ムスタファー JID_FIGHTER // MVID_歩行 WID_斧
#define JID_サイリ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_エメリナ JID_PRIEST // MVID_歩行 WID_杖
#define JID_ギャンレル JID_THIEF // MVID_歩行 WID_暗
#define JID_双界ワユ JID_NOMAD // MVID_騎馬 WID_暗
#define JID_水着セライナ JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_水着ルーテ JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_水着ヨシュア JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_水着キルロイ JID_PRIEST // MVID_歩行 WID_杖
#define JID_伝承セリス JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_比翼ベレス JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_水着ドロテア JID_DANCER // MVID_歩行 WID_暗
#define JID_水着イングリット JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_水着シルヴァン JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_水着ローレンツ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_クリス男 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_クリス女 JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ジュリアン JID_THIEF // MVID_歩行 WID_暗
#define JID_レナ JID_PRIEST // MVID_歩行 WID_杖
#define JID_エレミヤ JID_PRIEST // MVID_歩行 WID_杖
#define JID_双界ヴェロニカ JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_海賊ギース JID_SOLDIER // MVID_歩行 WID_槍
#define JID_海賊ブリギッド JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_海賊ティバーン JID_MANAKETE_F // MVID_飛行 WID_無獣
#define JID_海賊ダロス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_総選挙ディミトリ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_総選挙クロード JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_総選挙エーデル JID_ARMOR // MVID_重装 WID_斧
#define JID_総選挙リシテア JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ジョージ JID_ARCHER // MVID_歩行 WID_青弓
#define JID_伝承カムイ女 JID_MANAKETE // MVID_歩行 WID_無竜
#define JID_比翼シグルド JID_DANCER // MVID_騎馬 WID_赤魔
#define JID_舞踏キュアン JID_DANCER // MVID_飛行 WID_青弓
#define JID_舞踏エスリン JID_DANCER // MVID_飛行 WID_暗
#define JID_舞踏ラケシス JID_DANCER // MVID_飛行 WID_緑暗
#define JID_舞踏エルトシャン JID_DANCER // MVID_飛行 WID_槍
#define JID_ジル JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_イレース JID_MAGE // MVID_歩行 WID_青魔
#define JID_シノン JID_ARCHER // MVID_歩行 WID_弓
#define JID_ガトリー JID_ARMOR // MVID_重装 WID_槍
#define JID_プラハ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_双界チキ JID_MANAKETE_F // MVID_飛行 WID_青竜
#define JID_ハロチェイニー JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_ハロルフレ女 JID_MANAKETE_F // MVID_飛行 WID_緑竜
#define JID_ハロデギンハンザー JID_MANAKETE // MVID_重装 WID_赤竜
#define JID_ハロイナ JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_シャミア JID_ARCHER // MVID_歩行 WID_緑弓
#define JID_カトリーヌ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_セテス JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_フレン JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_ネメシス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_伝承ディミトリ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_比翼リン JID_PEGASUSKNIGHT // MVID_飛行 WID_暗
#define JID_忍者ツイハーク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_忍者レーヴァテイン JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_忍者ナバール JID_SOLDIER // MVID_歩行 WID_槍
#define JID_忍者カザハナ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ギネヴィア JID_MAGE // MVID_歩行 WID_青魔
#define JID_ミレディ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ディーク JID_FIGHTER // MVID_歩行 WID_斧
#define JID_マリナス JID_NOMAD // MVID_騎馬 WID_暗
#define JID_ゲイル JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_デュッセル JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_セライナ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_ナターシャ JID_PRIEST // MVID_歩行 WID_杖
#define JID_ノール JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ケセルダ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_双界オルティナ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_冬祭ベルナデッタ JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_冬祭ヒルダ JID_ARMOR // MVID_重装 WID_槍
#define JID_冬祭セフェラン JID_ARMOR // MVID_重装 WID_杖
#define JID_冬祭フェリクス JID_ARMOR // MVID_重装 WID_青弓
#define JID_伝承リリーナ JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_比翼ピアニー JID_DANCER // MVID_飛行 WID_緑魔
#define JID_年明プルメリア JID_DANCER // MVID_飛行 WID_弓
#define JID_年明ベロア JID_MANAKETE // MVID_歩行 WID_青獣
#define JID_年明ニシキ JID_MANAKETE_F // MVID_騎馬 WID_赤獣
#define JID_年明フランネル JID_MANAKETE // MVID_歩行 WID_緑獣
#define JID_サラ JID_PRIEST // MVID_歩行 WID_杖
#define JID_アスベル JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ロナン JID_ARCHER // MVID_歩行 WID_青弓
#define JID_ミランダ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ベルド JID_MAGE // MVID_歩行 WID_赤魔
#define JID_双界ドロテア JID_DANCER // MVID_飛行 WID_赤魔
#define JID_砂漠カタリナ JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_砂漠ラファエル JID_ARMOR // MVID_重装 WID_弓
#define JID_砂漠サーリャ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_砂漠クリス男 JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_神階セイロス JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_比翼リーヴ JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_愛の祭グスタフ JID_ARMOR // MVID_重装 WID_斧
#define JID_愛の祭アルフォンス JID_ARMOR // MVID_重装 WID_緑魔
#define JID_愛の祭ヴェロニカ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_マーニャ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_フュリー JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_アゼル JID_MAGE // MVID_歩行 WID_赤魔
#define JID_レックス JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ディートバ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_伝承クロード JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_ドゥドゥ_ JID_ARMOR // MVID_重装 WID_斧
#define JID_リンハルト JID_PRIEST // MVID_歩行 WID_杖
#define JID_イングリット JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_マリアンヌ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ソロン JID_MAGE // MVID_歩行 WID_赤魔
#define JID_双界ミルラ JID_MANAKETE_F // MVID_飛行 WID_無竜
#define JID_春祭ミネルバ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_春祭アズール JID_PEGASUSKNIGHT // MVID_飛行 WID_緑弓
#define JID_春祭セレナ JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_春祭サレフ JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ファリナ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ルイーズ JID_ARCHER // MVID_歩行 WID_弓
#define JID_パント JID_MAGE // MVID_歩行 WID_緑魔
#define JID_エルク JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ソーニャ JID_MAGE // MVID_歩行 WID_青魔
#define JID_比翼エイリーク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_幼少ターナ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_幼少リオン JID_MAGE // MVID_歩行 WID_青魔
#define JID_幼少ラーチェル JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_幼少ヒーニアス JID_ARCHER // MVID_歩行 WID_弓
#define JID_伝承シグルド JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_闇ディミトリ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_覇骸エーデルガルト JID_MANAKETE // MVID_重装 WID_無獣
#define JID_闇マーク男 JID_MAGE // MVID_歩行 WID_赤魔
#define JID_闇マーク女 JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_闇オルソン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_双界外伝カチュア JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_花嫁ユーノ JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_花嫁シャニー JID_PEGASUSKNIGHT // MVID_飛行 WID_赤弓
#define JID_立会人サウル JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_花婿ゼロット JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_神階アスタルテ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_外伝パオラ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_リュート JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ティータ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ジーク JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_フェルナン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_比翼ヒルダ JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_水着メルセデス JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_水着アッシュ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_水着カスパル JID_FIGHTER // MVID_歩行 WID_斧
#define JID_水着レオニー JID_NOMAD // MVID_騎馬 WID_弓
#define JID_伝承ベレト JID_MAGE // MVID_歩行 WID_緑魔
#define JID_双界シーダ JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_水着フロージ JID_MANAKETE_F // MVID_騎馬 WID_赤獣
#define JID_水着フレイヤ JID_MANAKETE_F // MVID_騎馬 WID_無獣
#define JID_水着オグマ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_水着ノルン JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ニフル JID_MANAKETE_F // MVID_騎馬 WID_青竜
#define JID_シャーロッテ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ニュクス JID_MAGE // MVID_歩行 WID_赤魔
#define JID_オロチ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ブノワ JID_ARMOR // MVID_重装 WID_槍
#define JID_シェンメイ JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_神階ウル JID_ARCHER // MVID_歩行 WID_青弓
#define JID_比翼ヒノカ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑弓
#define JID_海賊スルト JID_ARMOR // MVID_重装 WID_槍
#define JID_海賊ネサラ JID_MANAKETE_F // MVID_飛行 WID_赤獣
#define JID_海賊ビーゼ JID_MANAKETE_F // MVID_飛行 WID_無獣
#define JID_海賊リフィス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_総選挙門番 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_総選挙マルス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_総選挙マリアンヌ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_総選挙エイリーク JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ペレアス JID_MAGE // MVID_歩行 WID_赤魔
#define JID_伝承ミカヤ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_双界リーフ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_聖祭ユリア JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_聖祭ラクチェ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_聖祭レヴィン JID_MAGE // MVID_歩行 WID_青魔
#define JID_聖祭ナンナ JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_ムスペル JID_MANAKETE_F // MVID_騎馬 WID_赤竜
#define JID_ユーリス JID_THIEF // MVID_歩行 WID_暗
#define JID_コンスタンツェ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_ハピ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_バルタザール JID_FIGHTER // MVID_歩行 WID_斧
#define JID_アルファルド JID_MAGE // MVID_歩行 WID_赤魔
#define JID_比翼ソティス JID_MANAKETE_F // MVID_飛行 WID_青竜
#define JID_ハロルフレ男 JID_MANAKETE // MVID_重装 WID_無竜
#define JID_ハロレア JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_ハロクルトナーガ JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_ハロソフィーヤ JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_開花フィヨルム JID_ARMOR // MVID_重装 WID_斧
#define JID_ウルフ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_ロシェ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_マリス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ビラク JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ザガロ JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_伝承ファ JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_比翼カムイ女 JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_忍者イグレーヌ JID_PEGASUSKNIGHT // MVID_飛行 WID_暗
#define JID_忍者シノン JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_忍者カムイ男 JID_SOLDIER // MVID_歩行 WID_槍
#define JID_忍者シャミア JID_FIGHTER // MVID_歩行 WID_斧
#define JID_開花レーギャルン JID_NOMAD // MVID_騎馬 WID_弓
#define JID_フォルカ JID_THIEF // MVID_歩行 WID_赤暗
#define JID_マーシャ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ステラ JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_タニス JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ベウフォレス JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_トール JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_パリス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ミリエル JID_MAGE // MVID_歩行 WID_青魔
#define JID_フラヴィア JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_バジーリオ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_レンハ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_双界リシテア JID_TROUBADOUR // MVID_騎馬 WID_無魔
#define JID_冬祭ルピナス JID_DANCER // MVID_飛行 WID_青暗
#define JID_冬祭アスレイ JID_ARMOR // MVID_重装 WID_緑魔
#define JID_冬祭マヌエラ JID_ARMOR // MVID_重装 WID_剣
#define JID_冬祭イグナーツ JID_ARMOR // MVID_重装 WID_弓
#define JID_伝承ベレス JID_MAGE // MVID_歩行 WID_青魔
#define JID_比翼ダグ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑弓
#define JID_年明レギン JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_年明ファフニール JID_NOMAD // MVID_騎馬 WID_赤暗
#define JID_年明リィレ JID_MANAKETE_F // MVID_騎馬 WID_無獣
#define JID_年明キサ JID_MANAKETE // MVID_歩行 WID_赤獣
#define JID_開花ヨシュア JID_THIEF // MVID_歩行 WID_暗
#define JID_レナック JID_THIEF // MVID_歩行 WID_緑暗
#define JID_コーマ JID_THIEF // MVID_歩行 WID_青暗
#define JID_ネイミー JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_アーヴ JID_MAGE // MVID_歩行 WID_青魔
#define JID_双界アクア JID_DANCER // MVID_騎馬 WID_緑魔
#define JID_ハタリカアラ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ハタリニケ JID_MANAKETE // MVID_歩行 WID_赤獣
#define JID_ハタリチェイニー JID_PRIEST // MVID_歩行 WID_杖
#define JID_ハタリディーン JID_NOMAD // MVID_騎馬 WID_暗
#define JID_神階エリミーヌ JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_比翼クロム JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_愛の祭ルキナ JID_ARMOR // MVID_重装 WID_斧
#define JID_愛の祭ルフレ女 JID_ARMOR // MVID_重装 WID_無魔
#define JID_愛の祭ウード JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_愛の祭リズ JID_ARMOR // MVID_重装 WID_杖
#define JID_開花イドゥン JID_MANAKETE // MVID_重装 WID_青竜
#define JID_ヒュウ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ニイメ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_キャス JID_THIEF // MVID_歩行 WID_緑暗
#define JID_ゴンザレス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_伝承シーダ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_双界ソニア JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_春祭デューテ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_春祭ヘンリー JID_NOMAD // MVID_騎馬 WID_弓
#define JID_春祭マリア JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_春祭リュート JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_開花マリータ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_アウグスト JID_PRIEST // MVID_歩行 WID_杖
#define JID_ガルザス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_カリン JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_セイラム JID_MAGE // MVID_歩行 WID_赤魔
#define JID_伝承ナンナ JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_比翼アイク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_幼少セネリオ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_幼少イレース JID_MAGE // MVID_歩行 WID_緑魔
#define JID_幼少ワユ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_幼少ボーレ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_開花イシュタル JID_MAGE // MVID_歩行 WID_青魔
#define JID_ティニー JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_アーサー JID_MAGE // MVID_歩行 WID_緑魔
#define JID_スカサハ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_聖戦ヒルダ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_神階メディウス JID_MANAKETE // MVID_歩行 WID_無竜
#define JID_暴走レア JID_MANAKETE // MVID_重装 WID_無竜
#define JID_闇リリス JID_MANAKETE_F // MVID_飛行 WID_赤竜
#define JID_催眠ニニアン JID_DANCER // MVID_歩行 WID_青竜
#define JID_闇ムワリム JID_MANAKETE // MVID_歩行 WID_青獣
#define JID_双界ロイ JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_花嫁リリーナ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_花嫁セシリア JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_花嫁ソフィーヤ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_花嫁ララム JID_DANCER // MVID_飛行 WID_槍
#define JID_伝承ミルラ JID_MANAKETE_F // MVID_飛行 WID_青竜
#define JID_開花フロリーナ JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_セイン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ケント JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_ギィ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_リムステラ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_双界エーデルガルト JID_ARMOR // MVID_重装 WID_剣
#define JID_水着ディミトリ JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_水着クロード JID_PEGASUSKNIGHT // MVID_飛行 WID_青暗
#define JID_水着ミカヤ JID_TROUBADOUR // MVID_騎馬 WID_無魔
#define JID_水着エリンシア JID_PEGASUSKNIGHT // MVID_飛行 WID_青弓
#define JID_伝承マークス JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_比翼トール JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_水着ニフル JID_MANAKETE_F // MVID_騎馬 WID_無竜
#define JID_水着エイリーク JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_水着リオン JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_水着ゼト JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_ユーミル JID_MANAKETE_F // MVID_騎馬 WID_緑竜
#define JID_開花セリカ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_外伝エスト JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_外伝カムイ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_アトラス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_盗賊頭 JID_FIGHTER // MVID_歩行 WID_斧
#define JID_比翼エポニーヌ JID_NOMAD // MVID_騎馬 WID_暗
#define JID_怪盗キャス JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_怪盗レイラ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_怪盗サザ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑暗
#define JID_怪盗リカード JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_総選挙クロム JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_総選挙セリス JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_総選挙覚醒チキ JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_総選挙ベレス JID_PEGASUSKNIGHT // MVID_飛行 WID_無魔
#define JID_ジェラルト JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_伝承ディアドラ JID_MAGE // MVID_歩行 WID_青魔
#define JID_双界ターナ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑暗
#define JID_炎部族リン JID_SOLDIER // MVID_歩行 WID_槍
#define JID_炎部族リンカ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_炎部族ムスペル JID_MANAKETE_F // MVID_騎馬 WID_無竜
#define JID_炎部族モゥディ JID_MANAKETE // MVID_歩行 WID_緑獣
#define JID_開花ヒルダ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_リーヴ2 JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_シェズ男 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_シェズ女 JID_FIGHTER // MVID_歩行 WID_斧
#define JID_モニカ JID_MAGE // MVID_歩行 WID_青魔
#define JID_ホルスト JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_伝承ニニアン JID_DANCER // MVID_騎馬 WID_緑竜
#define JID_比翼ドーマ JID_MANAKETE // MVID_重装 WID_赤竜
#define JID_ハロカムイ女 JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_ハロナーガ JID_MANAKETE_F // MVID_飛行 WID_無竜
#define JID_ハロカムイ男 JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_ハロニルス JID_DANCER // MVID_歩行 WID_緑竜
#define JID_開花エイル JID_NOMAD // MVID_騎馬 WID_緑暗
#define JID_魔器ルフレ女 JID_MANAKETE // MVID_重装 WID_無竜
#define JID_グレゴ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_リヒト JID_MAGE // MVID_歩行 WID_緑魔
#define JID_フィレイン JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_セルバンテス JID_ARMOR // MVID_重装 WID_槍
#define JID_神階ラルヴァ JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_比翼レーギャルン JID_PEGASUSKNIGHT // MVID_飛行 WID_青弓
#define JID_忍者カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_忍者セルジュ JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_忍者ヒース JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_忍者ハール JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_開花チキ JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_魔器ガングレト JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ニーナ JID_PRIEST // MVID_歩行 WID_杖
#define JID_ハーディン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_エリス JID_PRIEST // MVID_歩行 WID_杖
#define JID_マチス JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ヴェロニカ2 JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_ジークベルト JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_シノノメ JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ソレイユ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_シャラ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_冬祭クロム JID_ARMOR // MVID_重装 WID_斧
#define JID_冬祭ルフレ男 JID_ARMOR // MVID_重装 WID_槍
#define JID_冬祭サーリャ JID_ARMOR // MVID_重装 WID_赤魔
#define JID_冬祭リズ JID_ARMOR // MVID_重装 WID_斧
#define JID_年明けカムイ男 JID_ARCHER // MVID_歩行 WID_弓
#define JID_年明けタクミ JID_THIEF // MVID_歩行 WID_暗
#define JID_年明けカミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_年明けアクア JID_DANCER // MVID_飛行 WID_斧
#define JID_ミカヤ JID_MAGE // MVID_歩行 WID_青魔
#define JID_サザ JID_THIEF // MVID_歩行 WID_暗
#define JID_ゼルギウス JID_ARMOR // MVID_重装 WID_剣
#define JID_オリヴァー JID_MAGE // MVID_歩行 WID_青魔
#define JID_エイリーク2 JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_ミルラ JID_MANAKETE_F // MVID_飛行 WID_緑竜
#define JID_ラーチェル JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_マリカ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_リオン JID_MAGE // MVID_歩行 WID_赤魔
#define JID_伝承アイク JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_愛の祭ロイ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_愛の祭リリーナ JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_愛の祭ヘクトル JID_ARMOR // MVID_重装 WID_斧
#define JID_愛の祭リン JID_ARMOR // MVID_重装 WID_青魔
#define JID_愛の祭エリウッド JID_ARMOR // MVID_重装 WID_槍
#define JID_眷属タクミ JID_ARCHER // MVID_歩行 WID_弓
#define JID_魔女セリカ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_邪竜ルフレ男 JID_MANAKETE // MVID_重装 WID_緑竜
#define JID_暗黒ハーディン JID_ARMOR // MVID_重装 WID_槍
#define JID_伝承エフラム JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_クロム2 JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_マーク男 JID_MAGE // MVID_歩行 WID_赤魔
#define JID_マーク女 JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_ジェローム JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_春祭アルフォンス JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_春祭シャロン JID_MAGE // MVID_歩行 WID_緑魔
#define JID_春祭カチュア JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_春祭カゲロウ JID_PEGASUSKNIGHT // MVID_飛行 WID_暗
#define JID_伝承ルフレ女 JID_MANAKETE_F // MVID_飛行 WID_無竜
#define JID_ラインハルト2 JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_オルエン2 JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_リーフ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ナンナ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_フィン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_サイアス JID_MAGE // MVID_歩行 WID_青魔
#define JID_ヒノカ2 JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_シグレ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_カンナ女 JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_カンナ男 JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_スズカゼ JID_THIEF // MVID_歩行 WID_暗
#define JID_伝承リン JID_ARCHER // MVID_歩行 WID_緑弓
#define JID_アレス JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_イシュタル JID_MAGE // MVID_歩行 WID_青魔
#define JID_リーン JID_DANCER // MVID_歩行 WID_剣
#define JID_ユリウス JID_MAGE // MVID_歩行 WID_赤魔
#define JID_花婿マルス JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_花嫁サナキ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_花嫁サーリャ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_花嫁ニニアン JID_DANCER // MVID_飛行 WID_青魔
#define JID_伝承リョウマ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ニノ2 JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_カアラ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ラガルト JID_THIEF // MVID_歩行 WID_暗
#define JID_カナス JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ライナス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_水着ノワール JID_ARCHER // MVID_歩行 WID_弓
#define JID_水着ティアモ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_水着ターナ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_水着ヒーニアス JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_伝承ヘクトル JID_ARMOR // MVID_重装 WID_斧
#define JID_水着タクミ JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_水着カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_水着チキ JID_MANAKETE_F // MVID_飛行 WID_赤竜
#define JID_水着リンダ JID_NOMAD // MVID_騎馬 WID_暗
#define JID_オリヴィエ2 JID_DANCER // MVID_飛行 WID_剣
#define JID_スミア JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_マリアベル JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_リベラ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ヴァルハルト JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_伝承ルキナ JID_ARCHER // MVID_歩行 WID_青弓
#define JID_夏祭マークス JID_DANCER // MVID_歩行 WID_暗
#define JID_夏祭リョウマ JID_DANCER // MVID_歩行 WID_青暗
#define JID_夏祭エリンシア JID_DANCER // MVID_歩行 WID_緑暗
#define JID_夏祭ミカヤ JID_DANCER // MVID_歩行 WID_赤魔
#define JID_総選挙セリカ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_総選挙ヘクトル JID_ARMOR // MVID_重装 WID_槍
#define JID_総選挙エフラム JID_ARMOR // MVID_重装 WID_斧
#define JID_総選挙ヴェロニカ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_伝承マルス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ジャムカ JID_ARCHER // MVID_歩行 WID_弓
#define JID_シルヴィア JID_DANCER // MVID_歩行 WID_剣
#define JID_キュアン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_レヴィン JID_MAGE // MVID_歩行 WID_緑魔
#define JID_エスリン JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_エポニーヌ JID_ARCHER // MVID_歩行 WID_弓
#define JID_フローラ JID_THIEF // MVID_歩行 WID_赤暗
#define JID_オフェリア JID_MAGE // MVID_歩行 WID_青魔
#define JID_サイラス JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ガロン JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_伝承チキ JID_MANAKETE // MVID_重装 WID_青竜
#define JID_ハロカゲロウ JID_ARMOR // MVID_重装 WID_緑暗
#define JID_ハロゼロ JID_ARMOR // MVID_重装 WID_青弓
#define JID_ハロミルラ JID_MANAKETE // MVID_重装 WID_赤竜
#define JID_ハロワユ JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_ハロドルカス JID_ARMOR // MVID_重装 WID_斧
#define JID_ウード JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_クリフ JID_MAGE // MVID_歩行 WID_青魔
#define JID_インバース JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_伝承エイリーク JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_夢カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_夢カムイ男 JID_MANAKETE // MVID_歩行 WID_青竜
#define JID_夢カムイ女 JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_夢ミコト JID_PRIEST // MVID_歩行 WID_杖
#define JID_幼少アクア JID_DANCER // MVID_歩行 WID_緑魔
#define JID_ガーネフ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_冬祭エイリーク JID_ARMOR // MVID_重装 WID_杖
#define JID_冬祭エフラム JID_ARMOR // MVID_重装 WID_槍
#define JID_冬祭ファ JID_MANAKETE // MVID_重装 WID_緑竜
#define JID_冬祭セシリア JID_ARMOR // MVID_重装 WID_暗
#define JID_伝承アクア JID_DANCER // MVID_飛行 WID_青魔
#define JID_年明フィヨルム JID_PEGASUSKNIGHT // MVID_飛行 WID_緑弓
#define JID_年明スリーズ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_年明レーヴァテイン JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_年明フリーズ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_年明レーギャルン JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ティバーン JID_MANAKETE_F // MVID_飛行 WID_赤獣
#define JID_リュシオン JID_DANCER // MVID_飛行 WID_緑獣
#define JID_リアーネ JID_DANCER // MVID_飛行 WID_無獣
#define JID_ニケ JID_MANAKETE // MVID_歩行 WID_青獣
#define JID_ネサラ JID_MANAKETE_F // MVID_飛行 WID_青獣
#define JID_温泉サクラ JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_温泉エリーゼ JID_NOMAD // MVID_騎馬 WID_赤暗
#define JID_温泉ヒノカ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑暗
#define JID_温泉リョウマ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_温泉カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_暗
#define JID_神階ドーマ JID_MANAKETE // MVID_重装 WID_無竜
#define JID_愛の祭アイク JID_ARMOR // MVID_重装 WID_剣
#define JID_愛の祭グレイル JID_ARMOR // MVID_重装 WID_斧
#define JID_愛の祭セネリオ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_愛の祭ミスト JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_愛の祭ティアマト JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_フランネル JID_MANAKETE // MVID_歩行 WID_赤獣
#define JID_ベロア JID_MANAKETE // MVID_歩行 WID_無獣
#define JID_ニシキ JID_MANAKETE_F // MVID_騎馬 WID_緑獣
#define JID_キヌ JID_MANAKETE_F // MVID_騎馬 WID_青獣
#define JID_ベルベット JID_MANAKETE_F // MVID_騎馬 WID_青獣
#define JID_伝承ロイ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_イドゥン JID_MANAKETE // MVID_重装 WID_赤竜
#define JID_ルゥ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_スー JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_ティト JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_ルトガー JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_春祭パオラ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤暗
#define JID_春祭マリカ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_春祭ブルーノ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_春祭ヴェロニカ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_春祭ロキ JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_神階ユンヌ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_ライ JID_MANAKETE_F // MVID_騎馬 WID_緑獣
#define JID_レテ JID_MANAKETE_F // MVID_騎馬 WID_赤獣
#define JID_モゥディ JID_MANAKETE // MVID_歩行 WID_青獣
#define JID_カイネギス JID_MANAKETE // MVID_重装 WID_無獣
#define JID_ハール JID_PEGASUSKNIGHT // MVID_飛行 WID_斧
#define JID_行楽ジェニー JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_行楽ルカ JID_ARMOR // MVID_重装 WID_槍
#define JID_行楽フェリシア JID_ARMOR // MVID_重装 WID_斧
#define JID_行楽フローラ JID_ARMOR // MVID_重装 WID_赤暗
#define JID_行楽レオン JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_伝承アルム JID_ARCHER // MVID_歩行 WID_弓
#define JID_催眠チキ JID_MANAKETE // MVID_重装 WID_無竜
#define JID_魔剣マリータ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_闇ベルクト JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_暴走カムイ女 JID_MANAKETE // MVID_歩行 WID_無竜
#define JID_催眠デューテ JID_MAGE // MVID_歩行 WID_青魔
#define JID_花嫁フィヨルム JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_花嫁シグルーン JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_花嫁タニス JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_花婿パント JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_花嫁ルイーズ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_神階ナーガ JID_MANAKETE_F // MVID_飛行 WID_青竜
#define JID_ンン JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_ブレディ JID_PRIEST // MVID_歩行 WID_杖
#define JID_シャンブレー JID_MANAKETE_F // MVID_騎馬 WID_緑獣
#define JID_デジェル JID_ARMOR // MVID_重装 WID_槍
#define JID_シンシア JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_水着レーギャルン JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_水着レーヴァテイン JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_水着ヘルビンディ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_水着スリーズ JID_NOMAD // MVID_騎馬 WID_暗
#define JID_水着ユルグ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_伝承エリウッド JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_水着リリーナ JID_NOMAD // MVID_騎馬 WID_赤暗
#define JID_水着ウォルト JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_水着リン JID_PEGASUSKNIGHT // MVID_飛行 WID_青弓
#define JID_水着ウルスラ JID_NOMAD // MVID_騎馬 WID_暗
#define JID_水着フィオーラ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_エーデルガルト JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ディミトリ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_クロード JID_NOMAD // MVID_騎馬 WID_弓
#define JID_ベレス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ベレト JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_クロニエ JID_THIEF // MVID_歩行 WID_暗
#define JID_神階ソティス JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_ヒューベルト JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ペトラ JID_PEGASUSKNIGHT // MVID_飛行 WID_青暗
#define JID_メルセデス JID_PRIEST // MVID_歩行 WID_杖
#define JID_ヒルダ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_死神騎士 JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_総選挙アルム JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_総選挙エリウッド JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_総選挙ミカヤ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_総選挙カミラ JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_シグルーン JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_伝承ユリア JID_MAGE // MVID_歩行 WID_青魔
#define JID_舞踏ラインハルト JID_DANCER // MVID_飛行 WID_緑魔
#define JID_舞踏イシュタル JID_DANCER // MVID_飛行 WID_赤魔
#define JID_舞踏ベルクト JID_DANCER // MVID_歩行 WID_槍
#define JID_舞踏ネフェニー JID_DANCER // MVID_歩行 WID_弓
#define JID_舞踏リネア JID_DANCER // MVID_歩行 WID_青魔
#define JID_シリウス JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ナギ JID_MANAKETE // MVID_重装 WID_緑竜
#define JID_フィーナ JID_DANCER // MVID_歩行 WID_剣
#define JID_ノルン JID_ARCHER // MVID_歩行 WID_弓
#define JID_バヌトゥ JID_MANAKETE // MVID_歩行 WID_赤竜
#define JID_アストリア JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_比翼ヘクトル JID_ARMOR // MVID_重装 WID_剣
#define JID_ハロラーチェル JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_ハロドズラ JID_ARMOR // MVID_重装 WID_暗
#define JID_ハロイレース JID_ARMOR // MVID_重装 WID_青魔
#define JID_ハロヨファ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_外伝カチュア JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_フォルス JID_ARMOR // MVID_重装 WID_槍
#define JID_パイソン JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_シルク JID_PRIEST // MVID_歩行 WID_杖
#define JID_バルボ JID_ARMOR // MVID_重装 WID_槍
#define JID_コンラート JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_伝承リーフ JID_NOMAD // MVID_騎馬 WID_弓
#define JID_比翼エフラム JID_SOLDIER // MVID_歩行 WID_槍
#define JID_ジスト JID_FIGHTER // MVID_歩行 WID_斧
#define JID_ユアン JID_MAGE // MVID_歩行 WID_赤魔
#define JID_テティス JID_DANCER // MVID_歩行 WID_暗
#define JID_ロス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_クーガー JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_エキドナ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_パーシバル JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ララム JID_DANCER // MVID_歩行 WID_暗
#define JID_イグレーヌ JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_チャド JID_THIEF // MVID_歩行 WID_暗
#define JID_ブルーニャ JID_MAGE // MVID_歩行 WID_青魔
#define JID_神階オルティナ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ヴィオール JID_ARCHER // MVID_歩行 WID_弓
#define JID_マシュー JID_THIEF // MVID_歩行 WID_暗
#define JID_レイ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_タクミ JID_ARCHER // MVID_歩行 WID_弓
#define JID_魔器オフェリア JID_MAGE // MVID_歩行 WID_赤魔
#define JID_ディーア JID_PRIEST // MVID_歩行 WID_杖
#define JID_マトイ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_キサラギ JID_ARCHER // MVID_歩行 WID_弓
#define JID_ガンズ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_双界ティアモ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_冬祭ドロテア JID_DANCER // MVID_騎馬 WID_赤魔
#define JID_冬祭アネット JID_ARMOR // MVID_重装 WID_弓
#define JID_冬祭漆黒の騎士 JID_ARMOR // MVID_重装 WID_斧
#define JID_冬祭ブルーノ JID_ARMOR // MVID_重装 WID_緑魔
#define JID_伝承シェズ女 JID_THIEF // MVID_歩行 WID_青暗
#define JID_比翼アスク JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_年明アシュ JID_MANAKETE // MVID_歩行 WID_青獣
#define JID_年明エルム JID_MANAKETE_F // MVID_飛行 WID_緑獣
#define JID_年明ベルベット JID_MANAKETE_F // MVID_騎馬 WID_赤獣
#define JID_年明シャンブレー JID_MANAKETE_F // MVID_騎馬 WID_青獣
#define JID_双界リンダ JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_カダインウルスラ JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_カダインニノ JID_MAGE // MVID_歩行 WID_赤魔
#define JID_カダインベレト JID_MAGE // MVID_歩行 WID_青魔
#define JID_カダインセネリオ JID_MAGE // MVID_歩行 WID_青魔
#define JID_魔器アルフレッド JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_リュール女 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_セリーヌ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_クロエ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_エーティエ JID_ARCHER // MVID_歩行 WID_弓
#define JID_ルミエル JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_神階フォデス JID_MANAKETE // MVID_重装 WID_無獣
#define JID_神階ガトー JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_比翼エリーゼ JID_TROUBADOUR // MVID_騎馬 WID_杖
#define JID_愛の祭タクミ JID_ARMOR // MVID_重装 WID_青魔
#define JID_愛の祭レオン JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_愛の祭カザハナ JID_ARMOR // MVID_重装 WID_剣
#define JID_愛の祭エルフィ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_開花エリンシア JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_ジョフレ JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_ルキノ JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ユリシーズ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ルドベック JID_ARMOR // MVID_重装 WID_斧
#define JID_伝承ルフレ男 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_双界カアラ JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_春祭スカビオサ JID_DANCER // MVID_飛行 WID_無魔
#define JID_春祭ベルナデッタ JID_NOMAD // MVID_騎馬 WID_青弓
#define JID_春祭アッシュ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤暗
#define JID_春祭ミシェイル JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_魔器ターナ JID_PEGASUSKNIGHT // MVID_飛行 WID_弓
#define JID_ギリアム JID_ARMOR // MVID_重装 WID_槍
#define JID_ヴァネッサ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_シレーネ JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_ヴィガルド JID_ARMOR // MVID_重装 WID_槍
#define JID_伝承ユーリス JID_THIEF // MVID_歩行 WID_赤暗
#define JID_比翼軍師マーク JID_MAGE // MVID_歩行 WID_青魔
#define JID_幼少エリウッド JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_幼少ヘクトル JID_ARMOR // MVID_重装 WID_斧
#define JID_幼少レベッカ JID_ARCHER // MVID_歩行 WID_弓
#define JID_幼少ルセア JID_PRIEST // MVID_歩行 WID_杖
#define JID_魔器イングリット JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_フェリクス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_シルヴァン JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_レア JID_MANAKETE // MVID_歩行 WID_無竜
#define JID_コルネリア JID_PRIEST // MVID_歩行 WID_杖
#define JID_魔器闇クロム JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_闇ベレス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_闇マリア JID_PRIEST // MVID_歩行 WID_杖
#define JID_闇ハイドラ JID_MANAKETE // MVID_重装 WID_青竜
#define JID_闇ライナス JID_FIGHTER // MVID_歩行 WID_斧
#define JID_双界チキ覚醒 JID_MANAKETE // MVID_重装 WID_無竜
#define JID_花嫁アンナ覚醒 JID_NOMAD // MVID_騎馬 WID_緑弓
#define JID_花嫁サイリ JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_花嫁フラヴィア JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_花婿ルフレ男 JID_TROUBADOUR // MVID_騎馬 WID_赤魔
#define JID_伝承ヒノカ JID_PEGASUSKNIGHT // MVID_飛行 WID_赤弓
#define JID_開花フィル JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_サウル JID_PRIEST // MVID_歩行 WID_杖
#define JID_ドロシー JID_ARCHER // MVID_歩行 WID_弓
#define JID_ノア JID_CAVALIER // MVID_騎馬 WID_槍
#define JID_マードック JID_ARMOR // MVID_重装 WID_斧
#define JID_比翼シャミア JID_NOMAD // MVID_騎馬 WID_青弓
#define JID_水着シェズ女 JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_水着ラーチェル JID_PEGASUSKNIGHT // MVID_飛行 WID_杖
#define JID_水着エフラム JID_CAVALIER // MVID_騎馬 WID_斧
#define JID_水着シェズ男 JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_伝承ギネヴィア JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_比翼ユーミル JID_SHAMAN // MVID_歩行 WID_無魔
#define JID_水着フィヨルム JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_水着アイビー JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_水着サーリャ JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_水着ドニ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_魔器アイト JID_MANAKETE_F // MVID_騎馬 WID_青獣
#define JID_魔器スタルーク JID_ARCHER // MVID_歩行 WID_弓
#define JID_ディアマンド JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ラピス JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_シトリニカ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_リュール男 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_セピア JID_PEGASUSKNIGHT // MVID_飛行 WID_赤魔
#define JID_双界アイラ JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_お茶会リシテア JID_PEGASUSKNIGHT // MVID_飛行 WID_無魔
#define JID_お茶会フェルディ JID_PEGASUSKNIGHT // MVID_飛行 WID_緑魔
#define JID_お茶会シグルド JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_お茶会ティルテュ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_総選挙ルフレ男 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_総選挙セネリオ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_総選挙グルヴェイグ JID_PEGASUSKNIGHT // MVID_飛行 WID_青魔
#define JID_総選挙カムイ女 JID_MANAKETE // MVID_重装 WID_無竜
#define JID_ツィリル JID_ARCHER // MVID_歩行 WID_赤弓
#define JID_伝承リュール女 JID_MANAKETE // MVID_歩行 WID_緑竜
#define JID_比翼カゲロウ JID_NOMAD // MVID_騎馬 WID_暗
#define JID_風部族ダグ JID_CAVALIER // MVID_騎馬 WID_剣
#define JID_風部族カチュア JID_PEGASUSKNIGHT // MVID_飛行 WID_青弓
#define JID_風部族クロード JID_PEGASUSKNIGHT // MVID_飛行 WID_緑暗
#define JID_風部族フウガ JID_FIGHTER // MVID_歩行 WID_斧
#define JID_魔器プルメリア JID_DANCER // MVID_飛行 WID_青魔
#define JID_開花セティ JID_MAGE // MVID_歩行 WID_緑魔
#define JID_フィー JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_パティ JID_THIEF // MVID_歩行 WID_暗
#define JID_ファバル JID_ARCHER // MVID_歩行 WID_青弓
#define JID_アリオーン JID_PEGASUSKNIGHT // MVID_飛行 WID_槍
#define JID_伝承エリンシア JID_PEGASUSKNIGHT // MVID_飛行 WID_剣
#define JID_フード無印 JID_MYRMIDON // MVID_歩行 WID_剣
#define JID_ファフニール2 JID_MANAKETE // MVID_重装 WID_無竜
#define JID_ヴェロニカ洗脳 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_レティシア洗脳 JID_TROUBADOUR // MVID_騎馬 WID_緑魔
#define JID_ブルーノ洗脳 JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_ヴェロニカ洗脳2 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ブルーノ素顔 JID_TROUBADOUR // MVID_騎馬 WID_青魔
#define JID_ヘイズ敵0 JID_MAGE // MVID_歩行 WID_緑魔
#define JID_ヘイズ敵 JID_MAGE // MVID_歩行 WID_緑魔
