#pragma once

#define EID_ENEMY_GENERIC (HERO_NUM + 1)

#define EID_ENEMY_HERO_1 (EID_ENEMY_GENERIC + 1)
#define EID_ENEMY_HERO_2 (EID_ENEMY_GENERIC + 2)
#define EID_ENEMY_HERO_3 (EID_ENEMY_GENERIC + 3)
#define EID_ENEMY_HERO_4 (EID_ENEMY_GENERIC + 4)
#define EID_ENEMY_HERO_5 (EID_ENEMY_GENERIC + 5)
#define EID_ENEMY_HERO_6 (EID_ENEMY_GENERIC + 6)
#define EID_ENEMY_HERO_7 (EID_ENEMY_GENERIC + 7)

#define JID_ENEMY_GENERIC JID_FIGHTER

#define MEID_ENEMY_GENERIC 3789
#define MEID_ENEMY_HERO_1 (MEID_ENEMY_GENERIC + 1)
#define MEID_H_ENEMY_HERO_1 (MEID_ENEMY_GENERIC + 2)
#define MEID_ENEMY_HERO_2 (MEID_ENEMY_GENERIC + 3)
#define MEID_H_ENEMY_HERO_2 (MEID_ENEMY_GENERIC + 4)
#define MEID_ENEMY_HERO_3 (MEID_ENEMY_GENERIC + 5)
#define MEID_H_ENEMY_HERO_3 (MEID_ENEMY_GENERIC + 6)
#define MEID_ENEMY_HERO_4 (MEID_ENEMY_GENERIC + 7)
#define MEID_H_ENEMY_HERO_4 (MEID_ENEMY_GENERIC + 8)
#define MEID_ENEMY_HERO_5 (MEID_ENEMY_GENERIC + 9)
#define MEID_H_ENEMY_HERO_5 (MEID_ENEMY_GENERIC + 10)
#define MEID_ENEMY_HERO_6 (MEID_ENEMY_GENERIC + 11)
#define MEID_H_ENEMY_HERO_6 (MEID_ENEMY_GENERIC + 12)
#define MEID_ENEMY_HERO_7 (MEID_ENEMY_GENERIC + 13)
#define MEID_H_ENEMY_HERO_7 (MEID_ENEMY_GENERIC + 14)

extern const u16 ChapterEnemyHeroNames[][14];

#define FID_ENEMY_HERO_1 (FID_LAST + 1)
#define FID_ENEMY_HERO_2 (FID_LAST + 2)
#define FID_ENEMY_HERO_3 (FID_LAST + 3)
#define FID_ENEMY_HERO_4 (FID_LAST + 4)
#define FID_ENEMY_HERO_5 (FID_LAST + 5)
#define FID_ENEMY_HERO_6 (FID_LAST + 6)
#define FID_ENEMY_HERO_7 (FID_LAST + 7)

extern const u16 ChapterEnemyHeroFaces[][7];
