#pragma once

#include "constants/jids.h"

#include "jobs.h"

#define JID_アルフォンス JID_ROY
#define JID_シャロン JID_SOLDIER
#define JID_アンナ JID_FIGHTER
#define JID_ヴェロニカ JID_MAGE_F
#define JID_レギン JID_CAVALIER
#define JID_ブルーノ JID_TROUBADOUR
#define JID_神階ピアニー JID_PEGASUSKNIGHT
#define JID_フィヨルム JID_SOLDIER
#define JID_神階エイル JID_PEGASUSKNIGHT
#define JID_レティシア JID_TROUBADOUR
#define JID_オッテル JID_CAVALIER
#define JID_ファフニール JID_CAVALIER
#define JID_フレイヤ JID_MANAKETE_F
#define JID_セイズ JID_TROUBADOUR
#define JID_スルト JID_ARMOR
#define JID_アシュ JID_MANAKETE
#define JID_神階アスク JID_MANAKETE
#define JID_リーヴ JID_MERCENARY
#define JID_レーギャルン JID_WYVERNRIDER_F
#define JID_ダグ JID_FIGHTER
#define JID_エイトリ JID_MAGE
#define JID_レーヴァテイン JID_MYRMIDON_F
#define JID_ヘル JID_WYVERNRIDER_F
#define JID_エンブラ JID_MANAKETE_F
#define JID_グスタフ JID_CAVALIER
#define JID_ユルグ JID_THIEF_F
#define JID_ロキ JID_CLERIC
#define JID_ノート JID_SOLDIER
#define JID_スカビオサ JID_PEGASUSKNIGHT
#define JID_エルム JID_MANAKETE_F
#define JID_ヘルビンディ JID_BRIGAND
#define JID_フロージ JID_MANAKETE_F
#define JID_神階ルピナス JID_PEGASUSKNIGHT
#define JID_フリーズ JID_CAVALIER
#define JID_プルメリア JID_PEGASUSKNIGHT
#define JID_スラシル JID_MAGE_F
#define JID_グルヴェイグ JID_TROUBADOUR
#define JID_ネルトゥス JID_MANAKETE_F
#define JID_マークス JID_CAVALIER
#define JID_スリーズ JID_TROUBADOUR
#define JID_フード JID_PRIEST
#define JID_愛の祭ヘンリエッテ JID_SHAMAN_F
#define JID_クワシル JID_TROUBADOUR
#define JID_神階ヘイズ JID_MAGE_F

#define JID_アルフォンス_PROMOTED JID_ROY_PROMOTED
#define JID_シャロン_PROMOTED JID_HALBERDIER
#define JID_アンナ_PROMOTED JID_WARRIOR
#define JID_ヴェロニカ_PROMOTED JID_SAGE_F
#define JID_レギン_PROMOTED JID_PALADIN
#define JID_ブルーノ_PROMOTED JID_VALKYRIE
#define JID_神階ピアニー_PROMOTED JID_FALCONKNIGHT
#define JID_フィヨルム_PROMOTED JID_HALBERDIER
#define JID_神階エイル_PROMOTED JID_FALCONKNIGHT
#define JID_レティシア_PROMOTED JID_VALKYRIE
#define JID_オッテル_PROMOTED JID_PALADIN
#define JID_ファフニール_PROMOTED JID_PALADIN
#define JID_フレイヤ_PROMOTED JID_フレイヤ
#define JID_セイズ_PROMOTED JID_VALKYRIE
#define JID_スルト_PROMOTED JID_GENERAL
#define JID_アシュ_PROMOTED JID_アシュ
#define JID_神階アスク_PROMOTED JID_神階アスク
#define JID_リーヴ_PROMOTED JID_HERO
#define JID_レーギャルン_PROMOTED JID_WYVERNLORD_F
#define JID_ダグ_PROMOTED JID_WARRIOR
#define JID_エイトリ_PROMOTED JID_SAGE
#define JID_レーヴァテイン_PROMOTED JID_SWORDMASTER_F
#define JID_ヘル_PROMOTED JID_WYVERNLORD_F
#define JID_エンブラ_PROMOTED JID_エンブラ
#define JID_グスタフ_PROMOTED JID_PALADIN
#define JID_ユルグ_PROMOTED JID_RIGHTEOUS_THIEF_F
#define JID_ロキ_PROMOTED JID_BISHOP_F
#define JID_ノート_PROMOTED JID_HALBERDIER
#define JID_スカビオサ_PROMOTED JID_FALCONKNIGHT
#define JID_エルム_PROMOTED JID_エルム
#define JID_ヘルビンディ_PROMOTED JID_BERSERKER
#define JID_フロージ_PROMOTED JID_フロージ
#define JID_神階ルピナス_PROMOTED JID_FALCONKNIGHT
#define JID_フリーズ_PROMOTED JID_PALADIN
#define JID_プルメリア_PROMOTED JID_FALCONKNIGHT
#define JID_スラシル_PROMOTED JID_SAGE_F
#define JID_グルヴェイグ_PROMOTED JID_VALKYRIE
#define JID_ネルトゥス_PROMOTED JID_ネルトゥス
#define JID_マークス_PROMOTED JID_PALADIN
#define JID_スリーズ_PROMOTED JID_VALKYRIE
#define JID_フード_PROMOTED JID_SAGE
#define JID_愛の祭ヘンリエッテ_PROMOTED JID_DRUID_F
#define JID_クワシル_PROMOTED JID_VALKYRIE
#define JID_神階ヘイズ_PROMOTED JID_SAGE_F
