#pragma once

#define HERO_NUM 44

#define PID_アルフォンス 1
#define PID_シャロン 2
#define PID_アンナ 3
#define EID_ヴェロニカ 4
#define PID_レギン 5
#define EID_ブルーノ 6
#define PID_神階ピアニー 7
#define PID_セイズ 8
#define PID_フィヨルム 9
#define PID_神階エイル 10
#define EID_レティシア 11
#define EID_オッテル 12
#define EID_ファフニール 13
#define EID_フレイヤ 14
#define EID_スルト 15
#define PID_アシュ 16
#define PID_神階アスク 17
#define EID_リーヴ 18
#define EID_レーギャルン 19
#define EID_ダグ 20
#define EID_エイトリ 21
#define EID_レーヴァテイン 22
#define EID_ヘル 23
#define EID_エンブラ 24
#define EID_ネルトゥス 25
#define EID_グスタフ 26
#define PID_ユルグ 27
#define PID_愛の祭ヘンリエッテ 28
#define EID_ロキ 29
#define EID_ノート 30
#define EID_スカビオサ 31
#define EID_エルム 32
#define EID_ヘルビンディ 33
#define EID_フロージ 34
#define PID_神階ルピナス 35
#define EID_グルヴェイグ 36
#define PID_フリーズ 37
#define EID_プルメリア 38
#define EID_クワシル 39
#define PID_神階ヘイズ 40
#define EID_スラシル 41
#define PID_マークス 42
#define PID_スリーズ 43
#define EID_フード 44
