#pragma once

#define HERO_NUM 43

#define PID_アルフォンス 1
#define PID_シャロン 2
#define PID_アンナ 3
#define EID_ヴェロニカ 4
#define PID_レギン 5
#define EID_ブルーノ 6
#define PID_神階ピアニー 7
#define PID_フィヨルム 8
#define PID_神階エイル 9
#define EID_レティシア 10
#define EID_オッテル 11
#define EID_ファフニール 12
#define EID_フレイヤ 13
#define EID_スルト 14
#define PID_アシュ 15
#define PID_神階アスク 16
#define EID_リーヴ 17
#define EID_レーギャルン 18
#define EID_ダグ 19
#define EID_エイトリ 20
#define EID_レーヴァテイン 21
#define EID_ヘル 22
#define EID_エンブラ 23
#define PID_セイズ 24
#define EID_グスタフ 25
#define PID_ユルグ 26
#define EID_ロキ 27
#define EID_ノート 28
#define EID_スカビオサ 29
#define EID_エルム 30
#define EID_ヘルビンディ 31
#define EID_フロージ 32
#define PID_神階ルピナス 33
#define EID_ヴェロニカ洗脳 34
#define PID_フリーズ 35
#define EID_プルメリア 36
#define EID_スラシル 37
#define EID_ネルトゥス 38
#define EID_グルヴェイグ 39
#define PID_マークス 40
#define EID_レティシア洗脳 41
#define PID_スリーズ 42
#define EID_フード 43
