// This file is generated by make_texts.py
// Text type: TextType.MUSIC

[MID_MUSIC_NAME_BGM_AMB_USERNAME] = {
    [LANGUAGE_JAPANESE] = "ユーザー名を入力",
    [LANGUAGE_ENGLISH] = "Enter Username",
    [LANGUAGE_CHINESE] = "输入用户名",
},

[MID_MUSIC_NAME_BGM_BOSS12] = {
    [LANGUAGE_JAPANESE] = "ボス戦１２",
    [LANGUAGE_ENGLISH] = "Boss Battle 12",
    [LANGUAGE_CHINESE] = "Boss战12",
},

[MID_MUSIC_NAME_BGM_EVENT_HAPPY_01] = {
    [LANGUAGE_JAPANESE] = "フェアリィワルツ",
    [LANGUAGE_ENGLISH] = "Fairy Waltz",
    [LANGUAGE_CHINESE] = "仙女华尔兹",
},

[MID_MUSIC_NAME_BGM_EVENT_PLAIN_01] = {
    [LANGUAGE_JAPANESE] = "ヴァイスブレイヴ",
    [LANGUAGE_ENGLISH] = "Order of Heroes",
    [LANGUAGE_CHINESE] = "纯白义勇队",
},

[MID_MUSIC_NAME_BGM_EVENT_PLAIN_02] = {
    [LANGUAGE_JAPANESE] = "ヴィクトリィ",
    [LANGUAGE_ENGLISH] = "Victory",
    [LANGUAGE_CHINESE] = "胜利",
},

[MID_MUSIC_NAME_BGM_EVENT_PLAIN_03] = {
    [LANGUAGE_JAPANESE] = "キャリィオーバー",
    [LANGUAGE_ENGLISH] = "Carry Over",
    [LANGUAGE_CHINESE] = "结转",
},

[MID_MUSIC_NAME_BGM_EVENT_PLAIN_04] = {
    [LANGUAGE_JAPANESE] = "平穏４",
    [LANGUAGE_ENGLISH] = "Plain 4",
    [LANGUAGE_CHINESE] = "平静4",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_01] = {
    [LANGUAGE_JAPANESE] = "インヴァージョン",
    [LANGUAGE_ENGLISH] = "Invasion",
    [LANGUAGE_CHINESE] = "入侵",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_02] = {
    [LANGUAGE_JAPANESE] = "ヴェロニカ",
    [LANGUAGE_ENGLISH] = "Veronica",
    [LANGUAGE_CHINESE] = "维洛妮卡",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_03] = {
    [LANGUAGE_JAPANESE] = "ソリタリィ",
    [LANGUAGE_ENGLISH] = "Solitary",
    [LANGUAGE_CHINESE] = "孤独",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_04] = {
    [LANGUAGE_JAPANESE] = "アナザーメナス",
    [LANGUAGE_ENGLISH] = "Another Menace",
    [LANGUAGE_CHINESE] = "另一个威胁",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_05] = {
    [LANGUAGE_JAPANESE] = "ルーミングデス",
    [LANGUAGE_ENGLISH] = "Looming Death",
    [LANGUAGE_CHINESE] = "迫在眉睫的死亡",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_06] = {
    [LANGUAGE_JAPANESE] = "サクリファイス",
    [LANGUAGE_ENGLISH] = "Sacrifice",
    [LANGUAGE_CHINESE] = "牺牲",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_06B] = {
    [LANGUAGE_JAPANESE] = "ペインフルアフェクション",
    [LANGUAGE_ENGLISH] = "Painful Affection",
    [LANGUAGE_CHINESE] = "痛苦的感情",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_07_2] = {
    [LANGUAGE_JAPANESE] = "サスピシャス",
    [LANGUAGE_ENGLISH] = "Suspicious",
    [LANGUAGE_CHINESE] = "多疑",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_08] = {
    [LANGUAGE_JAPANESE] = "クィーンズナイトメア",
    [LANGUAGE_ENGLISH] = "Queen's Nightmare",
    [LANGUAGE_CHINESE] = "女王的噩梦",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_09] = {
    [LANGUAGE_JAPANESE] = "リトルスキミング",
    [LANGUAGE_ENGLISH] = "Little Skimming",
    [LANGUAGE_CHINESE] = "稍微浏览",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_10] = {
    [LANGUAGE_JAPANESE] = "フォルスラヴ",
    [LANGUAGE_ENGLISH] = "False Love",
    [LANGUAGE_CHINESE] = "假爱",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_11] = {
    [LANGUAGE_JAPANESE] = "バットコンダクター",
    [LANGUAGE_ENGLISH] = "Bat Conductor",
    [LANGUAGE_CHINESE] = "蝙蝠指挥",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_12] = {
    [LANGUAGE_JAPANESE] = "緊張１２",
    [LANGUAGE_ENGLISH] = "Serious 12",
    [LANGUAGE_CHINESE] = "紧张12",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_01] = {
    [LANGUAGE_JAPANESE] = "ウィンドオブアスク",
    [LANGUAGE_ENGLISH] = "Winds of Askr",
    [LANGUAGE_CHINESE] = "亚斯克的风",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_02] = {
    [LANGUAGE_JAPANESE] = "グランドオブアスク",
    [LANGUAGE_ENGLISH] = "The Grandeur of Askr",
    [LANGUAGE_CHINESE] = "雄伟的亚斯克",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_03] = {
    [LANGUAGE_JAPANESE] = "ラストフェイズ",
    [LANGUAGE_ENGLISH] = "Last Phase",
    [LANGUAGE_CHINESE] = "末世",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_04] = {
    [LANGUAGE_JAPANESE] = "リターントゥニフル",
    [LANGUAGE_ENGLISH] = "Return To Nifl",
    [LANGUAGE_CHINESE] = "回到尼福尔",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_05] = {
    [LANGUAGE_JAPANESE] = "トラジディオブアスク",
    [LANGUAGE_ENGLISH] = "Tragedy of Askr",
    [LANGUAGE_CHINESE] = "亚斯克的悲剧",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_10] = {
    [LANGUAGE_JAPANESE] = "勇敢１０",
    [LANGUAGE_ENGLISH] = "Brave 10",
    [LANGUAGE_CHINESE] = "英勇10",
},

[MID_MUSIC_NAME_BGM_MAP_FE03_01] = {
    [LANGUAGE_JAPANESE] = "この旗の下に",
    [LANGUAGE_ENGLISH] = "Under This Banner",
    [LANGUAGE_CHINESE] = "在此旗帜下",
},

[MID_MUSIC_NAME_BGM_MAP_FE03_02] = {
    [LANGUAGE_JAPANESE] = "栄光は永遠に",
    [LANGUAGE_ENGLISH] = "Valor Everlasting",
    [LANGUAGE_CHINESE] = "荣耀永存",
},

[MID_MUSIC_NAME_BGM_MAP_FE03_06] = {
    [LANGUAGE_JAPANESE] = "竜の祭壇",
    [LANGUAGE_ENGLISH] = "The Dragon's Table",
    [LANGUAGE_CHINESE] = "龙之祭坛",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_03] = {
    [LANGUAGE_JAPANESE] = "第9章（誰がために）",
    [LANGUAGE_ENGLISH] = "Chapter 9 For Whose Sake",
    [LANGUAGE_CHINESE] = "第九章（为谁而战）",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_05] = {
    [LANGUAGE_JAPANESE] = "第3章(獅子王エルトシャン)",
    [LANGUAGE_ENGLISH] = "Chapter 3 Eldigan, the Lionheart",
    [LANGUAGE_CHINESE] = "第3章(狮子王艾尔多尚)",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_06] = {
    [LANGUAGE_JAPANESE] = "第2章（アグストリアの動乱）",
    [LANGUAGE_ENGLISH] = "Chapter 2 Disturbance in Augustria",
    [LANGUAGE_CHINESE] = "第二章（阿古斯多利亚的动乱）",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_09] = {
    [LANGUAGE_JAPANESE] = "第6章（光をつぐもの）",
    [LANGUAGE_ENGLISH] = "Chapter 6: Inheritors of Light",
    [LANGUAGE_CHINESE] = "第六章（光之继承者）",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_11] = {
    [LANGUAGE_JAPANESE] = "第4章（空を舞う）",
    [LANGUAGE_ENGLISH] = "Chapter 4 Dance in the Skies",
    [LANGUAGE_CHINESE] = "第4章（飞舞于空中）",
},

[MID_MUSIC_NAME_BGM_MAP_FE05_01] = {
    [LANGUAGE_JAPANESE] = "リーフ軍、勝利を求めて　ベース",
    [LANGUAGE_ENGLISH] = "Leif's Army, In Search of Victory - Base",
    [LANGUAGE_CHINESE] = "里弗军，寻求胜利 基调",
},

[MID_MUSIC_NAME_BGM_MAP_FE05_03] = {
    [LANGUAGE_JAPANESE] = "リーフ軍,勝利を求めて 索敵",
    [LANGUAGE_ENGLISH] = "Leif's Army, In Search of Victory - Scout for Enemies",
    [LANGUAGE_CHINESE] = "里弗军，寻求胜利 索敌",
},

[MID_MUSIC_NAME_BGM_MAP_FE05_04] = {
    [LANGUAGE_JAPANESE] = "リーフ軍,勝利を求めて 進撃A",
    [LANGUAGE_ENGLISH] = "Leif's Army in Search of Victory - Advance A",
    [LANGUAGE_CHINESE] = "里弗军，寻求胜利 进击A",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_01] = {
    [LANGUAGE_JAPANESE] = "大切なもの",
    [LANGUAGE_ENGLISH] = "Precious Things",
    [LANGUAGE_CHINESE] = "重要的事物",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_08] = {
    [LANGUAGE_JAPANESE] = "はるかなる旅路",
    [LANGUAGE_ENGLISH] = "Distant Travels",
    [LANGUAGE_CHINESE] = "遥远的旅程",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_09] = {
    [LANGUAGE_JAPANESE] = "人竜戦役のきずあと（烈火Ｖｅｒ）",
    [LANGUAGE_ENGLISH] = "Scars of the Scouring",
    [LANGUAGE_CHINESE] = "人龙战役的伤痕（烈火版）",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_12] = {
    [LANGUAGE_JAPANESE] = "課せられた運命とともに",
    [LANGUAGE_ENGLISH] = "Inescapable Fate",
    [LANGUAGE_CHINESE] = "无法逃避的命运",
},

[MID_MUSIC_NAME_BGM_MAP_FE08_02] = {
    [LANGUAGE_JAPANESE] = "遥かなる道",
    [LANGUAGE_ENGLISH] = "Distant Roads",
    [LANGUAGE_CHINESE] = "遥远的道路",
},

[MID_MUSIC_NAME_BGM_MAP_FE08_03] = {
    [LANGUAGE_JAPANESE] = "不動なる志",
    [LANGUAGE_ENGLISH] = "Determination",
    [LANGUAGE_CHINESE] = "坚定不移的决心",
},

[MID_MUSIC_NAME_BGM_MAP_FE08_05] = {
    [LANGUAGE_JAPANESE] = "苦境を乗り越えて",
    [LANGUAGE_ENGLISH] = "Rise Above",
    [LANGUAGE_CHINESE] = "克服逆境",
},

[MID_MUSIC_NAME_BGM_MAP_FE08_08] = {
    [LANGUAGE_JAPANESE] = "Ｆｏｌｌｏｗ　ｍｅ！",
    [LANGUAGE_ENGLISH] = "Follow Me!",
    [LANGUAGE_CHINESE] = "跟我来！",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_01] = {
    [LANGUAGE_JAPANESE] = "A Battle and a Beginning",
    [LANGUAGE_ENGLISH] = "A Battle and a Beginning",
    [LANGUAGE_CHINESE] = "A Battle and a Beginning",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_02] = {
    [LANGUAGE_JAPANESE] = "Greil’s Mercenaries",
    [LANGUAGE_ENGLISH] = "Greil Mercenaries",
    [LANGUAGE_CHINESE] = "Greil's Mercenaries",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_03_NI] = {
    [LANGUAGE_JAPANESE] = "Ｔｈｅ　Ｄａｒｋ　Ｋｎｉｇｈｔ",
    [LANGUAGE_ENGLISH] = "The Black Knight",
    [LANGUAGE_CHINESE] = "黑骑士",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_06] = {
    [LANGUAGE_JAPANESE] = "Ｔｈｅ　Ｆｉｒｓｔ　Ｆｉｇｈｔ",
    [LANGUAGE_ENGLISH] = "The First Fight",
    [LANGUAGE_CHINESE] = "第一场战斗",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_07] = {
    [LANGUAGE_JAPANESE] = "Ｃｏｎｇｒｅｇａｔｉｏｎ　ｏｆ　Ａｍｂｉｔｉｏｎ",
    [LANGUAGE_ENGLISH] = "Congregation of Ambition",
    [LANGUAGE_CHINESE] = "雄心壮志会众",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_01] = {
    [LANGUAGE_JAPANESE] = "闇の旅人",
    [LANGUAGE_ENGLISH] = "Dark Traveler",
    [LANGUAGE_CHINESE] = "黑暗旅行者",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_03] = {
    [LANGUAGE_JAPANESE] = "力試す時",
    [LANGUAGE_ENGLISH] = "A Test of Will",
    [LANGUAGE_CHINESE] = "意志的考验",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_05] = {
    [LANGUAGE_JAPANESE] = "強き思いここに",
    [LANGUAGE_ENGLISH] = "Bearer of Hope",
    [LANGUAGE_CHINESE] = "于此的信念",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_08] = {
    [LANGUAGE_JAPANESE] = "翻弄の道",
    [LANGUAGE_ENGLISH] = "Road of Sorrow",
    [LANGUAGE_CHINESE] = "翻弄之道",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_13] = {
    [LANGUAGE_JAPANESE] = "殊勝の翔り",
    [LANGUAGE_ENGLISH] = "Proud Flight",
    [LANGUAGE_CHINESE] = "自豪的飞行",
},

[MID_MUSIC_NAME_BGM_MAP_FE11_01] = {
    [LANGUAGE_JAPANESE] = "決起のとき",
    [LANGUAGE_ENGLISH] = "The Time to Act",
    [LANGUAGE_CHINESE] = "起义之时",
},

[MID_MUSIC_NAME_BGM_MAP_FE11_03] = {
    [LANGUAGE_JAPANESE] = "英雄の宿命",
    [LANGUAGE_ENGLISH] = "A Hero's Destiny",
    [LANGUAGE_CHINESE] = "英雄的命运",
},

[MID_MUSIC_NAME_BGM_MAP_FE12_01] = {
    [LANGUAGE_JAPANESE] = "進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "进击",
},

[MID_MUSIC_NAME_BGM_MAP_FE12_03] = {
    [LANGUAGE_JAPANESE] = "戦い果てることなく",
    [LANGUAGE_ENGLISH] = "Endless Fighting",
    [LANGUAGE_CHINESE] = "永不停止战斗",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_01] = {
    [LANGUAGE_JAPANESE] = "宿命~炎",
    [LANGUAGE_ENGLISH] = "Destiny (Ablaze)",
    [LANGUAGE_CHINESE] = "宿命~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_02] = {
    [LANGUAGE_JAPANESE] = "序幕~炎",
    [LANGUAGE_ENGLISH] = "Prelude (Ablaze)",
    [LANGUAGE_CHINESE] = "序幕~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_06] = {
    [LANGUAGE_JAPANESE] = "天命~炎",
    [LANGUAGE_ENGLISH] = "Divine Decree (Ablaze)",
    [LANGUAGE_CHINESE] = "天命~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_07] = {
    [LANGUAGE_JAPANESE] = "使命〜炎",
    [LANGUAGE_ENGLISH] = "Duty (Ablaze)",
    [LANGUAGE_CHINESE] = "职责~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_12] = {
    [LANGUAGE_JAPANESE] = "強襲〜鋼",
    [LANGUAGE_ENGLISH] = "Aggression (Galvanised)",
    [LANGUAGE_CHINESE] = "突击~钢铁",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_13] = {
    [LANGUAGE_JAPANESE] = "貴様らが...姉さんの言葉を語るな!",
    [LANGUAGE_ENGLISH] = "\"Don't speak her name!\"",
    [LANGUAGE_CHINESE] = "你……不许说姐姐！",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_16] = {
    [LANGUAGE_JAPANESE] = "強者〜炎",
    [LANGUAGE_ENGLISH] = "Champion (Ablaze)",
    [LANGUAGE_CHINESE] = "强者~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_18] = {
    [LANGUAGE_JAPANESE] = "凶襲〜鋼",
    [LANGUAGE_ENGLISH] = "Annihilation (Galvanized)",
    [LANGUAGE_CHINESE] = "猛攻~钢铁",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_01] = {
    [LANGUAGE_JAPANESE] = "遠い夜明け~颯",
    [LANGUAGE_ENGLISH] = "Far Dawn (Storm)",
    [LANGUAGE_CHINESE] = "遥远的黎明~疾风",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_02] = {
    [LANGUAGE_JAPANESE] = "黄昏をつれて~焔",
    [LANGUAGE_ENGLISH] = "Dusk Falls (Fire)",
    [LANGUAGE_CHINESE] = "黄昏降临~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_06] = {
    [LANGUAGE_JAPANESE] = "輝く大地を越えて~颯",
    [LANGUAGE_ENGLISH] = "Past Light (Storm)",
    [LANGUAGE_CHINESE] = "越过闪耀的大地~飒",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_07] = {
    [LANGUAGE_JAPANESE] = "光亡き荒野の果てに~焔",
    [LANGUAGE_ENGLISH] = "Dark Wastes (Fire)",
    [LANGUAGE_CHINESE] = "永暗荒野的尽头~焔",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_11] = {
    [LANGUAGE_JAPANESE] = "矜持の競～爆",
    [LANGUAGE_ENGLISH] = "Contest of Pride (Blast)",
    [LANGUAGE_CHINESE] = "骄傲竞赛~爆",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_13] = {
    [LANGUAGE_JAPANESE] = "沈み逝く王国～濫",
    [LANGUAGE_ENGLISH] = "Land Below (Flow)",
    [LANGUAGE_CHINESE] = "沉没的王国~流",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_15] = {
    [LANGUAGE_JAPANESE] = "正義は此処に～颯",
    [LANGUAGE_ENGLISH] = "Justice RIP (Storm)",
    [LANGUAGE_CHINESE] = "正义就在这里~飒",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_18] = {
    [LANGUAGE_JAPANESE] = "正義は何処に～焔",
    [LANGUAGE_ENGLISH] = "No Justice (Fire)",
    [LANGUAGE_CHINESE] = "正义在哪里~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_20] = {
    [LANGUAGE_JAPANESE] = "譬え闇に堕ちるとも～焔",
    [LANGUAGE_ENGLISH] = "A Dark Fall (Fire)",
    [LANGUAGE_CHINESE] = "坠入黑暗~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_02] = {
    [LANGUAGE_JAPANESE] = "ミラの加護とともに",
    [LANGUAGE_ENGLISH] = "With Mila's Divine Protection",
    [LANGUAGE_CHINESE] = "与美拉的加护同在",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_03] = {
    [LANGUAGE_JAPANESE] = "往く地の果てには",
    [LANGUAGE_ENGLISH] = "What Lies at the End",
    [LANGUAGE_CHINESE] = "于前往之地的尽头",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_06] = {
    [LANGUAGE_JAPANESE] = "不穏の足音",
    [LANGUAGE_ENGLISH] = "Disquieting Steps",
    [LANGUAGE_CHINESE] = "令人不安的脚步声",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_07] = {
    [LANGUAGE_JAPANESE] = "朋輩の勇戦",
    [LANGUAGE_ENGLISH] = "Courage in Numbers",
    [LANGUAGE_CHINESE] = "好友的勇猛之战",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_09] = {
    [LANGUAGE_JAPANESE] = "まだ見ぬ地平へ",
    [LANGUAGE_ENGLISH] = "Undiscovered Horizons",
    [LANGUAGE_CHINESE] = "尚未看到的地平线",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_11] = {
    [LANGUAGE_JAPANESE] = "平野に風を追いかけて",
    [LANGUAGE_ENGLISH] = "Chasing the Wind on the Plains",
    [LANGUAGE_CHINESE] = "在平原上追逐风",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_01] = {
    [LANGUAGE_JAPANESE] = "フォドラの暁風",
    [LANGUAGE_ENGLISH] = "Fódlan Winds",
    [LANGUAGE_CHINESE] = "芙朵拉的晓风",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_02] = {
    [LANGUAGE_JAPANESE] = "天裂く流星",
    [LANGUAGE_ENGLISH] = "Tearing Through Heaven",
    [LANGUAGE_CHINESE] = "撕裂天堂",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_04] = {
    [LANGUAGE_JAPANESE] = "嵐は巡る",
    [LANGUAGE_ENGLISH] = "Tempest of Seasons",
    [LANGUAGE_CHINESE] = "四季风暴",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_06] = {
    [LANGUAGE_JAPANESE] = "野望の地平",
    [LANGUAGE_ENGLISH] = "Chasing Daybreak",
    [LANGUAGE_CHINESE] = "追逐黎明",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_07] = {
    [LANGUAGE_JAPANESE] = "鷲獅子たちの蒼穹",
    [LANGUAGE_ENGLISH] = "Blue Skies and Battle",
    [LANGUAGE_CHINESE] = "狮鹫们的苍穹",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_09] = {
    [LANGUAGE_JAPANESE] = "風塵回廊",
    [LANGUAGE_ENGLISH] = "Corridors of the Tempest",
    [LANGUAGE_CHINESE] = "风暴走廊",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_10] = {
    [LANGUAGE_JAPANESE] = "遠き道",
    [LANGUAGE_ENGLISH] = "The Long Road",
    [LANGUAGE_CHINESE] = "漫长的道路",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_12] = {
    [LANGUAGE_JAPANESE] = "鉑鎖の群狼",
    [LANGUAGE_ENGLISH] = "The Shackled Wolves",
    [LANGUAGE_CHINESE] = "戴着镣铐的狼群",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_13] = {
    [LANGUAGE_JAPANESE] = "花片の葬列",
    [LANGUAGE_ENGLISH] = "A Funeral of Flowers",
    [LANGUAGE_CHINESE] = "鲜花葬礼",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_15] = {
    [LANGUAGE_JAPANESE] = "天と地の境界",
    [LANGUAGE_ENGLISH] = "Between Heaven and Earth",
    [LANGUAGE_CHINESE] = "天与地的共界",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_18] = {
    [LANGUAGE_JAPANESE] = "覇の轟き",
    [LANGUAGE_ENGLISH] = "Roar of Dominion",
    [LANGUAGE_CHINESE] = "胜利咆哮",
},

[MID_MUSIC_NAME_BGM_MAP_FE17_13] = {
    [LANGUAGE_JAPANESE] = "遥かなる聖地～閃",
    [LANGUAGE_ENGLISH] = "Faraway Holy Land (Flare)",
    [LANGUAGE_CHINESE] = "遥远的圣地~闪",
},

[MID_MUSIC_NAME_BGM_MAP_FE17_15] = {
    [LANGUAGE_JAPANESE] = "王家の矜持～剛",
    [LANGUAGE_ENGLISH] = "Royal Confidence (Might)",
    [LANGUAGE_CHINESE] = "皇家自信~刚",
},

[MID_MUSIC_NAME_BGM_MAP_FEH_06] = {
    [LANGUAGE_JAPANESE] = "ルシッドドリーム",
    [LANGUAGE_ENGLISH] = "Lucid Dream",
    [LANGUAGE_CHINESE] = "清醒梦",
},

[MID_MUSIC_NAME_BGM_MAP_FEH_07] = {
    [LANGUAGE_JAPANESE] = "ハゥリングギア",
    [LANGUAGE_ENGLISH] = "Howling Gears",
    [LANGUAGE_CHINESE] = "嚎叫的齿轮",
},

[MID_MUSIC_NAME_BGM_MAP_FEH_09] = {
    [LANGUAGE_JAPANESE] = "ヴァイオレントストリングス",
    [LANGUAGE_ENGLISH] = "Violent Strings",
    [LANGUAGE_CHINESE] = "紫色弦",
},

[MID_MUSIC_NAME_BGM_MAP_FEH_11] = {
    [LANGUAGE_JAPANESE] = "マップ１１",
    [LANGUAGE_ENGLISH] = "Map 11",
    [LANGUAGE_CHINESE] = "地图11",
},

[MID_MUSIC_NAME_BGM_MAP_FEM_08] = {
    [LANGUAGE_JAPANESE] = "我が剣に誓って",
    [LANGUAGE_ENGLISH] = "I Swear By My Sword",
    [LANGUAGE_CHINESE] = "我以我的剑发誓",
},

[MID_MUSIC_NAME_BGM_MAP_FES_02] = {
    [LANGUAGE_JAPANESE] = "モアファンフェスト",
    [LANGUAGE_ENGLISH] = "More Fan Fest",
    [LANGUAGE_CHINESE] = "More Fan Fest",
},

[MID_MUSIC_NAME_BGM_MENU_GOLDWITCH] = {
    [LANGUAGE_JAPANESE] = "時を戻す、黄金の魔女",
    [LANGUAGE_ENGLISH] = "Seer's Snare",
    [LANGUAGE_CHINESE] = "倒转时间，黄金魔女",
},

[MID_MUSIC_NAME_BGM_MENU_MJOLLNIR] = {
    [LANGUAGE_JAPANESE] = "ダイティハンマー",
    [LANGUAGE_ENGLISH] = "Deity Hammer",
    [LANGUAGE_CHINESE] = "神锤",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_01] = {
    [LANGUAGE_JAPANESE] = "アカネイア序曲",
    [LANGUAGE_ENGLISH] = "Archanean Overture",
    [LANGUAGE_CHINESE] = "阿卡奈亚序曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_02] = {
    [LANGUAGE_JAPANESE] = "神竜伝説(A)",
    [LANGUAGE_ENGLISH] = "Legend of the Dragon God (A)",
    [LANGUAGE_CHINESE] = "神龙传说(A)",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_01] = {
    [LANGUAGE_JAPANESE] = "栄光なるグランベル",
    [LANGUAGE_ENGLISH] = "Glory to Grannvale",
    [LANGUAGE_CHINESE] = "格兰贝鲁的荣耀",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_05] = {
    [LANGUAGE_JAPANESE] = "デュー&パティ",
    [LANGUAGE_ENGLISH] = "Dew and Patty",
    [LANGUAGE_CHINESE] = "迪优&帕蒂",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_04] = {
    [LANGUAGE_JAPANESE] = "トラキア776 始まり",
    [LANGUAGE_ENGLISH] = "Thracia 776 Begins",
    [LANGUAGE_CHINESE] = "トラキア776 起始",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_05] = {
    [LANGUAGE_JAPANESE] = "戦いの中で 運命",
    [LANGUAGE_ENGLISH] = "Battle: Destiny",
    [LANGUAGE_CHINESE] = "战斗之中 命运",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_06] = {
    [LANGUAGE_JAPANESE] = "戦いの中で 進撃",
    [LANGUAGE_ENGLISH] = "Battle: Advance",
    [LANGUAGE_CHINESE] = "战斗之中 进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_02] = {
    [LANGUAGE_JAPANESE] = "I進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "I进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_01] = {
    [LANGUAGE_JAPANESE] = "黒い牙",
    [LANGUAGE_ENGLISH] = "Black Fang",
    [LANGUAGE_CHINESE] = "黑牙",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_04] = {
    [LANGUAGE_JAPANESE] = "大賢者アトス",
    [LANGUAGE_ENGLISH] = "The Archsage Athos",
    [LANGUAGE_CHINESE] = "大贤者亚托思",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_08] = {
    [LANGUAGE_JAPANESE] = "驚愕の事実Ⅱ",
    [LANGUAGE_ENGLISH] = "Shocking Truth II",
    [LANGUAGE_CHINESE] = "惊天真相II",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_02] = {
    [LANGUAGE_JAPANESE] = "すべては始まりのとき",
    [LANGUAGE_ENGLISH] = "The Beginning",
    [LANGUAGE_CHINESE] = "一切皆在开端之时",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_03] = {
    [LANGUAGE_JAPANESE] = "リオン(オルゴールアレンジ)",
    [LANGUAGE_ENGLISH] = "Lyon (Organ Arrangement)",
    [LANGUAGE_CHINESE] = "利昂(水晶音乐改编版)",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_05] = {
    [LANGUAGE_JAPANESE] = "Sadness time",
    [LANGUAGE_ENGLISH] = "Sorrow",
    [LANGUAGE_CHINESE] = "Sadness time",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_04] = {
    [LANGUAGE_JAPANESE] = "For Victory",
    [LANGUAGE_ENGLISH] = "For Victory",
    [LANGUAGE_CHINESE] = "For Victory",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_06] = {
    [LANGUAGE_JAPANESE] = "Quiet Days",
    [LANGUAGE_ENGLISH] = "Quiet Days",
    [LANGUAGE_CHINESE] = "Quiet Days",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_08] = {
    [LANGUAGE_JAPANESE] = "Wonderful Pirates",
    [LANGUAGE_ENGLISH] = "Wonderful Pirates",
    [LANGUAGE_CHINESE] = "Wonderful Pirates",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_02] = {
    [LANGUAGE_JAPANESE] = "忘我な夢",
    [LANGUAGE_ENGLISH] = "Cats at Play",
    [LANGUAGE_CHINESE] = "忘我的梦",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_03] = {
    [LANGUAGE_JAPANESE] = "心穏やかなるとき",
    [LANGUAGE_ENGLISH] = "At Peace",
    [LANGUAGE_CHINESE] = "心静时刻",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_04] = {
    [LANGUAGE_JAPANESE] = "道標に光そそぎて",
    [LANGUAGE_ENGLISH] = "Neutiquam Erro",
    [LANGUAGE_CHINESE] = "光芒洒落于路标",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_05] = {
    [LANGUAGE_JAPANESE] = "セフェラン浮遊する意識",
    [LANGUAGE_ENGLISH] = "Sephiran's Sorrow",
    [LANGUAGE_CHINESE] = "瑟菲兰漂浮的意识",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_06] = {
    [LANGUAGE_JAPANESE] = "憤怒の目",
    [LANGUAGE_ENGLISH] = "Eyes of Rage",
    [LANGUAGE_CHINESE] = "愤怒之眼",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_08] = {
    [LANGUAGE_JAPANESE] = "奇才イズカ",
    [LANGUAGE_ENGLISH] = "The Mind of Izuka",
    [LANGUAGE_CHINESE] = "奇才伊兹卡",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_03] = {
    [LANGUAGE_JAPANESE] = "誇り高き将",
    [LANGUAGE_ENGLISH] = "The Proud Commander",
    [LANGUAGE_CHINESE] = "身怀荣耀的将领",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_04] = {
    [LANGUAGE_JAPANESE] = "進むべき道",
    [LANGUAGE_ENGLISH] = "Going Forward",
    [LANGUAGE_CHINESE] = "应行之道",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_05] = {
    [LANGUAGE_JAPANESE] = "ひとときの安らぎ",
    [LANGUAGE_ENGLISH] = "A Momentary Peace",
    [LANGUAGE_CHINESE] = "一时的安稳",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_02] = {
    [LANGUAGE_JAPANESE] = "力を感じる...私たちと同じ力...",
    [LANGUAGE_ENGLISH] = "\"You have power... like mine.\"",
    [LANGUAGE_CHINESE] = "感受到了与我们相同的力量......",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_05] = {
    [LANGUAGE_JAPANESE] = "泊らせてもらおうよ?ね?",
    [LANGUAGE_ENGLISH] = "\"But, Frederick, it's nearly dark!\"",
    [LANGUAGE_CHINESE] = "我们就去借住嘛?好不好?",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_07] = {
    [LANGUAGE_JAPANESE] = "今日はもう休みましょう",
    [LANGUAGE_ENGLISH] = "We should turn in for the night",
    [LANGUAGE_CHINESE] = "今天就休息吧",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_08] = {
    [LANGUAGE_JAPANESE] = "...そんな方法が,本当にうまくいくのか?",
    [LANGUAGE_ENGLISH] = "\"Someone has to save you from your good intentions.\"",
    [LANGUAGE_CHINESE] = "...这样真的能行吗？",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_10] = {
    [LANGUAGE_JAPANESE] = "こんなところにも、屍兵が...!",
    [LANGUAGE_ENGLISH] = "Gods, have the Risen spread this far?",
    [LANGUAGE_CHINESE] = "这种地方竟也有尸兵......!",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_11] = {
    [LANGUAGE_JAPANESE] = "「I」~安",
    [LANGUAGE_ENGLISH] = "Id (Serenity)",
    [LANGUAGE_CHINESE] = "「I」~安",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_14] = {
    [LANGUAGE_JAPANESE] = "その来たるべき終焉を",
    [LANGUAGE_ENGLISH] = "Coming Demise",
    [LANGUAGE_CHINESE] = "注定要来的终结",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_15] = {
    [LANGUAGE_JAPANESE] = "揺蕩う幻",
    [LANGUAGE_ENGLISH] = "Flickering Illusion",
    [LANGUAGE_CHINESE] = "摇摆的幻影",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_04] = {
    [LANGUAGE_JAPANESE] = "御心のままに",
    [LANGUAGE_ENGLISH] = "As You Will It",
    [LANGUAGE_CHINESE] = "如您所愿",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_06] = {
    [LANGUAGE_JAPANESE] = "Echoes",
    [LANGUAGE_ENGLISH] = "Echoes",
    [LANGUAGE_CHINESE] = "Echoes",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_07] = {
    [LANGUAGE_JAPANESE] = "兄妹",
    [LANGUAGE_ENGLISH] = "Brother and Sister",
    [LANGUAGE_CHINESE] = "兄妹",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_08] = {
    [LANGUAGE_JAPANESE] = "静穏",
    [LANGUAGE_ENGLISH] = "Serenity",
    [LANGUAGE_CHINESE] = "安稳",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_09] = {
    [LANGUAGE_JAPANESE] = "日常",
    [LANGUAGE_ENGLISH] = "An Ordinary Day",
    [LANGUAGE_CHINESE] = "日常",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_10] = {
    [LANGUAGE_JAPANESE] = "彷徨の森",
    [LANGUAGE_ENGLISH] = "Forest of Wandering",
    [LANGUAGE_CHINESE] = "彷徨之森",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_11] = {
    [LANGUAGE_JAPANESE] = "戦備 邂逅",
    [LANGUAGE_ENGLISH] = "Preparations: Reunion",
    [LANGUAGE_CHINESE] = "备战 邂逅",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_07] = {
    [LANGUAGE_JAPANESE] = "星影の守り人",
    [LANGUAGE_ENGLISH] = "Guardian of Starlight",
    [LANGUAGE_CHINESE] = "星影守护者",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_08] = {
    [LANGUAGE_JAPANESE] = "迫る暗雲",
    [LANGUAGE_ENGLISH] = "Dark Clouds Gather",
    [LANGUAGE_CHINESE] = "乌云将至",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_10] = {
    [LANGUAGE_JAPANESE] = "覚醒",
    [LANGUAGE_ENGLISH] = "Awakening",
    [LANGUAGE_CHINESE] = "觉醒",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_11] = {
    [LANGUAGE_JAPANESE] = "金鹿と三日月",
    [LANGUAGE_ENGLISH] = "Golden Deer and Crescent Moon",
    [LANGUAGE_CHINESE] = "金鹿和月牙",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_12] = {
    [LANGUAGE_JAPANESE] = "策略",
    [LANGUAGE_ENGLISH] = "Tactics",
    [LANGUAGE_CHINESE] = "策略",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_13] = {
    [LANGUAGE_JAPANESE] = "緊迫",
    [LANGUAGE_ENGLISH] = "Anxiety",
    [LANGUAGE_CHINESE] = "紧迫",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_16] = {
    [LANGUAGE_JAPANESE] = "軍事国家",
    [LANGUAGE_ENGLISH] = "Mighty Governance",
    [LANGUAGE_CHINESE] = "军事国家",
},

[MID_MUSIC_NAME_BGM_SUMMON_COMMON] = {
    [LANGUAGE_JAPANESE] = "コントラクト",
    [LANGUAGE_ENGLISH] = "Contract",
    [LANGUAGE_CHINESE] = "合同",
},
