// This file is generated by make_texts.py
// Text type: TextType.MUSIC

[MID_MUSIC_NAME_BGM_BATTLE_FE06_01] = {
    [LANGUAGE_JAPANESE] = "Attack!",
    [LANGUAGE_ENGLISH] = "Attack!",
    [LANGUAGE_CHINESE] = "Attack!",
},

[MID_MUSIC_NAME_BGM_BATTLE_FE13_01] = {
    [LANGUAGE_JAPANESE] = "演習~鋼",
    [LANGUAGE_ENGLISH] = "Training (Galvanized)",
    [LANGUAGE_CHINESE] = "演习~钢",
},

[MID_MUSIC_NAME_BGM_BATTLE_FE14_01] = {
    [LANGUAGE_JAPANESE] = "その手が拓く未来は",
    [LANGUAGE_ENGLISH] = "The Path Is Yours to Climb",
    [LANGUAGE_CHINESE] = "那双手所开拓的未来",
},

[MID_MUSIC_NAME_BGM_EVENT_PLAIN_01] = {
    [LANGUAGE_JAPANESE] = "ヴァイスブレイヴ",
    [LANGUAGE_ENGLISH] = "Order of Heroes",
    [LANGUAGE_CHINESE] = "纯白义勇队",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_02] = {
    [LANGUAGE_JAPANESE] = "ヴェロニカ",
    [LANGUAGE_ENGLISH] = "Veronica",
    [LANGUAGE_CHINESE] = "维洛妮卡",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_01] = {
    [LANGUAGE_JAPANESE] = "ウィンドオブアスク",
    [LANGUAGE_ENGLISH] = "Winds of Askr",
    [LANGUAGE_CHINESE] = "亚斯克的风",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_02] = {
    [LANGUAGE_JAPANESE] = "グランドオブアスク",
    [LANGUAGE_ENGLISH] = "The Grandeur of Askr",
    [LANGUAGE_CHINESE] = "雄伟的亚斯克",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_03] = {
    [LANGUAGE_JAPANESE] = "ラストフェイズ",
    [LANGUAGE_ENGLISH] = "Last Phase",
    [LANGUAGE_CHINESE] = "末世",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_04] = {
    [LANGUAGE_JAPANESE] = "リターントゥニフル",
    [LANGUAGE_ENGLISH] = "Return To Nifl",
    [LANGUAGE_CHINESE] = "回到尼福尔",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_05] = {
    [LANGUAGE_JAPANESE] = "トラジディオブアスク",
    [LANGUAGE_ENGLISH] = "Tragedy of Askr",
    [LANGUAGE_CHINESE] = "亚斯克的悲剧",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_01] = {
    [LANGUAGE_JAPANESE] = "序章(聖騎士誕生)",
    [LANGUAGE_ENGLISH] = "Prologue" TEXT_CMD_NEWLINE "Birth of a Holy Knight",
    [LANGUAGE_CHINESE] = "序章(圣骑士诞生)",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_05] = {
    [LANGUAGE_JAPANESE] = "第3章(獅子王エルトシャン)",
    [LANGUAGE_ENGLISH] = "Chapter 3" TEXT_CMD_NEWLINE "Eldigan, the Lionheart",
    [LANGUAGE_CHINESE] = "第3章(狮子王艾尔多尚)",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_07] = {
    [LANGUAGE_JAPANESE] = "第5章(運命の扉)",
    [LANGUAGE_ENGLISH] = "Chapter 5" TEXT_CMD_NEWLINE "Doorway to Destiny",
    [LANGUAGE_CHINESE] = "第5章(命运之门)",
},

[MID_MUSIC_NAME_BGM_MAP_FE06_01] = {
    [LANGUAGE_JAPANESE] = "はるかなる空の向こうに" TEXT_CMD_NEWLINE "~ロイの旅立ち",
    [LANGUAGE_ENGLISH] = "Beyond Distant Skies -" TEXT_CMD_NEWLINE "Roy's Departure",
    [LANGUAGE_CHINESE] = "遥远天空的彼端" TEXT_CMD_NEWLINE "~罗伊的旅程",
},

[MID_MUSIC_NAME_BGM_MAP_FE06_02] = {
    [LANGUAGE_JAPANESE] = "Winning Road" TEXT_CMD_NEWLINE "~ロイの希望",
    [LANGUAGE_ENGLISH] = "Winning Road - Roy's Hope",
    [LANGUAGE_CHINESE] = "Winning Road" TEXT_CMD_NEWLINE "~罗伊的希望",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_01] = {
    [LANGUAGE_JAPANESE] = "大切なもの",
    [LANGUAGE_ENGLISH] = "Precious Things",
    [LANGUAGE_CHINESE] = "重要的事物",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_02] = {
    [LANGUAGE_JAPANESE] = "草原の風",
    [LANGUAGE_ENGLISH] = "Winds across the Plains",
    [LANGUAGE_CHINESE] = "草原之风",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_03] = {
    [LANGUAGE_JAPANESE] = "友情と使命と勇気と",
    [LANGUAGE_ENGLISH] = "Friendship and Adventure",
    [LANGUAGE_CHINESE] = "友情、使命及勇气",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_01] = {
    [LANGUAGE_JAPANESE] = "A Battle and" TEXT_CMD_NEWLINE "a Beginning",
    [LANGUAGE_ENGLISH] = "A Battle and a Beginning",
    [LANGUAGE_CHINESE] = "A Battle and" TEXT_CMD_NEWLINE "a Beginning",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_02] = {
    [LANGUAGE_JAPANESE] = "Greil’s" TEXT_CMD_NEWLINE "Mercenaries",
    [LANGUAGE_ENGLISH] = "Greil Mercenaries",
    [LANGUAGE_CHINESE] = "Greil's Mercenaries",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_05] = {
    [LANGUAGE_JAPANESE] = "強き思いここに",
    [LANGUAGE_ENGLISH] = "Bearer of Hope",
    [LANGUAGE_CHINESE] = "于此的信念",
},

[MID_MUSIC_NAME_BGM_MAP_FE11_01] = {
    [LANGUAGE_JAPANESE] = "決起のとき",
    [LANGUAGE_ENGLISH] = "The Time to Act",
    [LANGUAGE_CHINESE] = "起义之时",
},

[MID_MUSIC_NAME_BGM_MAP_FE12_01] = {
    [LANGUAGE_JAPANESE] = "進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "进击",
},

[MID_MUSIC_NAME_BGM_MAP_FE12_02] = {
    [LANGUAGE_JAPANESE] = "新たなる歴史を刻む者",
    [LANGUAGE_ENGLISH] = "Those Who Dare to Change History",
    [LANGUAGE_CHINESE] = "铭刻崭新历史之人",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_01] = {
    [LANGUAGE_JAPANESE] = "宿命~炎",
    [LANGUAGE_ENGLISH] = "Destiny (Ablaze)",
    [LANGUAGE_CHINESE] = "宿命~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_02] = {
    [LANGUAGE_JAPANESE] = "序幕~炎",
    [LANGUAGE_ENGLISH] = "Prelude (Ablaze)",
    [LANGUAGE_CHINESE] = "序幕~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_04] = {
    [LANGUAGE_JAPANESE] = "遠征~炎",
    [LANGUAGE_ENGLISH] = "Conquest (Ablaze)",
    [LANGUAGE_CHINESE] = "远征~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_06] = {
    [LANGUAGE_JAPANESE] = "天命~炎",
    [LANGUAGE_ENGLISH] = "Divine Decree (Ablaze)",
    [LANGUAGE_CHINESE] = "天命~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_01] = {
    [LANGUAGE_JAPANESE] = "遠い夜明け~颯",
    [LANGUAGE_ENGLISH] = "Far Dawn (Storm)",
    [LANGUAGE_CHINESE] = "遥远的黎明~疾风",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_02] = {
    [LANGUAGE_JAPANESE] = "黄昏をつれて~焔",
    [LANGUAGE_ENGLISH] = "Dusk Falls (Fire)",
    [LANGUAGE_CHINESE] = "黄昏降临~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_06] = {
    [LANGUAGE_JAPANESE] = "輝く大地を越えて~颯",
    [LANGUAGE_ENGLISH] = "Past Light (Storm)",
    [LANGUAGE_CHINESE] = "越过闪耀的大地~飒",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_07] = {
    [LANGUAGE_JAPANESE] = "光亡き荒野の果てに~焔",
    [LANGUAGE_ENGLISH] = "Dark Wastes (Fire)",
    [LANGUAGE_CHINESE] = "永暗荒野的尽头~焔",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_02] = {
    [LANGUAGE_JAPANESE] = "ミラの加護とともに",
    [LANGUAGE_ENGLISH] = "With Mila's Divine Protection",
    [LANGUAGE_CHINESE] = "与美拉的加护同在",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_03] = {
    [LANGUAGE_JAPANESE] = "往く地の果てには",
    [LANGUAGE_ENGLISH] = "What Lies at the End",
    [LANGUAGE_CHINESE] = "于前往之地的尽头",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_04] = {
    [LANGUAGE_JAPANESE] = "贄と聖女",
    [LANGUAGE_ENGLISH] = "The Sacrifice and the Saint",
    [LANGUAGE_CHINESE] = "祭品及圣女",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_05] = {
    [LANGUAGE_JAPANESE] = "神よ、その黄昏よ",
    [LANGUAGE_ENGLISH] = "Twilight of the Gods",
    [LANGUAGE_CHINESE] = "神啊,黄昏啊",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_01] = {
    [LANGUAGE_JAPANESE] = "フォドラの暁風",
    [LANGUAGE_ENGLISH] = "Fódlan Winds",
    [LANGUAGE_CHINESE] = "芙朵拉的晓风",
},

[MID_MUSIC_NAME_BGM_MAP_FEM_01] = {
    [LANGUAGE_JAPANESE] = "序幕~快炎",
    [LANGUAGE_ENGLISH] = "Prelude (Warm Blaze)",
    [LANGUAGE_CHINESE] = "序幕~快炎",
},

[MID_MUSIC_NAME_BGM_MAP_FEM_04] = {
    [LANGUAGE_JAPANESE] = "いつかきた旅路~轟轟",
    [LANGUAGE_ENGLISH] = "Road Taken (Roar)",
    [LANGUAGE_CHINESE] = "曾几何时的旅途~轰然",
},

[MID_MUSIC_NAME_BGM_MAP_FEM_05] = {
    [LANGUAGE_JAPANESE] = "正義は此処に~暗颯",
    [LANGUAGE_ENGLISH] = "Justice RIP (Nohrian Storm)",
    [LANGUAGE_CHINESE] = "正义在此~暗飒",
},

[MID_MUSIC_NAME_BGM_MAP_FEM_06] = {
    [LANGUAGE_JAPANESE] = "戦闘マップ1~回奏",
    [LANGUAGE_ENGLISH] = "Onward! (Reprise)",
    [LANGUAGE_CHINESE] = "战斗地图1~轮奏",
},

[MID_MUSIC_NAME_BGM_MAP_FES_01] = {
    [LANGUAGE_JAPANESE] = "ファンフェスト",
    [LANGUAGE_ENGLISH] = "Fan Fest",
    [LANGUAGE_CHINESE] = "Fan Fest",
},

[MID_MUSIC_NAME_BGM_MAP_FES_02] = {
    [LANGUAGE_JAPANESE] = "モアファンフェスト",
    [LANGUAGE_ENGLISH] = "More Fan Fest",
    [LANGUAGE_CHINESE] = "More Fan Fest",
},

[MID_MUSIC_NAME_BGM_MAP_POPULARITY_01] = {
    [LANGUAGE_JAPANESE] = "ブレイヴヒーローズ",
    [LANGUAGE_ENGLISH] = "Brave Heroes",
    [LANGUAGE_CHINESE] = "Brave Heroes",
},

[MID_MUSIC_NAME_BGM_MENU_FRIEND1] = {
    [LANGUAGE_JAPANESE] = "フレンドシップ",
    [LANGUAGE_ENGLISH] = "Friendship",
    [LANGUAGE_CHINESE] = "Friendship",
},

[MID_MUSIC_NAME_BGM_MENU_NORMAL] = {
    [LANGUAGE_JAPANESE] = "ギアアップフォー",
    [LANGUAGE_ENGLISH] = "Gear Up For...",
    [LANGUAGE_CHINESE] = "蓄势待发",
},

[MID_MUSIC_NAME_BGM_MENU_POST] = {
    [LANGUAGE_JAPANESE] = "キャストアバロット",
    [LANGUAGE_ENGLISH] = "Cast Your Vote",
    [LANGUAGE_CHINESE] = "Cast A Ballot",
},

[MID_MUSIC_NAME_BGM_MENU_SKYCASTLE] = {
    [LANGUAGE_JAPANESE] = "クライムザスカイ",
    [LANGUAGE_ENGLISH] = "Climb the Sky",
    [LANGUAGE_CHINESE] = "攀上天空",
},

[MID_MUSIC_NAME_BGM_MENU_TITLE] = {
    [LANGUAGE_JAPANESE] = "ファイアーエムブレム" TEXT_CMD_NEWLINE "メインテーマ" TEXT_CMD_NEWLINE "(Ver.Heroes)",
    [LANGUAGE_ENGLISH] = "Fire Emblem" TEXT_CMD_NEWLINE "Main Theme" TEXT_CMD_NEWLINE "(Heroes Ver.)",
    [LANGUAGE_CHINESE] = "ファイアーエムブレム" TEXT_CMD_NEWLINE "主题曲" TEXT_CMD_NEWLINE "(Ver.Heroes)",
},

[MID_MUSIC_NAME_BGM_MNS_FE01_01] = {
    [LANGUAGE_JAPANESE] = "ストーリー6" TEXT_CMD_NEWLINE "マルスとシーダの会話",
    [LANGUAGE_ENGLISH] = "Story 6" TEXT_CMD_NEWLINE "Marth and Caeda's Talk",
    [LANGUAGE_CHINESE] = "剧情6" TEXT_CMD_NEWLINE "马尔斯与希达的对话",
},

[MID_MUSIC_NAME_BGM_MNS_FE01_02] = {
    [LANGUAGE_JAPANESE] = "オープニングタイトル~デモ",
    [LANGUAGE_ENGLISH] = "Opening Title (Demo)",
    [LANGUAGE_CHINESE] = "Opening Title~Demo",
},

[MID_MUSIC_NAME_BGM_MNS_FE02_01] = {
    [LANGUAGE_JAPANESE] = "全体マップ・セリカの旅立ち",
    [LANGUAGE_ENGLISH] = "The Ark of Dawn (Classic)",
    [LANGUAGE_CHINESE] = "全地图・赛莉卡的旅程",
},

[MID_MUSIC_NAME_BGM_MNS_FE02_02] = {
    [LANGUAGE_JAPANESE] = "城(マーチ)",
    [LANGUAGE_ENGLISH] = "Castle (March)",
    [LANGUAGE_CHINESE] = "城堡(进行曲)",
},

[MID_MUSIC_NAME_BGM_MNS_FE02_03] = {
    [LANGUAGE_JAPANESE] = "全体マップ3章" TEXT_CMD_NEWLINE "(解放戦争:それぞれの道)",
    [LANGUAGE_ENGLISH] = "World Map Act 3:" TEXT_CMD_NEWLINE "(War of Deliverance:" TEXT_CMD_NEWLINE "Respective Paths)",
    [LANGUAGE_CHINESE] = "全地图第3章" TEXT_CMD_NEWLINE "(解放战争:各自的道路)",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_01] = {
    [LANGUAGE_JAPANESE] = "アカネイア序曲",
    [LANGUAGE_ENGLISH] = "Archanean Overture",
    [LANGUAGE_CHINESE] = "阿卡奈亚序曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_02] = {
    [LANGUAGE_JAPANESE] = "神竜伝説(A)",
    [LANGUAGE_ENGLISH] = "Legend of the" TEXT_CMD_NEWLINE "Dragon God (A)",
    [LANGUAGE_CHINESE] = "神龙传说(A)",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_03] = {
    [LANGUAGE_JAPANESE] = "新たなる旅立ち",
    [LANGUAGE_ENGLISH] = "A New Journey",
    [LANGUAGE_CHINESE] = "全新的旅程",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_01] = {
    [LANGUAGE_JAPANESE] = "栄光なるグランベル",
    [LANGUAGE_ENGLISH] = "Glory to Grannvale",
    [LANGUAGE_CHINESE] = "格兰贝鲁的荣耀",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_02] = {
    [LANGUAGE_JAPANESE] = "城下町グランベル",
    [LANGUAGE_ENGLISH] = "Grannvale Castle Town",
    [LANGUAGE_CHINESE] = "城镇格兰贝鲁",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_03] = {
    [LANGUAGE_JAPANESE] = "城下町シレジア",
    [LANGUAGE_ENGLISH] = "Silesse Castle Town",
    [LANGUAGE_CHINESE] = "城镇西里西亚",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_04] = {
    [LANGUAGE_JAPANESE] = "シレジア王宮",
    [LANGUAGE_ENGLISH] = "Royal Palace of Silesse",
    [LANGUAGE_CHINESE] = "西里西亚王宫",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_05] = {
    [LANGUAGE_JAPANESE] = "デュー&パティ",
    [LANGUAGE_ENGLISH] = "Dew and Patty",
    [LANGUAGE_CHINESE] = "迪优&帕蒂",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_06] = {
    [LANGUAGE_JAPANESE] = "巡る想い",
    [LANGUAGE_ENGLISH] = "Embracing Destiny",
    [LANGUAGE_CHINESE] = "思绪万千",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_07] = {
    [LANGUAGE_JAPANESE] = "アグストリア王宮",
    [LANGUAGE_ENGLISH] = "Agustria Royal Palace",
    [LANGUAGE_CHINESE] = "阿古斯特里亚王宫",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_01] = {
    [LANGUAGE_JAPANESE] = "トラキア776 出撃",
    [LANGUAGE_ENGLISH] = "Thracia 776 Sally Forth",
    [LANGUAGE_CHINESE] = "トラキア776 出击",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_02] = {
    [LANGUAGE_JAPANESE] = "章の中で 出会い、再会",
    [LANGUAGE_ENGLISH] = "Encounters and Reunions",
    [LANGUAGE_CHINESE] = "在章节中 相遇、重逢",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_03] = {
    [LANGUAGE_JAPANESE] = "章終り ゆけゆけリーフ",
    [LANGUAGE_ENGLISH] = "Let's Go, Leif!",
    [LANGUAGE_CHINESE] = "终章 上啊上啊里弗",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_04] = {
    [LANGUAGE_JAPANESE] = "トラキア776 始まり",
    [LANGUAGE_ENGLISH] = "Thracia 776 Begins",
    [LANGUAGE_CHINESE] = "トラキア776 起始",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_05] = {
    [LANGUAGE_JAPANESE] = "戦いの中で 運命",
    [LANGUAGE_ENGLISH] = "Battle: Destiny",
    [LANGUAGE_CHINESE] = "战斗之中 命运",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_06] = {
    [LANGUAGE_JAPANESE] = "戦いの中で 進撃",
    [LANGUAGE_ENGLISH] = "Battle: Advance",
    [LANGUAGE_CHINESE] = "战斗之中 进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_07] = {
    [LANGUAGE_JAPANESE] = "章の中で サラ",
    [LANGUAGE_ENGLISH] = "Sara",
    [LANGUAGE_CHINESE] = "在章节中 莎拉",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_01] = {
    [LANGUAGE_JAPANESE] = "はるかなる理想郷",
    [LANGUAGE_ENGLISH] = "Far from Arcadia",
    [LANGUAGE_CHINESE] = "遥远的理想乡",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_02] = {
    [LANGUAGE_JAPANESE] = "I進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "I进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_04] = {
    [LANGUAGE_JAPANESE] = "Suspicious" TEXT_CMD_NEWLINE "~三竜将のテーマ",
    [LANGUAGE_ENGLISH] = "Suspicious" TEXT_CMD_NEWLINE "Wyvern Generals Theme",
    [LANGUAGE_CHINESE] = "Suspicious" TEXT_CMD_NEWLINE "~三龙将的主题曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_05] = {
    [LANGUAGE_JAPANESE] = "Melancholy" TEXT_CMD_NEWLINE "~三竜将のテーマ",
    [LANGUAGE_ENGLISH] = "Melancholy" TEXT_CMD_NEWLINE "Wyvern Generals Theme",
    [LANGUAGE_CHINESE] = "Melancholy" TEXT_CMD_NEWLINE "~三龙将的主题曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_06] = {
    [LANGUAGE_JAPANESE] = "進撃準備",
    [LANGUAGE_ENGLISH] = "Combat Preparation",
    [LANGUAGE_CHINESE] = "进击准备",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_07] = {
    [LANGUAGE_JAPANESE] = "躍進のときを",
    [LANGUAGE_ENGLISH] = "When the Rush Comes",
    [LANGUAGE_CHINESE] = "跃进之时",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_08] = {
    [LANGUAGE_JAPANESE] = "誘惑の踊り",
    [LANGUAGE_ENGLISH] = "Enticing Dance",
    [LANGUAGE_CHINESE] = "诱惑的舞蹈",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_09] = {
    [LANGUAGE_JAPANESE] = "II王都奪還",
    [LANGUAGE_ENGLISH] = "II - Reclaim the Capital",
    [LANGUAGE_CHINESE] = "II夺回王都",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_01] = {
    [LANGUAGE_JAPANESE] = "黒い牙",
    [LANGUAGE_ENGLISH] = "Black Fang",
    [LANGUAGE_CHINESE] = "黑牙",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_02] = {
    [LANGUAGE_JAPANESE] = "進撃準備(烈火Ver)",
    [LANGUAGE_ENGLISH] = "Prepare to Charge",
    [LANGUAGE_CHINESE] = "进击准备(烈火Ver)",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_03] = {
    [LANGUAGE_JAPANESE] = "Going My Way",
    [LANGUAGE_ENGLISH] = "Going My Way",
    [LANGUAGE_CHINESE] = "Going My Way",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_04] = {
    [LANGUAGE_JAPANESE] = "大賢者アトス",
    [LANGUAGE_ENGLISH] = "The Archsage Athos",
    [LANGUAGE_CHINESE] = "大贤者亚托思",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_05] = {
    [LANGUAGE_JAPANESE] = "草原の少女 ~ リンのテーマ",
    [LANGUAGE_ENGLISH] = "Girl of the Plains:" TEXT_CMD_NEWLINE "Lyn's Theme",
    [LANGUAGE_CHINESE] = "草原的少女 ~ 琳的主题曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_06] = {
    [LANGUAGE_JAPANESE] = "心ひとつに" TEXT_CMD_NEWLINE "~エリウッドのテーマ",
    [LANGUAGE_ENGLISH] = "One Heart:" TEXT_CMD_NEWLINE "Eliwood's Theme",
    [LANGUAGE_CHINESE] = "团结一心" TEXT_CMD_NEWLINE "~艾利乌德的主题曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_09] = {
    [LANGUAGE_JAPANESE] = "街並み",
    [LANGUAGE_ENGLISH] = "Ships and Homes",
    [LANGUAGE_CHINESE] = "城市风貌",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_10] = {
    [LANGUAGE_JAPANESE] = "友を信じて" TEXT_CMD_NEWLINE "~ヘクトルのテーマ",
    [LANGUAGE_ENGLISH] = "Loyalty: Hector's Theme",
    [LANGUAGE_CHINESE] = "相信朋友" TEXT_CMD_NEWLINE "~海克托尔的主题曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_01] = {
    [LANGUAGE_JAPANESE] = "進撃準備",
    [LANGUAGE_ENGLISH] = "Combat Preparation",
    [LANGUAGE_CHINESE] = "进击准备",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_02] = {
    [LANGUAGE_JAPANESE] = "すべては始まりのとき",
    [LANGUAGE_ENGLISH] = "The Beginning",
    [LANGUAGE_CHINESE] = "一切皆在开端之时",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_03] = {
    [LANGUAGE_JAPANESE] = "リオン(オルゴールアレンジ)",
    [LANGUAGE_ENGLISH] = "Lyon (Organ Arrangement)",
    [LANGUAGE_CHINESE] = "利昂(水晶音乐改编版)",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_04] = {
    [LANGUAGE_JAPANESE] = "再会",
    [LANGUAGE_ENGLISH] = "Reunion",
    [LANGUAGE_CHINESE] = "重逢",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_05] = {
    [LANGUAGE_JAPANESE] = "Sadness time",
    [LANGUAGE_ENGLISH] = "Sorrow",
    [LANGUAGE_CHINESE] = "Sadness time",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_06] = {
    [LANGUAGE_JAPANESE] = "進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_07] = {
    [LANGUAGE_JAPANESE] = "リオン",
    [LANGUAGE_ENGLISH] = "Lyon",
    [LANGUAGE_CHINESE] = "利昂",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_01] = {
    [LANGUAGE_JAPANESE] = "The Dark Knight",
    [LANGUAGE_ENGLISH] = "The Black Knight",
    [LANGUAGE_CHINESE] = "The Dark Knight",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_02] = {
    [LANGUAGE_JAPANESE] = "His" TEXT_CMD_NEWLINE "Father’s Son",
    [LANGUAGE_ENGLISH] = "His Father's Son",
    [LANGUAGE_CHINESE] = "His" TEXT_CMD_NEWLINE "Father's Son",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_03] = {
    [LANGUAGE_JAPANESE] = "Rising Morale",
    [LANGUAGE_ENGLISH] = "Rising Morale",
    [LANGUAGE_CHINESE] = "Rising Morale",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_04] = {
    [LANGUAGE_JAPANESE] = "For Victory",
    [LANGUAGE_ENGLISH] = "For Victory",
    [LANGUAGE_CHINESE] = "For Victory",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_05] = {
    [LANGUAGE_JAPANESE] = "Young Warriors",
    [LANGUAGE_ENGLISH] = "Young Warriors",
    [LANGUAGE_CHINESE] = "Young Warriors",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_06] = {
    [LANGUAGE_JAPANESE] = "Quiet Days",
    [LANGUAGE_ENGLISH] = "Quiet Days",
    [LANGUAGE_CHINESE] = "Quiet Days",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_07] = {
    [LANGUAGE_JAPANESE] = "Beautiful" TEXT_CMD_NEWLINE "Princess" TEXT_CMD_NEWLINE "Erincia",
    [LANGUAGE_ENGLISH] = "Beautiful Princess Elincia",
    [LANGUAGE_CHINESE] = "Beautiful" TEXT_CMD_NEWLINE "Princess" TEXT_CMD_NEWLINE "Erincia",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_08] = {
    [LANGUAGE_JAPANESE] = "Wonderful" TEXT_CMD_NEWLINE "Pirates",
    [LANGUAGE_ENGLISH] = "Wonderful Pirates",
    [LANGUAGE_CHINESE] = "Wonderful" TEXT_CMD_NEWLINE "Pirates",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_10] = {
    [LANGUAGE_JAPANESE] = "The White" TEXT_CMD_NEWLINE "Heron",
    [LANGUAGE_ENGLISH] = "The White Heron",
    [LANGUAGE_CHINESE] = "The White" TEXT_CMD_NEWLINE "Heron",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_11] = {
    [LANGUAGE_JAPANESE] = "Move Out!",
    [LANGUAGE_ENGLISH] = "Move Out!",
    [LANGUAGE_CHINESE] = "Move Out!",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_01] = {
    [LANGUAGE_JAPANESE] = "備忘",
    [LANGUAGE_ENGLISH] = "The Task at Hand",
    [LANGUAGE_CHINESE] = "备忘",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_02] = {
    [LANGUAGE_JAPANESE] = "忘我な夢",
    [LANGUAGE_ENGLISH] = "Cats at Play",
    [LANGUAGE_CHINESE] = "忘我的梦",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_03] = {
    [LANGUAGE_JAPANESE] = "心穏やかなるとき",
    [LANGUAGE_ENGLISH] = "At Peace",
    [LANGUAGE_CHINESE] = "心静时刻",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_04] = {
    [LANGUAGE_JAPANESE] = "道標に光そそぎて",
    [LANGUAGE_ENGLISH] = "Neutiquam Erro",
    [LANGUAGE_CHINESE] = "光芒洒落于路标",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_05] = {
    [LANGUAGE_JAPANESE] = "セフェラン浮遊する意識",
    [LANGUAGE_ENGLISH] = "Sephiran's Sorrow",
    [LANGUAGE_CHINESE] = "瑟菲兰漂浮的意识",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_06] = {
    [LANGUAGE_JAPANESE] = "憤怒の目",
    [LANGUAGE_ENGLISH] = "Eyes of Rage",
    [LANGUAGE_CHINESE] = "愤怒之眼",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_07] = {
    [LANGUAGE_JAPANESE] = "堕するオリヴァー",
    [LANGUAGE_ENGLISH] = "Oliver's Fall",
    [LANGUAGE_CHINESE] = "堕落的奥利瓦",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_08] = {
    [LANGUAGE_JAPANESE] = "奇才イズカ",
    [LANGUAGE_ENGLISH] = "The Mind of Izuka",
    [LANGUAGE_CHINESE] = "奇才伊兹卡",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_09] = {
    [LANGUAGE_JAPANESE] = "進まざるは退転",
    [LANGUAGE_ENGLISH] = "Backsliding",
    [LANGUAGE_CHINESE] = "不进则退",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_01] = {
    [LANGUAGE_JAPANESE] = "戦支度",
    [LANGUAGE_ENGLISH] = "Preparations",
    [LANGUAGE_CHINESE] = "战斗的准备",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_02] = {
    [LANGUAGE_JAPANESE] = "勝利のよろこび",
    [LANGUAGE_ENGLISH] = "Sweet Victory",
    [LANGUAGE_CHINESE] = "胜利的喜悦",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_03] = {
    [LANGUAGE_JAPANESE] = "誇り高き将",
    [LANGUAGE_ENGLISH] = "The Proud Commander",
    [LANGUAGE_CHINESE] = "身怀荣耀的将领",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_04] = {
    [LANGUAGE_JAPANESE] = "決意をあらたに",
    [LANGUAGE_ENGLISH] = "Renewed Purpose",
    [LANGUAGE_CHINESE] = "立下新的决意",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_05] = {
    [LANGUAGE_JAPANESE] = "進撃あるのみ",
    [LANGUAGE_ENGLISH] = "Keep Marching On",
    [LANGUAGE_CHINESE] = "唯有进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_06] = {
    [LANGUAGE_JAPANESE] = "幼き神竜",
    [LANGUAGE_ENGLISH] = "The Little Divine Dragon",
    [LANGUAGE_CHINESE] = "幼小的神龙",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_01] = {
    [LANGUAGE_JAPANESE] = "戦を前に",
    [LANGUAGE_ENGLISH] = "Before Battle",
    [LANGUAGE_CHINESE] = "出战之前",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_02] = {
    [LANGUAGE_JAPANESE] = "絆永遠に",
    [LANGUAGE_ENGLISH] = "Bonds Everlasting",
    [LANGUAGE_CHINESE] = "永远的牵绊",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_03] = {
    [LANGUAGE_JAPANESE] = "戦士たちの日常",
    [LANGUAGE_ENGLISH] = "Daily Lives of Warriors",
    [LANGUAGE_CHINESE] = "战士们的日常",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_04] = {
    [LANGUAGE_JAPANESE] = "進むべき道",
    [LANGUAGE_ENGLISH] = "Going Forward",
    [LANGUAGE_CHINESE] = "应行之道",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_05] = {
    [LANGUAGE_JAPANESE] = "ひとときの安らぎ",
    [LANGUAGE_ENGLISH] = "A Momentary Peace",
    [LANGUAGE_CHINESE] = "一时的安稳",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_06] = {
    [LANGUAGE_JAPANESE] = "可笑しな人々",
    [LANGUAGE_ENGLISH] = "Odd Folk",
    [LANGUAGE_CHINESE] = "奇怪的人们",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_07] = {
    [LANGUAGE_JAPANESE] = "汝、その名は",
    [LANGUAGE_ENGLISH] = "Your Name Is...",
    [LANGUAGE_CHINESE] = "汝之名",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_01] = {
    [LANGUAGE_JAPANESE] = "メインテーマ・夏" TEXT_CMD_NEWLINE "(OFF VOICE)",
    [LANGUAGE_ENGLISH] = "Main Theme (Summer)" TEXT_CMD_NEWLINE "(No Voice)",
    [LANGUAGE_CHINESE] = "主题曲・夏" TEXT_CMD_NEWLINE "(OFF VOICE)",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_02] = {
    [LANGUAGE_JAPANESE] = "力を感じる...私たちと同じ力...",
    [LANGUAGE_ENGLISH] = "\"You have power..." TEXT_CMD_NEWLINE "like mine.\"",
    [LANGUAGE_CHINESE] = "感受到了与我们相同的力量......",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_04] = {
    [LANGUAGE_JAPANESE] = "ここで進撃の準備を" TEXT_CMD_NEWLINE "整えましょう",
    [LANGUAGE_ENGLISH] = "\"We'd best prepare for" TEXT_CMD_NEWLINE "combat, just to be safe.\"",
    [LANGUAGE_CHINESE] = "在这里进行进击的整备吧",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_05] = {
    [LANGUAGE_JAPANESE] = "泊らせてもらおうよ?ね?",
    [LANGUAGE_ENGLISH] = "\"But, Frederick," TEXT_CMD_NEWLINE "it's nearly dark!\"",
    [LANGUAGE_CHINESE] = "我们就去借住嘛?好不好?",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_06] = {
    [LANGUAGE_JAPANESE] = "遠征",
    [LANGUAGE_ENGLISH] = "Conquest",
    [LANGUAGE_CHINESE] = "远征",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_07] = {
    [LANGUAGE_JAPANESE] = "今日はもう休みましょう",
    [LANGUAGE_ENGLISH] = "We should turn in" TEXT_CMD_NEWLINE "for the night",
    [LANGUAGE_CHINESE] = "今天就休息吧",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_09] = {
    [LANGUAGE_JAPANESE] = "メインテーマ・湯",
    [LANGUAGE_ENGLISH] = "Main Theme (Hot Spring)",
    [LANGUAGE_CHINESE] = "主题曲・温泉",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_10] = {
    [LANGUAGE_JAPANESE] = "こんなところにも、屍兵が...!",
    [LANGUAGE_ENGLISH] = "Gods, have the Risen" TEXT_CMD_NEWLINE "spread this far?",
    [LANGUAGE_CHINESE] = "这种地方竟也有尸兵......!",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_11] = {
    [LANGUAGE_JAPANESE] = "「I」~安",
    [LANGUAGE_ENGLISH] = "Id (Serenity)",
    [LANGUAGE_CHINESE] = "「I」~安",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_03] = {
    [LANGUAGE_JAPANESE] = "異境への轍",
    [LANGUAGE_ENGLISH] = "To a Foreign Land",
    [LANGUAGE_CHINESE] = "通往异境的车辙",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_06] = {
    [LANGUAGE_JAPANESE] = "宵闇に踊る",
    [LANGUAGE_ENGLISH] = "Dance in the Dark",
    [LANGUAGE_CHINESE] = "夜幕中起舞",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_07] = {
    [LANGUAGE_JAPANESE] = "暁光に煌く",
    [LANGUAGE_ENGLISH] = "Shine in the Light",
    [LANGUAGE_CHINESE] = "曙光中闪耀",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_08] = {
    [LANGUAGE_JAPANESE] = "あなたへ続く道",
    [LANGUAGE_ENGLISH] = "The Path to You",
    [LANGUAGE_CHINESE] = "通往你的道路",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_09] = {
    [LANGUAGE_JAPANESE] = "輝く大地を越えて",
    [LANGUAGE_ENGLISH] = "Past Light",
    [LANGUAGE_CHINESE] = "越过闪耀的大地",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_10] = {
    [LANGUAGE_JAPANESE] = "望郷・光",
    [LANGUAGE_ENGLISH] = "Homesick (Light)",
    [LANGUAGE_CHINESE] = "望乡・光",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_11] = {
    [LANGUAGE_JAPANESE] = "ENISHI" TEXT_CMD_NEWLINE "~サクラとエリーゼのために~",
    [LANGUAGE_ENGLISH] = "Bound by Fate" TEXT_CMD_NEWLINE "(Sakura and Elise)",
    [LANGUAGE_CHINESE] = "ENISHI" TEXT_CMD_NEWLINE "~为了樱和艾丽泽~",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_12] = {
    [LANGUAGE_JAPANESE] = "水底の希求",
    [LANGUAGE_ENGLISH] = "Desire Below",
    [LANGUAGE_CHINESE] = "水底的希冀",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_13] = {
    [LANGUAGE_JAPANESE] = "窓辺には木漏れ日を",
    [LANGUAGE_ENGLISH] = "Light on a Window",
    [LANGUAGE_CHINESE] = "在窗边洒入林间隙光",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_14] = {
    [LANGUAGE_JAPANESE] = "その来たるべき終焉を",
    [LANGUAGE_ENGLISH] = "Coming Demise",
    [LANGUAGE_CHINESE] = "注定要来的终结",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_15] = {
    [LANGUAGE_JAPANESE] = "揺蕩う幻",
    [LANGUAGE_ENGLISH] = "Flickering Illusion",
    [LANGUAGE_CHINESE] = "摇摆的幻影",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_01] = {
    [LANGUAGE_JAPANESE] = "潮風と旅人",
    [LANGUAGE_ENGLISH] = "Sea Winds and Travelers",
    [LANGUAGE_CHINESE] = "海风与旅人",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_02] = {
    [LANGUAGE_JAPANESE] = "戦備 解",
    [LANGUAGE_ENGLISH] = "Preparations: Deliverance",
    [LANGUAGE_CHINESE] = "备战 解",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_03] = {
    [LANGUAGE_JAPANESE] = "戦備 祈",
    [LANGUAGE_ENGLISH] = "Preparations: Pilgrimage",
    [LANGUAGE_CHINESE] = "备战 祈",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_04] = {
    [LANGUAGE_JAPANESE] = "御心のままに",
    [LANGUAGE_ENGLISH] = "As You Will It",
    [LANGUAGE_CHINESE] = "如您所愿",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_05] = {
    [LANGUAGE_JAPANESE] = "春陽",
    [LANGUAGE_ENGLISH] = "Spring Radiance",
    [LANGUAGE_CHINESE] = "春阳",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_06] = {
    [LANGUAGE_JAPANESE] = "Echoes",
    [LANGUAGE_ENGLISH] = "Echoes",
    [LANGUAGE_CHINESE] = "Echoes",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_07] = {
    [LANGUAGE_JAPANESE] = "兄妹",
    [LANGUAGE_ENGLISH] = "Brother and Sister",
    [LANGUAGE_CHINESE] = "兄妹",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_08] = {
    [LANGUAGE_JAPANESE] = "静穏",
    [LANGUAGE_ENGLISH] = "Serenity",
    [LANGUAGE_CHINESE] = "安稳",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_09] = {
    [LANGUAGE_JAPANESE] = "日常",
    [LANGUAGE_ENGLISH] = "An Ordinary Day",
    [LANGUAGE_CHINESE] = "日常",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_11] = {
    [LANGUAGE_JAPANESE] = "戦備 邂逅",
    [LANGUAGE_ENGLISH] = "Preparations: Reunion",
    [LANGUAGE_CHINESE] = "备战 邂逅",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_12] = {
    [LANGUAGE_JAPANESE] = "銀の庭であなたと",
    [LANGUAGE_ENGLISH] = "In a Silver Garden" TEXT_CMD_NEWLINE "with You",
    [LANGUAGE_CHINESE] = "与你在银色庭园",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_01] = {
    [LANGUAGE_JAPANESE] = "その疾きこと風の如く",
    [LANGUAGE_ENGLISH] = "As Swift as Wind",
    [LANGUAGE_CHINESE] = "疾如风",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_02] = {
    [LANGUAGE_JAPANESE] = "ガルグ=マク大修道院の日常",
    [LANGUAGE_ENGLISH] = "Life at Garreg Mach" TEXT_CMD_NEWLINE "Monastery",
    [LANGUAGE_CHINESE] = "加尔古‧玛库大修道院的日常",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_03] = {
    [LANGUAGE_JAPANESE] = "侵掠すること火の如く",
    [LANGUAGE_ENGLISH] = "As Fierce as Fire",
    [LANGUAGE_CHINESE] = "侵略如火",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_04] = {
    [LANGUAGE_JAPANESE] = "市場の人々",
    [LANGUAGE_ENGLISH] = "People of the Marketplace",
    [LANGUAGE_CHINESE] = "市场的人们",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_05] = {
    [LANGUAGE_JAPANESE] = "湯気ごしの幸福",
    [LANGUAGE_ENGLISH] = "Teatime Joy",
    [LANGUAGE_CHINESE] = "热气腾腾的幸福",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_06] = {
    [LANGUAGE_JAPANESE] = "約束",
    [LANGUAGE_ENGLISH] = "A Promise",
    [LANGUAGE_CHINESE] = "约定",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_07] = {
    [LANGUAGE_JAPANESE] = "星影の守り人",
    [LANGUAGE_ENGLISH] = "Guardian of Starlight",
    [LANGUAGE_CHINESE] = "星影守护者",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_08] = {
    [LANGUAGE_JAPANESE] = "迫る暗雲",
    [LANGUAGE_ENGLISH] = "Dark Clouds Gather",
    [LANGUAGE_CHINESE] = "乌云将至",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_09] = {
    [LANGUAGE_JAPANESE] = "安息と陽だまり",
    [LANGUAGE_ENGLISH] = "Respite and Sunlight",
    [LANGUAGE_CHINESE] = "安歇与向阳处",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_10] = {
    [LANGUAGE_JAPANESE] = "覚醒",
    [LANGUAGE_ENGLISH] = "Awakening",
    [LANGUAGE_CHINESE] = "觉醒",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_12] = {
    [LANGUAGE_JAPANESE] = "策略",
    [LANGUAGE_ENGLISH] = "Tactics",
    [LANGUAGE_CHINESE] = "策略",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_13] = {
    [LANGUAGE_JAPANESE] = "緊迫",
    [LANGUAGE_ENGLISH] = "Anxiety",
    [LANGUAGE_CHINESE] = "紧迫",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_14] = {
    [LANGUAGE_JAPANESE] = "蒸し風呂の静寂",
    [LANGUAGE_ENGLISH] = "Steam Baths Respite",
    [LANGUAGE_CHINESE] = "蒸气浴里的寂静",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_15] = {
    [LANGUAGE_JAPANESE] = "未来へのしるべ",
    [LANGUAGE_ENGLISH] = "A Guide for the Future",
    [LANGUAGE_CHINESE] = "迈向未来的路标",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_01] = {
    [LANGUAGE_JAPANESE] = "紋章の試練",
    [LANGUAGE_ENGLISH] = "Trial of Emblems",
    [LANGUAGE_CHINESE] = "纹章的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_02] = {
    [LANGUAGE_JAPANESE] = "響きの試練",
    [LANGUAGE_ENGLISH] = "Trial of Echoes",
    [LANGUAGE_CHINESE] = "声响的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_03] = {
    [LANGUAGE_JAPANESE] = "聖戦の試練",
    [LANGUAGE_ENGLISH] = "Trial of the Holy War",
    [LANGUAGE_CHINESE] = "圣战的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_04] = {
    [LANGUAGE_JAPANESE] = "系譜の試練",
    [LANGUAGE_ENGLISH] = "Trial of Genealogy",
    [LANGUAGE_CHINESE] = "系谱的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_05] = {
    [LANGUAGE_JAPANESE] = "封印の試練",
    [LANGUAGE_ENGLISH] = "Trial of Binding",
    [LANGUAGE_CHINESE] = "封印的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_06] = {
    [LANGUAGE_JAPANESE] = "烈火の試練",
    [LANGUAGE_ENGLISH] = "Trial of Blazing",
    [LANGUAGE_CHINESE] = "烈火的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_07] = {
    [LANGUAGE_JAPANESE] = "聖魔の試練",
    [LANGUAGE_ENGLISH] = "Trial of the Sacred",
    [LANGUAGE_CHINESE] = "圣魔的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_08] = {
    [LANGUAGE_JAPANESE] = "蒼炎の試練",
    [LANGUAGE_ENGLISH] = "Trial of Radiance",
    [LANGUAGE_CHINESE] = "苍炎的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_09] = {
    [LANGUAGE_JAPANESE] = "暁の試練",
    [LANGUAGE_ENGLISH] = "Trial of Dawn",
    [LANGUAGE_CHINESE] = "拂晓的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_10] = {
    [LANGUAGE_JAPANESE] = "覚醒の試練",
    [LANGUAGE_ENGLISH] = "Trial of Awakening",
    [LANGUAGE_CHINESE] = "觉醒的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_11] = {
    [LANGUAGE_JAPANESE] = "選択の試練",
    [LANGUAGE_ENGLISH] = "Trial of Fates",
    [LANGUAGE_CHINESE] = "选择的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_12] = {
    [LANGUAGE_JAPANESE] = "風花の試練",
    [LANGUAGE_ENGLISH] = "Trial of the Academy",
    [LANGUAGE_CHINESE] = "风花的试炼",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_13] = {
    [LANGUAGE_JAPANESE] = "臨戦",
    [LANGUAGE_ENGLISH] = "Preparations",
    [LANGUAGE_CHINESE] = "备战",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_15] = {
    [LANGUAGE_JAPANESE] = "お昼の見回りですか、神竜様",
    [LANGUAGE_ENGLISH] = "On Day Patrol," TEXT_CMD_NEWLINE "Divine One?",
    [LANGUAGE_CHINESE] = "神龙大人,您在午间巡逻吗?",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_16] = {
    [LANGUAGE_JAPANESE] = "軍事国家",
    [LANGUAGE_ENGLISH] = "Mighty Governance",
    [LANGUAGE_CHINESE] = "军事国家",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_18] = {
    [LANGUAGE_JAPANESE] = "目覚めし光芒",
    [LANGUAGE_ENGLISH] = "A Beacon of" TEXT_CMD_NEWLINE "Light Awakens",
    [LANGUAGE_CHINESE] = "苏醒的光芒",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_19] = {
    [LANGUAGE_JAPANESE] = "今日も鍛錬に励もうか!",
    [LANGUAGE_ENGLISH] = "Another Day of Training?",
    [LANGUAGE_CHINESE] = "今天也要努力锻炼喔!",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_20] = {
    [LANGUAGE_JAPANESE] = "邪竜の狗たち",
    [LANGUAGE_ENGLISH] = "The Fell Dragon's Hounds",
    [LANGUAGE_CHINESE] = "邪龙的走狗",
},

[MID_MUSIC_NAME_BGM_MNS_FEA_01] = {
    [LANGUAGE_JAPANESE] = "ファイアーエムブレム" TEXT_CMD_NEWLINE "メインテーマ" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Fire Emblem" TEXT_CMD_NEWLINE "Main Theme" TEXT_CMD_NEWLINE "(Arranged Ver.)",
    [LANGUAGE_CHINESE] = "ファイアーエムブレム" TEXT_CMD_NEWLINE "主题曲" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_MNS_FEH_01] = {
    [LANGUAGE_JAPANESE] = "ハゥリングギア" TEXT_CMD_NEWLINE "(Danceable" TEXT_CMD_NEWLINE "Remix)",
    [LANGUAGE_ENGLISH] = "Howling Gears" TEXT_CMD_NEWLINE "(Danceable Remix)",
    [LANGUAGE_CHINESE] = "怒吼的齿轮" TEXT_CMD_NEWLINE "(DanceableRemix)",
},

[MID_MUSIC_NAME_BGM_TB_AF21_INGAME] = {
    [LANGUAGE_JAPANESE] = "ハゥリングギア" TEXT_CMD_NEWLINE "(Danceable" TEXT_CMD_NEWLINE "Remix)",
    [LANGUAGE_ENGLISH] = "Howling Gears" TEXT_CMD_NEWLINE "(Danceable Remix)",
    [LANGUAGE_CHINESE] = "怒吼的齿轮" TEXT_CMD_NEWLINE "(DanceableRemix)",
},

[MID_MUSIC_NAME_BGM_TB_FE09_01] = {
    [LANGUAGE_JAPANESE] = "Life Returns",
    [LANGUAGE_ENGLISH] = "Life Returns",
    [LANGUAGE_CHINESE] = "Life Returns",
},

[MID_MUSIC_NAME_BGM_TB_FE15_01] = {
    [LANGUAGE_JAPANESE] = "アルカディアの継ぎびと",
    [LANGUAGE_ENGLISH] = "The Heritors of Arcadia",
    [LANGUAGE_CHINESE] = "阿卡迪亚的传承者",
},

[MID_MUSIC_NAME_BGM_TB_FE16_01] = {
    [LANGUAGE_JAPANESE] = "ファイアーエムブレム 風花雪月" TEXT_CMD_NEWLINE "メインテーマ",
    [LANGUAGE_ENGLISH] = "Fire Emblem:" TEXT_CMD_NEWLINE "Three Houses" TEXT_CMD_NEWLINE "Main Theme",
    [LANGUAGE_CHINESE] = "FIRE EMBLEM 风花雪月" TEXT_CMD_NEWLINE "主题曲",
},

[MID_MUSIC_NAME_BGM_TB_FE16_02] = {
    [LANGUAGE_JAPANESE] = "フレスベルグの少女" TEXT_CMD_NEWLINE "~風花雪月~",
    [LANGUAGE_ENGLISH] = "The Edge of Dawn" TEXT_CMD_NEWLINE "(Seasons of Warfare)" TEXT_CMD_NEWLINE "(Short Version)",
    [LANGUAGE_CHINESE] = "弗雷斯贝尔古的少女" TEXT_CMD_NEWLINE "~风花雪月~",
},

[MID_MUSIC_NAME_BGM_TB_FEA_01] = {
    [LANGUAGE_JAPANESE] = "貴様らが..." TEXT_CMD_NEWLINE "姉さんの言葉を語るな!" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "\"Don't speak her name!\"" TEXT_CMD_NEWLINE "(Arranged)",
    [LANGUAGE_CHINESE] = "你们这些家伙......" TEXT_CMD_NEWLINE "不准谈论我的姊姊!" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_02] = {
    [LANGUAGE_JAPANESE] = "真実 絶望 そして希望" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Truth, Despair, and Hope" TEXT_CMD_NEWLINE "(Arranged)",
    [LANGUAGE_CHINESE] = "真实 绝望 以及希望" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_03] = {
    [LANGUAGE_JAPANESE] = "正義は此処に~颯" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Justice RIP (Storm)" TEXT_CMD_NEWLINE "(Arranged)",
    [LANGUAGE_CHINESE] = "正义在此~飒" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_04] = {
    [LANGUAGE_JAPANESE] = "新たなる歴史を刻む者" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Those Who Dare to" TEXT_CMD_NEWLINE "Change History" TEXT_CMD_NEWLINE "(Arranged)",
    [LANGUAGE_CHINESE] = "铭刻崭新历史之人" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_05] = {
    [LANGUAGE_JAPANESE] = "フォドラの暁風" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Fódlan Winds (Arranged)",
    [LANGUAGE_CHINESE] = "芙朵拉的晓风" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_06] = {
    [LANGUAGE_JAPANESE] = "ミラの加護とともに" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "With Mila's Divine" TEXT_CMD_NEWLINE "Protection (Arranged)",
    [LANGUAGE_CHINESE] = "与美拉的加护同在" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_07] = {
    [LANGUAGE_JAPANESE] = "新たなる光の下へ(ロイの勇気)" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Beneath a New Light" TEXT_CMD_NEWLINE "(Roy's Courage)" TEXT_CMD_NEWLINE "(Arranged)",
    [LANGUAGE_CHINESE] = "迈向崭新的光芒照耀之处(罗伊的勇气)" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_08] = {
    [LANGUAGE_JAPANESE] = "絆永久に" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "Eternal Bond (Arranged)",
    [LANGUAGE_CHINESE] = "使羁绊长久永存" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEA_09] = {
    [LANGUAGE_JAPANESE] = "終章(最後の聖戦)" TEXT_CMD_NEWLINE "(アレンジバージョン)",
    [LANGUAGE_ENGLISH] = "End of the Holy War" TEXT_CMD_NEWLINE "(Arranged)",
    [LANGUAGE_CHINESE] = "终章(最后的圣战)" TEXT_CMD_NEWLINE "(改编版本)",
},

[MID_MUSIC_NAME_BGM_TB_FEG_01] = {
    [LANGUAGE_JAPANESE] = "Feel",
    [LANGUAGE_ENGLISH] = "Feel",
    [LANGUAGE_CHINESE] = "Feel",
},

[MID_MUSIC_NAME_BGM_TB_FEG_02] = {
    [LANGUAGE_JAPANESE] = "ドリーム☆キャッチャー",
    [LANGUAGE_ENGLISH] = "Dream Catcher",
    [LANGUAGE_CHINESE] = "追梦☆少女",
},

[MID_MUSIC_NAME_BGM_TB_FEG_03] = {
    [LANGUAGE_JAPANESE] = "雨音のメモリー",
    [LANGUAGE_ENGLISH] = "Raindrop Memories",
    [LANGUAGE_CHINESE] = "雨声的Memory",
},

[MID_MUSIC_NAME_BGM_TB_FEG_04] = {
    [LANGUAGE_JAPANESE] = "Reincarnation",
    [LANGUAGE_ENGLISH] = "Reincarnation",
    [LANGUAGE_CHINESE] = "Reincarnation",
},

[MID_MUSIC_NAME_BGM_TB_FEG_05] = {
    [LANGUAGE_JAPANESE] = "Smile Smile",
    [LANGUAGE_ENGLISH] = "Smile for Me",
    [LANGUAGE_CHINESE] = "Smile Smile",
},

[MID_MUSIC_NAME_BGM_TB_FEG_06] = {
    [LANGUAGE_JAPANESE] = "ファイアーエムブレム" TEXT_CMD_NEWLINE "~光の戯曲~",
    [LANGUAGE_ENGLISH] = "Fire Emblem:" TEXT_CMD_NEWLINE "Opera of Light",
    [LANGUAGE_CHINESE] = "Fire Emblem" TEXT_CMD_NEWLINE "~光之戏曲~",
},

[MID_MUSIC_NAME_BGM_TB_FEG_07] = {
    [LANGUAGE_JAPANESE] = "幻じゃない世界",
    [LANGUAGE_ENGLISH] = "This World Isn't an Illusion",
    [LANGUAGE_CHINESE] = "不虚幻的世界",
},

[MID_MUSIC_NAME_BGM_TB_FEG_08] = {
    [LANGUAGE_JAPANESE] = "ディア☆マジョ! Sweet♡" TEXT_CMD_NEWLINE "Kiria Ver.",
    [LANGUAGE_ENGLISH] = "Dia Sweet Witch" TEXT_CMD_NEWLINE "(Kiria Ver.)",
    [LANGUAGE_CHINESE] = "迪亚☆魔女!Sweet♡" TEXT_CMD_NEWLINE "Kiria Ver.",
},

[MID_MUSIC_NAME_BGM_TB_FEG_09] = {
    [LANGUAGE_JAPANESE] = "She is...",
    [LANGUAGE_ENGLISH] = "She Is...",
    [LANGUAGE_CHINESE] = "She is......",
},
