// This file is generated by make_texts.py
// Text type: TextType.MUSIC

[MID_MUSIC_NAME_BGM_EVENT_PLAIN_01] = {
    [LANGUAGE_JAPANESE] = "ヴァイスブレイヴ",
    [LANGUAGE_ENGLISH] = "Order of Heroes",
    [LANGUAGE_CHINESE] = "纯白义勇队",
},

[MID_MUSIC_NAME_BGM_EVENT_SERIOUS_02] = {
    [LANGUAGE_JAPANESE] = "ヴェロニカ",
    [LANGUAGE_ENGLISH] = "Veronica",
    [LANGUAGE_CHINESE] = "维洛妮卡",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_01] = {
    [LANGUAGE_JAPANESE] = "ウィンドオブアスク",
    [LANGUAGE_ENGLISH] = "Winds of Askr",
    [LANGUAGE_CHINESE] = "亚斯克的风",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_02] = {
    [LANGUAGE_JAPANESE] = "グランドオブアスク",
    [LANGUAGE_ENGLISH] = "The Grandeur of Askr",
    [LANGUAGE_CHINESE] = "雄伟的亚斯克",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_03] = {
    [LANGUAGE_JAPANESE] = "ラストフェイズ",
    [LANGUAGE_ENGLISH] = "Last Phase",
    [LANGUAGE_CHINESE] = "末世",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_04] = {
    [LANGUAGE_JAPANESE] = "リターントゥニフル",
    [LANGUAGE_ENGLISH] = "Return To Nifl",
    [LANGUAGE_CHINESE] = "回到尼福尔",
},

[MID_MUSIC_NAME_BGM_MAP_BRAVE_05] = {
    [LANGUAGE_JAPANESE] = "トラジディオブアスク",
    [LANGUAGE_ENGLISH] = "Tragedy of Askr",
    [LANGUAGE_CHINESE] = "亚斯克的悲剧",
},

[MID_MUSIC_NAME_BGM_MAP_FE04_05] = {
    [LANGUAGE_JAPANESE] = "第3章(獅子王エルトシャン)",
    [LANGUAGE_ENGLISH] = "Chapter 3" TEXT_CMD_NEWLINE "Eldigan, the Lionheart",
    [LANGUAGE_CHINESE] = "第3章(狮子王艾尔多尚)",
},

[MID_MUSIC_NAME_BGM_MAP_FE07_01] = {
    [LANGUAGE_JAPANESE] = "大切なもの",
    [LANGUAGE_ENGLISH] = "Precious Things",
    [LANGUAGE_CHINESE] = "重要的事物",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_01] = {
    [LANGUAGE_JAPANESE] = "A Battle and" TEXT_CMD_NEWLINE "a Beginning",
    [LANGUAGE_ENGLISH] = "A Battle and a Beginning",
    [LANGUAGE_CHINESE] = "A Battle and" TEXT_CMD_NEWLINE "a Beginning",
},

[MID_MUSIC_NAME_BGM_MAP_FE09_02] = {
    [LANGUAGE_JAPANESE] = "Greil’s" TEXT_CMD_NEWLINE "Mercenaries",
    [LANGUAGE_ENGLISH] = "Greil Mercenaries",
    [LANGUAGE_CHINESE] = "Greil's Mercenaries",
},

[MID_MUSIC_NAME_BGM_MAP_FE10_05] = {
    [LANGUAGE_JAPANESE] = "強き思いここに",
    [LANGUAGE_ENGLISH] = "Bearer of Hope",
    [LANGUAGE_CHINESE] = "于此的信念",
},

[MID_MUSIC_NAME_BGM_MAP_FE11_01] = {
    [LANGUAGE_JAPANESE] = "決起のとき",
    [LANGUAGE_ENGLISH] = "The Time to Act",
    [LANGUAGE_CHINESE] = "起义之时",
},

[MID_MUSIC_NAME_BGM_MAP_FE12_01] = {
    [LANGUAGE_JAPANESE] = "進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "进击",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_01] = {
    [LANGUAGE_JAPANESE] = "宿命~炎",
    [LANGUAGE_ENGLISH] = "Destiny (Ablaze)",
    [LANGUAGE_CHINESE] = "宿命~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_02] = {
    [LANGUAGE_JAPANESE] = "序幕~炎",
    [LANGUAGE_ENGLISH] = "Prelude (Ablaze)",
    [LANGUAGE_CHINESE] = "序幕~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE13_06] = {
    [LANGUAGE_JAPANESE] = "天命~炎",
    [LANGUAGE_ENGLISH] = "Divine Decree (Ablaze)",
    [LANGUAGE_CHINESE] = "天命~炎",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_01] = {
    [LANGUAGE_JAPANESE] = "遠い夜明け~颯",
    [LANGUAGE_ENGLISH] = "Far Dawn (Storm)",
    [LANGUAGE_CHINESE] = "遥远的黎明~疾风",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_02] = {
    [LANGUAGE_JAPANESE] = "黄昏をつれて~焔",
    [LANGUAGE_ENGLISH] = "Dusk Falls (Fire)",
    [LANGUAGE_CHINESE] = "黄昏降临~焰",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_06] = {
    [LANGUAGE_JAPANESE] = "輝く大地を越えて~颯",
    [LANGUAGE_ENGLISH] = "Past Light (Storm)",
    [LANGUAGE_CHINESE] = "越过闪耀的大地~飒",
},

[MID_MUSIC_NAME_BGM_MAP_FE14_07] = {
    [LANGUAGE_JAPANESE] = "光亡き荒野の果てに~焔",
    [LANGUAGE_ENGLISH] = "Dark Wastes (Fire)",
    [LANGUAGE_CHINESE] = "永暗荒野的尽头~焔",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_02] = {
    [LANGUAGE_JAPANESE] = "ミラの加護とともに",
    [LANGUAGE_ENGLISH] = "With Mila's Divine Protection",
    [LANGUAGE_CHINESE] = "与美拉的加护同在",
},

[MID_MUSIC_NAME_BGM_MAP_FE15_03] = {
    [LANGUAGE_JAPANESE] = "往く地の果てには",
    [LANGUAGE_ENGLISH] = "What Lies at the End",
    [LANGUAGE_CHINESE] = "于前往之地的尽头",
},

[MID_MUSIC_NAME_BGM_MAP_FE16_01] = {
    [LANGUAGE_JAPANESE] = "フォドラの暁風",
    [LANGUAGE_ENGLISH] = "Fódlan Winds",
    [LANGUAGE_CHINESE] = "芙朵拉的晓风",
},

[MID_MUSIC_NAME_BGM_MAP_FES_02] = {
    [LANGUAGE_JAPANESE] = "モアファンフェスト",
    [LANGUAGE_ENGLISH] = "More Fan Fest",
    [LANGUAGE_CHINESE] = "More Fan Fest",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_01] = {
    [LANGUAGE_JAPANESE] = "アカネイア序曲",
    [LANGUAGE_ENGLISH] = "Archanean Overture",
    [LANGUAGE_CHINESE] = "阿卡奈亚序曲",
},

[MID_MUSIC_NAME_BGM_MNS_FE03_02] = {
    [LANGUAGE_JAPANESE] = "神竜伝説(A)",
    [LANGUAGE_ENGLISH] = "Legend of the" TEXT_CMD_NEWLINE "Dragon God (A)",
    [LANGUAGE_CHINESE] = "神龙传说(A)",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_01] = {
    [LANGUAGE_JAPANESE] = "栄光なるグランベル",
    [LANGUAGE_ENGLISH] = "Glory to Grannvale",
    [LANGUAGE_CHINESE] = "格兰贝鲁的荣耀",
},

[MID_MUSIC_NAME_BGM_MNS_FE04_05] = {
    [LANGUAGE_JAPANESE] = "デュー&パティ",
    [LANGUAGE_ENGLISH] = "Dew and Patty",
    [LANGUAGE_CHINESE] = "迪优&帕蒂",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_04] = {
    [LANGUAGE_JAPANESE] = "トラキア776 始まり",
    [LANGUAGE_ENGLISH] = "Thracia 776 Begins",
    [LANGUAGE_CHINESE] = "トラキア776 起始",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_05] = {
    [LANGUAGE_JAPANESE] = "戦いの中で 運命",
    [LANGUAGE_ENGLISH] = "Battle: Destiny",
    [LANGUAGE_CHINESE] = "战斗之中 命运",
},

[MID_MUSIC_NAME_BGM_MNS_FE05_06] = {
    [LANGUAGE_JAPANESE] = "戦いの中で 進撃",
    [LANGUAGE_ENGLISH] = "Battle: Advance",
    [LANGUAGE_CHINESE] = "战斗之中 进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE06_02] = {
    [LANGUAGE_JAPANESE] = "I進撃",
    [LANGUAGE_ENGLISH] = "Advance",
    [LANGUAGE_CHINESE] = "I进击",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_01] = {
    [LANGUAGE_JAPANESE] = "黒い牙",
    [LANGUAGE_ENGLISH] = "Black Fang",
    [LANGUAGE_CHINESE] = "黑牙",
},

[MID_MUSIC_NAME_BGM_MNS_FE07_04] = {
    [LANGUAGE_JAPANESE] = "大賢者アトス",
    [LANGUAGE_ENGLISH] = "The Archsage Athos",
    [LANGUAGE_CHINESE] = "大贤者亚托思",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_02] = {
    [LANGUAGE_JAPANESE] = "すべては始まりのとき",
    [LANGUAGE_ENGLISH] = "The Beginning",
    [LANGUAGE_CHINESE] = "一切皆在开端之时",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_03] = {
    [LANGUAGE_JAPANESE] = "リオン(オルゴールアレンジ)",
    [LANGUAGE_ENGLISH] = "Lyon (Organ Arrangement)",
    [LANGUAGE_CHINESE] = "利昂(水晶音乐改编版)",
},

[MID_MUSIC_NAME_BGM_MNS_FE08_05] = {
    [LANGUAGE_JAPANESE] = "Sadness time",
    [LANGUAGE_ENGLISH] = "Sorrow",
    [LANGUAGE_CHINESE] = "Sadness time",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_04] = {
    [LANGUAGE_JAPANESE] = "For Victory",
    [LANGUAGE_ENGLISH] = "For Victory",
    [LANGUAGE_CHINESE] = "For Victory",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_06] = {
    [LANGUAGE_JAPANESE] = "Quiet Days",
    [LANGUAGE_ENGLISH] = "Quiet Days",
    [LANGUAGE_CHINESE] = "Quiet Days",
},

[MID_MUSIC_NAME_BGM_MNS_FE09_08] = {
    [LANGUAGE_JAPANESE] = "Wonderful" TEXT_CMD_NEWLINE "Pirates",
    [LANGUAGE_ENGLISH] = "Wonderful Pirates",
    [LANGUAGE_CHINESE] = "Wonderful" TEXT_CMD_NEWLINE "Pirates",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_02] = {
    [LANGUAGE_JAPANESE] = "忘我な夢",
    [LANGUAGE_ENGLISH] = "Cats at Play",
    [LANGUAGE_CHINESE] = "忘我的梦",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_03] = {
    [LANGUAGE_JAPANESE] = "心穏やかなるとき",
    [LANGUAGE_ENGLISH] = "At Peace",
    [LANGUAGE_CHINESE] = "心静时刻",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_04] = {
    [LANGUAGE_JAPANESE] = "道標に光そそぎて",
    [LANGUAGE_ENGLISH] = "Neutiquam Erro",
    [LANGUAGE_CHINESE] = "光芒洒落于路标",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_05] = {
    [LANGUAGE_JAPANESE] = "セフェラン浮遊する意識",
    [LANGUAGE_ENGLISH] = "Sephiran's Sorrow",
    [LANGUAGE_CHINESE] = "瑟菲兰漂浮的意识",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_06] = {
    [LANGUAGE_JAPANESE] = "憤怒の目",
    [LANGUAGE_ENGLISH] = "Eyes of Rage",
    [LANGUAGE_CHINESE] = "愤怒之眼",
},

[MID_MUSIC_NAME_BGM_MNS_FE10_08] = {
    [LANGUAGE_JAPANESE] = "奇才イズカ",
    [LANGUAGE_ENGLISH] = "The Mind of Izuka",
    [LANGUAGE_CHINESE] = "奇才伊兹卡",
},

[MID_MUSIC_NAME_BGM_MNS_FE11_03] = {
    [LANGUAGE_JAPANESE] = "誇り高き将",
    [LANGUAGE_ENGLISH] = "The Proud Commander",
    [LANGUAGE_CHINESE] = "身怀荣耀的将领",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_04] = {
    [LANGUAGE_JAPANESE] = "進むべき道",
    [LANGUAGE_ENGLISH] = "Going Forward",
    [LANGUAGE_CHINESE] = "应行之道",
},

[MID_MUSIC_NAME_BGM_MNS_FE12_05] = {
    [LANGUAGE_JAPANESE] = "ひとときの安らぎ",
    [LANGUAGE_ENGLISH] = "A Momentary Peace",
    [LANGUAGE_CHINESE] = "一时的安稳",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_02] = {
    [LANGUAGE_JAPANESE] = "力を感じる...私たちと同じ力...",
    [LANGUAGE_ENGLISH] = "\"You have power..." TEXT_CMD_NEWLINE "like mine.\"",
    [LANGUAGE_CHINESE] = "感受到了与我们相同的力量......",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_05] = {
    [LANGUAGE_JAPANESE] = "泊らせてもらおうよ?ね?",
    [LANGUAGE_ENGLISH] = "\"But, Frederick," TEXT_CMD_NEWLINE "it's nearly dark!\"",
    [LANGUAGE_CHINESE] = "我们就去借住嘛?好不好?",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_07] = {
    [LANGUAGE_JAPANESE] = "今日はもう休みましょう",
    [LANGUAGE_ENGLISH] = "We should turn in" TEXT_CMD_NEWLINE "for the night",
    [LANGUAGE_CHINESE] = "今天就休息吧",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_10] = {
    [LANGUAGE_JAPANESE] = "こんなところにも、屍兵が...!",
    [LANGUAGE_ENGLISH] = "Gods, have the Risen" TEXT_CMD_NEWLINE "spread this far?",
    [LANGUAGE_CHINESE] = "这种地方竟也有尸兵......!",
},

[MID_MUSIC_NAME_BGM_MNS_FE13_11] = {
    [LANGUAGE_JAPANESE] = "「I」~安",
    [LANGUAGE_ENGLISH] = "Id (Serenity)",
    [LANGUAGE_CHINESE] = "「I」~安",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_14] = {
    [LANGUAGE_JAPANESE] = "その来たるべき終焉を",
    [LANGUAGE_ENGLISH] = "Coming Demise",
    [LANGUAGE_CHINESE] = "注定要来的终结",
},

[MID_MUSIC_NAME_BGM_MNS_FE14_15] = {
    [LANGUAGE_JAPANESE] = "揺蕩う幻",
    [LANGUAGE_ENGLISH] = "Flickering Illusion",
    [LANGUAGE_CHINESE] = "摇摆的幻影",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_04] = {
    [LANGUAGE_JAPANESE] = "御心のままに",
    [LANGUAGE_ENGLISH] = "As You Will It",
    [LANGUAGE_CHINESE] = "如您所愿",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_06] = {
    [LANGUAGE_JAPANESE] = "Echoes",
    [LANGUAGE_ENGLISH] = "Echoes",
    [LANGUAGE_CHINESE] = "Echoes",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_07] = {
    [LANGUAGE_JAPANESE] = "兄妹",
    [LANGUAGE_ENGLISH] = "Brother and Sister",
    [LANGUAGE_CHINESE] = "兄妹",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_08] = {
    [LANGUAGE_JAPANESE] = "静穏",
    [LANGUAGE_ENGLISH] = "Serenity",
    [LANGUAGE_CHINESE] = "安稳",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_09] = {
    [LANGUAGE_JAPANESE] = "日常",
    [LANGUAGE_ENGLISH] = "An Ordinary Day",
    [LANGUAGE_CHINESE] = "日常",
},

[MID_MUSIC_NAME_BGM_MNS_FE15_11] = {
    [LANGUAGE_JAPANESE] = "戦備 邂逅",
    [LANGUAGE_ENGLISH] = "Preparations: Reunion",
    [LANGUAGE_CHINESE] = "备战 邂逅",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_07] = {
    [LANGUAGE_JAPANESE] = "星影の守り人",
    [LANGUAGE_ENGLISH] = "Guardian of Starlight",
    [LANGUAGE_CHINESE] = "星影守护者",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_08] = {
    [LANGUAGE_JAPANESE] = "迫る暗雲",
    [LANGUAGE_ENGLISH] = "Dark Clouds Gather",
    [LANGUAGE_CHINESE] = "乌云将至",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_10] = {
    [LANGUAGE_JAPANESE] = "覚醒",
    [LANGUAGE_ENGLISH] = "Awakening",
    [LANGUAGE_CHINESE] = "觉醒",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_12] = {
    [LANGUAGE_JAPANESE] = "策略",
    [LANGUAGE_ENGLISH] = "Tactics",
    [LANGUAGE_CHINESE] = "策略",
},

[MID_MUSIC_NAME_BGM_MNS_FE16_13] = {
    [LANGUAGE_JAPANESE] = "緊迫",
    [LANGUAGE_ENGLISH] = "Anxiety",
    [LANGUAGE_CHINESE] = "紧迫",
},

[MID_MUSIC_NAME_BGM_MNS_FE17_16] = {
    [LANGUAGE_JAPANESE] = "軍事国家",
    [LANGUAGE_ENGLISH] = "Mighty Governance",
    [LANGUAGE_CHINESE] = "军事国家",
},
