#pragma once

extern const unsigned int TextGlyphs_System_E382A1Tiles[]; /* ァ */
extern const unsigned int TextGlyphs_System_E285B0Tiles[]; /* ⅰ */
extern const unsigned int TextGlyphs_System_E38080Tiles[]; /* 　 */
extern const unsigned int TextGlyphs_System_E6B395Tiles[]; /* 法 */
extern const unsigned int TextGlyphs_System_E999A2Tiles[]; /* 院 */
extern const unsigned int TextGlyphs_System_E6A99FTiles[]; /* 機 */
extern const unsigned int TextGlyphs_System_E68E98Tiles[]; /* 掘 */
extern const unsigned int TextGlyphs_System_E58FA9Tiles[]; /* 叩 */
extern const unsigned int TextGlyphs_System_E291A0Tiles[]; /* ① */
extern const unsigned int TextGlyphs_System_E893AETiles[]; /* 蓮 */
extern const unsigned int TextGlyphs_System_E382A2Tiles[]; /* ア */
extern const unsigned int TextGlyphs_System_E285B1Tiles[]; /* ⅱ */
extern const unsigned int TextGlyphs_System_E38081Tiles[]; /* 、 */
extern const unsigned int TextGlyphs_System_E999B0Tiles[]; /* 陰 */
extern const unsigned int TextGlyphs_System_E980A3Tiles[]; /* 連 */
extern const unsigned int TextGlyphs_System_E5B8B0Tiles[]; /* 帰 */
extern const unsigned int TextGlyphs_System_E291A1Tiles[]; /* ② */
extern const unsigned int TextGlyphs_System_E8BCB8Tiles[]; /* 輸 */
extern const unsigned int TextGlyphs_System_E7AA9FTiles[]; /* 窟 */
extern const unsigned int TextGlyphs_System_E382A3Tiles[]; /* ィ */
extern const unsigned int TextGlyphs_System_E285B2Tiles[]; /* ⅲ */
extern const unsigned int TextGlyphs_System_E38082Tiles[]; /* 。 */
extern const unsigned int TextGlyphs_System_E594AFTiles[]; /* 唯 */
extern const unsigned int TextGlyphs_System_E98194Tiles[]; /* 達 */
extern const unsigned int TextGlyphs_System_E99AA0Tiles[]; /* 隠 */
extern const unsigned int TextGlyphs_System_E291A2Tiles[]; /* ③ */
extern const unsigned int TextGlyphs_System_E382A4Tiles[]; /* イ */
extern const unsigned int TextGlyphs_System_E285B3Tiles[]; /* ⅳ */
extern const unsigned int TextGlyphs_System_EFBC8CTiles[]; /* ， */
extern const unsigned int TextGlyphs_System_E6B097Tiles[]; /* 気 */
extern const unsigned int TextGlyphs_System_E6B5B7Tiles[]; /* 海 */
extern const unsigned int TextGlyphs_System_E4BFAETiles[]; /* 修 */
extern const unsigned int TextGlyphs_System_E4BBBBTiles[]; /* 任 */
extern const unsigned int TextGlyphs_System_E291A3Tiles[]; /* ④ */
extern const unsigned int TextGlyphs_System_E382A5Tiles[]; /* ゥ */
extern const unsigned int TextGlyphs_System_E285B4Tiles[]; /* ⅴ */
extern const unsigned int TextGlyphs_System_EFBC8ETiles[]; /* ． */
extern const unsigned int TextGlyphs_System_E5A5BDTiles[]; /* 好 */
extern const unsigned int TextGlyphs_System_E5A5AATiles[]; /* 奪 */
extern const unsigned int TextGlyphs_System_E7B994Tiles[]; /* 織 */
extern const unsigned int TextGlyphs_System_E6B3A5Tiles[]; /* 泥 */
extern const unsigned int TextGlyphs_System_E584AATiles[]; /* 優 */
extern const unsigned int TextGlyphs_System_E291A4Tiles[]; /* ⑤ */
extern const unsigned int TextGlyphs_System_E781B0Tiles[]; /* 灰 */
extern const unsigned int TextGlyphs_System_E382A6Tiles[]; /* ウ */
extern const unsigned int TextGlyphs_System_E285B5Tiles[]; /* ⅵ */
extern const unsigned int TextGlyphs_System_E383BBTiles[]; /* ・ */
extern const unsigned int TextGlyphs_System_E58B87Tiles[]; /* 勇 */
extern const unsigned int TextGlyphs_System_E6AEBATiles[]; /* 殺 */
extern const unsigned int TextGlyphs_System_E7958CTiles[]; /* 界 */
extern const unsigned int TextGlyphs_System_E884B1Tiles[]; /* 脱 */
extern const unsigned int TextGlyphs_System_E881B7Tiles[]; /* 職 */
extern const unsigned int TextGlyphs_System_E58FB3Tiles[]; /* 右 */
extern const unsigned int TextGlyphs_System_E291A5Tiles[]; /* ⑥ */
extern const unsigned int TextGlyphs_System_E382A7Tiles[]; /* ェ */
extern const unsigned int TextGlyphs_System_E285B6Tiles[]; /* ⅶ */
extern const unsigned int TextGlyphs_System_EFBC9ATiles[]; /* ： */
extern const unsigned int TextGlyphs_System_E58F8BTiles[]; /* 友 */
extern const unsigned int TextGlyphs_System_E79A86Tiles[]; /* 皆 */
extern const unsigned int TextGlyphs_System_E8AA8DTiles[]; /* 認 */
extern const unsigned int TextGlyphs_System_E5AD9DTiles[]; /* 孝 */
extern const unsigned int TextGlyphs_System_E291A6Tiles[]; /* ⑦ */
extern const unsigned int TextGlyphs_System_E889B2Tiles[]; /* 色 */
extern const unsigned int TextGlyphs_System_E382A8Tiles[]; /* エ */
extern const unsigned int TextGlyphs_System_E285B7Tiles[]; /* ⅷ */
extern const unsigned int TextGlyphs_System_E695B5Tiles[]; /* 敵 */
extern const unsigned int TextGlyphs_System_E99B91Tiles[]; /* 雑 */
extern const unsigned int TextGlyphs_System_E7A780Tiles[]; /* 秀 */
extern const unsigned int TextGlyphs_System_E382A9Tiles[]; /* ォ */
extern const unsigned int TextGlyphs_System_E285B8Tiles[]; /* ⅸ */
extern const unsigned int TextGlyphs_System_EFBC9FTiles[]; /* ？ */
extern const unsigned int TextGlyphs_System_E8B7AFTiles[]; /* 路 */
extern const unsigned int TextGlyphs_System_E7BEBDTiles[]; /* 羽 */
extern const unsigned int TextGlyphs_System_E382AATiles[]; /* オ */
extern const unsigned int TextGlyphs_System_E285B9Tiles[]; /* ⅹ */
extern const unsigned int TextGlyphs_System_EFBC81Tiles[]; /* ！ */
extern const unsigned int TextGlyphs_System_E79A84Tiles[]; /* 的 */
extern const unsigned int TextGlyphs_System_E981B8Tiles[]; /* 選 */
extern const unsigned int TextGlyphs_System_E7B582Tiles[]; /* 終 */
extern const unsigned int TextGlyphs_System_E89C82Tiles[]; /* 蜂 */
extern const unsigned int TextGlyphs_System_E382ABTiles[]; /* カ */
extern const unsigned int TextGlyphs_System_E8B0B7Tiles[]; /* 谷 */
extern const unsigned int TextGlyphs_System_E9968BTiles[]; /* 開 */
extern const unsigned int TextGlyphs_System_E58AB4Tiles[]; /* 労 */
extern const unsigned int TextGlyphs_System_E99BA8Tiles[]; /* 雨 */
extern const unsigned int TextGlyphs_System_E291AATiles[]; /* ⑪ */
extern const unsigned int TextGlyphs_System_E3829BTiles[]; /* ゛ */
extern const unsigned int TextGlyphs_System_E382ACTiles[]; /* ガ */
extern const unsigned int TextGlyphs_System_E68F96Tiles[]; /* 揖 */
extern const unsigned int TextGlyphs_System_E5BF85Tiles[]; /* 必 */
extern const unsigned int TextGlyphs_System_E5B9B8Tiles[]; /* 幸 */
extern const unsigned int TextGlyphs_System_E8A8AATiles[]; /* 訪 */
extern const unsigned int TextGlyphs_System_E8A68FTiles[]; /* 規 */
extern const unsigned int TextGlyphs_System_E99A8ETiles[]; /* 階 */
extern const unsigned int TextGlyphs_System_E291ABTiles[]; /* ⑫ */
extern const unsigned int TextGlyphs_System_E3829CTiles[]; /* ゜ */
extern const unsigned int TextGlyphs_System_E7BF92Tiles[]; /* 習 */
extern const unsigned int TextGlyphs_System_E382ADTiles[]; /* キ */
extern const unsigned int TextGlyphs_System_E8B18ATiles[]; /* 豊 */
extern const unsigned int TextGlyphs_System_E8A898Tiles[]; /* 記 */
extern const unsigned int TextGlyphs_System_E69C89Tiles[]; /* 有 */
extern const unsigned int TextGlyphs_System_E5BA83Tiles[]; /* 広 */
extern const unsigned int TextGlyphs_System_E291ACTiles[]; /* ⑬ */
extern const unsigned int TextGlyphs_System_E78CABTiles[]; /* 猫 */
extern const unsigned int TextGlyphs_System_E382AETiles[]; /* ギ */
extern const unsigned int TextGlyphs_System_E8B2B4Tiles[]; /* 貴 */
extern const unsigned int TextGlyphs_System_E4BFA1Tiles[]; /* 信 */
extern const unsigned int TextGlyphs_System_E786B1Tiles[]; /* 熱 */
extern const unsigned int TextGlyphs_System_E587B1Tiles[]; /* 凱 */
extern const unsigned int TextGlyphs_System_E58BB2Tiles[]; /* 勲 */
extern const unsigned int TextGlyphs_System_E291ADTiles[]; /* ⑭ */
extern const unsigned int TextGlyphs_System_E382AFTiles[]; /* ク */
extern const unsigned int TextGlyphs_System_E5B9B4Tiles[]; /* 年 */
extern const unsigned int TextGlyphs_System_E4BEB5Tiles[]; /* 侵 */
extern const unsigned int TextGlyphs_System_E8B5B7Tiles[]; /* 起 */
extern const unsigned int TextGlyphs_System_E5909BTiles[]; /* 君 */
extern const unsigned int TextGlyphs_System_E8AAB0Tiles[]; /* 誰 */
extern const unsigned int TextGlyphs_System_E291AETiles[]; /* ⑮ */
extern const unsigned int TextGlyphs_System_E69C97Tiles[]; /* 朗 */
extern const unsigned int TextGlyphs_System_E382B0Tiles[]; /* グ */
extern const unsigned int TextGlyphs_System_EFBC90Tiles[]; /* ０ */
extern const unsigned int TextGlyphs_System_E5898DTiles[]; /* 前 */
extern const unsigned int TextGlyphs_System_E5A496Tiles[]; /* 外 */
extern const unsigned int TextGlyphs_System_E5BFB5Tiles[]; /* 念 */
extern const unsigned int TextGlyphs_System_E4B889Tiles[]; /* 三 */
extern const unsigned int TextGlyphs_System_E291AFTiles[]; /* ⑯ */
extern const unsigned int TextGlyphs_System_E382B1Tiles[]; /* ケ */
extern const unsigned int TextGlyphs_System_EFBC91Tiles[]; /* １ */
extern const unsigned int TextGlyphs_System_E5A7ABTiles[]; /* 姫 */
extern const unsigned int TextGlyphs_System_E59684Tiles[]; /* 善 */
extern const unsigned int TextGlyphs_System_E58D98Tiles[]; /* 単 */
extern const unsigned int TextGlyphs_System_E291B0Tiles[]; /* ⑰ */
extern const unsigned int TextGlyphs_System_E382B2Tiles[]; /* ゲ */
extern const unsigned int TextGlyphs_System_EFBC92Tiles[]; /* ２ */
extern const unsigned int TextGlyphs_System_E59886Tiles[]; /* 嘆 */
extern const unsigned int TextGlyphs_System_E58F82Tiles[]; /* 参 */
extern const unsigned int TextGlyphs_System_E5AEB3Tiles[]; /* 害 */
extern const unsigned int TextGlyphs_System_E6B5AATiles[]; /* 浪 */
extern const unsigned int TextGlyphs_System_E7BEA4Tiles[]; /* 群 */
extern const unsigned int TextGlyphs_System_E382B3Tiles[]; /* コ */
extern const unsigned int TextGlyphs_System_EFBC93Tiles[]; /* ３ */
extern const unsigned int TextGlyphs_System_E8BB8DTiles[]; /* 軍 */
extern const unsigned int TextGlyphs_System_E9A88ETiles[]; /* 騎 */
extern const unsigned int TextGlyphs_System_E5B1B1Tiles[]; /* 山 */
extern const unsigned int TextGlyphs_System_E784B6Tiles[]; /* 然 */
extern const unsigned int TextGlyphs_System_E794B1Tiles[]; /* 由 */
extern const unsigned int TextGlyphs_System_E68A97Tiles[]; /* 抗 */
extern const unsigned int TextGlyphs_System_E382B4Tiles[]; /* ゴ */
extern const unsigned int TextGlyphs_System_EFBC94Tiles[]; /* ４ */
extern const unsigned int TextGlyphs_System_E585A8Tiles[]; /* 全 */
extern const unsigned int TextGlyphs_System_E4BAA1Tiles[]; /* 亡 */
extern const unsigned int TextGlyphs_System_E5BF83Tiles[]; /* 心 */
extern const unsigned int TextGlyphs_System_E98984Tiles[]; /* 鉄 */
extern const unsigned int TextGlyphs_System_E799BETiles[]; /* 百 */
extern const unsigned int TextGlyphs_System_E683A8Tiles[]; /* 惨 */
extern const unsigned int TextGlyphs_System_E68B85Tiles[]; /* 担 */
extern const unsigned int TextGlyphs_System_E789A2Tiles[]; /* 牢 */
extern const unsigned int TextGlyphs_System_E9ACBCTiles[]; /* 鬼 */
extern const unsigned int TextGlyphs_System_E382B5Tiles[]; /* サ */
extern const unsigned int TextGlyphs_System_EFBC95Tiles[]; /* ５ */
extern const unsigned int TextGlyphs_System_E78BBCTiles[]; /* 狼 */
extern const unsigned int TextGlyphs_System_E68EA7Tiles[]; /* 控 */
extern const unsigned int TextGlyphs_System_E68EA2Tiles[]; /* 探 */
extern const unsigned int TextGlyphs_System_E585B8Tiles[]; /* 典 */
extern const unsigned int TextGlyphs_System_E285A0Tiles[]; /* Ⅰ */
extern const unsigned int TextGlyphs_System_E382B6Tiles[]; /* ザ */
extern const unsigned int TextGlyphs_System_EFBC96Tiles[]; /* ６ */
extern const unsigned int TextGlyphs_System_E694BBTiles[]; /* 攻 */
extern const unsigned int TextGlyphs_System_E695A3Tiles[]; /* 散 */
extern const unsigned int TextGlyphs_System_E8AA98Tiles[]; /* 誘 */
extern const unsigned int TextGlyphs_System_E6B6AFTiles[]; /* 涯 */
extern const unsigned int TextGlyphs_System_E285A1Tiles[]; /* Ⅱ */
extern const unsigned int TextGlyphs_System_E382B7Tiles[]; /* シ */
extern const unsigned int TextGlyphs_System_EFBC97Tiles[]; /* ７ */
extern const unsigned int TextGlyphs_System_E88081Tiles[]; /* 老 */
extern const unsigned int TextGlyphs_System_E5A4A9Tiles[]; /* 天 */
extern const unsigned int TextGlyphs_System_E696B0Tiles[]; /* 新 */
extern const unsigned int TextGlyphs_System_E9818ATiles[]; /* 遊 */
extern const unsigned int TextGlyphs_System_E58480Tiles[]; /* 儀 */
extern const unsigned int TextGlyphs_System_E285A2Tiles[]; /* Ⅲ */
extern const unsigned int TextGlyphs_System_E382B8Tiles[]; /* ジ */
extern const unsigned int TextGlyphs_System_EFBC98Tiles[]; /* ８ */
extern const unsigned int TextGlyphs_System_E99B86Tiles[]; /* 集 */
extern const unsigned int TextGlyphs_System_E6A899Tiles[]; /* 標 */
extern const unsigned int TextGlyphs_System_E4BF82Tiles[]; /* 係 */
extern const unsigned int TextGlyphs_System_E5B195Tiles[]; /* 展 */
extern const unsigned int TextGlyphs_System_E285A3Tiles[]; /* Ⅳ */
extern const unsigned int TextGlyphs_System_E382B9Tiles[]; /* ス */
extern const unsigned int TextGlyphs_System_EFBC99Tiles[]; /* ９ */
extern const unsigned int TextGlyphs_System_E5BA97Tiles[]; /* 店 */
extern const unsigned int TextGlyphs_System_E38085Tiles[]; /* 々 */
extern const unsigned int TextGlyphs_System_E8A197Tiles[]; /* 街 */
extern const unsigned int TextGlyphs_System_E6B0B7Tiles[]; /* 氷 */
extern const unsigned int TextGlyphs_System_E6A3AETiles[]; /* 森 */
extern const unsigned int TextGlyphs_System_E69BB4Tiles[]; /* 更 */
extern const unsigned int TextGlyphs_System_E285A4Tiles[]; /* Ⅴ */
extern const unsigned int TextGlyphs_System_E382BATiles[]; /* ズ */
extern const unsigned int TextGlyphs_System_E99B84Tiles[]; /* 雄 */
extern const unsigned int TextGlyphs_System_E794A3Tiles[]; /* 産 */
extern const unsigned int TextGlyphs_System_E58891Tiles[]; /* 刑 */
extern const unsigned int TextGlyphs_System_E5BF98Tiles[]; /* 忘 */
extern const unsigned int TextGlyphs_System_E9838ETiles[]; /* 郎 */
extern const unsigned int TextGlyphs_System_E285A5Tiles[]; /* Ⅵ */
extern const unsigned int TextGlyphs_System_E382BBTiles[]; /* セ */
extern const unsigned int TextGlyphs_System_E68A80Tiles[]; /* 技 */
extern const unsigned int TextGlyphs_System_E58584Tiles[]; /* 兄 */
extern const unsigned int TextGlyphs_System_E79FADTiles[]; /* 短 */
extern const unsigned int TextGlyphs_System_E4BD8FTiles[]; /* 住 */
extern const unsigned int TextGlyphs_System_E6A0A1Tiles[]; /* 校 */
extern const unsigned int TextGlyphs_System_E585ADTiles[]; /* 六 */
extern const unsigned int TextGlyphs_System_E285A6Tiles[]; /* Ⅶ */
extern const unsigned int TextGlyphs_System_E382BCTiles[]; /* ゼ */
extern const unsigned int TextGlyphs_System_E383BCTiles[]; /* ー */
extern const unsigned int TextGlyphs_System_E6B7B1Tiles[]; /* 深 */
extern const unsigned int TextGlyphs_System_E7ABAFTiles[]; /* 端 */
extern const unsigned int TextGlyphs_System_E382BDTiles[]; /* ソ */
extern const unsigned int TextGlyphs_System_E8A1A8Tiles[]; /* 表 */
extern const unsigned int TextGlyphs_System_E883BDTiles[]; /* 能 */
extern const unsigned int TextGlyphs_System_E794B3Tiles[]; /* 申 */
extern const unsigned int TextGlyphs_System_E4BA88Tiles[]; /* 予 */
extern const unsigned int TextGlyphs_System_E58D81Tiles[]; /* 十 */
extern const unsigned int TextGlyphs_System_E382BETiles[]; /* ゾ */
extern const unsigned int TextGlyphs_System_E5BE93Tiles[]; /* 従 */
extern const unsigned int TextGlyphs_System_E69C9BTiles[]; /* 望 */
extern const unsigned int TextGlyphs_System_E8BBA2Tiles[]; /* 転 */
extern const unsigned int TextGlyphs_System_E78AA0Tiles[]; /* 犠 */
extern const unsigned int TextGlyphs_System_E4BD99Tiles[]; /* 余 */
extern const unsigned int TextGlyphs_System_E8A995Tiles[]; /* 評 */
extern const unsigned int TextGlyphs_System_E382BFTiles[]; /* タ */
extern const unsigned int TextGlyphs_System_EFBC8FTiles[]; /* ／ */
extern const unsigned int TextGlyphs_System_E9818BTiles[]; /* 運 */
extern const unsigned int TextGlyphs_System_E79C9FTiles[]; /* 真 */
extern const unsigned int TextGlyphs_System_E98CB2Tiles[]; /* 録 */
extern const unsigned int TextGlyphs_System_E4B88ETiles[]; /* 与 */
extern const unsigned int TextGlyphs_System_E38380Tiles[]; /* ダ */
extern const unsigned int TextGlyphs_System_E7A59ETiles[]; /* 神 */
extern const unsigned int TextGlyphs_System_E99BB2Tiles[]; /* 雲 */
extern const unsigned int TextGlyphs_System_E8AA89Tiles[]; /* 誉 */
extern const unsigned int TextGlyphs_System_E5A591Tiles[]; /* 契 */
extern const unsigned int TextGlyphs_System_EFBCBCTiles[]; /* ＼ */
extern const unsigned int TextGlyphs_System_E782B9Tiles[]; /* 点 */
extern const unsigned int TextGlyphs_System_E38381Tiles[]; /* チ */
extern const unsigned int TextGlyphs_System_EFBD9ETiles[]; /* ～ */
extern const unsigned int TextGlyphs_System_EFBCA1Tiles[]; /* Ａ */
extern const unsigned int TextGlyphs_System_E6B8AFTiles[]; /* 港 */
extern const unsigned int TextGlyphs_System_E7BEA9Tiles[]; /* 義 */
extern const unsigned int TextGlyphs_System_E4BC9DTiles[]; /* 伝 */
extern const unsigned int TextGlyphs_System_E5BDA2Tiles[]; /* 形 */
extern const unsigned int TextGlyphs_System_E580ADTiles[]; /* 倭 */
extern const unsigned int TextGlyphs_System_E38382Tiles[]; /* ヂ */
extern const unsigned int TextGlyphs_System_EFBCA2Tiles[]; /* Ｂ */
extern const unsigned int TextGlyphs_System_E6AEBFTiles[]; /* 殿 */
extern const unsigned int TextGlyphs_System_E5928CTiles[]; /* 和 */
extern const unsigned int TextGlyphs_System_E79785Tiles[]; /* 病 */
extern const unsigned int TextGlyphs_System_E8AA95Tiles[]; /* 誕 */
extern const unsigned int TextGlyphs_System_E9A090Tiles[]; /* 預 */
extern const unsigned int TextGlyphs_System_E38383Tiles[]; /* ッ */
extern const unsigned int TextGlyphs_System_EFBCA3Tiles[]; /* Ｃ */
extern const unsigned int TextGlyphs_System_E8A9B1Tiles[]; /* 話 */
extern const unsigned int TextGlyphs_System_E582ADTiles[]; /* 傭 */
extern const unsigned int TextGlyphs_System_E887A3Tiles[]; /* 臣 */
extern const unsigned int TextGlyphs_System_E794B2Tiles[]; /* 甲 */
extern const unsigned int TextGlyphs_System_E38384Tiles[]; /* ツ */
extern const unsigned int TextGlyphs_System_EFBCA4Tiles[]; /* Ｄ */
extern const unsigned int TextGlyphs_System_E79A87Tiles[]; /* 皇 */
extern const unsigned int TextGlyphs_System_E59BA3Tiles[]; /* 団 */
extern const unsigned int TextGlyphs_System_E7A596Tiles[]; /* 祖 */
extern const unsigned int TextGlyphs_System_E6AE8BTiles[]; /* 残 */
extern const unsigned int TextGlyphs_System_E8ADB0Tiles[]; /* 議 */
extern const unsigned int TextGlyphs_System_E596B6Tiles[]; /* 営 */
extern const unsigned int TextGlyphs_System_E5B9BCTiles[]; /* 幼 */
extern const unsigned int TextGlyphs_System_E38385Tiles[]; /* ヅ */
extern const unsigned int TextGlyphs_System_EFBCA5Tiles[]; /* Ｅ */
extern const unsigned int TextGlyphs_System_E5A387Tiles[]; /* 壇 */
extern const unsigned int TextGlyphs_System_E99BBBTiles[]; /* 電 */
extern const unsigned int TextGlyphs_System_E9878DTiles[]; /* 重 */
extern const unsigned int TextGlyphs_System_E4BB95Tiles[]; /* 仕 */
extern const unsigned int TextGlyphs_System_E8AC80Tiles[]; /* 謀 */
extern const unsigned int TextGlyphs_System_E38386Tiles[]; /* テ */
extern const unsigned int TextGlyphs_System_EFBCA6Tiles[]; /* Ｆ */
extern const unsigned int TextGlyphs_System_E8A6AATiles[]; /* 親 */
extern const unsigned int TextGlyphs_System_E59084Tiles[]; /* 各 */
extern const unsigned int TextGlyphs_System_E8A687Tiles[]; /* 覇 */
extern const unsigned int TextGlyphs_System_E5AEB9Tiles[]; /* 容 */
extern const unsigned int TextGlyphs_System_E5BDB1Tiles[]; /* 影 */
extern const unsigned int TextGlyphs_System_E5BCBETiles[]; /* 弾 */
extern const unsigned int TextGlyphs_System_E38387Tiles[]; /* デ */
extern const unsigned int TextGlyphs_System_EFBCA7Tiles[]; /* Ｇ */
extern const unsigned int TextGlyphs_System_E696ADTiles[]; /* 断 */
extern const unsigned int TextGlyphs_System_E8B2BFTiles[]; /* 貿 */
extern const unsigned int TextGlyphs_System_E68391Tiles[]; /* 惑 */
extern const unsigned int TextGlyphs_System_E7B4A0Tiles[]; /* 素 */
extern const unsigned int TextGlyphs_System_E38388Tiles[]; /* ト */
extern const unsigned int TextGlyphs_System_EFBCA8Tiles[]; /* Ｈ */
extern const unsigned int TextGlyphs_System_E4BDBFTiles[]; /* 使 */
extern const unsigned int TextGlyphs_System_E8BAABTiles[]; /* 身 */
extern const unsigned int TextGlyphs_System_E7B485Tiles[]; /* 紅 */
extern const unsigned int TextGlyphs_System_E69A96Tiles[]; /* 暖 */
extern const unsigned int TextGlyphs_System_E7B584Tiles[]; /* 組 */
extern const unsigned int TextGlyphs_System_E68BA1Tiles[]; /* 拡 */
extern const unsigned int TextGlyphs_System_E38389Tiles[]; /* ド */
extern const unsigned int TextGlyphs_System_EFBCA9Tiles[]; /* Ｉ */
extern const unsigned int TextGlyphs_System_E8BE9BTiles[]; /* 辛 */
extern const unsigned int TextGlyphs_System_E998B2Tiles[]; /* 防 */
extern const unsigned int TextGlyphs_System_E6A084Tiles[]; /* 栄 */
extern const unsigned int TextGlyphs_System_E6B4BETiles[]; /* 派 */
extern const unsigned int TextGlyphs_System_E5AEBFTiles[]; /* 宿 */
extern const unsigned int TextGlyphs_System_E695ACTiles[]; /* 敬 */
extern const unsigned int TextGlyphs_System_E3838ATiles[]; /* ナ */
extern const unsigned int TextGlyphs_System_EFBC88Tiles[]; /* （ */
extern const unsigned int TextGlyphs_System_EFBCAATiles[]; /* Ｊ */
extern const unsigned int TextGlyphs_System_E980B2Tiles[]; /* 進 */
extern const unsigned int TextGlyphs_System_E58FB8Tiles[]; /* 司 */
extern const unsigned int TextGlyphs_System_E699AFTiles[]; /* 景 */
extern const unsigned int TextGlyphs_System_E6B0B8Tiles[]; /* 永 */
extern const unsigned int TextGlyphs_System_E6A0BCTiles[]; /* 格 */
extern const unsigned int TextGlyphs_System_E6AEB5Tiles[]; /* 段 */
extern const unsigned int TextGlyphs_System_E59381Tiles[]; /* 品 */
extern const unsigned int TextGlyphs_System_E590A0Tiles[]; /* 吠 */
extern const unsigned int TextGlyphs_System_E3838BTiles[]; /* ニ */
extern const unsigned int TextGlyphs_System_EFBC89Tiles[]; /* ） */
extern const unsigned int TextGlyphs_System_EFBCABTiles[]; /* Ｋ */
extern const unsigned int TextGlyphs_System_E794B7Tiles[]; /* 男 */
extern const unsigned int TextGlyphs_System_E7A0B4Tiles[]; /* 破 */
extern const unsigned int TextGlyphs_System_E998BBTiles[]; /* 阻 */
extern const unsigned int TextGlyphs_System_E58FB2Tiles[]; /* 史 */
extern const unsigned int TextGlyphs_System_E3838CTiles[]; /* ヌ */
extern const unsigned int TextGlyphs_System_EFBCACTiles[]; /* Ｌ */
extern const unsigned int TextGlyphs_System_E58C97Tiles[]; /* 北 */
extern const unsigned int TextGlyphs_System_E5BE92Tiles[]; /* 徒 */
extern const unsigned int TextGlyphs_System_E8AB87Tiles[]; /* 談 */
extern const unsigned int TextGlyphs_System_E3838DTiles[]; /* ネ */
extern const unsigned int TextGlyphs_System_EFBCADTiles[]; /* Ｍ */
extern const unsigned int TextGlyphs_System_E4BABATiles[]; /* 人 */
extern const unsigned int TextGlyphs_System_E6A798Tiles[]; /* 様 */
extern const unsigned int TextGlyphs_System_E580A4Tiles[]; /* 値 */
extern const unsigned int TextGlyphs_System_E7B29BTiles[]; /* 粛 */
extern const unsigned int TextGlyphs_System_E59B9BTiles[]; /* 四 */
extern const unsigned int TextGlyphs_System_E3838ETiles[]; /* ノ */
extern const unsigned int TextGlyphs_System_EFBCAETiles[]; /* Ｎ */
extern const unsigned int TextGlyphs_System_E5A3ABTiles[]; /* 士 */
extern const unsigned int TextGlyphs_System_E79FA5Tiles[]; /* 知 */
extern const unsigned int TextGlyphs_System_E583A7Tiles[]; /* 僧 */
extern const unsigned int TextGlyphs_System_E7A2BATiles[]; /* 確 */
extern const unsigned int TextGlyphs_System_E3838FTiles[]; /* ハ */
extern const unsigned int TextGlyphs_System_EFBCAFTiles[]; /* Ｏ */
extern const unsigned int TextGlyphs_System_E7B3BBTiles[]; /* 系 */
extern const unsigned int TextGlyphs_System_E59CB0Tiles[]; /* 地 */
extern const unsigned int TextGlyphs_System_E5A78BTiles[]; /* 始 */
extern const unsigned int TextGlyphs_System_E9A6ACTiles[]; /* 馬 */
extern const unsigned int TextGlyphs_System_E6BAB6Tiles[]; /* 溶 */
extern const unsigned int TextGlyphs_System_E589B5Tiles[]; /* 創 */
extern const unsigned int TextGlyphs_System_E58883Tiles[]; /* 刃 */
extern const unsigned int TextGlyphs_System_E6B8A1Tiles[]; /* 渡 */
extern const unsigned int TextGlyphs_System_E38390Tiles[]; /* バ */
extern const unsigned int TextGlyphs_System_EFBCB0Tiles[]; /* Ｐ */
extern const unsigned int TextGlyphs_System_E587BATiles[]; /* 出 */
extern const unsigned int TextGlyphs_System_E5A789Tiles[]; /* 姉 */
extern const unsigned int TextGlyphs_System_E7B58CTiles[]; /* 経 */
extern const unsigned int TextGlyphs_System_E58F8CTiles[]; /* 双 */
extern const unsigned int TextGlyphs_System_E8A69ATiles[]; /* 覚 */
extern const unsigned int TextGlyphs_System_E38391Tiles[]; /* パ */
extern const unsigned int TextGlyphs_System_EFBCB1Tiles[]; /* Ｑ */
extern const unsigned int TextGlyphs_System_E794A8Tiles[]; /* 用 */
extern const unsigned int TextGlyphs_System_E88BB1Tiles[]; /* 英 */
extern const unsigned int TextGlyphs_System_E8A193Tiles[]; /* 術 */
extern const unsigned int TextGlyphs_System_E7B699Tiles[]; /* 継 */
extern const unsigned int TextGlyphs_System_E5A7BFTiles[]; /* 姿 */
extern const unsigned int TextGlyphs_System_E58DB4Tiles[]; /* 却 */
extern const unsigned int TextGlyphs_System_E681A5Tiles[]; /* 恥 */
extern const unsigned int TextGlyphs_System_E5BB83Tiles[]; /* 廃 */
extern const unsigned int TextGlyphs_System_E38392Tiles[]; /* ヒ */
extern const unsigned int TextGlyphs_System_EFBCB2Tiles[]; /* Ｒ */
extern const unsigned int TextGlyphs_System_E5AD90Tiles[]; /* 子 */
extern const unsigned int TextGlyphs_System_E8A19BTiles[]; /* 衛 */
extern const unsigned int TextGlyphs_System_E789A7Tiles[]; /* 牧 */
extern const unsigned int TextGlyphs_System_E38393Tiles[]; /* ビ */
extern const unsigned int TextGlyphs_System_EFBCB3Tiles[]; /* Ｓ */
extern const unsigned int TextGlyphs_System_E88D92Tiles[]; /* 荒 */
extern const unsigned int TextGlyphs_System_E98094Tiles[]; /* 途 */
extern const unsigned int TextGlyphs_System_E88595Tiles[]; /* 腕 */
extern const unsigned int TextGlyphs_System_E38394Tiles[]; /* ピ */
extern const unsigned int TextGlyphs_System_EFBCB4Tiles[]; /* Ｔ */
extern const unsigned int TextGlyphs_System_E8A18CTiles[]; /* 行 */
extern const unsigned int TextGlyphs_System_E983BDTiles[]; /* 都 */
extern const unsigned int TextGlyphs_System_E5B882Tiles[]; /* 市 */
extern const unsigned int TextGlyphs_System_E69597Tiles[]; /* 敗 */
extern const unsigned int TextGlyphs_System_E5A3AETiles[]; /* 壮 */
extern const unsigned int TextGlyphs_System_E98BADTiles[]; /* 鋭 */
extern const unsigned int TextGlyphs_System_E4B88DTiles[]; /* 不 */
extern const unsigned int TextGlyphs_System_E5B0BDTiles[]; /* 尽 */
extern const unsigned int TextGlyphs_System_E89990Tiles[]; /* 虐 */
extern const unsigned int TextGlyphs_System_E38395Tiles[]; /* フ */
extern const unsigned int TextGlyphs_System_EFBCB5Tiles[]; /* Ｕ */
extern const unsigned int TextGlyphs_System_E98086Tiles[]; /* 逆 */
extern const unsigned int TextGlyphs_System_E5B8ABTiles[]; /* 師 */
extern const unsigned int TextGlyphs_System_E4BB98Tiles[]; /* 付 */
extern const unsigned int TextGlyphs_System_E89189Tiles[]; /* 葉 */
extern const unsigned int TextGlyphs_System_E698A5Tiles[]; /* 春 */
extern const unsigned int TextGlyphs_System_E5A58FTiles[]; /* 奏 */
extern const unsigned int TextGlyphs_System_E38396Tiles[]; /* ブ */
extern const unsigned int TextGlyphs_System_E3808CTiles[]; /* 「 */
extern const unsigned int TextGlyphs_System_EFBCB6Tiles[]; /* Ｖ */
extern const unsigned int TextGlyphs_System_E5BF97Tiles[]; /* 志 */
extern const unsigned int TextGlyphs_System_E58B83Tiles[]; /* 勃 */
extern const unsigned int TextGlyphs_System_E7BDAETiles[]; /* 置 */
extern const unsigned int TextGlyphs_System_E38397Tiles[]; /* プ */
extern const unsigned int TextGlyphs_System_E3808DTiles[]; /* 」 */
extern const unsigned int TextGlyphs_System_EFBCB7Tiles[]; /* Ｗ */
extern const unsigned int TextGlyphs_System_E4B985Tiles[]; /* 久 */
extern const unsigned int TextGlyphs_System_E8A681Tiles[]; /* 要 */
extern const unsigned int TextGlyphs_System_E6809DTiles[]; /* 思 */
extern const unsigned int TextGlyphs_System_E5A4ABTiles[]; /* 夫 */
extern const unsigned int TextGlyphs_System_E8A888Tiles[]; /* 計 */
extern const unsigned int TextGlyphs_System_E99DA9Tiles[]; /* 革 */
extern const unsigned int TextGlyphs_System_E6B2A1Tiles[]; /* 没 */
extern const unsigned int TextGlyphs_System_E79B8ATiles[]; /* 益 */
extern const unsigned int TextGlyphs_System_E38398Tiles[]; /* ヘ */
extern const unsigned int TextGlyphs_System_EFBCB8Tiles[]; /* Ｘ */
extern const unsigned int TextGlyphs_System_E68C87Tiles[]; /* 指 */
extern const unsigned int TextGlyphs_System_E8838CTiles[]; /* 背 */
extern const unsigned int TextGlyphs_System_E5ADA6Tiles[]; /* 学 */
extern const unsigned int TextGlyphs_System_E999A3Tiles[]; /* 陣 */
extern const unsigned int TextGlyphs_System_E58AAATiles[]; /* 努 */
extern const unsigned int TextGlyphs_System_E5A9A6Tiles[]; /* 婦 */
extern const unsigned int TextGlyphs_System_E3808ETiles[]; /* 『 */
extern const unsigned int TextGlyphs_System_E38399Tiles[]; /* ベ */
extern const unsigned int TextGlyphs_System_EFBCB9Tiles[]; /* Ｙ */
extern const unsigned int TextGlyphs_System_E4BC91Tiles[]; /* 休 */
extern const unsigned int TextGlyphs_System_E5BAA6Tiles[]; /* 度 */
extern const unsigned int TextGlyphs_System_E694AFTiles[]; /* 支 */
extern const unsigned int TextGlyphs_System_E8B88ATiles[]; /* 踊 */
extern const unsigned int TextGlyphs_System_E9838ATiles[]; /* 郊 */
extern const unsigned int TextGlyphs_System_E5AF8CTiles[]; /* 富 */
extern const unsigned int TextGlyphs_System_E8ADA6Tiles[]; /* 警 */
extern const unsigned int TextGlyphs_System_E3808FTiles[]; /* 』 */
extern const unsigned int TextGlyphs_System_E3839ATiles[]; /* ペ */
extern const unsigned int TextGlyphs_System_EFBCBATiles[]; /* Ｚ */
extern const unsigned int TextGlyphs_System_E59C9FTiles[]; /* 土 */
extern const unsigned int TextGlyphs_System_E8BBBDTiles[]; /* 軽 */
extern const unsigned int TextGlyphs_System_E8BCA9Tiles[]; /* 輩 */
extern const unsigned int TextGlyphs_System_E6A5BDTiles[]; /* 楽 */
extern const unsigned int TextGlyphs_System_E8AB8DTiles[]; /* 諍 */
extern const unsigned int TextGlyphs_System_E3839BTiles[]; /* ホ */
extern const unsigned int TextGlyphs_System_E5A5B4Tiles[]; /* 奴 */
extern const unsigned int TextGlyphs_System_E7AF89Tiles[]; /* 築 */
extern const unsigned int TextGlyphs_System_E9858DTiles[]; /* 配 */
extern const unsigned int TextGlyphs_System_E999BDTiles[]; /* 陽 */
extern const unsigned int TextGlyphs_System_E683B3Tiles[]; /* 想 */
extern const unsigned int TextGlyphs_System_E9A18DTiles[]; /* 額 */
extern const unsigned int TextGlyphs_System_E989B1Tiles[]; /* 鉱 */
extern const unsigned int TextGlyphs_System_E3839CTiles[]; /* ボ */
extern const unsigned int TextGlyphs_System_EFBC8BTiles[]; /* ＋ */
extern const unsigned int TextGlyphs_System_E9A48ATiles[]; /* 養 */
extern const unsigned int TextGlyphs_System_E5AEAETiles[]; /* 宮 */
extern const unsigned int TextGlyphs_System_E69CACTiles[]; /* 本 */
extern const unsigned int TextGlyphs_System_E5808DTiles[]; /* 倍 */
extern const unsigned int TextGlyphs_System_E68092Tiles[]; /* 怒 */
extern const unsigned int TextGlyphs_System_E68D9CTiles[]; /* 捜 */
extern const unsigned int TextGlyphs_System_E7959CTiles[]; /* 畜 */
extern const unsigned int TextGlyphs_System_E3839DTiles[]; /* ポ */
extern const unsigned int TextGlyphs_System_E58092Tiles[]; /* 倒 */
extern const unsigned int TextGlyphs_System_E5BC93Tiles[]; /* 弓 */
extern const unsigned int TextGlyphs_System_E68096Tiles[]; /* 怖 */
extern const unsigned int TextGlyphs_System_E68E83Tiles[]; /* 掃 */
extern const unsigned int TextGlyphs_System_E98BBCTiles[]; /* 鋼 */
extern const unsigned int TextGlyphs_System_E68E9FTiles[]; /* 掟 */
extern const unsigned int TextGlyphs_System_E88AB8Tiles[]; /* 芸 */
extern const unsigned int TextGlyphs_System_E3839ETiles[]; /* マ */
extern const unsigned int TextGlyphs_System_E8BF8ETiles[]; /* 迎 */
extern const unsigned int TextGlyphs_System_E5859ATiles[]; /* 党 */
extern const unsigned int TextGlyphs_System_E680A5Tiles[]; /* 急 */
extern const unsigned int TextGlyphs_System_E59BB3Tiles[]; /* 図 */
extern const unsigned int TextGlyphs_System_E3839FTiles[]; /* ミ */
extern const unsigned int TextGlyphs_System_E69591Tiles[]; /* 救 */
extern const unsigned int TextGlyphs_System_E6ADA2Tiles[]; /* 止 */
extern const unsigned int TextGlyphs_System_E9998DTiles[]; /* 降 */
extern const unsigned int TextGlyphs_System_E6ACB2Tiles[]; /* 欲 */
extern const unsigned int TextGlyphs_System_E586ACTiles[]; /* 冬 */
extern const unsigned int TextGlyphs_System_E383A0Tiles[]; /* ム */
extern const unsigned int TextGlyphs_System_E6ADBBTiles[]; /* 死 */
extern const unsigned int TextGlyphs_System_E696A7Tiles[]; /* 斧 */
extern const unsigned int TextGlyphs_System_E6BA96Tiles[]; /* 準 */
extern const unsigned int TextGlyphs_System_E5878DTiles[]; /* 凍 */
extern const unsigned int TextGlyphs_System_E98090Tiles[]; /* 逐 */
extern const unsigned int TextGlyphs_System_E383A1Tiles[]; /* メ */
extern const unsigned int TextGlyphs_System_EFBD81Tiles[]; /* ａ */
extern const unsigned int TextGlyphs_System_E7A3A8Tiles[]; /* 磨 */
extern const unsigned int TextGlyphs_System_E6B182Tiles[]; /* 求 */
extern const unsigned int TextGlyphs_System_E697A9Tiles[]; /* 早 */
extern const unsigned int TextGlyphs_System_E58880Tiles[]; /* 刀 */
extern const unsigned int TextGlyphs_System_E699AETiles[]; /* 普 */
extern const unsigned int TextGlyphs_System_E590B9Tiles[]; /* 吹 */
extern const unsigned int TextGlyphs_System_E383A2Tiles[]; /* モ */
extern const unsigned int TextGlyphs_System_EFBD82Tiles[]; /* ｂ */
extern const unsigned int TextGlyphs_System_E69283Tiles[]; /* 撃 */
extern const unsigned int TextGlyphs_System_E9AD94Tiles[]; /* 魔 */
extern const unsigned int TextGlyphs_System_E9AB98Tiles[]; /* 高 */
extern const unsigned int TextGlyphs_System_E79BBETiles[]; /* 盾 */
extern const unsigned int TextGlyphs_System_E78D85Tiles[]; /* 獅 */
extern const unsigned int TextGlyphs_System_E383A3Tiles[]; /* ャ */
extern const unsigned int TextGlyphs_System_EFBD83Tiles[]; /* ｃ */
extern const unsigned int TextGlyphs_System_E788B6Tiles[]; /* 父 */
extern const unsigned int TextGlyphs_System_E5A194Tiles[]; /* 塔 */
extern const unsigned int TextGlyphs_System_E5B7A3Tiles[]; /* 巣 */
extern const unsigned int TextGlyphs_System_E6BF80Tiles[]; /* 激 */
extern const unsigned int TextGlyphs_System_E8B2B7Tiles[]; /* 買 */
extern const unsigned int TextGlyphs_System_E6B3A3Tiles[]; /* 泣 */
extern const unsigned int TextGlyphs_System_E383A4Tiles[]; /* ヤ */
extern const unsigned int TextGlyphs_System_EFBD84Tiles[]; /* ｄ */
extern const unsigned int TextGlyphs_System_E6A78DTiles[]; /* 槍 */
extern const unsigned int TextGlyphs_System_E5A3B2Tiles[]; /* 売 */
extern const unsigned int TextGlyphs_System_E59F8BTiles[]; /* 埋 */
extern const unsigned int TextGlyphs_System_E7A781Tiles[]; /* 私 */
extern const unsigned int TextGlyphs_System_E5BBB6Tiles[]; /* 延 */
extern const unsigned int TextGlyphs_System_E5899BTiles[]; /* 剛 */
extern const unsigned int TextGlyphs_System_E383A5Tiles[]; /* ュ */
extern const unsigned int TextGlyphs_System_EFBD85Tiles[]; /* ｅ */
extern const unsigned int TextGlyphs_System_E6B0B4Tiles[]; /* 水 */
extern const unsigned int TextGlyphs_System_E79D80Tiles[]; /* 着 */
extern const unsigned int TextGlyphs_System_E5A6B9Tiles[]; /* 妹 */
extern const unsigned int TextGlyphs_System_E7B3B8Tiles[]; /* 糸 */
extern const unsigned int TextGlyphs_System_E383A6Tiles[]; /* ユ */
extern const unsigned int TextGlyphs_System_EFBD86Tiles[]; /* ｆ */
extern const unsigned int TextGlyphs_System_E4B8ADTiles[]; /* 中 */
extern const unsigned int TextGlyphs_System_E58FB7Tiles[]; /* 号 */
extern const unsigned int TextGlyphs_System_E7B499Tiles[]; /* 紙 */
extern const unsigned int TextGlyphs_System_E7A9B6Tiles[]; /* 究 */
extern const unsigned int TextGlyphs_System_E383A7Tiles[]; /* ョ */
extern const unsigned int TextGlyphs_System_EFBD87Tiles[]; /* ｇ */
extern const unsigned int TextGlyphs_System_E68FB4Tiles[]; /* 援 */
extern const unsigned int TextGlyphs_System_E5B3B6Tiles[]; /* 島 */
extern const unsigned int TextGlyphs_System_E59088Tiles[]; /* 合 */
extern const unsigned int TextGlyphs_System_E4BBB2Tiles[]; /* 仲 */
extern const unsigned int TextGlyphs_System_E9A086Tiles[]; /* 順 */
extern const unsigned int TextGlyphs_System_E383A8Tiles[]; /* ヨ */
extern const unsigned int TextGlyphs_System_EFBD88Tiles[]; /* ｈ */
extern const unsigned int TextGlyphs_System_E4BA89Tiles[]; /* 争 */
extern const unsigned int TextGlyphs_System_E69DA5Tiles[]; /* 来 */
extern const unsigned int TextGlyphs_System_E6B1BATiles[]; /* 決 */
extern const unsigned int TextGlyphs_System_E6B4BBTiles[]; /* 活 */
extern const unsigned int TextGlyphs_System_E587A6Tiles[]; /* 処 */
extern const unsigned int TextGlyphs_System_E6AF8ETiles[]; /* 毎 */
extern const unsigned int TextGlyphs_System_E383A9Tiles[]; /* ラ */
extern const unsigned int TextGlyphs_System_EFBD89Tiles[]; /* ｉ */
extern const unsigned int TextGlyphs_System_E5BFA0Tiles[]; /* 忠 */
extern const unsigned int TextGlyphs_System_E5889DTiles[]; /* 初 */
extern const unsigned int TextGlyphs_System_E8B2A0Tiles[]; /* 負 */
extern const unsigned int TextGlyphs_System_E7B49ATiles[]; /* 級 */
extern const unsigned int TextGlyphs_System_E383AATiles[]; /* リ */
extern const unsigned int TextGlyphs_System_EFBD8ATiles[]; /* ｊ */
extern const unsigned int TextGlyphs_System_E68980Tiles[]; /* 所 */
extern const unsigned int TextGlyphs_System_E7828ETiles[]; /* 炎 */
extern const unsigned int TextGlyphs_System_E79BB8Tiles[]; /* 相 */
extern const unsigned int TextGlyphs_System_E9A0BCTiles[]; /* 頼 */
extern const unsigned int TextGlyphs_System_E8A1B0Tiles[]; /* 衰 */
extern const unsigned int TextGlyphs_System_E887B3Tiles[]; /* 至 */
extern const unsigned int TextGlyphs_System_E68A95Tiles[]; /* 投 */
extern const unsigned int TextGlyphs_System_E383ABTiles[]; /* ル */
extern const unsigned int TextGlyphs_System_EFBD8BTiles[]; /* ｋ */
extern const unsigned int TextGlyphs_System_E8A696Tiles[]; /* 視 */
extern const unsigned int TextGlyphs_System_E7B590Tiles[]; /* 結 */
extern const unsigned int TextGlyphs_System_E8B5B4Tiles[]; /* 赴 */
extern const unsigned int TextGlyphs_System_E698BCTiles[]; /* 昼 */
extern const unsigned int TextGlyphs_System_E5B995Tiles[]; /* 幕 */
extern const unsigned int TextGlyphs_System_E99BB7Tiles[]; /* 雷 */
extern const unsigned int TextGlyphs_System_E7B5A6Tiles[]; /* 給 */
extern const unsigned int TextGlyphs_System_E8B1AATiles[]; /* 豪 */
extern const unsigned int TextGlyphs_System_E383ACTiles[]; /* レ */
extern const unsigned int TextGlyphs_System_EFBD8CTiles[]; /* ｌ */
extern const unsigned int TextGlyphs_System_E69DB1Tiles[]; /* 東 */
extern const unsigned int TextGlyphs_System_E8A180Tiles[]; /* 血 */
extern const unsigned int TextGlyphs_System_E4BCAFTiles[]; /* 伯 */
extern const unsigned int TextGlyphs_System_E697A7Tiles[]; /* 旧 */
extern const unsigned int TextGlyphs_System_E69FB1Tiles[]; /* 柱 */
extern const unsigned int TextGlyphs_System_E383ADTiles[]; /* ロ */
extern const unsigned int TextGlyphs_System_EFBD8DTiles[]; /* ｍ */
extern const unsigned int TextGlyphs_System_E6B3A8Tiles[]; /* 注 */
extern const unsigned int TextGlyphs_System_E7B5A1Tiles[]; /* 絡 */
extern const unsigned int TextGlyphs_System_E7B78FTiles[]; /* 総 */
extern const unsigned int TextGlyphs_System_E8A9A9Tiles[]; /* 詩 */
extern const unsigned int TextGlyphs_System_EFBD8ETiles[]; /* ｎ */
extern const unsigned int TextGlyphs_System_E69C88Tiles[]; /* 月 */
extern const unsigned int TextGlyphs_System_E58EBBTiles[]; /* 去 */
extern const unsigned int TextGlyphs_System_E890BDTiles[]; /* 落 */
extern const unsigned int TextGlyphs_System_E4BEAETiles[]; /* 侮 */
extern const unsigned int TextGlyphs_System_E8A9A6Tiles[]; /* 試 */
extern const unsigned int TextGlyphs_System_E5BAB6Tiles[]; /* 庶 */
extern const unsigned int TextGlyphs_System_E383AFTiles[]; /* ワ */
extern const unsigned int TextGlyphs_System_EFBD8FTiles[]; /* ｏ */
extern const unsigned int TextGlyphs_System_E7B792Tiles[]; /* 緒 */
extern const unsigned int TextGlyphs_System_E588BBTiles[]; /* 刻 */
extern const unsigned int TextGlyphs_System_E5B185Tiles[]; /* 居 */
extern const unsigned int TextGlyphs_System_E68B8DTiles[]; /* 拍 */
extern const unsigned int TextGlyphs_System_E4BBB6Tiles[]; /* 件 */
extern const unsigned int TextGlyphs_System_EFBD90Tiles[]; /* ｐ */
extern const unsigned int TextGlyphs_System_E88D89Tiles[]; /* 草 */
extern const unsigned int TextGlyphs_System_E6ADA6Tiles[]; /* 武 */
extern const unsigned int TextGlyphs_System_E79B97Tiles[]; /* 盗 */
extern const unsigned int TextGlyphs_System_E4B9B1Tiles[]; /* 乱 */
extern const unsigned int TextGlyphs_System_E5B7A8Tiles[]; /* 巨 */
extern const unsigned int TextGlyphs_System_E5918ATiles[]; /* 告 */
extern const unsigned int TextGlyphs_System_EFBD91Tiles[]; /* ｑ */
extern const unsigned int TextGlyphs_System_E69BB8Tiles[]; /* 書 */
extern const unsigned int TextGlyphs_System_E59BBDTiles[]; /* 国 */
extern const unsigned int TextGlyphs_System_E8889ETiles[]; /* 舞 */
extern const unsigned int TextGlyphs_System_E68B92Tiles[]; /* 拒 */
extern const unsigned int TextGlyphs_System_E8B387Tiles[]; /* 資 */
extern const unsigned int TextGlyphs_System_EFBD92Tiles[]; /* ｒ */
extern const unsigned int TextGlyphs_System_E383B2Tiles[]; /* ヲ */
extern const unsigned int TextGlyphs_System_E799BDTiles[]; /* 白 */
extern const unsigned int TextGlyphs_System_E68BA0Tiles[]; /* 拠 */
extern const unsigned int TextGlyphs_System_E383B3Tiles[]; /* ン */
extern const unsigned int TextGlyphs_System_EFBD93Tiles[]; /* ｓ */
extern const unsigned int TextGlyphs_System_E981A0Tiles[]; /* 遠 */
extern const unsigned int TextGlyphs_System_E985B7Tiles[]; /* 酷 */
extern const unsigned int TextGlyphs_System_E68C99Tiles[]; /* 挙 */
extern const unsigned int TextGlyphs_System_E9A790Tiles[]; /* 駐 */
extern const unsigned int TextGlyphs_System_EFBC85Tiles[]; /* ％ */
extern const unsigned int TextGlyphs_System_E383B4Tiles[]; /* ヴ */
extern const unsigned int TextGlyphs_System_EFBD94Tiles[]; /* ｔ */
extern const unsigned int TextGlyphs_System_E695B0Tiles[]; /* 数 */
extern const unsigned int TextGlyphs_System_E983A8Tiles[]; /* 部 */
extern const unsigned int TextGlyphs_System_E8ABB8Tiles[]; /* 諸 */
extern const unsigned int TextGlyphs_System_EFBD95Tiles[]; /* ｕ */
extern const unsigned int TextGlyphs_System_E9BB92Tiles[]; /* 黒 */
extern const unsigned int TextGlyphs_System_E589A3Tiles[]; /* 剣 */
extern const unsigned int TextGlyphs_System_E58AA9Tiles[]; /* 助 */
extern const unsigned int TextGlyphs_System_E69EA2Tiles[]; /* 枢 */
extern const unsigned int TextGlyphs_System_E8A385Tiles[]; /* 装 */
extern const unsigned int TextGlyphs_System_E5B081Tiles[]; /* 封 */
extern const unsigned int TextGlyphs_System_E6ADAFTiles[]; /* 歯 */
extern const unsigned int TextGlyphs_System_EFBD96Tiles[]; /* ｖ */
extern const unsigned int TextGlyphs_System_E69CABTiles[]; /* 末 */
extern const unsigned int TextGlyphs_System_E4BA8BTiles[]; /* 事 */
extern const unsigned int TextGlyphs_System_E5BD93Tiles[]; /* 当 */
extern const unsigned int TextGlyphs_System_E78D84Tiles[]; /* 獄 */
extern const unsigned int TextGlyphs_System_E8A8B1Tiles[]; /* 許 */
extern const unsigned int TextGlyphs_System_E8B5B0Tiles[]; /* 走 */
extern const unsigned int TextGlyphs_System_E58F99Tiles[]; /* 叙 */
extern const unsigned int TextGlyphs_System_EFBD97Tiles[]; /* ｗ */
extern const unsigned int TextGlyphs_System_E5A5B3Tiles[]; /* 女 */
extern const unsigned int TextGlyphs_System_E9A2A8Tiles[]; /* 風 */
extern const unsigned int TextGlyphs_System_E8BFABTiles[]; /* 迫 */
extern const unsigned int TextGlyphs_System_E98081Tiles[]; /* 送 */
extern const unsigned int TextGlyphs_System_E8A6A7Tiles[]; /* 覧 */
extern const unsigned int TextGlyphs_System_EFBD98Tiles[]; /* ｘ */
extern const unsigned int TextGlyphs_System_E588A9Tiles[]; /* 利 */
extern const unsigned int TextGlyphs_System_E885B0Tiles[]; /* 腰 */
extern const unsigned int TextGlyphs_System_E5BA8FTiles[]; /* 序 */
extern const unsigned int TextGlyphs_System_E6B19ATiles[]; /* 汚 */
extern const unsigned int TextGlyphs_System_EFBD99Tiles[]; /* ｙ */
extern const unsigned int TextGlyphs_System_E6BCA0Tiles[]; /* 漠 */
extern const unsigned int TextGlyphs_System_E58590Tiles[]; /* 児 */
extern const unsigned int TextGlyphs_System_E8B2AFTiles[]; /* 貯 */
extern const unsigned int TextGlyphs_System_E6BC81Tiles[]; /* 漁 */
extern const unsigned int TextGlyphs_System_E7AD89Tiles[]; /* 等 */
extern const unsigned int TextGlyphs_System_E794A5Tiles[]; /* 甥 */
extern const unsigned int TextGlyphs_System_EFBD9ATiles[]; /* ｚ */
extern const unsigned int TextGlyphs_System_E5BBBATiles[]; /* 建 */
extern const unsigned int TextGlyphs_System_E4BC8FTiles[]; /* 伏 */
extern const unsigned int TextGlyphs_System_E7AD94Tiles[]; /* 答 */
extern const unsigned int TextGlyphs_System_E5AD97Tiles[]; /* 字 */
extern const unsigned int TextGlyphs_System_E2978BTiles[]; /* ○ */
extern const unsigned int TextGlyphs_System_E5AFBATiles[]; /* 寺 */
extern const unsigned int TextGlyphs_System_E5A4AETiles[]; /* 央 */
extern const unsigned int TextGlyphs_System_E5BEA9Tiles[]; /* 復 */
extern const unsigned int TextGlyphs_System_E5838FTiles[]; /* 像 */
extern const unsigned int TextGlyphs_System_E4B887Tiles[]; /* 万 */
extern const unsigned int TextGlyphs_System_E999A4Tiles[]; /* 除 */
extern const unsigned int TextGlyphs_System_E68C81Tiles[]; /* 持 */
extern const unsigned int TextGlyphs_System_E7B5B1Tiles[]; /* 統 */
extern const unsigned int TextGlyphs_System_E79086Tiles[]; /* 理 */
extern const unsigned int TextGlyphs_System_E5A297Tiles[]; /* 増 */
extern const unsigned int TextGlyphs_System_E5B985Tiles[]; /* 幅 */
extern const unsigned int TextGlyphs_System_E582B7Tiles[]; /* 傷 */
extern const unsigned int TextGlyphs_System_E685A2Tiles[]; /* 慢 */
extern const unsigned int TextGlyphs_System_E2978ETiles[]; /* ◎ */
extern const unsigned int TextGlyphs_System_E8BEBCTiles[]; /* 込 */
extern const unsigned int TextGlyphs_System_E69982Tiles[]; /* 時 */
extern const unsigned int TextGlyphs_System_E5849FTiles[]; /* 償 */
extern const unsigned int TextGlyphs_System_E69C8DTiles[]; /* 服 */
extern const unsigned int TextGlyphs_System_E5BF9CTiles[]; /* 応 */
extern const unsigned int TextGlyphs_System_E588B0Tiles[]; /* 到 */
extern const unsigned int TextGlyphs_System_E6BA80Tiles[]; /* 満 */
extern const unsigned int TextGlyphs_System_E6868ETiles[]; /* 憎 */
extern const unsigned int TextGlyphs_System_E5AFB5Tiles[]; /* 寵 */
extern const unsigned int TextGlyphs_System_E38181Tiles[]; /* ぁ */
extern const unsigned int TextGlyphs_System_E58B9DTiles[]; /* 勝 */
extern const unsigned int TextGlyphs_System_E7A68FTiles[]; /* 福 */
extern const unsigned int TextGlyphs_System_E4BE9BTiles[]; /* 供 */
extern const unsigned int TextGlyphs_System_E6ACA1Tiles[]; /* 次 */
extern const unsigned int TextGlyphs_System_E68ABCTiles[]; /* 押 */
extern const unsigned int TextGlyphs_System_E38182Tiles[]; /* あ */
extern const unsigned int TextGlyphs_System_E7AEB1Tiles[]; /* 箱 */
extern const unsigned int TextGlyphs_System_E9A083Tiles[]; /* 頃 */
extern const unsigned int TextGlyphs_System_E6A8A9Tiles[]; /* 権 */
extern const unsigned int TextGlyphs_System_E8A38FTiles[]; /* 裏 */
extern const unsigned int TextGlyphs_System_E885B9Tiles[]; /* 腹 */
extern const unsigned int TextGlyphs_System_E38183Tiles[]; /* ぃ */
extern const unsigned int TextGlyphs_System_E4BB8ATiles[]; /* 今 */
extern const unsigned int TextGlyphs_System_E6B2BBTiles[]; /* 治 */
extern const unsigned int TextGlyphs_System_E591B3Tiles[]; /* 味 */
extern const unsigned int TextGlyphs_System_E8A487Tiles[]; /* 複 */
extern const unsigned int TextGlyphs_System_E5AFB8Tiles[]; /* 寸 */
extern const unsigned int TextGlyphs_System_E38184Tiles[]; /* い */
extern const unsigned int TextGlyphs_System_E8A88ETiles[]; /* 討 */
extern const unsigned int TextGlyphs_System_E4B896Tiles[]; /* 世 */
extern const unsigned int TextGlyphs_System_E69CAATiles[]; /* 未 */
extern const unsigned int TextGlyphs_System_E5BC94Tiles[]; /* 弔 */
extern const unsigned int TextGlyphs_System_E980A0Tiles[]; /* 造 */
extern const unsigned int TextGlyphs_System_E78AACTiles[]; /* 犬 */
extern const unsigned int TextGlyphs_System_E59BB0Tiles[]; /* 困 */
extern const unsigned int TextGlyphs_System_E9878CTiles[]; /* 里 */
extern const unsigned int TextGlyphs_System_E296B3Tiles[]; /* △ */
extern const unsigned int TextGlyphs_System_E38185Tiles[]; /* ぅ */
extern const unsigned int TextGlyphs_System_E99BA2Tiles[]; /* 離 */
extern const unsigned int TextGlyphs_System_E59380Tiles[]; /* 哀 */
extern const unsigned int TextGlyphs_System_E38186Tiles[]; /* う */
extern const unsigned int TextGlyphs_System_E78E8BTiles[]; /* 王 */
extern const unsigned int TextGlyphs_System_E6849BTiles[]; /* 愛 */
extern const unsigned int TextGlyphs_System_E999B8Tiles[]; /* 陸 */
extern const unsigned int TextGlyphs_System_E59586Tiles[]; /* 商 */
extern const unsigned int TextGlyphs_System_E585B1Tiles[]; /* 共 */
extern const unsigned int TextGlyphs_System_E581B4Tiles[]; /* 側 */
extern const unsigned int TextGlyphs_System_E7AD88Tiles[]; /* 筈 */
extern const unsigned int TextGlyphs_System_E7A094Tiles[]; /* 研 */
extern const unsigned int TextGlyphs_System_E38187Tiles[]; /* ぇ */
extern const unsigned int TextGlyphs_System_E5A99ATiles[]; /* 婚 */
extern const unsigned int TextGlyphs_System_E68995Tiles[]; /* 払 */
extern const unsigned int TextGlyphs_System_E594B1Tiles[]; /* 唱 */
extern const unsigned int TextGlyphs_System_E5BEB4Tiles[]; /* 徴 */
extern const unsigned int TextGlyphs_System_E38188Tiles[]; /* え */
extern const unsigned int TextGlyphs_System_E78E87Tiles[]; /* 率 */
extern const unsigned int TextGlyphs_System_E7A4BATiles[]; /* 示 */
extern const unsigned int TextGlyphs_System_E58D94Tiles[]; /* 協 */
extern const unsigned int TextGlyphs_System_E98083Tiles[]; /* 逃 */
extern const unsigned int TextGlyphs_System_E38189Tiles[]; /* ぉ */
extern const unsigned int TextGlyphs_System_E38092Tiles[]; /* 〒 */
extern const unsigned int TextGlyphs_System_E68C91Tiles[]; /* 挑 */
extern const unsigned int TextGlyphs_System_E7AB8BTiles[]; /* 立 */
extern const unsigned int TextGlyphs_System_E588B6Tiles[]; /* 制 */
extern const unsigned int TextGlyphs_System_E5AF86Tiles[]; /* 密 */
extern const unsigned int TextGlyphs_System_E8828CTiles[]; /* 肌 */
extern const unsigned int TextGlyphs_System_E681AFTiles[]; /* 息 */
extern const unsigned int TextGlyphs_System_E3818ATiles[]; /* お */
extern const unsigned int TextGlyphs_System_E28692Tiles[]; /* → */
extern const unsigned int TextGlyphs_System_E789A9Tiles[]; /* 物 */
extern const unsigned int TextGlyphs_System_E58DBFTiles[]; /* 卿 */
extern const unsigned int TextGlyphs_System_E880B3Tiles[]; /* 耳 */
extern const unsigned int TextGlyphs_System_E58BA2Tiles[]; /* 勢 */
extern const unsigned int TextGlyphs_System_E882A9Tiles[]; /* 肩 */
extern const unsigned int TextGlyphs_System_E3818BTiles[]; /* か */
extern const unsigned int TextGlyphs_System_E887AATiles[]; /* 自 */
extern const unsigned int TextGlyphs_System_E7BDA0Tiles[]; /* 罠 */
extern const unsigned int TextGlyphs_System_E8A68BTiles[]; /* 見 */
extern const unsigned int TextGlyphs_System_E9BB84Tiles[]; /* 黄 */
extern const unsigned int TextGlyphs_System_E69D9FTiles[]; /* 束 */
extern const unsigned int TextGlyphs_System_E69C9DTiles[]; /* 朝 */
extern const unsigned int TextGlyphs_System_E3818CTiles[]; /* が */
extern const unsigned int TextGlyphs_System_E58886Tiles[]; /* 分 */
extern const unsigned int TextGlyphs_System_E5BE81Tiles[]; /* 征 */
extern const unsigned int TextGlyphs_System_E795A5Tiles[]; /* 略 */
extern const unsigned int TextGlyphs_System_E9A0ADTiles[]; /* 頭 */
extern const unsigned int TextGlyphs_System_E5B7BBTiles[]; /* 巻 */
extern const unsigned int TextGlyphs_System_E6A0B9Tiles[]; /* 根 */
extern const unsigned int TextGlyphs_System_E585ABTiles[]; /* 八 */
extern const unsigned int TextGlyphs_System_E3818DTiles[]; /* き */
extern const unsigned int TextGlyphs_System_E5A283Tiles[]; /* 境 */
extern const unsigned int TextGlyphs_System_E682AATiles[]; /* 悪 */
extern const unsigned int TextGlyphs_System_E5B086Tiles[]; /* 将 */
extern const unsigned int TextGlyphs_System_E680A7Tiles[]; /* 性 */
extern const unsigned int TextGlyphs_System_E8B3A2Tiles[]; /* 賢 */
extern const unsigned int TextGlyphs_System_E8B6B3Tiles[]; /* 足 */
extern const unsigned int TextGlyphs_System_E8BE9ETiles[]; /* 辞 */
extern const unsigned int TextGlyphs_System_E3818ETiles[]; /* ぎ */
extern const unsigned int TextGlyphs_System_E99798Tiles[]; /* 闘 */
extern const unsigned int TextGlyphs_System_E9809FTiles[]; /* 速 */
extern const unsigned int TextGlyphs_System_E5B08FTiles[]; /* 小 */
extern const unsigned int TextGlyphs_System_E794BATiles[]; /* 町 */
extern const unsigned int TextGlyphs_System_E5B3A1Tiles[]; /* 峡 */
extern const unsigned int TextGlyphs_System_E68890Tiles[]; /* 成 */
extern const unsigned int TextGlyphs_System_E88488Tiles[]; /* 脈 */
extern const unsigned int TextGlyphs_System_E6B581Tiles[]; /* 流 */
extern const unsigned int TextGlyphs_System_E6B7B7Tiles[]; /* 混 */
extern const unsigned int TextGlyphs_System_E68FA1Tiles[]; /* 握 */
extern const unsigned int TextGlyphs_System_E3818FTiles[]; /* く */
extern const unsigned int TextGlyphs_System_E5BCB7Tiles[]; /* 強 */
extern const unsigned int TextGlyphs_System_E799BATiles[]; /* 発 */
extern const unsigned int TextGlyphs_System_E694BFTiles[]; /* 政 */
extern const unsigned int TextGlyphs_System_E5B091Tiles[]; /* 少 */
extern const unsigned int TextGlyphs_System_E981A3Tiles[]; /* 遣 */
extern const unsigned int TextGlyphs_System_E5838DTiles[]; /* 働 */
extern const unsigned int TextGlyphs_System_E5A699Tiles[]; /* 妙 */
extern const unsigned int TextGlyphs_System_E9B9BFTiles[]; /* 鹿 */
extern const unsigned int TextGlyphs_System_E38190Tiles[]; /* ぐ */
extern const unsigned int TextGlyphs_System_E58B95Tiles[]; /* 動 */
extern const unsigned int TextGlyphs_System_E5B18BTiles[]; /* 屋 */
extern const unsigned int TextGlyphs_System_E5AE8CTiles[]; /* 完 */
extern const unsigned int TextGlyphs_System_E5BC8FTiles[]; /* 式 */
extern const unsigned int TextGlyphs_System_E5B19ETiles[]; /* 属 */
extern const unsigned int TextGlyphs_System_E695B4Tiles[]; /* 整 */
extern const unsigned int TextGlyphs_System_E38191Tiles[]; /* け */
extern const unsigned int TextGlyphs_System_E8B38ATiles[]; /* 賊 */
extern const unsigned int TextGlyphs_System_E6989FTiles[]; /* 星 */
extern const unsigned int TextGlyphs_System_E5908CTiles[]; /* 同 */
extern const unsigned int TextGlyphs_System_E6B091Tiles[]; /* 民 */
extern const unsigned int TextGlyphs_System_E8AD98Tiles[]; /* 識 */
extern const unsigned int TextGlyphs_System_E5AE98Tiles[]; /* 官 */
extern const unsigned int TextGlyphs_System_E686B6Tiles[]; /* 憶 */
extern const unsigned int TextGlyphs_System_E79599Tiles[]; /* 留 */
extern const unsigned int TextGlyphs_System_E999BATiles[]; /* 険 */
extern const unsigned int TextGlyphs_System_E38192Tiles[]; /* げ */
extern const unsigned int TextGlyphs_System_E68190Tiles[]; /* 恐 */
extern const unsigned int TextGlyphs_System_E6978FTiles[]; /* 族 */
extern const unsigned int TextGlyphs_System_E4BC90Tiles[]; /* 伐 */
extern const unsigned int TextGlyphs_System_E5A082Tiles[]; /* 堂 */
extern const unsigned int TextGlyphs_System_E9AD82Tiles[]; /* 魂 */
extern const unsigned int TextGlyphs_System_E699B4Tiles[]; /* 晴 */
extern const unsigned int TextGlyphs_System_E5BA8ATiles[]; /* 床 */
extern const unsigned int TextGlyphs_System_E38193Tiles[]; /* こ */
extern const unsigned int TextGlyphs_System_E7B69ATiles[]; /* 続 */
extern const unsigned int TextGlyphs_System_E58B99Tiles[]; /* 務 */
extern const unsigned int TextGlyphs_System_E9A893Tiles[]; /* 験 */
extern const unsigned int TextGlyphs_System_E5B08ETiles[]; /* 導 */
extern const unsigned int TextGlyphs_System_E7BDB0Tiles[]; /* 罰 */
extern const unsigned int TextGlyphs_System_E38194Tiles[]; /* ご */
extern const unsigned int TextGlyphs_System_E68C9FTiles[]; /* 挟 */
extern const unsigned int TextGlyphs_System_E68A9CTiles[]; /* 抜 */
extern const unsigned int TextGlyphs_System_E8AABFTiles[]; /* 調 */
extern const unsigned int TextGlyphs_System_E5A4A2Tiles[]; /* 夢 */
extern const unsigned int TextGlyphs_System_E38195Tiles[]; /* さ */
extern const unsigned int TextGlyphs_System_E58583Tiles[]; /* 元 */
extern const unsigned int TextGlyphs_System_E7AB9CTiles[]; /* 竜 */
extern const unsigned int TextGlyphs_System_E784A1Tiles[]; /* 無 */
extern const unsigned int TextGlyphs_System_E6ADA3Tiles[]; /* 正 */
extern const unsigned int TextGlyphs_System_E59CA7Tiles[]; /* 圧 */
extern const unsigned int TextGlyphs_System_E69599Tiles[]; /* 教 */
extern const unsigned int TextGlyphs_System_E689BFTiles[]; /* 承 */
extern const unsigned int TextGlyphs_System_E38196Tiles[]; /* ざ */
extern const unsigned int TextGlyphs_System_E58E9FTiles[]; /* 原 */
extern const unsigned int TextGlyphs_System_E4BFBATiles[]; /* 俺 */
extern const unsigned int TextGlyphs_System_E6A98BTiles[]; /* 橋 */
extern const unsigned int TextGlyphs_System_E6849FTiles[]; /* 感 */
extern const unsigned int TextGlyphs_System_E8B685Tiles[]; /* 超 */
extern const unsigned int TextGlyphs_System_E6B885Tiles[]; /* 清 */
extern const unsigned int TextGlyphs_System_E6B49ETiles[]; /* 洞 */
extern const unsigned int TextGlyphs_System_E38197Tiles[]; /* し */
extern const unsigned int TextGlyphs_System_E689B1Tiles[]; /* 扱 */
extern const unsigned int TextGlyphs_System_E4BEB6Tiles[]; /* 侶 */
extern const unsigned int TextGlyphs_System_E6B381Tiles[]; /* 況 */
extern const unsigned int TextGlyphs_System_E789B2Tiles[]; /* 牲 */
extern const unsigned int TextGlyphs_System_E68B9BTiles[]; /* 招 */
extern const unsigned int TextGlyphs_System_E4B883Tiles[]; /* 七 */
extern const unsigned int TextGlyphs_System_E38198Tiles[]; /* じ */
extern const unsigned int TextGlyphs_System_E681A9Tiles[]; /* 恩 */
extern const unsigned int TextGlyphs_System_E7949FTiles[]; /* 生 */
extern const unsigned int TextGlyphs_System_E69687Tiles[]; /* 文 */
extern const unsigned int TextGlyphs_System_E78B82Tiles[]; /* 狂 */
extern const unsigned int TextGlyphs_System_E5AD98Tiles[]; /* 存 */
extern const unsigned int TextGlyphs_System_E5B7A6Tiles[]; /* 左 */
extern const unsigned int TextGlyphs_System_E99CA7Tiles[]; /* 霧 */
extern const unsigned int TextGlyphs_System_E38199Tiles[]; /* す */
extern const unsigned int TextGlyphs_System_E69785Tiles[]; /* 旅 */
extern const unsigned int TextGlyphs_System_E995B7Tiles[]; /* 長 */
extern const unsigned int TextGlyphs_System_E5ADABTiles[]; /* 孫 */
extern const unsigned int TextGlyphs_System_E79B9BTiles[]; /* 盛 */
extern const unsigned int TextGlyphs_System_E8819ETiles[]; /* 聞 */
extern const unsigned int TextGlyphs_System_E5B7AETiles[]; /* 差 */
extern const unsigned int TextGlyphs_System_E6B8A9Tiles[]; /* 温 */
extern const unsigned int TextGlyphs_System_E68F9BTiles[]; /* 換 */
extern const unsigned int TextGlyphs_System_E3819ATiles[]; /* ず */
extern const unsigned int TextGlyphs_System_E5A4B1Tiles[]; /* 失 */
extern const unsigned int TextGlyphs_System_E7B2BETiles[]; /* 精 */
extern const unsigned int TextGlyphs_System_E6B89BTiles[]; /* 減 */
extern const unsigned int TextGlyphs_System_E69887Tiles[]; /* 昇 */
extern const unsigned int TextGlyphs_System_E8999CTiles[]; /* 虜 */
extern const unsigned int TextGlyphs_System_E5B08ATiles[]; /* 尊 */
extern const unsigned int TextGlyphs_System_E9A082Tiles[]; /* 頂 */
extern const unsigned int TextGlyphs_System_E3819BTiles[]; /* せ */
extern const unsigned int TextGlyphs_System_E88196Tiles[]; /* 聖 */
extern const unsigned int TextGlyphs_System_E98193Tiles[]; /* 道 */
extern const unsigned int TextGlyphs_System_E4BDB5Tiles[]; /* 併 */
extern const unsigned int TextGlyphs_System_E4BA86Tiles[]; /* 了 */
extern const unsigned int TextGlyphs_System_E99FB3Tiles[]; /* 音 */
extern const unsigned int TextGlyphs_System_E9B3A5Tiles[]; /* 鳥 */
extern const unsigned int TextGlyphs_System_E6908DTiles[]; /* 損 */
extern const unsigned int TextGlyphs_System_E99ABCTiles[]; /* 隼 */
extern const unsigned int TextGlyphs_System_E3819CTiles[]; /* ぜ */
extern const unsigned int TextGlyphs_System_E585B5Tiles[]; /* 兵 */
extern const unsigned int TextGlyphs_System_E69D91Tiles[]; /* 村 */
extern const unsigned int TextGlyphs_System_E4B88BTiles[]; /* 下 */
extern const unsigned int TextGlyphs_System_E5A3B0Tiles[]; /* 声 */
extern const unsigned int TextGlyphs_System_E5AEA4Tiles[]; /* 室 */
extern const unsigned int TextGlyphs_System_E5A898Tiles[]; /* 娘 */
extern const unsigned int TextGlyphs_System_E28A86Tiles[]; /* ⊆ */
extern const unsigned int TextGlyphs_System_E3819DTiles[]; /* そ */
extern const unsigned int TextGlyphs_System_E78FBETiles[]; /* 現 */
extern const unsigned int TextGlyphs_System_E7A082Tiles[]; /* 砂 */
extern const unsigned int TextGlyphs_System_E88888Tiles[]; /* 興 */
extern const unsigned int TextGlyphs_System_E58C96Tiles[]; /* 化 */
extern const unsigned int TextGlyphs_System_E5B3A0Tiles[]; /* 峠 */
extern const unsigned int TextGlyphs_System_E5A180Tiles[]; /* 塀 */
extern const unsigned int TextGlyphs_System_E588A4Tiles[]; /* 判 */
extern const unsigned int TextGlyphs_System_E28A87Tiles[]; /* ⊇ */
extern const unsigned int TextGlyphs_System_E3819ETiles[]; /* ぞ */
extern const unsigned int TextGlyphs_System_E4B8A1Tiles[]; /* 両 */
extern const unsigned int TextGlyphs_System_E8A5BFTiles[]; /* 西 */
extern const unsigned int TextGlyphs_System_E4BB96Tiles[]; /* 他 */
extern const unsigned int TextGlyphs_System_E5908DTiles[]; /* 名 */
extern const unsigned int TextGlyphs_System_E58D8ATiles[]; /* 半 */
extern const unsigned int TextGlyphs_System_E4BBAETiles[]; /* 仮 */
extern const unsigned int TextGlyphs_System_E79BB4Tiles[]; /* 直 */
extern const unsigned int TextGlyphs_System_E3819FTiles[]; /* た */
extern const unsigned int TextGlyphs_System_E4BD95Tiles[]; /* 何 */
extern const unsigned int TextGlyphs_System_E5A49ATiles[]; /* 多 */
extern const unsigned int TextGlyphs_System_E591BDTiles[]; /* 命 */
extern const unsigned int TextGlyphs_System_E5B9B3Tiles[]; /* 平 */
extern const unsigned int TextGlyphs_System_E8AAA0Tiles[]; /* 誠 */
extern const unsigned int TextGlyphs_System_E58F8DTiles[]; /* 反 */
extern const unsigned int TextGlyphs_System_E6AD93Tiles[]; /* 歓 */
extern const unsigned int TextGlyphs_System_E983B7Tiles[]; /* 郷 */
extern const unsigned int TextGlyphs_System_E381A0Tiles[]; /* だ */
extern const unsigned int TextGlyphs_System_E6B288Tiles[]; /* 沈 */
extern const unsigned int TextGlyphs_System_E8A880Tiles[]; /* 言 */
extern const unsigned int TextGlyphs_System_E6988ETiles[]; /* 明 */
extern const unsigned int TextGlyphs_System_E5A4AATiles[]; /* 太 */
extern const unsigned int TextGlyphs_System_E5BE97Tiles[]; /* 得 */
extern const unsigned int TextGlyphs_System_E8AA93Tiles[]; /* 誓 */
extern const unsigned int TextGlyphs_System_E6B197Tiles[]; /* 汗 */
extern const unsigned int TextGlyphs_System_E796BETiles[]; /* 疾 */
extern const unsigned int TextGlyphs_System_E381A1Tiles[]; /* ち */
extern const unsigned int TextGlyphs_System_E79B9FTiles[]; /* 盟 */
extern const unsigned int TextGlyphs_System_E8B3AATiles[]; /* 質 */
extern const unsigned int TextGlyphs_System_E8AB8BTiles[]; /* 請 */
extern const unsigned int TextGlyphs_System_E69F84Tiles[]; /* 柄 */
extern const unsigned int TextGlyphs_System_E4BEA1Tiles[]; /* 価 */
extern const unsigned int TextGlyphs_System_E69699Tiles[]; /* 料 */
extern const unsigned int TextGlyphs_System_E99FBFTiles[]; /* 響 */
extern const unsigned int TextGlyphs_System_E381A2Tiles[]; /* ぢ */
extern const unsigned int TextGlyphs_System_E5AE89Tiles[]; /* 安 */
extern const unsigned int TextGlyphs_System_E5BAA7Tiles[]; /* 座 */
extern const unsigned int TextGlyphs_System_E8BFB7Tiles[]; /* 迷 */
extern const unsigned int TextGlyphs_System_E99990Tiles[]; /* 限 */
extern const unsigned int TextGlyphs_System_E5AE9FTiles[]; /* 実 */
extern const unsigned int TextGlyphs_System_E9809DTiles[]; /* 逝 */
extern const unsigned int TextGlyphs_System_E381A3Tiles[]; /* っ */
extern const unsigned int TextGlyphs_System_E58AA0Tiles[]; /* 加 */
extern const unsigned int TextGlyphs_System_E6B688Tiles[]; /* 消 */
extern const unsigned int TextGlyphs_System_E789B9Tiles[]; /* 特 */
extern const unsigned int TextGlyphs_System_E381A4Tiles[]; /* つ */
extern const unsigned int TextGlyphs_System_E58FAFTiles[]; /* 可 */
extern const unsigned int TextGlyphs_System_E5808BTiles[]; /* 個 */
extern const unsigned int TextGlyphs_System_E78C9FTiles[]; /* 猟 */
extern const unsigned int TextGlyphs_System_E99689Tiles[]; /* 閉 */
extern const unsigned int TextGlyphs_System_E6B889Tiles[]; /* 渉 */
extern const unsigned int TextGlyphs_System_E99D92Tiles[]; /* 青 */
extern const unsigned int TextGlyphs_System_E381A5Tiles[]; /* づ */
extern const unsigned int TextGlyphs_System_CEB5Tiles[]; /* ε */
extern const unsigned int TextGlyphs_System_E69A97Tiles[]; /* 暗 */
extern const unsigned int TextGlyphs_System_E58FA4Tiles[]; /* 古 */
extern const unsigned int TextGlyphs_System_E9999BTiles[]; /* 陛 */
extern const unsigned int TextGlyphs_System_E5A7AATiles[]; /* 姪 */
extern const unsigned int TextGlyphs_System_E79498Tiles[]; /* 甘 */
extern const unsigned int TextGlyphs_System_E99D99Tiles[]; /* 静 */
extern const unsigned int TextGlyphs_System_E381A6Tiles[]; /* て */
extern const unsigned int TextGlyphs_System_E5868DTiles[]; /* 再 */
extern const unsigned int TextGlyphs_System_E784BCTiles[]; /* 焼 */
extern const unsigned int TextGlyphs_System_E591BCTiles[]; /* 呼 */
extern const unsigned int TextGlyphs_System_E6A188Tiles[]; /* 案 */
extern const unsigned int TextGlyphs_System_E7899DTiles[]; /* 牝 */
extern const unsigned int TextGlyphs_System_E381A7Tiles[]; /* で */
extern const unsigned int TextGlyphs_System_E69C80Tiles[]; /* 最 */
extern const unsigned int TextGlyphs_System_E7A88ETiles[]; /* 税 */
extern const unsigned int TextGlyphs_System_E6BB85Tiles[]; /* 滅 */
extern const unsigned int TextGlyphs_System_E68993Tiles[]; /* 打 */
extern const unsigned int TextGlyphs_System_E99787Tiles[]; /* 闇 */
extern const unsigned int TextGlyphs_System_E5AB81Tiles[]; /* 嫁 */
extern const unsigned int TextGlyphs_System_E59BBATiles[]; /* 固 */
extern const unsigned int TextGlyphs_System_E6AF92Tiles[]; /* 毒 */
extern const unsigned int TextGlyphs_System_E784A6Tiles[]; /* 焦 */
extern const unsigned int TextGlyphs_System_E381A8Tiles[]; /* と */
extern const unsigned int TextGlyphs_System_E5AEB6Tiles[]; /* 家 */
extern const unsigned int TextGlyphs_System_E78BACTiles[]; /* 独 */
extern const unsigned int TextGlyphs_System_E6A5ADTiles[]; /* 業 */
extern const unsigned int TextGlyphs_System_E381A9Tiles[]; /* ど */
extern const unsigned int TextGlyphs_System_E5A19ETiles[]; /* 塞 */
extern const unsigned int TextGlyphs_System_E8BFBDTiles[]; /* 追 */
extern const unsigned int TextGlyphs_System_E5ADA4Tiles[]; /* 孤 */
extern const unsigned int TextGlyphs_System_E889AFTiles[]; /* 良 */
extern const unsigned int TextGlyphs_System_E5B180Tiles[]; /* 局 */
extern const unsigned int TextGlyphs_System_E7AEA1Tiles[]; /* 管 */
extern const unsigned int TextGlyphs_System_E5A381Tiles[]; /* 壁 */
extern const unsigned int TextGlyphs_System_E5AFA1Tiles[]; /* 寡 */
extern const unsigned int TextGlyphs_System_E381AATiles[]; /* な */
extern const unsigned int TextGlyphs_System_E4BBA5Tiles[]; /* 以 */
extern const unsigned int TextGlyphs_System_E5A6BBTiles[]; /* 妻 */
extern const unsigned int TextGlyphs_System_E7B0A1Tiles[]; /* 簡 */
extern const unsigned int TextGlyphs_System_E5B7B1Tiles[]; /* 己 */
extern const unsigned int TextGlyphs_System_E381ABTiles[]; /* に */
extern const unsigned int TextGlyphs_System_E7979BTiles[]; /* 痛 */
extern const unsigned int TextGlyphs_System_E6839CTiles[]; /* 惜 */
extern const unsigned int TextGlyphs_System_E5AEB0Tiles[]; /* 宰 */
extern const unsigned int TextGlyphs_System_E6A5B5Tiles[]; /* 極 */
extern const unsigned int TextGlyphs_System_E381ACTiles[]; /* ぬ */
extern const unsigned int TextGlyphs_System_E4BD8DTiles[]; /* 位 */
extern const unsigned int TextGlyphs_System_E58699Tiles[]; /* 写 */
extern const unsigned int TextGlyphs_System_E78E89Tiles[]; /* 玉 */
extern const unsigned int TextGlyphs_System_E69E9CTiles[]; /* 果 */
extern const unsigned int TextGlyphs_System_E588A5Tiles[]; /* 別 */
extern const unsigned int TextGlyphs_System_E99DA2Tiles[]; /* 面 */
extern const unsigned int TextGlyphs_System_E9809ATiles[]; /* 通 */
extern const unsigned int TextGlyphs_System_E9878FTiles[]; /* 量 */
extern const unsigned int TextGlyphs_System_E381ADTiles[]; /* ね */
extern const unsigned int TextGlyphs_System_E6898DTiles[]; /* 才 */
extern const unsigned int TextGlyphs_System_E7AA81Tiles[]; /* 突 */
extern const unsigned int TextGlyphs_System_E5B084Tiles[]; /* 射 */
extern const unsigned int TextGlyphs_System_E381AETiles[]; /* の */
extern const unsigned int TextGlyphs_System_E9A098Tiles[]; /* 領 */
extern const unsigned int TextGlyphs_System_E58189Tiles[]; /* 偉 */
extern const unsigned int TextGlyphs_System_E69894Tiles[]; /* 昔 */
extern const unsigned int TextGlyphs_System_E4BD93Tiles[]; /* 体 */
extern const unsigned int TextGlyphs_System_E7A7B0Tiles[]; /* 称 */
extern const unsigned int TextGlyphs_System_E68DA8Tiles[]; /* 捨 */
extern const unsigned int TextGlyphs_System_E6AD8CTiles[]; /* 歌 */
extern const unsigned int TextGlyphs_System_E69585Tiles[]; /* 故 */
extern const unsigned int TextGlyphs_System_E381AFTiles[]; /* は */
extern const unsigned int TextGlyphs_System_E58A9BTiles[]; /* 力 */
extern const unsigned int TextGlyphs_System_E59BB2Tiles[]; /* 囲 */
extern const unsigned int TextGlyphs_System_E7ABA0Tiles[]; /* 章 */
extern const unsigned int TextGlyphs_System_E6A8A1Tiles[]; /* 模 */
extern const unsigned int TextGlyphs_System_E6B2B3Tiles[]; /* 河 */
extern const unsigned int TextGlyphs_System_E8B5A6Tiles[]; /* 赦 */
extern const unsigned int TextGlyphs_System_E381B0Tiles[]; /* ば */
extern const unsigned int TextGlyphs_System_E79FB3Tiles[]; /* 石 */
extern const unsigned int TextGlyphs_System_E781ABTiles[]; /* 火 */
extern const unsigned int TextGlyphs_System_E5AFBETiles[]; /* 対 */
extern const unsigned int TextGlyphs_System_E7B791Tiles[]; /* 緑 */
extern const unsigned int TextGlyphs_System_E7AC91Tiles[]; /* 笑 */
extern const unsigned int TextGlyphs_System_E6B996Tiles[]; /* 湖 */
extern const unsigned int TextGlyphs_System_E381B1Tiles[]; /* ぱ */
extern const unsigned int TextGlyphs_System_E5A489Tiles[]; /* 変 */
extern const unsigned int TextGlyphs_System_E5A794Tiles[]; /* 委 */
extern const unsigned int TextGlyphs_System_E7A98DTiles[]; /* 積 */
extern const unsigned int TextGlyphs_System_E6B888Tiles[]; /* 済 */
extern const unsigned int TextGlyphs_System_E381B2Tiles[]; /* ひ */
extern const unsigned int TextGlyphs_System_E781BDTiles[]; /* 災 */
extern const unsigned int TextGlyphs_System_E5A881Tiles[]; /* 威 */
extern const unsigned int TextGlyphs_System_E78987Tiles[]; /* 片 */
extern const unsigned int TextGlyphs_System_E8AB8CTiles[]; /* 諌 */
extern const unsigned int TextGlyphs_System_E5A29FTiles[]; /* 墟 */
extern const unsigned int TextGlyphs_System_E381B3Tiles[]; /* び */
extern const unsigned int TextGlyphs_System_E5B8AFTiles[]; /* 帯 */
extern const unsigned int TextGlyphs_System_E69E97Tiles[]; /* 林 */
extern const unsigned int TextGlyphs_System_E7B8BETiles[]; /* 績 */
extern const unsigned int TextGlyphs_System_E6AF9BTiles[]; /* 毛 */
extern const unsigned int TextGlyphs_System_E381B4Tiles[]; /* ぴ */
extern const unsigned int TextGlyphs_System_E88085Tiles[]; /* 者 */
extern const unsigned int TextGlyphs_System_E5BE85Tiles[]; /* 待 */
extern const unsigned int TextGlyphs_System_E78C9BTiles[]; /* 猛 */
extern const unsigned int TextGlyphs_System_E98284Tiles[]; /* 還 */
extern const unsigned int TextGlyphs_System_E7B7A8Tiles[]; /* 編 */
extern const unsigned int TextGlyphs_System_E7A8BCTiles[]; /* 稼 */
extern const unsigned int TextGlyphs_System_E381B5Tiles[]; /* ふ */
extern const unsigned int TextGlyphs_System_E8BEBATiles[]; /* 辺 */
extern const unsigned int TextGlyphs_System_E6848FTiles[]; /* 意 */
extern const unsigned int TextGlyphs_System_E8B2ACTiles[]; /* 責 */
extern const unsigned int TextGlyphs_System_E7A095Tiles[]; /* 砕 */
extern const unsigned int TextGlyphs_System_E8AC9DTiles[]; /* 謝 */
extern const unsigned int TextGlyphs_System_E381B6Tiles[]; /* ぶ */
extern const unsigned int TextGlyphs_System_E7A0A6Tiles[]; /* 砦 */
extern const unsigned int TextGlyphs_System_E99693Tiles[]; /* 間 */
extern const unsigned int TextGlyphs_System_E8B5A4Tiles[]; /* 赤 */
extern const unsigned int TextGlyphs_System_E8BF94Tiles[]; /* 返 */
extern const unsigned int TextGlyphs_System_E8BB8ATiles[]; /* 車 */
extern const unsigned int TextGlyphs_System_E6858BTiles[]; /* 態 */
extern const unsigned int TextGlyphs_System_E795AATiles[]; /* 番 */
extern const unsigned int TextGlyphs_System_E88AB1Tiles[]; /* 花 */
extern const unsigned int TextGlyphs_System_E5B1AFTiles[]; /* 屯 */
extern const unsigned int TextGlyphs_System_E381B7Tiles[]; /* ぷ */
extern const unsigned int TextGlyphs_System_E7A5ADTiles[]; /* 祭 */
extern const unsigned int TextGlyphs_System_E69893Tiles[]; /* 易 */
extern const unsigned int TextGlyphs_System_E8B7A1Tiles[]; /* 跡 */
extern const unsigned int TextGlyphs_System_E887A8Tiles[]; /* 臨 */
extern const unsigned int TextGlyphs_System_E8998ETiles[]; /* 虎 */
extern const unsigned int TextGlyphs_System_E381B8Tiles[]; /* へ */
extern const unsigned int TextGlyphs_System_E8AA87Tiles[]; /* 誇 */
extern const unsigned int TextGlyphs_System_E996A2Tiles[]; /* 関 */
extern const unsigned int TextGlyphs_System_E4BEBFTiles[]; /* 便 */
extern const unsigned int TextGlyphs_System_E7A681Tiles[]; /* 禁 */
extern const unsigned int TextGlyphs_System_E8BCAATiles[]; /* 輪 */
extern const unsigned int TextGlyphs_System_E69BBFTiles[]; /* 替 */
extern const unsigned int TextGlyphs_System_E381B9Tiles[]; /* べ */
extern const unsigned int TextGlyphs_System_E99AA3Tiles[]; /* 隣 */
extern const unsigned int TextGlyphs_System_E982AATiles[]; /* 邪 */
extern const unsigned int TextGlyphs_System_E58B89Tiles[]; /* 勉 */
extern const unsigned int TextGlyphs_System_E7B4B0Tiles[]; /* 細 */
extern const unsigned int TextGlyphs_System_E999A5Tiles[]; /* 陥 */
extern const unsigned int TextGlyphs_System_E782BATiles[]; /* 為 */
extern const unsigned int TextGlyphs_System_E88DB7Tiles[]; /* 荷 */
extern const unsigned int TextGlyphs_System_E381BATiles[]; /* ぺ */
extern const unsigned int TextGlyphs_System_E7AD8BTiles[]; /* 筋 */
extern const unsigned int TextGlyphs_System_E58887Tiles[]; /* 切 */
extern const unsigned int TextGlyphs_System_E89BAETiles[]; /* 蛮 */
extern const unsigned int TextGlyphs_System_E5809FTiles[]; /* 借 */
extern const unsigned int TextGlyphs_System_E8A8BCTiles[]; /* 証 */
extern const unsigned int TextGlyphs_System_E69CA8Tiles[]; /* 木 */
extern const unsigned int TextGlyphs_System_E381BBTiles[]; /* ほ */
extern const unsigned int TextGlyphs_System_E9BB99Tiles[]; /* 黙 */
extern const unsigned int TextGlyphs_System_E795B0Tiles[]; /* 異 */
extern const unsigned int TextGlyphs_System_E99B87Tiles[]; /* 雇 */
extern const unsigned int TextGlyphs_System_E8838ETiles[]; /* 胎 */
extern const unsigned int TextGlyphs_System_E5BC81Tiles[]; /* 弁 */
extern const unsigned int TextGlyphs_System_E9A4A8Tiles[]; /* 館 */
extern const unsigned int TextGlyphs_System_E88F93Tiles[]; /* 菓 */
extern const unsigned int TextGlyphs_System_E381BCTiles[]; /* ぼ */
extern const unsigned int TextGlyphs_System_E79BAETiles[]; /* 目 */
extern const unsigned int TextGlyphs_System_E7A7BBTiles[]; /* 移 */
extern const unsigned int TextGlyphs_System_E68EA5Tiles[]; /* 接 */
extern const unsigned int TextGlyphs_System_E58D91Tiles[]; /* 卑 */
extern const unsigned int TextGlyphs_System_E9A1A7Tiles[]; /* 顧 */
extern const unsigned int TextGlyphs_System_E8A9B3Tiles[]; /* 詳 */
extern const unsigned int TextGlyphs_System_E381BDTiles[]; /* ぽ */
extern const unsigned int TextGlyphs_System_E4BF9DTiles[]; /* 保 */
extern const unsigned int TextGlyphs_System_E590A6Tiles[]; /* 否 */
extern const unsigned int TextGlyphs_System_E7B6ADTiles[]; /* 維 */
extern const unsigned int TextGlyphs_System_E381BETiles[]; /* ま */
extern const unsigned int TextGlyphs_System_E8B39ETiles[]; /* 賞 */
extern const unsigned int TextGlyphs_System_E781BCTiles[]; /* 灼 */
extern const unsigned int TextGlyphs_System_E6B699Tiles[]; /* 涙 */
extern const unsigned int TextGlyphs_System_E5A683Tiles[]; /* 妃 */
extern const unsigned int TextGlyphs_System_E4BA94Tiles[]; /* 五 */
extern const unsigned int TextGlyphs_System_E381BFTiles[]; /* み */
extern const unsigned int TextGlyphs_System_E5B2B8Tiles[]; /* 岸 */
extern const unsigned int TextGlyphs_System_E788B5Tiles[]; /* 爵 */
extern const unsigned int TextGlyphs_System_E8B2A8Tiles[]; /* 貨 */
extern const unsigned int TextGlyphs_System_E59CA8Tiles[]; /* 在 */
extern const unsigned int TextGlyphs_System_E8A8ADTiles[]; /* 設 */
extern const unsigned int TextGlyphs_System_E9888DTiles[]; /* 鈍 */
extern const unsigned int TextGlyphs_System_E8B2B8Tiles[]; /* 貸 */
extern const unsigned int TextGlyphs_System_E38280Tiles[]; /* む */
extern const unsigned int TextGlyphs_System_E5BDBCTiles[]; /* 彼 */
extern const unsigned int TextGlyphs_System_E98080Tiles[]; /* 退 */
extern const unsigned int TextGlyphs_System_E9A19ETiles[]; /* 類 */
extern const unsigned int TextGlyphs_System_E5B7ABTiles[]; /* 巫 */
extern const unsigned int TextGlyphs_System_E38281Tiles[]; /* め */
extern const unsigned int TextGlyphs_System_E8BF91Tiles[]; /* 近 */
extern const unsigned int TextGlyphs_System_E68D95Tiles[]; /* 捕 */
extern const unsigned int TextGlyphs_System_E682B2Tiles[]; /* 悲 */
extern const unsigned int TextGlyphs_System_E7BDAATiles[]; /* 罪 */
extern const unsigned int TextGlyphs_System_E4BBA4Tiles[]; /* 令 */
extern const unsigned int TextGlyphs_System_E7AF80Tiles[]; /* 節 */
extern const unsigned int TextGlyphs_System_E688BBTiles[]; /* 戻 */
extern const unsigned int TextGlyphs_System_E9818ETiles[]; /* 過 */
extern const unsigned int TextGlyphs_System_E8A1A3Tiles[]; /* 衣 */
extern const unsigned int TextGlyphs_System_E38282Tiles[]; /* も */
extern const unsigned int TextGlyphs_System_E58685Tiles[]; /* 内 */
extern const unsigned int TextGlyphs_System_E8B2A1Tiles[]; /* 財 */
extern const unsigned int TextGlyphs_System_E98791Tiles[]; /* 金 */
extern const unsigned int TextGlyphs_System_E99A8ATiles[]; /* 隊 */
extern const unsigned int TextGlyphs_System_E6ADA9Tiles[]; /* 歩 */
extern const unsigned int TextGlyphs_System_E8AAACTiles[]; /* 説 */
extern const unsigned int TextGlyphs_System_E68989Tiles[]; /* 扉 */
extern const unsigned int TextGlyphs_System_E38283Tiles[]; /* ゃ */
extern const unsigned int TextGlyphs_System_E88BA5Tiles[]; /* 若 */
extern const unsigned int TextGlyphs_System_E79CBCTiles[]; /* 眼 */
extern const unsigned int TextGlyphs_System_E4BD8ETiles[]; /* 低 */
extern const unsigned int TextGlyphs_System_E8A394Tiles[]; /* 裔 */
extern const unsigned int TextGlyphs_System_E99A9CTiles[]; /* 障 */
extern const unsigned int TextGlyphs_System_E5909FTiles[]; /* 吟 */
extern const unsigned int TextGlyphs_System_E99BAATiles[]; /* 雪 */
extern const unsigned int TextGlyphs_System_E4BE8BTiles[]; /* 例 */
extern const unsigned int TextGlyphs_System_E38284Tiles[]; /* や */
extern const unsigned int TextGlyphs_System_E7B5B6Tiles[]; /* 絶 */
extern const unsigned int TextGlyphs_System_E98A80Tiles[]; /* 銀 */
extern const unsigned int TextGlyphs_System_E586B7Tiles[]; /* 冷 */
extern const unsigned int TextGlyphs_System_E5B2A9Tiles[]; /* 岩 */
extern const unsigned int TextGlyphs_System_E981BATiles[]; /* 遺 */
extern const unsigned int TextGlyphs_System_E5958FTiles[]; /* 問 */
extern const unsigned int TextGlyphs_System_E5819CTiles[]; /* 停 */
extern const unsigned int TextGlyphs_System_E38285Tiles[]; /* ゅ */
extern const unsigned int TextGlyphs_System_E5BE8CTiles[]; /* 後 */
extern const unsigned int TextGlyphs_System_E4B88ATiles[]; /* 上 */
extern const unsigned int TextGlyphs_System_E4BBA3Tiles[]; /* 代 */
extern const unsigned int TextGlyphs_System_E5BCB1Tiles[]; /* 弱 */
extern const unsigned int TextGlyphs_System_E8888CTiles[]; /* 舌 */
extern const unsigned int TextGlyphs_System_E4B99DTiles[]; /* 九 */
extern const unsigned int TextGlyphs_System_E38286Tiles[]; /* ゆ */
extern const unsigned int TextGlyphs_System_E7B48BTiles[]; /* 紋 */
extern const unsigned int TextGlyphs_System_E8AC8ETiles[]; /* 謎 */
extern const unsigned int TextGlyphs_System_E5BEA1Tiles[]; /* 御 */
extern const unsigned int TextGlyphs_System_E68891Tiles[]; /* 我 */
extern const unsigned int TextGlyphs_System_E58FB0Tiles[]; /* 台 */
extern const unsigned int TextGlyphs_System_E4B888Tiles[]; /* 丈 */
extern const unsigned int TextGlyphs_System_E38287Tiles[]; /* ょ */
extern const unsigned int TextGlyphs_System_E5A4A7Tiles[]; /* 大 */
extern const unsigned int TextGlyphs_System_E4B8BBTiles[]; /* 主 */
extern const unsigned int TextGlyphs_System_E99680Tiles[]; /* 門 */
extern const unsigned int TextGlyphs_System_E78999Tiles[]; /* 牙 */
extern const unsigned int TextGlyphs_System_E58B9FTiles[]; /* 募 */
extern const unsigned int TextGlyphs_System_E6829FTiles[]; /* 悟 */
extern const unsigned int TextGlyphs_System_E38288Tiles[]; /* よ */
extern const unsigned int TextGlyphs_System_E58F96Tiles[]; /* 取 */
extern const unsigned int TextGlyphs_System_E59F9FTiles[]; /* 域 */
extern const unsigned int TextGlyphs_System_E58588Tiles[]; /* 先 */
extern const unsigned int TextGlyphs_System_E7ACACTiles[]; /* 第 */
extern const unsigned int TextGlyphs_System_E5A293Tiles[]; /* 墓 */
extern const unsigned int TextGlyphs_System_E4B997Tiles[]; /* 乗 */
extern const unsigned int TextGlyphs_System_E794BBTiles[]; /* 画 */
extern const unsigned int TextGlyphs_System_E38289Tiles[]; /* ら */
extern const unsigned int TextGlyphs_System_E5AE88Tiles[]; /* 守 */
extern const unsigned int TextGlyphs_System_E58D83Tiles[]; /* 千 */
extern const unsigned int TextGlyphs_System_E7A4BCTiles[]; /* 礼 */
extern const unsigned int TextGlyphs_System_E9A194Tiles[]; /* 顔 */
extern const unsigned int TextGlyphs_System_E882B2Tiles[]; /* 育 */
extern const unsigned int TextGlyphs_System_E58697Tiles[]; /* 冗 */
extern const unsigned int TextGlyphs_System_E592B2Tiles[]; /* 咲 */
extern const unsigned int TextGlyphs_System_E3828ATiles[]; /* り */
extern const unsigned int TextGlyphs_System_E58DA0Tiles[]; /* 占 */
extern const unsigned int TextGlyphs_System_E9A198Tiles[]; /* 願 */
extern const unsigned int TextGlyphs_System_E6898BTiles[]; /* 手 */
extern const unsigned int TextGlyphs_System_E5AE9ATiles[]; /* 定 */
extern const unsigned int TextGlyphs_System_E9A18CTiles[]; /* 題 */
extern const unsigned int TextGlyphs_System_E3828BTiles[]; /* る */
extern const unsigned int TextGlyphs_System_E5B89DTiles[]; /* 帝 */
extern const unsigned int TextGlyphs_System_E59F8ETiles[]; /* 城 */
extern const unsigned int TextGlyphs_System_E7A798Tiles[]; /* 秘 */
extern const unsigned int TextGlyphs_System_E69AAETiles[]; /* 暮 */
extern const unsigned int TextGlyphs_System_E5AEA3Tiles[]; /* 宣 */
extern const unsigned int TextGlyphs_System_E5A49CTiles[]; /* 夜 */
extern const unsigned int TextGlyphs_System_E3828CTiles[]; /* れ */
extern const unsigned int TextGlyphs_System_E88BA6Tiles[]; /* 苦 */
extern const unsigned int TextGlyphs_System_E5A0B4Tiles[]; /* 場 */
extern const unsigned int TextGlyphs_System_E6AF8DTiles[]; /* 母 */
extern const unsigned int TextGlyphs_System_E99AB7Tiles[]; /* 隷 */
extern const unsigned int TextGlyphs_System_E8AA9ETiles[]; /* 語 */
extern const unsigned int TextGlyphs_System_E6AE8ATiles[]; /* 殊 */
extern const unsigned int TextGlyphs_System_E4B880Tiles[]; /* 一 */
extern const unsigned int TextGlyphs_System_E5BA95Tiles[]; /* 底 */
extern const unsigned int TextGlyphs_System_E5B082Tiles[]; /* 専 */
extern const unsigned int TextGlyphs_System_E3828DTiles[]; /* ろ */
extern const unsigned int TextGlyphs_System_E58DB1Tiles[]; /* 危 */
extern const unsigned int TextGlyphs_System_E99B85Tiles[]; /* 雅 */
extern const unsigned int TextGlyphs_System_E78BA9Tiles[]; /* 狩 */
extern const unsigned int TextGlyphs_System_E8AAA4Tiles[]; /* 誤 */
extern const unsigned int TextGlyphs_System_E58D97Tiles[]; /* 南 */
extern const unsigned int TextGlyphs_System_E5969CTiles[]; /* 喜 */
extern const unsigned int TextGlyphs_System_E9878ETiles[]; /* 野 */
extern const unsigned int TextGlyphs_System_E5BBB7Tiles[]; /* 廷 */
extern const unsigned int TextGlyphs_System_E9A786Tiles[]; /* 駆 */
extern const unsigned int TextGlyphs_System_E8ADB7Tiles[]; /* 護 */
extern const unsigned int TextGlyphs_System_E4BD9CTiles[]; /* 作 */
extern const unsigned int TextGlyphs_System_E5B79DTiles[]; /* 川 */
extern const unsigned int TextGlyphs_System_E99C8ATiles[]; /* 霊 */
extern const unsigned int TextGlyphs_System_E3828FTiles[]; /* わ */
extern const unsigned int TextGlyphs_System_E688A6Tiles[]; /* 戦 */
extern const unsigned int TextGlyphs_System_E5BC9FTiles[]; /* 弟 */
extern const unsigned int TextGlyphs_System_E7A8AETiles[]; /* 種 */
extern const unsigned int TextGlyphs_System_E599A8Tiles[]; /* 器 */
extern const unsigned int TextGlyphs_System_E8A2ABTiles[]; /* 被 */
extern const unsigned int TextGlyphs_System_E580A3Tiles[]; /* 倣 */
extern const unsigned int TextGlyphs_System_E5898ATiles[]; /* 削 */
extern const unsigned int TextGlyphs_System_E5B8B8Tiles[]; /* 常 */
extern const unsigned int TextGlyphs_System_E68385Tiles[]; /* 情 */
extern const unsigned int TextGlyphs_System_E79FA2Tiles[]; /* 矢 */
extern const unsigned int TextGlyphs_System_E59FBATiles[]; /* 基 */
extern const unsigned int TextGlyphs_System_E7A8B2Tiles[]; /* 稲 */
extern const unsigned int TextGlyphs_System_E4BC9ATiles[]; /* 会 */
extern const unsigned int TextGlyphs_System_E58C85Tiles[]; /* 包 */
extern const unsigned int TextGlyphs_System_E99BA3Tiles[]; /* 難 */
extern const unsigned int TextGlyphs_System_E585B7Tiles[]; /* 具 */
extern const unsigned int TextGlyphs_System_E68AB5Tiles[]; /* 抵 */
extern const unsigned int TextGlyphs_System_E69AA6Tiles[]; /* 暦 */
extern const unsigned int TextGlyphs_System_E5A587Tiles[]; /* 奇 */
extern const unsigned int TextGlyphs_System_E38292Tiles[]; /* を */
extern const unsigned int TextGlyphs_System_E8A7A3Tiles[]; /* 解 */
extern const unsigned int TextGlyphs_System_E6ADB4Tiles[]; /* 歴 */
extern const unsigned int TextGlyphs_System_E68A9ETiles[]; /* 択 */
extern const unsigned int TextGlyphs_System_E5BDB9Tiles[]; /* 役 */
extern const unsigned int TextGlyphs_System_E4BAA4Tiles[]; /* 交 */
extern const unsigned int TextGlyphs_System_E69DA1Tiles[]; /* 条 */
extern const unsigned int TextGlyphs_System_E981BFTiles[]; /* 避 */
extern const unsigned int TextGlyphs_System_E6B19DTiles[]; /* 汝 */
extern const unsigned int TextGlyphs_System_E98592Tiles[]; /* 酒 */
extern const unsigned int TextGlyphs_System_E38293Tiles[]; /* ん */
extern const unsigned int TextGlyphs_System_E69D96Tiles[]; /* 杖 */
extern const unsigned int TextGlyphs_System_E59B9ETiles[]; /* 回 */
extern const unsigned int TextGlyphs_System_E99D9ETiles[]; /* 非 */
extern const unsigned int TextGlyphs_System_E5A0B1Tiles[]; /* 報 */
extern const unsigned int TextGlyphs_System_E7B484Tiles[]; /* 約 */
extern const unsigned int TextGlyphs_System_E68B93Tiles[]; /* 拓 */
extern const unsigned int TextGlyphs_System_E5AF84Tiles[]; /* 寄 */
extern const unsigned int TextGlyphs_System_E9A696Tiles[]; /* 首 */
extern const unsigned int TextGlyphs_System_E4BA8CTiles[]; /* 二 */
extern const unsigned int TextGlyphs_System_E9A39BTiles[]; /* 飛 */
extern const unsigned int TextGlyphs_System_E4BEAFTiles[]; /* 侯 */
extern const unsigned int TextGlyphs_System_E58AA3Tiles[]; /* 劣 */
extern const unsigned int TextGlyphs_System_E78AB6Tiles[]; /* 状 */
extern const unsigned int TextGlyphs_System_E5AE9DTiles[]; /* 宝 */
extern const unsigned int TextGlyphs_System_E58F97Tiles[]; /* 受 */
extern const unsigned int TextGlyphs_System_E7A9BATiles[]; /* 空 */
extern const unsigned int TextGlyphs_System_E5A38ATiles[]; /* 壊 */
extern const unsigned int TextGlyphs_System_E58DB0Tiles[]; /* 印 */
extern const unsigned int TextGlyphs_System_E5B88CTiles[]; /* 希 */
extern const unsigned int TextGlyphs_System_E8A8B3Tiles[]; /* 訳 */
extern const unsigned int TextGlyphs_System_E78388Tiles[]; /* 烈 */
extern const unsigned int TextGlyphs_System_E591AATiles[]; /* 呪 */
extern const unsigned int TextGlyphs_System_E8A382Tiles[]; /* 裂 */
extern const unsigned int TextGlyphs_System_E8BA8DTiles[]; /* 躍 */
extern const unsigned int TextGlyphs_System_E58299Tiles[]; /* 備 */
extern const unsigned int TextGlyphs_System_E58589Tiles[]; /* 光 */
extern const unsigned int TextGlyphs_System_E593A1Tiles[]; /* 員 */
extern const unsigned int TextGlyphs_System_E8A897Tiles[]; /* 託 */
extern const unsigned int TextGlyphs_System_E5BFABTiles[]; /* 快 */
extern const unsigned int TextGlyphs_System_E58C82Tiles[]; /* 匂 */
extern const unsigned int TextGlyphs_System_E585ACTiles[]; /* 公 */
extern const unsigned int TextGlyphs_System_E68FAETiles[]; /* 揮 */
extern const unsigned int TextGlyphs_System_E6818BTiles[]; /* 恋 */
extern const unsigned int TextGlyphs_System_E5B4A9Tiles[]; /* 崩 */
extern const unsigned int TextGlyphs_System_E68E88Tiles[]; /* 授 */
extern const unsigned int TextGlyphs_System_E680AATiles[]; /* 怪 */
extern const unsigned int TextGlyphs_System_E59BA0Tiles[]; /* 因 */
extern const unsigned int TextGlyphs_System_E7A88BTiles[]; /* 程 */
extern const unsigned int TextGlyphs_System_E68294Tiles[]; /* 悔 */
extern const unsigned int TextGlyphs_System_E88289Tiles[]; /* 肉 */
extern const unsigned int TextGlyphs_System_E58A9FTiles[]; /* 功 */
extern const unsigned int TextGlyphs_System_E5BEAETiles[]; /* 微 */
extern const unsigned int TextGlyphs_System_E68690Tiles[]; /* 憐 */
extern const unsigned int TextGlyphs_System_E58AB9Tiles[]; /* 効 */
extern const unsigned int TextGlyphs_System_E5BC95Tiles[]; /* 引 */
extern const unsigned int TextGlyphs_System_E69797Tiles[]; /* 旗 */
extern const unsigned int TextGlyphs_System_E68AB1Tiles[]; /* 抱 */
extern const unsigned int TextGlyphs_System_E5A5A2Tiles[]; /* 奢 */
extern const unsigned int TextGlyphs_System_E6978BTiles[]; /* 旋 */
extern const unsigned int TextGlyphs_System_E9A3B2Tiles[]; /* 飲 */
extern const unsigned int TextGlyphs_System_E697A5Tiles[]; /* 日 */
extern const unsigned int TextGlyphs_System_E694BETiles[]; /* 放 */
extern const unsigned int TextGlyphs_System_E69C9FTiles[]; /* 期 */
extern const unsigned int TextGlyphs_System_E6AA84Tiles[]; /* 檄 */
extern const unsigned int TextGlyphs_System_E59B9ATiles[]; /* 囚 */
extern const unsigned int TextGlyphs_System_E58E9ATiles[]; /* 厚 */
extern const unsigned int TextGlyphs_System_E696B9Tiles[]; /* 方 */
extern const unsigned int TextGlyphs_System_E68B90Tiles[]; /* 拐 */
extern const unsigned int TextGlyphs_System_E58FA3Tiles[]; /* 口 */
extern const unsigned int TextGlyphs_System_E6B2B9Tiles[]; /* 油 */
extern const unsigned int TextGlyphs_System_E7B7B4Tiles[]; /* 練 */
extern const unsigned int TextGlyphs_System_E585A5Tiles[]; /* 入 */
extern const unsigned int TextGlyphs_System_E59091Tiles[]; /* 向 */
extern const unsigned int TextGlyphs_System_E7BE8ETiles[]; /* 美 */
extern const unsigned int TextGlyphs_System_E5B188Tiles[]; /* 屈 */
extern const unsigned int TextGlyphs_System_E694B9Tiles[]; /* 改 */
extern const unsigned int TextGlyphs_System_E7B79ATiles[]; /* 線 */
extern const unsigned int TextGlyphs_System_E591A8Tiles[]; /* 周 */
