#pragma once

extern const u32 TextGlyphs_System_e382a1_bitmap[]; // ァ
extern const u32 TextGlyphs_System_e285b0_bitmap[]; // ⅰ
extern const u32 TextGlyphs_System_e38080_bitmap[]; // 　
extern const u32 TextGlyphs_System_e6b395_bitmap[]; // 法
extern const u32 TextGlyphs_System_e999a2_bitmap[]; // 院
extern const u32 TextGlyphs_System_e6a99f_bitmap[]; // 機
extern const u32 TextGlyphs_System_e68e98_bitmap[]; // 掘
extern const u32 TextGlyphs_System_e58fa9_bitmap[]; // 叩
extern const u32 TextGlyphs_System_e291a0_bitmap[]; // ①
extern const u32 TextGlyphs_System_e893ae_bitmap[]; // 蓮
extern const u32 TextGlyphs_System_e382a2_bitmap[]; // ア
extern const u32 TextGlyphs_System_e285b1_bitmap[]; // ⅱ
extern const u32 TextGlyphs_System_e38081_bitmap[]; // 、
extern const u32 TextGlyphs_System_e999b0_bitmap[]; // 陰
extern const u32 TextGlyphs_System_e980a3_bitmap[]; // 連
extern const u32 TextGlyphs_System_e5b8b0_bitmap[]; // 帰
extern const u32 TextGlyphs_System_e291a1_bitmap[]; // ②
extern const u32 TextGlyphs_System_e8bcb8_bitmap[]; // 輸
extern const u32 TextGlyphs_System_e7aa9f_bitmap[]; // 窟
extern const u32 TextGlyphs_System_e382a3_bitmap[]; // ィ
extern const u32 TextGlyphs_System_e285b2_bitmap[]; // ⅲ
extern const u32 TextGlyphs_System_e38082_bitmap[]; // 。
extern const u32 TextGlyphs_System_e594af_bitmap[]; // 唯
extern const u32 TextGlyphs_System_e98194_bitmap[]; // 達
extern const u32 TextGlyphs_System_e99aa0_bitmap[]; // 隠
extern const u32 TextGlyphs_System_e291a2_bitmap[]; // ③
extern const u32 TextGlyphs_System_e382a4_bitmap[]; // イ
extern const u32 TextGlyphs_System_e285b3_bitmap[]; // ⅳ
extern const u32 TextGlyphs_System_efbc8c_bitmap[]; // ，
extern const u32 TextGlyphs_System_e6b097_bitmap[]; // 気
extern const u32 TextGlyphs_System_e6b5b7_bitmap[]; // 海
extern const u32 TextGlyphs_System_e4bfae_bitmap[]; // 修
extern const u32 TextGlyphs_System_e4bbbb_bitmap[]; // 任
extern const u32 TextGlyphs_System_e291a3_bitmap[]; // ④
extern const u32 TextGlyphs_System_e382a5_bitmap[]; // ゥ
extern const u32 TextGlyphs_System_e285b4_bitmap[]; // ⅴ
extern const u32 TextGlyphs_System_efbc8e_bitmap[]; // ．
extern const u32 TextGlyphs_System_e5a5bd_bitmap[]; // 好
extern const u32 TextGlyphs_System_e5a5aa_bitmap[]; // 奪
extern const u32 TextGlyphs_System_e7b994_bitmap[]; // 織
extern const u32 TextGlyphs_System_e6b3a5_bitmap[]; // 泥
extern const u32 TextGlyphs_System_e584aa_bitmap[]; // 優
extern const u32 TextGlyphs_System_e291a4_bitmap[]; // ⑤
extern const u32 TextGlyphs_System_e781b0_bitmap[]; // 灰
extern const u32 TextGlyphs_System_e382a6_bitmap[]; // ウ
extern const u32 TextGlyphs_System_e285b5_bitmap[]; // ⅵ
extern const u32 TextGlyphs_System_e383bb_bitmap[]; // ・
extern const u32 TextGlyphs_System_e58b87_bitmap[]; // 勇
extern const u32 TextGlyphs_System_e6aeba_bitmap[]; // 殺
extern const u32 TextGlyphs_System_e7958c_bitmap[]; // 界
extern const u32 TextGlyphs_System_e884b1_bitmap[]; // 脱
extern const u32 TextGlyphs_System_e881b7_bitmap[]; // 職
extern const u32 TextGlyphs_System_e58fb3_bitmap[]; // 右
extern const u32 TextGlyphs_System_e291a5_bitmap[]; // ⑥
extern const u32 TextGlyphs_System_e382a7_bitmap[]; // ェ
extern const u32 TextGlyphs_System_e285b6_bitmap[]; // ⅶ
extern const u32 TextGlyphs_System_efbc9a_bitmap[]; // ：
extern const u32 TextGlyphs_System_e58f8b_bitmap[]; // 友
extern const u32 TextGlyphs_System_e79a86_bitmap[]; // 皆
extern const u32 TextGlyphs_System_e8aa8d_bitmap[]; // 認
extern const u32 TextGlyphs_System_e5ad9d_bitmap[]; // 孝
extern const u32 TextGlyphs_System_e291a6_bitmap[]; // ⑦
extern const u32 TextGlyphs_System_e889b2_bitmap[]; // 色
extern const u32 TextGlyphs_System_e382a8_bitmap[]; // エ
extern const u32 TextGlyphs_System_e285b7_bitmap[]; // ⅷ
extern const u32 TextGlyphs_System_e695b5_bitmap[]; // 敵
extern const u32 TextGlyphs_System_e99b91_bitmap[]; // 雑
extern const u32 TextGlyphs_System_e7a780_bitmap[]; // 秀
extern const u32 TextGlyphs_System_e382a9_bitmap[]; // ォ
extern const u32 TextGlyphs_System_e285b8_bitmap[]; // ⅸ
extern const u32 TextGlyphs_System_efbc9f_bitmap[]; // ？
extern const u32 TextGlyphs_System_e8b7af_bitmap[]; // 路
extern const u32 TextGlyphs_System_e7bebd_bitmap[]; // 羽
extern const u32 TextGlyphs_System_e382aa_bitmap[]; // オ
extern const u32 TextGlyphs_System_e285b9_bitmap[]; // ⅹ
extern const u32 TextGlyphs_System_efbc81_bitmap[]; // ！
extern const u32 TextGlyphs_System_e79a84_bitmap[]; // 的
extern const u32 TextGlyphs_System_e981b8_bitmap[]; // 選
extern const u32 TextGlyphs_System_e7b582_bitmap[]; // 終
extern const u32 TextGlyphs_System_e89c82_bitmap[]; // 蜂
extern const u32 TextGlyphs_System_e382ab_bitmap[]; // カ
extern const u32 TextGlyphs_System_e8b0b7_bitmap[]; // 谷
extern const u32 TextGlyphs_System_e9968b_bitmap[]; // 開
extern const u32 TextGlyphs_System_e58ab4_bitmap[]; // 労
extern const u32 TextGlyphs_System_e99ba8_bitmap[]; // 雨
extern const u32 TextGlyphs_System_e291aa_bitmap[]; // ⑪
extern const u32 TextGlyphs_System_e3829b_bitmap[]; // ゛
extern const u32 TextGlyphs_System_e382ac_bitmap[]; // ガ
extern const u32 TextGlyphs_System_e68f96_bitmap[]; // 揖
extern const u32 TextGlyphs_System_e5bf85_bitmap[]; // 必
extern const u32 TextGlyphs_System_e5b9b8_bitmap[]; // 幸
extern const u32 TextGlyphs_System_e8a8aa_bitmap[]; // 訪
extern const u32 TextGlyphs_System_e8a68f_bitmap[]; // 規
extern const u32 TextGlyphs_System_e99a8e_bitmap[]; // 階
extern const u32 TextGlyphs_System_e291ab_bitmap[]; // ⑫
extern const u32 TextGlyphs_System_e3829c_bitmap[]; // ゜
extern const u32 TextGlyphs_System_e7bf92_bitmap[]; // 習
extern const u32 TextGlyphs_System_e382ad_bitmap[]; // キ
extern const u32 TextGlyphs_System_e8b18a_bitmap[]; // 豊
extern const u32 TextGlyphs_System_e8a898_bitmap[]; // 記
extern const u32 TextGlyphs_System_e69c89_bitmap[]; // 有
extern const u32 TextGlyphs_System_e5ba83_bitmap[]; // 広
extern const u32 TextGlyphs_System_e291ac_bitmap[]; // ⑬
extern const u32 TextGlyphs_System_e78cab_bitmap[]; // 猫
extern const u32 TextGlyphs_System_e382ae_bitmap[]; // ギ
extern const u32 TextGlyphs_System_e8b2b4_bitmap[]; // 貴
extern const u32 TextGlyphs_System_e4bfa1_bitmap[]; // 信
extern const u32 TextGlyphs_System_e786b1_bitmap[]; // 熱
extern const u32 TextGlyphs_System_e587b1_bitmap[]; // 凱
extern const u32 TextGlyphs_System_e58bb2_bitmap[]; // 勲
extern const u32 TextGlyphs_System_e291ad_bitmap[]; // ⑭
extern const u32 TextGlyphs_System_e382af_bitmap[]; // ク
extern const u32 TextGlyphs_System_e5b9b4_bitmap[]; // 年
extern const u32 TextGlyphs_System_e4beb5_bitmap[]; // 侵
extern const u32 TextGlyphs_System_e8b5b7_bitmap[]; // 起
extern const u32 TextGlyphs_System_e5909b_bitmap[]; // 君
extern const u32 TextGlyphs_System_e8aab0_bitmap[]; // 誰
extern const u32 TextGlyphs_System_e291ae_bitmap[]; // ⑮
extern const u32 TextGlyphs_System_e69c97_bitmap[]; // 朗
extern const u32 TextGlyphs_System_e382b0_bitmap[]; // グ
extern const u32 TextGlyphs_System_efbc90_bitmap[]; // ０
extern const u32 TextGlyphs_System_e5898d_bitmap[]; // 前
extern const u32 TextGlyphs_System_e5a496_bitmap[]; // 外
extern const u32 TextGlyphs_System_e5bfb5_bitmap[]; // 念
extern const u32 TextGlyphs_System_e4b889_bitmap[]; // 三
extern const u32 TextGlyphs_System_e291af_bitmap[]; // ⑯
extern const u32 TextGlyphs_System_e382b1_bitmap[]; // ケ
extern const u32 TextGlyphs_System_efbc91_bitmap[]; // １
extern const u32 TextGlyphs_System_e5a7ab_bitmap[]; // 姫
extern const u32 TextGlyphs_System_e59684_bitmap[]; // 善
extern const u32 TextGlyphs_System_e58d98_bitmap[]; // 単
extern const u32 TextGlyphs_System_e291b0_bitmap[]; // ⑰
extern const u32 TextGlyphs_System_e382b2_bitmap[]; // ゲ
extern const u32 TextGlyphs_System_efbc92_bitmap[]; // ２
extern const u32 TextGlyphs_System_e59886_bitmap[]; // 嘆
extern const u32 TextGlyphs_System_e58f82_bitmap[]; // 参
extern const u32 TextGlyphs_System_e5aeb3_bitmap[]; // 害
extern const u32 TextGlyphs_System_e6b5aa_bitmap[]; // 浪
extern const u32 TextGlyphs_System_e7bea4_bitmap[]; // 群
extern const u32 TextGlyphs_System_e382b3_bitmap[]; // コ
extern const u32 TextGlyphs_System_efbc93_bitmap[]; // ３
extern const u32 TextGlyphs_System_e8bb8d_bitmap[]; // 軍
extern const u32 TextGlyphs_System_e9a88e_bitmap[]; // 騎
extern const u32 TextGlyphs_System_e5b1b1_bitmap[]; // 山
extern const u32 TextGlyphs_System_e784b6_bitmap[]; // 然
extern const u32 TextGlyphs_System_e794b1_bitmap[]; // 由
extern const u32 TextGlyphs_System_e68a97_bitmap[]; // 抗
extern const u32 TextGlyphs_System_e382b4_bitmap[]; // ゴ
extern const u32 TextGlyphs_System_efbc94_bitmap[]; // ４
extern const u32 TextGlyphs_System_e585a8_bitmap[]; // 全
extern const u32 TextGlyphs_System_e4baa1_bitmap[]; // 亡
extern const u32 TextGlyphs_System_e5bf83_bitmap[]; // 心
extern const u32 TextGlyphs_System_e98984_bitmap[]; // 鉄
extern const u32 TextGlyphs_System_e799be_bitmap[]; // 百
extern const u32 TextGlyphs_System_e683a8_bitmap[]; // 惨
extern const u32 TextGlyphs_System_e68b85_bitmap[]; // 担
extern const u32 TextGlyphs_System_e789a2_bitmap[]; // 牢
extern const u32 TextGlyphs_System_e9acbc_bitmap[]; // 鬼
extern const u32 TextGlyphs_System_e382b5_bitmap[]; // サ
extern const u32 TextGlyphs_System_efbc95_bitmap[]; // ５
extern const u32 TextGlyphs_System_e78bbc_bitmap[]; // 狼
extern const u32 TextGlyphs_System_e68ea7_bitmap[]; // 控
extern const u32 TextGlyphs_System_e68ea2_bitmap[]; // 探
extern const u32 TextGlyphs_System_e585b8_bitmap[]; // 典
extern const u32 TextGlyphs_System_e285a0_bitmap[]; // Ⅰ
extern const u32 TextGlyphs_System_e382b6_bitmap[]; // ザ
extern const u32 TextGlyphs_System_efbc96_bitmap[]; // ６
extern const u32 TextGlyphs_System_e694bb_bitmap[]; // 攻
extern const u32 TextGlyphs_System_e695a3_bitmap[]; // 散
extern const u32 TextGlyphs_System_e8aa98_bitmap[]; // 誘
extern const u32 TextGlyphs_System_e6b6af_bitmap[]; // 涯
extern const u32 TextGlyphs_System_e285a1_bitmap[]; // Ⅱ
extern const u32 TextGlyphs_System_e382b7_bitmap[]; // シ
extern const u32 TextGlyphs_System_efbc97_bitmap[]; // ７
extern const u32 TextGlyphs_System_e88081_bitmap[]; // 老
extern const u32 TextGlyphs_System_e5a4a9_bitmap[]; // 天
extern const u32 TextGlyphs_System_e696b0_bitmap[]; // 新
extern const u32 TextGlyphs_System_e9818a_bitmap[]; // 遊
extern const u32 TextGlyphs_System_e58480_bitmap[]; // 儀
extern const u32 TextGlyphs_System_e285a2_bitmap[]; // Ⅲ
extern const u32 TextGlyphs_System_e382b8_bitmap[]; // ジ
extern const u32 TextGlyphs_System_efbc98_bitmap[]; // ８
extern const u32 TextGlyphs_System_e99b86_bitmap[]; // 集
extern const u32 TextGlyphs_System_e6a899_bitmap[]; // 標
extern const u32 TextGlyphs_System_e4bf82_bitmap[]; // 係
extern const u32 TextGlyphs_System_e5b195_bitmap[]; // 展
extern const u32 TextGlyphs_System_e285a3_bitmap[]; // Ⅳ
extern const u32 TextGlyphs_System_e382b9_bitmap[]; // ス
extern const u32 TextGlyphs_System_efbc99_bitmap[]; // ９
extern const u32 TextGlyphs_System_e5ba97_bitmap[]; // 店
extern const u32 TextGlyphs_System_e38085_bitmap[]; // 々
extern const u32 TextGlyphs_System_e8a197_bitmap[]; // 街
extern const u32 TextGlyphs_System_e6b0b7_bitmap[]; // 氷
extern const u32 TextGlyphs_System_e6a3ae_bitmap[]; // 森
extern const u32 TextGlyphs_System_e69bb4_bitmap[]; // 更
extern const u32 TextGlyphs_System_e285a4_bitmap[]; // Ⅴ
extern const u32 TextGlyphs_System_e382ba_bitmap[]; // ズ
extern const u32 TextGlyphs_System_e99b84_bitmap[]; // 雄
extern const u32 TextGlyphs_System_e794a3_bitmap[]; // 産
extern const u32 TextGlyphs_System_e58891_bitmap[]; // 刑
extern const u32 TextGlyphs_System_e5bf98_bitmap[]; // 忘
extern const u32 TextGlyphs_System_e9838e_bitmap[]; // 郎
extern const u32 TextGlyphs_System_e285a5_bitmap[]; // Ⅵ
extern const u32 TextGlyphs_System_e382bb_bitmap[]; // セ
extern const u32 TextGlyphs_System_e68a80_bitmap[]; // 技
extern const u32 TextGlyphs_System_e58584_bitmap[]; // 兄
extern const u32 TextGlyphs_System_e79fad_bitmap[]; // 短
extern const u32 TextGlyphs_System_e4bd8f_bitmap[]; // 住
extern const u32 TextGlyphs_System_e6a0a1_bitmap[]; // 校
extern const u32 TextGlyphs_System_e585ad_bitmap[]; // 六
extern const u32 TextGlyphs_System_e285a6_bitmap[]; // Ⅶ
extern const u32 TextGlyphs_System_e382bc_bitmap[]; // ゼ
extern const u32 TextGlyphs_System_e383bc_bitmap[]; // ー
extern const u32 TextGlyphs_System_e6b7b1_bitmap[]; // 深
extern const u32 TextGlyphs_System_e7abaf_bitmap[]; // 端
extern const u32 TextGlyphs_System_e382bd_bitmap[]; // ソ
extern const u32 TextGlyphs_System_e8a1a8_bitmap[]; // 表
extern const u32 TextGlyphs_System_e883bd_bitmap[]; // 能
extern const u32 TextGlyphs_System_e794b3_bitmap[]; // 申
extern const u32 TextGlyphs_System_e4ba88_bitmap[]; // 予
extern const u32 TextGlyphs_System_e58d81_bitmap[]; // 十
extern const u32 TextGlyphs_System_e382be_bitmap[]; // ゾ
extern const u32 TextGlyphs_System_e5be93_bitmap[]; // 従
extern const u32 TextGlyphs_System_e69c9b_bitmap[]; // 望
extern const u32 TextGlyphs_System_e8bba2_bitmap[]; // 転
extern const u32 TextGlyphs_System_e78aa0_bitmap[]; // 犠
extern const u32 TextGlyphs_System_e4bd99_bitmap[]; // 余
extern const u32 TextGlyphs_System_e8a995_bitmap[]; // 評
extern const u32 TextGlyphs_System_e382bf_bitmap[]; // タ
extern const u32 TextGlyphs_System_efbc8f_bitmap[]; // ／
extern const u32 TextGlyphs_System_e9818b_bitmap[]; // 運
extern const u32 TextGlyphs_System_e79c9f_bitmap[]; // 真
extern const u32 TextGlyphs_System_e98cb2_bitmap[]; // 録
extern const u32 TextGlyphs_System_e4b88e_bitmap[]; // 与
extern const u32 TextGlyphs_System_e38380_bitmap[]; // ダ
extern const u32 TextGlyphs_System_e7a59e_bitmap[]; // 神
extern const u32 TextGlyphs_System_e99bb2_bitmap[]; // 雲
extern const u32 TextGlyphs_System_e8aa89_bitmap[]; // 誉
extern const u32 TextGlyphs_System_e5a591_bitmap[]; // 契
extern const u32 TextGlyphs_System_efbcbc_bitmap[]; // ＼
extern const u32 TextGlyphs_System_e782b9_bitmap[]; // 点
extern const u32 TextGlyphs_System_e38381_bitmap[]; // チ
extern const u32 TextGlyphs_System_efbd9e_bitmap[]; // ～
extern const u32 TextGlyphs_System_efbca1_bitmap[]; // Ａ
extern const u32 TextGlyphs_System_e6b8af_bitmap[]; // 港
extern const u32 TextGlyphs_System_e7bea9_bitmap[]; // 義
extern const u32 TextGlyphs_System_e4bc9d_bitmap[]; // 伝
extern const u32 TextGlyphs_System_e5bda2_bitmap[]; // 形
extern const u32 TextGlyphs_System_e580ad_bitmap[]; // 倭
extern const u32 TextGlyphs_System_e38382_bitmap[]; // ヂ
extern const u32 TextGlyphs_System_efbca2_bitmap[]; // Ｂ
extern const u32 TextGlyphs_System_e6aebf_bitmap[]; // 殿
extern const u32 TextGlyphs_System_e5928c_bitmap[]; // 和
extern const u32 TextGlyphs_System_e79785_bitmap[]; // 病
extern const u32 TextGlyphs_System_e8aa95_bitmap[]; // 誕
extern const u32 TextGlyphs_System_e9a090_bitmap[]; // 預
extern const u32 TextGlyphs_System_e38383_bitmap[]; // ッ
extern const u32 TextGlyphs_System_efbca3_bitmap[]; // Ｃ
extern const u32 TextGlyphs_System_e8a9b1_bitmap[]; // 話
extern const u32 TextGlyphs_System_e582ad_bitmap[]; // 傭
extern const u32 TextGlyphs_System_e887a3_bitmap[]; // 臣
extern const u32 TextGlyphs_System_e794b2_bitmap[]; // 甲
extern const u32 TextGlyphs_System_e38384_bitmap[]; // ツ
extern const u32 TextGlyphs_System_efbca4_bitmap[]; // Ｄ
extern const u32 TextGlyphs_System_e79a87_bitmap[]; // 皇
extern const u32 TextGlyphs_System_e59ba3_bitmap[]; // 団
extern const u32 TextGlyphs_System_e7a596_bitmap[]; // 祖
extern const u32 TextGlyphs_System_e6ae8b_bitmap[]; // 残
extern const u32 TextGlyphs_System_e8adb0_bitmap[]; // 議
extern const u32 TextGlyphs_System_e596b6_bitmap[]; // 営
extern const u32 TextGlyphs_System_e5b9bc_bitmap[]; // 幼
extern const u32 TextGlyphs_System_e38385_bitmap[]; // ヅ
extern const u32 TextGlyphs_System_efbca5_bitmap[]; // Ｅ
extern const u32 TextGlyphs_System_e5a387_bitmap[]; // 壇
extern const u32 TextGlyphs_System_e99bbb_bitmap[]; // 電
extern const u32 TextGlyphs_System_e9878d_bitmap[]; // 重
extern const u32 TextGlyphs_System_e4bb95_bitmap[]; // 仕
extern const u32 TextGlyphs_System_e8ac80_bitmap[]; // 謀
extern const u32 TextGlyphs_System_e38386_bitmap[]; // テ
extern const u32 TextGlyphs_System_efbca6_bitmap[]; // Ｆ
extern const u32 TextGlyphs_System_e8a6aa_bitmap[]; // 親
extern const u32 TextGlyphs_System_e59084_bitmap[]; // 各
extern const u32 TextGlyphs_System_e8a687_bitmap[]; // 覇
extern const u32 TextGlyphs_System_e5aeb9_bitmap[]; // 容
extern const u32 TextGlyphs_System_e5bdb1_bitmap[]; // 影
extern const u32 TextGlyphs_System_e5bcbe_bitmap[]; // 弾
extern const u32 TextGlyphs_System_e38387_bitmap[]; // デ
extern const u32 TextGlyphs_System_efbca7_bitmap[]; // Ｇ
extern const u32 TextGlyphs_System_e696ad_bitmap[]; // 断
extern const u32 TextGlyphs_System_e8b2bf_bitmap[]; // 貿
extern const u32 TextGlyphs_System_e68391_bitmap[]; // 惑
extern const u32 TextGlyphs_System_e7b4a0_bitmap[]; // 素
extern const u32 TextGlyphs_System_e38388_bitmap[]; // ト
extern const u32 TextGlyphs_System_efbca8_bitmap[]; // Ｈ
extern const u32 TextGlyphs_System_e4bdbf_bitmap[]; // 使
extern const u32 TextGlyphs_System_e8baab_bitmap[]; // 身
extern const u32 TextGlyphs_System_e7b485_bitmap[]; // 紅
extern const u32 TextGlyphs_System_e69a96_bitmap[]; // 暖
extern const u32 TextGlyphs_System_e7b584_bitmap[]; // 組
extern const u32 TextGlyphs_System_e68ba1_bitmap[]; // 拡
extern const u32 TextGlyphs_System_e38389_bitmap[]; // ド
extern const u32 TextGlyphs_System_efbca9_bitmap[]; // Ｉ
extern const u32 TextGlyphs_System_e8be9b_bitmap[]; // 辛
extern const u32 TextGlyphs_System_e998b2_bitmap[]; // 防
extern const u32 TextGlyphs_System_e6a084_bitmap[]; // 栄
extern const u32 TextGlyphs_System_e6b4be_bitmap[]; // 派
extern const u32 TextGlyphs_System_e5aebf_bitmap[]; // 宿
extern const u32 TextGlyphs_System_e695ac_bitmap[]; // 敬
extern const u32 TextGlyphs_System_e3838a_bitmap[]; // ナ
extern const u32 TextGlyphs_System_efbc88_bitmap[]; // （
extern const u32 TextGlyphs_System_efbcaa_bitmap[]; // Ｊ
extern const u32 TextGlyphs_System_e980b2_bitmap[]; // 進
extern const u32 TextGlyphs_System_e58fb8_bitmap[]; // 司
extern const u32 TextGlyphs_System_e699af_bitmap[]; // 景
extern const u32 TextGlyphs_System_e6b0b8_bitmap[]; // 永
extern const u32 TextGlyphs_System_e6a0bc_bitmap[]; // 格
extern const u32 TextGlyphs_System_e6aeb5_bitmap[]; // 段
extern const u32 TextGlyphs_System_e59381_bitmap[]; // 品
extern const u32 TextGlyphs_System_e590a0_bitmap[]; // 吠
extern const u32 TextGlyphs_System_e3838b_bitmap[]; // ニ
extern const u32 TextGlyphs_System_efbc89_bitmap[]; // ）
extern const u32 TextGlyphs_System_efbcab_bitmap[]; // Ｋ
extern const u32 TextGlyphs_System_e794b7_bitmap[]; // 男
extern const u32 TextGlyphs_System_e7a0b4_bitmap[]; // 破
extern const u32 TextGlyphs_System_e998bb_bitmap[]; // 阻
extern const u32 TextGlyphs_System_e58fb2_bitmap[]; // 史
extern const u32 TextGlyphs_System_e3838c_bitmap[]; // ヌ
extern const u32 TextGlyphs_System_efbcac_bitmap[]; // Ｌ
extern const u32 TextGlyphs_System_e58c97_bitmap[]; // 北
extern const u32 TextGlyphs_System_e5be92_bitmap[]; // 徒
extern const u32 TextGlyphs_System_e8ab87_bitmap[]; // 談
extern const u32 TextGlyphs_System_e3838d_bitmap[]; // ネ
extern const u32 TextGlyphs_System_efbcad_bitmap[]; // Ｍ
extern const u32 TextGlyphs_System_e4baba_bitmap[]; // 人
extern const u32 TextGlyphs_System_e6a798_bitmap[]; // 様
extern const u32 TextGlyphs_System_e580a4_bitmap[]; // 値
extern const u32 TextGlyphs_System_e7b29b_bitmap[]; // 粛
extern const u32 TextGlyphs_System_e59b9b_bitmap[]; // 四
extern const u32 TextGlyphs_System_e3838e_bitmap[]; // ノ
extern const u32 TextGlyphs_System_efbcae_bitmap[]; // Ｎ
extern const u32 TextGlyphs_System_e5a3ab_bitmap[]; // 士
extern const u32 TextGlyphs_System_e79fa5_bitmap[]; // 知
extern const u32 TextGlyphs_System_e583a7_bitmap[]; // 僧
extern const u32 TextGlyphs_System_e7a2ba_bitmap[]; // 確
extern const u32 TextGlyphs_System_e3838f_bitmap[]; // ハ
extern const u32 TextGlyphs_System_efbcaf_bitmap[]; // Ｏ
extern const u32 TextGlyphs_System_e7b3bb_bitmap[]; // 系
extern const u32 TextGlyphs_System_e59cb0_bitmap[]; // 地
extern const u32 TextGlyphs_System_e5a78b_bitmap[]; // 始
extern const u32 TextGlyphs_System_e9a6ac_bitmap[]; // 馬
extern const u32 TextGlyphs_System_e6bab6_bitmap[]; // 溶
extern const u32 TextGlyphs_System_e589b5_bitmap[]; // 創
extern const u32 TextGlyphs_System_e58883_bitmap[]; // 刃
extern const u32 TextGlyphs_System_e6b8a1_bitmap[]; // 渡
extern const u32 TextGlyphs_System_e38390_bitmap[]; // バ
extern const u32 TextGlyphs_System_efbcb0_bitmap[]; // Ｐ
extern const u32 TextGlyphs_System_e587ba_bitmap[]; // 出
extern const u32 TextGlyphs_System_e5a789_bitmap[]; // 姉
extern const u32 TextGlyphs_System_e7b58c_bitmap[]; // 経
extern const u32 TextGlyphs_System_e58f8c_bitmap[]; // 双
extern const u32 TextGlyphs_System_e8a69a_bitmap[]; // 覚
extern const u32 TextGlyphs_System_e38391_bitmap[]; // パ
extern const u32 TextGlyphs_System_efbcb1_bitmap[]; // Ｑ
extern const u32 TextGlyphs_System_e794a8_bitmap[]; // 用
extern const u32 TextGlyphs_System_e88bb1_bitmap[]; // 英
extern const u32 TextGlyphs_System_e8a193_bitmap[]; // 術
extern const u32 TextGlyphs_System_e7b699_bitmap[]; // 継
extern const u32 TextGlyphs_System_e5a7bf_bitmap[]; // 姿
extern const u32 TextGlyphs_System_e58db4_bitmap[]; // 却
extern const u32 TextGlyphs_System_e681a5_bitmap[]; // 恥
extern const u32 TextGlyphs_System_e5bb83_bitmap[]; // 廃
extern const u32 TextGlyphs_System_e38392_bitmap[]; // ヒ
extern const u32 TextGlyphs_System_efbcb2_bitmap[]; // Ｒ
extern const u32 TextGlyphs_System_e5ad90_bitmap[]; // 子
extern const u32 TextGlyphs_System_e8a19b_bitmap[]; // 衛
extern const u32 TextGlyphs_System_e789a7_bitmap[]; // 牧
extern const u32 TextGlyphs_System_e38393_bitmap[]; // ビ
extern const u32 TextGlyphs_System_efbcb3_bitmap[]; // Ｓ
extern const u32 TextGlyphs_System_e88d92_bitmap[]; // 荒
extern const u32 TextGlyphs_System_e98094_bitmap[]; // 途
extern const u32 TextGlyphs_System_e88595_bitmap[]; // 腕
extern const u32 TextGlyphs_System_e38394_bitmap[]; // ピ
extern const u32 TextGlyphs_System_efbcb4_bitmap[]; // Ｔ
extern const u32 TextGlyphs_System_e8a18c_bitmap[]; // 行
extern const u32 TextGlyphs_System_e983bd_bitmap[]; // 都
extern const u32 TextGlyphs_System_e5b882_bitmap[]; // 市
extern const u32 TextGlyphs_System_e69597_bitmap[]; // 敗
extern const u32 TextGlyphs_System_e5a3ae_bitmap[]; // 壮
extern const u32 TextGlyphs_System_e98bad_bitmap[]; // 鋭
extern const u32 TextGlyphs_System_e4b88d_bitmap[]; // 不
extern const u32 TextGlyphs_System_e5b0bd_bitmap[]; // 尽
extern const u32 TextGlyphs_System_e89990_bitmap[]; // 虐
extern const u32 TextGlyphs_System_e38395_bitmap[]; // フ
extern const u32 TextGlyphs_System_efbcb5_bitmap[]; // Ｕ
extern const u32 TextGlyphs_System_e98086_bitmap[]; // 逆
extern const u32 TextGlyphs_System_e5b8ab_bitmap[]; // 師
extern const u32 TextGlyphs_System_e4bb98_bitmap[]; // 付
extern const u32 TextGlyphs_System_e89189_bitmap[]; // 葉
extern const u32 TextGlyphs_System_e698a5_bitmap[]; // 春
extern const u32 TextGlyphs_System_e5a58f_bitmap[]; // 奏
extern const u32 TextGlyphs_System_e38396_bitmap[]; // ブ
extern const u32 TextGlyphs_System_e3808c_bitmap[]; // 「
extern const u32 TextGlyphs_System_efbcb6_bitmap[]; // Ｖ
extern const u32 TextGlyphs_System_e5bf97_bitmap[]; // 志
extern const u32 TextGlyphs_System_e58b83_bitmap[]; // 勃
extern const u32 TextGlyphs_System_e7bdae_bitmap[]; // 置
extern const u32 TextGlyphs_System_e38397_bitmap[]; // プ
extern const u32 TextGlyphs_System_e3808d_bitmap[]; // 」
extern const u32 TextGlyphs_System_efbcb7_bitmap[]; // Ｗ
extern const u32 TextGlyphs_System_e4b985_bitmap[]; // 久
extern const u32 TextGlyphs_System_e8a681_bitmap[]; // 要
extern const u32 TextGlyphs_System_e6809d_bitmap[]; // 思
extern const u32 TextGlyphs_System_e5a4ab_bitmap[]; // 夫
extern const u32 TextGlyphs_System_e8a888_bitmap[]; // 計
extern const u32 TextGlyphs_System_e99da9_bitmap[]; // 革
extern const u32 TextGlyphs_System_e6b2a1_bitmap[]; // 没
extern const u32 TextGlyphs_System_e79b8a_bitmap[]; // 益
extern const u32 TextGlyphs_System_e38398_bitmap[]; // ヘ
extern const u32 TextGlyphs_System_efbcb8_bitmap[]; // Ｘ
extern const u32 TextGlyphs_System_e68c87_bitmap[]; // 指
extern const u32 TextGlyphs_System_e8838c_bitmap[]; // 背
extern const u32 TextGlyphs_System_e5ada6_bitmap[]; // 学
extern const u32 TextGlyphs_System_e999a3_bitmap[]; // 陣
extern const u32 TextGlyphs_System_e58aaa_bitmap[]; // 努
extern const u32 TextGlyphs_System_e5a9a6_bitmap[]; // 婦
extern const u32 TextGlyphs_System_e3808e_bitmap[]; // 『
extern const u32 TextGlyphs_System_e38399_bitmap[]; // ベ
extern const u32 TextGlyphs_System_efbcb9_bitmap[]; // Ｙ
extern const u32 TextGlyphs_System_e4bc91_bitmap[]; // 休
extern const u32 TextGlyphs_System_e5baa6_bitmap[]; // 度
extern const u32 TextGlyphs_System_e694af_bitmap[]; // 支
extern const u32 TextGlyphs_System_e8b88a_bitmap[]; // 踊
extern const u32 TextGlyphs_System_e9838a_bitmap[]; // 郊
extern const u32 TextGlyphs_System_e5af8c_bitmap[]; // 富
extern const u32 TextGlyphs_System_e8ada6_bitmap[]; // 警
extern const u32 TextGlyphs_System_e3808f_bitmap[]; // 』
extern const u32 TextGlyphs_System_e3839a_bitmap[]; // ペ
extern const u32 TextGlyphs_System_efbcba_bitmap[]; // Ｚ
extern const u32 TextGlyphs_System_e59c9f_bitmap[]; // 土
extern const u32 TextGlyphs_System_e8bbbd_bitmap[]; // 軽
extern const u32 TextGlyphs_System_e8bca9_bitmap[]; // 輩
extern const u32 TextGlyphs_System_e6a5bd_bitmap[]; // 楽
extern const u32 TextGlyphs_System_e8ab8d_bitmap[]; // 諍
extern const u32 TextGlyphs_System_e3839b_bitmap[]; // ホ
extern const u32 TextGlyphs_System_e5a5b4_bitmap[]; // 奴
extern const u32 TextGlyphs_System_e7af89_bitmap[]; // 築
extern const u32 TextGlyphs_System_e9858d_bitmap[]; // 配
extern const u32 TextGlyphs_System_e999bd_bitmap[]; // 陽
extern const u32 TextGlyphs_System_e683b3_bitmap[]; // 想
extern const u32 TextGlyphs_System_e9a18d_bitmap[]; // 額
extern const u32 TextGlyphs_System_e989b1_bitmap[]; // 鉱
extern const u32 TextGlyphs_System_e3839c_bitmap[]; // ボ
extern const u32 TextGlyphs_System_efbc8b_bitmap[]; // ＋
extern const u32 TextGlyphs_System_e9a48a_bitmap[]; // 養
extern const u32 TextGlyphs_System_e5aeae_bitmap[]; // 宮
extern const u32 TextGlyphs_System_e69cac_bitmap[]; // 本
extern const u32 TextGlyphs_System_e5808d_bitmap[]; // 倍
extern const u32 TextGlyphs_System_e68092_bitmap[]; // 怒
extern const u32 TextGlyphs_System_e68d9c_bitmap[]; // 捜
extern const u32 TextGlyphs_System_e7959c_bitmap[]; // 畜
extern const u32 TextGlyphs_System_e3839d_bitmap[]; // ポ
extern const u32 TextGlyphs_System_e58092_bitmap[]; // 倒
extern const u32 TextGlyphs_System_e5bc93_bitmap[]; // 弓
extern const u32 TextGlyphs_System_e68096_bitmap[]; // 怖
extern const u32 TextGlyphs_System_e68e83_bitmap[]; // 掃
extern const u32 TextGlyphs_System_e98bbc_bitmap[]; // 鋼
extern const u32 TextGlyphs_System_e68e9f_bitmap[]; // 掟
extern const u32 TextGlyphs_System_e88ab8_bitmap[]; // 芸
extern const u32 TextGlyphs_System_e3839e_bitmap[]; // マ
extern const u32 TextGlyphs_System_e8bf8e_bitmap[]; // 迎
extern const u32 TextGlyphs_System_e5859a_bitmap[]; // 党
extern const u32 TextGlyphs_System_e680a5_bitmap[]; // 急
extern const u32 TextGlyphs_System_e59bb3_bitmap[]; // 図
extern const u32 TextGlyphs_System_e3839f_bitmap[]; // ミ
extern const u32 TextGlyphs_System_e69591_bitmap[]; // 救
extern const u32 TextGlyphs_System_e6ada2_bitmap[]; // 止
extern const u32 TextGlyphs_System_e9998d_bitmap[]; // 降
extern const u32 TextGlyphs_System_e6acb2_bitmap[]; // 欲
extern const u32 TextGlyphs_System_e586ac_bitmap[]; // 冬
extern const u32 TextGlyphs_System_e383a0_bitmap[]; // ム
extern const u32 TextGlyphs_System_e6adbb_bitmap[]; // 死
extern const u32 TextGlyphs_System_e696a7_bitmap[]; // 斧
extern const u32 TextGlyphs_System_e6ba96_bitmap[]; // 準
extern const u32 TextGlyphs_System_e5878d_bitmap[]; // 凍
extern const u32 TextGlyphs_System_e98090_bitmap[]; // 逐
extern const u32 TextGlyphs_System_e383a1_bitmap[]; // メ
extern const u32 TextGlyphs_System_efbd81_bitmap[]; // ａ
extern const u32 TextGlyphs_System_e7a3a8_bitmap[]; // 磨
extern const u32 TextGlyphs_System_e6b182_bitmap[]; // 求
extern const u32 TextGlyphs_System_e697a9_bitmap[]; // 早
extern const u32 TextGlyphs_System_e58880_bitmap[]; // 刀
extern const u32 TextGlyphs_System_e699ae_bitmap[]; // 普
extern const u32 TextGlyphs_System_e590b9_bitmap[]; // 吹
extern const u32 TextGlyphs_System_e383a2_bitmap[]; // モ
extern const u32 TextGlyphs_System_efbd82_bitmap[]; // ｂ
extern const u32 TextGlyphs_System_e69283_bitmap[]; // 撃
extern const u32 TextGlyphs_System_e9ad94_bitmap[]; // 魔
extern const u32 TextGlyphs_System_e9ab98_bitmap[]; // 高
extern const u32 TextGlyphs_System_e79bbe_bitmap[]; // 盾
extern const u32 TextGlyphs_System_e78d85_bitmap[]; // 獅
extern const u32 TextGlyphs_System_e383a3_bitmap[]; // ャ
extern const u32 TextGlyphs_System_efbd83_bitmap[]; // ｃ
extern const u32 TextGlyphs_System_e788b6_bitmap[]; // 父
extern const u32 TextGlyphs_System_e5a194_bitmap[]; // 塔
extern const u32 TextGlyphs_System_e5b7a3_bitmap[]; // 巣
extern const u32 TextGlyphs_System_e6bf80_bitmap[]; // 激
extern const u32 TextGlyphs_System_e8b2b7_bitmap[]; // 買
extern const u32 TextGlyphs_System_e6b3a3_bitmap[]; // 泣
extern const u32 TextGlyphs_System_e383a4_bitmap[]; // ヤ
extern const u32 TextGlyphs_System_efbd84_bitmap[]; // ｄ
extern const u32 TextGlyphs_System_e6a78d_bitmap[]; // 槍
extern const u32 TextGlyphs_System_e5a3b2_bitmap[]; // 売
extern const u32 TextGlyphs_System_e59f8b_bitmap[]; // 埋
extern const u32 TextGlyphs_System_e7a781_bitmap[]; // 私
extern const u32 TextGlyphs_System_e5bbb6_bitmap[]; // 延
extern const u32 TextGlyphs_System_e5899b_bitmap[]; // 剛
extern const u32 TextGlyphs_System_e383a5_bitmap[]; // ュ
extern const u32 TextGlyphs_System_efbd85_bitmap[]; // ｅ
extern const u32 TextGlyphs_System_e6b0b4_bitmap[]; // 水
extern const u32 TextGlyphs_System_e79d80_bitmap[]; // 着
extern const u32 TextGlyphs_System_e5a6b9_bitmap[]; // 妹
extern const u32 TextGlyphs_System_e7b3b8_bitmap[]; // 糸
extern const u32 TextGlyphs_System_e383a6_bitmap[]; // ユ
extern const u32 TextGlyphs_System_efbd86_bitmap[]; // ｆ
extern const u32 TextGlyphs_System_e4b8ad_bitmap[]; // 中
extern const u32 TextGlyphs_System_e58fb7_bitmap[]; // 号
extern const u32 TextGlyphs_System_e7b499_bitmap[]; // 紙
extern const u32 TextGlyphs_System_e7a9b6_bitmap[]; // 究
extern const u32 TextGlyphs_System_e383a7_bitmap[]; // ョ
extern const u32 TextGlyphs_System_efbd87_bitmap[]; // ｇ
extern const u32 TextGlyphs_System_e68fb4_bitmap[]; // 援
extern const u32 TextGlyphs_System_e5b3b6_bitmap[]; // 島
extern const u32 TextGlyphs_System_e59088_bitmap[]; // 合
extern const u32 TextGlyphs_System_e4bbb2_bitmap[]; // 仲
extern const u32 TextGlyphs_System_e9a086_bitmap[]; // 順
extern const u32 TextGlyphs_System_e383a8_bitmap[]; // ヨ
extern const u32 TextGlyphs_System_efbd88_bitmap[]; // ｈ
extern const u32 TextGlyphs_System_e4ba89_bitmap[]; // 争
extern const u32 TextGlyphs_System_e69da5_bitmap[]; // 来
extern const u32 TextGlyphs_System_e6b1ba_bitmap[]; // 決
extern const u32 TextGlyphs_System_e6b4bb_bitmap[]; // 活
extern const u32 TextGlyphs_System_e587a6_bitmap[]; // 処
extern const u32 TextGlyphs_System_e6af8e_bitmap[]; // 毎
extern const u32 TextGlyphs_System_e383a9_bitmap[]; // ラ
extern const u32 TextGlyphs_System_efbd89_bitmap[]; // ｉ
extern const u32 TextGlyphs_System_e5bfa0_bitmap[]; // 忠
extern const u32 TextGlyphs_System_e5889d_bitmap[]; // 初
extern const u32 TextGlyphs_System_e8b2a0_bitmap[]; // 負
extern const u32 TextGlyphs_System_e7b49a_bitmap[]; // 級
extern const u32 TextGlyphs_System_e383aa_bitmap[]; // リ
extern const u32 TextGlyphs_System_efbd8a_bitmap[]; // ｊ
extern const u32 TextGlyphs_System_e68980_bitmap[]; // 所
extern const u32 TextGlyphs_System_e7828e_bitmap[]; // 炎
extern const u32 TextGlyphs_System_e79bb8_bitmap[]; // 相
extern const u32 TextGlyphs_System_e9a0bc_bitmap[]; // 頼
extern const u32 TextGlyphs_System_e8a1b0_bitmap[]; // 衰
extern const u32 TextGlyphs_System_e887b3_bitmap[]; // 至
extern const u32 TextGlyphs_System_e68a95_bitmap[]; // 投
extern const u32 TextGlyphs_System_e383ab_bitmap[]; // ル
extern const u32 TextGlyphs_System_efbd8b_bitmap[]; // ｋ
extern const u32 TextGlyphs_System_e8a696_bitmap[]; // 視
extern const u32 TextGlyphs_System_e7b590_bitmap[]; // 結
extern const u32 TextGlyphs_System_e8b5b4_bitmap[]; // 赴
extern const u32 TextGlyphs_System_e698bc_bitmap[]; // 昼
extern const u32 TextGlyphs_System_e5b995_bitmap[]; // 幕
extern const u32 TextGlyphs_System_e99bb7_bitmap[]; // 雷
extern const u32 TextGlyphs_System_e7b5a6_bitmap[]; // 給
extern const u32 TextGlyphs_System_e8b1aa_bitmap[]; // 豪
extern const u32 TextGlyphs_System_e383ac_bitmap[]; // レ
extern const u32 TextGlyphs_System_efbd8c_bitmap[]; // ｌ
extern const u32 TextGlyphs_System_e69db1_bitmap[]; // 東
extern const u32 TextGlyphs_System_e8a180_bitmap[]; // 血
extern const u32 TextGlyphs_System_e4bcaf_bitmap[]; // 伯
extern const u32 TextGlyphs_System_e697a7_bitmap[]; // 旧
extern const u32 TextGlyphs_System_e69fb1_bitmap[]; // 柱
extern const u32 TextGlyphs_System_e383ad_bitmap[]; // ロ
extern const u32 TextGlyphs_System_efbd8d_bitmap[]; // ｍ
extern const u32 TextGlyphs_System_e6b3a8_bitmap[]; // 注
extern const u32 TextGlyphs_System_e7b5a1_bitmap[]; // 絡
extern const u32 TextGlyphs_System_e7b78f_bitmap[]; // 総
extern const u32 TextGlyphs_System_e8a9a9_bitmap[]; // 詩
extern const u32 TextGlyphs_System_efbd8e_bitmap[]; // ｎ
extern const u32 TextGlyphs_System_e69c88_bitmap[]; // 月
extern const u32 TextGlyphs_System_e58ebb_bitmap[]; // 去
extern const u32 TextGlyphs_System_e890bd_bitmap[]; // 落
extern const u32 TextGlyphs_System_e4beae_bitmap[]; // 侮
extern const u32 TextGlyphs_System_e8a9a6_bitmap[]; // 試
extern const u32 TextGlyphs_System_e5bab6_bitmap[]; // 庶
extern const u32 TextGlyphs_System_e383af_bitmap[]; // ワ
extern const u32 TextGlyphs_System_efbd8f_bitmap[]; // ｏ
extern const u32 TextGlyphs_System_e7b792_bitmap[]; // 緒
extern const u32 TextGlyphs_System_e588bb_bitmap[]; // 刻
extern const u32 TextGlyphs_System_e5b185_bitmap[]; // 居
extern const u32 TextGlyphs_System_e68b8d_bitmap[]; // 拍
extern const u32 TextGlyphs_System_e4bbb6_bitmap[]; // 件
extern const u32 TextGlyphs_System_efbd90_bitmap[]; // ｐ
extern const u32 TextGlyphs_System_e88d89_bitmap[]; // 草
extern const u32 TextGlyphs_System_e6ada6_bitmap[]; // 武
extern const u32 TextGlyphs_System_e79b97_bitmap[]; // 盗
extern const u32 TextGlyphs_System_e4b9b1_bitmap[]; // 乱
extern const u32 TextGlyphs_System_e5b7a8_bitmap[]; // 巨
extern const u32 TextGlyphs_System_e5918a_bitmap[]; // 告
extern const u32 TextGlyphs_System_efbd91_bitmap[]; // ｑ
extern const u32 TextGlyphs_System_e69bb8_bitmap[]; // 書
extern const u32 TextGlyphs_System_e59bbd_bitmap[]; // 国
extern const u32 TextGlyphs_System_e8889e_bitmap[]; // 舞
extern const u32 TextGlyphs_System_e68b92_bitmap[]; // 拒
extern const u32 TextGlyphs_System_e8b387_bitmap[]; // 資
extern const u32 TextGlyphs_System_efbd92_bitmap[]; // ｒ
extern const u32 TextGlyphs_System_e383b2_bitmap[]; // ヲ
extern const u32 TextGlyphs_System_e799bd_bitmap[]; // 白
extern const u32 TextGlyphs_System_e68ba0_bitmap[]; // 拠
extern const u32 TextGlyphs_System_e383b3_bitmap[]; // ン
extern const u32 TextGlyphs_System_efbd93_bitmap[]; // ｓ
extern const u32 TextGlyphs_System_e981a0_bitmap[]; // 遠
extern const u32 TextGlyphs_System_e985b7_bitmap[]; // 酷
extern const u32 TextGlyphs_System_e68c99_bitmap[]; // 挙
extern const u32 TextGlyphs_System_e9a790_bitmap[]; // 駐
extern const u32 TextGlyphs_System_efbc85_bitmap[]; // ％
extern const u32 TextGlyphs_System_e383b4_bitmap[]; // ヴ
extern const u32 TextGlyphs_System_efbd94_bitmap[]; // ｔ
extern const u32 TextGlyphs_System_e695b0_bitmap[]; // 数
extern const u32 TextGlyphs_System_e983a8_bitmap[]; // 部
extern const u32 TextGlyphs_System_e8abb8_bitmap[]; // 諸
extern const u32 TextGlyphs_System_efbd95_bitmap[]; // ｕ
extern const u32 TextGlyphs_System_e9bb92_bitmap[]; // 黒
extern const u32 TextGlyphs_System_e589a3_bitmap[]; // 剣
extern const u32 TextGlyphs_System_e58aa9_bitmap[]; // 助
extern const u32 TextGlyphs_System_e69ea2_bitmap[]; // 枢
extern const u32 TextGlyphs_System_e8a385_bitmap[]; // 装
extern const u32 TextGlyphs_System_e5b081_bitmap[]; // 封
extern const u32 TextGlyphs_System_e6adaf_bitmap[]; // 歯
extern const u32 TextGlyphs_System_efbd96_bitmap[]; // ｖ
extern const u32 TextGlyphs_System_e69cab_bitmap[]; // 末
extern const u32 TextGlyphs_System_e4ba8b_bitmap[]; // 事
extern const u32 TextGlyphs_System_e5bd93_bitmap[]; // 当
extern const u32 TextGlyphs_System_e78d84_bitmap[]; // 獄
extern const u32 TextGlyphs_System_e8a8b1_bitmap[]; // 許
extern const u32 TextGlyphs_System_e8b5b0_bitmap[]; // 走
extern const u32 TextGlyphs_System_e58f99_bitmap[]; // 叙
extern const u32 TextGlyphs_System_efbd97_bitmap[]; // ｗ
extern const u32 TextGlyphs_System_e5a5b3_bitmap[]; // 女
extern const u32 TextGlyphs_System_e9a2a8_bitmap[]; // 風
extern const u32 TextGlyphs_System_e8bfab_bitmap[]; // 迫
extern const u32 TextGlyphs_System_e98081_bitmap[]; // 送
extern const u32 TextGlyphs_System_e8a6a7_bitmap[]; // 覧
extern const u32 TextGlyphs_System_efbd98_bitmap[]; // ｘ
extern const u32 TextGlyphs_System_e588a9_bitmap[]; // 利
extern const u32 TextGlyphs_System_e885b0_bitmap[]; // 腰
extern const u32 TextGlyphs_System_e5ba8f_bitmap[]; // 序
extern const u32 TextGlyphs_System_e6b19a_bitmap[]; // 汚
extern const u32 TextGlyphs_System_efbd99_bitmap[]; // ｙ
extern const u32 TextGlyphs_System_e6bca0_bitmap[]; // 漠
extern const u32 TextGlyphs_System_e58590_bitmap[]; // 児
extern const u32 TextGlyphs_System_e8b2af_bitmap[]; // 貯
extern const u32 TextGlyphs_System_e6bc81_bitmap[]; // 漁
extern const u32 TextGlyphs_System_e7ad89_bitmap[]; // 等
extern const u32 TextGlyphs_System_e794a5_bitmap[]; // 甥
extern const u32 TextGlyphs_System_efbd9a_bitmap[]; // ｚ
extern const u32 TextGlyphs_System_e5bbba_bitmap[]; // 建
extern const u32 TextGlyphs_System_e4bc8f_bitmap[]; // 伏
extern const u32 TextGlyphs_System_e7ad94_bitmap[]; // 答
extern const u32 TextGlyphs_System_e5ad97_bitmap[]; // 字
extern const u32 TextGlyphs_System_e2978b_bitmap[]; // ○
extern const u32 TextGlyphs_System_e5afba_bitmap[]; // 寺
extern const u32 TextGlyphs_System_e5a4ae_bitmap[]; // 央
extern const u32 TextGlyphs_System_e5bea9_bitmap[]; // 復
extern const u32 TextGlyphs_System_e5838f_bitmap[]; // 像
extern const u32 TextGlyphs_System_e4b887_bitmap[]; // 万
extern const u32 TextGlyphs_System_e999a4_bitmap[]; // 除
extern const u32 TextGlyphs_System_e68c81_bitmap[]; // 持
extern const u32 TextGlyphs_System_e7b5b1_bitmap[]; // 統
extern const u32 TextGlyphs_System_e79086_bitmap[]; // 理
extern const u32 TextGlyphs_System_e5a297_bitmap[]; // 増
extern const u32 TextGlyphs_System_e5b985_bitmap[]; // 幅
extern const u32 TextGlyphs_System_e582b7_bitmap[]; // 傷
extern const u32 TextGlyphs_System_e685a2_bitmap[]; // 慢
extern const u32 TextGlyphs_System_e2978e_bitmap[]; // ◎
extern const u32 TextGlyphs_System_e8bebc_bitmap[]; // 込
extern const u32 TextGlyphs_System_e69982_bitmap[]; // 時
extern const u32 TextGlyphs_System_e5849f_bitmap[]; // 償
extern const u32 TextGlyphs_System_e69c8d_bitmap[]; // 服
extern const u32 TextGlyphs_System_e5bf9c_bitmap[]; // 応
extern const u32 TextGlyphs_System_e588b0_bitmap[]; // 到
extern const u32 TextGlyphs_System_e6ba80_bitmap[]; // 満
extern const u32 TextGlyphs_System_e6868e_bitmap[]; // 憎
extern const u32 TextGlyphs_System_e5afb5_bitmap[]; // 寵
extern const u32 TextGlyphs_System_e38181_bitmap[]; // ぁ
extern const u32 TextGlyphs_System_e58b9d_bitmap[]; // 勝
extern const u32 TextGlyphs_System_e7a68f_bitmap[]; // 福
extern const u32 TextGlyphs_System_e4be9b_bitmap[]; // 供
extern const u32 TextGlyphs_System_e6aca1_bitmap[]; // 次
extern const u32 TextGlyphs_System_e68abc_bitmap[]; // 押
extern const u32 TextGlyphs_System_e38182_bitmap[]; // あ
extern const u32 TextGlyphs_System_e7aeb1_bitmap[]; // 箱
extern const u32 TextGlyphs_System_e9a083_bitmap[]; // 頃
extern const u32 TextGlyphs_System_e6a8a9_bitmap[]; // 権
extern const u32 TextGlyphs_System_e8a38f_bitmap[]; // 裏
extern const u32 TextGlyphs_System_e885b9_bitmap[]; // 腹
extern const u32 TextGlyphs_System_e38183_bitmap[]; // ぃ
extern const u32 TextGlyphs_System_e4bb8a_bitmap[]; // 今
extern const u32 TextGlyphs_System_e6b2bb_bitmap[]; // 治
extern const u32 TextGlyphs_System_e591b3_bitmap[]; // 味
extern const u32 TextGlyphs_System_e8a487_bitmap[]; // 複
extern const u32 TextGlyphs_System_e5afb8_bitmap[]; // 寸
extern const u32 TextGlyphs_System_e38184_bitmap[]; // い
extern const u32 TextGlyphs_System_e8a88e_bitmap[]; // 討
extern const u32 TextGlyphs_System_e4b896_bitmap[]; // 世
extern const u32 TextGlyphs_System_e69caa_bitmap[]; // 未
extern const u32 TextGlyphs_System_e5bc94_bitmap[]; // 弔
extern const u32 TextGlyphs_System_e980a0_bitmap[]; // 造
extern const u32 TextGlyphs_System_e78aac_bitmap[]; // 犬
extern const u32 TextGlyphs_System_e59bb0_bitmap[]; // 困
extern const u32 TextGlyphs_System_e9878c_bitmap[]; // 里
extern const u32 TextGlyphs_System_e296b3_bitmap[]; // △
extern const u32 TextGlyphs_System_e38185_bitmap[]; // ぅ
extern const u32 TextGlyphs_System_e99ba2_bitmap[]; // 離
extern const u32 TextGlyphs_System_e59380_bitmap[]; // 哀
extern const u32 TextGlyphs_System_e38186_bitmap[]; // う
extern const u32 TextGlyphs_System_e78e8b_bitmap[]; // 王
extern const u32 TextGlyphs_System_e6849b_bitmap[]; // 愛
extern const u32 TextGlyphs_System_e999b8_bitmap[]; // 陸
extern const u32 TextGlyphs_System_e59586_bitmap[]; // 商
extern const u32 TextGlyphs_System_e585b1_bitmap[]; // 共
extern const u32 TextGlyphs_System_e581b4_bitmap[]; // 側
extern const u32 TextGlyphs_System_e7ad88_bitmap[]; // 筈
extern const u32 TextGlyphs_System_e7a094_bitmap[]; // 研
extern const u32 TextGlyphs_System_e38187_bitmap[]; // ぇ
extern const u32 TextGlyphs_System_e5a99a_bitmap[]; // 婚
extern const u32 TextGlyphs_System_e68995_bitmap[]; // 払
extern const u32 TextGlyphs_System_e594b1_bitmap[]; // 唱
extern const u32 TextGlyphs_System_e5beb4_bitmap[]; // 徴
extern const u32 TextGlyphs_System_e38188_bitmap[]; // え
extern const u32 TextGlyphs_System_e78e87_bitmap[]; // 率
extern const u32 TextGlyphs_System_e7a4ba_bitmap[]; // 示
extern const u32 TextGlyphs_System_e58d94_bitmap[]; // 協
extern const u32 TextGlyphs_System_e98083_bitmap[]; // 逃
extern const u32 TextGlyphs_System_e38189_bitmap[]; // ぉ
extern const u32 TextGlyphs_System_e38092_bitmap[]; // 〒
extern const u32 TextGlyphs_System_e68c91_bitmap[]; // 挑
extern const u32 TextGlyphs_System_e7ab8b_bitmap[]; // 立
extern const u32 TextGlyphs_System_e588b6_bitmap[]; // 制
extern const u32 TextGlyphs_System_e5af86_bitmap[]; // 密
extern const u32 TextGlyphs_System_e8828c_bitmap[]; // 肌
extern const u32 TextGlyphs_System_e681af_bitmap[]; // 息
extern const u32 TextGlyphs_System_e3818a_bitmap[]; // お
extern const u32 TextGlyphs_System_e28692_bitmap[]; // →
extern const u32 TextGlyphs_System_e789a9_bitmap[]; // 物
extern const u32 TextGlyphs_System_e58dbf_bitmap[]; // 卿
extern const u32 TextGlyphs_System_e880b3_bitmap[]; // 耳
extern const u32 TextGlyphs_System_e58ba2_bitmap[]; // 勢
extern const u32 TextGlyphs_System_e882a9_bitmap[]; // 肩
extern const u32 TextGlyphs_System_e3818b_bitmap[]; // か
extern const u32 TextGlyphs_System_e887aa_bitmap[]; // 自
extern const u32 TextGlyphs_System_e7bda0_bitmap[]; // 罠
extern const u32 TextGlyphs_System_e8a68b_bitmap[]; // 見
extern const u32 TextGlyphs_System_e9bb84_bitmap[]; // 黄
extern const u32 TextGlyphs_System_e69d9f_bitmap[]; // 束
extern const u32 TextGlyphs_System_e69c9d_bitmap[]; // 朝
extern const u32 TextGlyphs_System_e3818c_bitmap[]; // が
extern const u32 TextGlyphs_System_e58886_bitmap[]; // 分
extern const u32 TextGlyphs_System_e5be81_bitmap[]; // 征
extern const u32 TextGlyphs_System_e795a5_bitmap[]; // 略
extern const u32 TextGlyphs_System_e9a0ad_bitmap[]; // 頭
extern const u32 TextGlyphs_System_e5b7bb_bitmap[]; // 巻
extern const u32 TextGlyphs_System_e6a0b9_bitmap[]; // 根
extern const u32 TextGlyphs_System_e585ab_bitmap[]; // 八
extern const u32 TextGlyphs_System_e3818d_bitmap[]; // き
extern const u32 TextGlyphs_System_e5a283_bitmap[]; // 境
extern const u32 TextGlyphs_System_e682aa_bitmap[]; // 悪
extern const u32 TextGlyphs_System_e5b086_bitmap[]; // 将
extern const u32 TextGlyphs_System_e680a7_bitmap[]; // 性
extern const u32 TextGlyphs_System_e8b3a2_bitmap[]; // 賢
extern const u32 TextGlyphs_System_e8b6b3_bitmap[]; // 足
extern const u32 TextGlyphs_System_e8be9e_bitmap[]; // 辞
extern const u32 TextGlyphs_System_e3818e_bitmap[]; // ぎ
extern const u32 TextGlyphs_System_e99798_bitmap[]; // 闘
extern const u32 TextGlyphs_System_e9809f_bitmap[]; // 速
extern const u32 TextGlyphs_System_e5b08f_bitmap[]; // 小
extern const u32 TextGlyphs_System_e794ba_bitmap[]; // 町
extern const u32 TextGlyphs_System_e5b3a1_bitmap[]; // 峡
extern const u32 TextGlyphs_System_e68890_bitmap[]; // 成
extern const u32 TextGlyphs_System_e88488_bitmap[]; // 脈
extern const u32 TextGlyphs_System_e6b581_bitmap[]; // 流
extern const u32 TextGlyphs_System_e6b7b7_bitmap[]; // 混
extern const u32 TextGlyphs_System_e68fa1_bitmap[]; // 握
extern const u32 TextGlyphs_System_e3818f_bitmap[]; // く
extern const u32 TextGlyphs_System_e5bcb7_bitmap[]; // 強
extern const u32 TextGlyphs_System_e799ba_bitmap[]; // 発
extern const u32 TextGlyphs_System_e694bf_bitmap[]; // 政
extern const u32 TextGlyphs_System_e5b091_bitmap[]; // 少
extern const u32 TextGlyphs_System_e981a3_bitmap[]; // 遣
extern const u32 TextGlyphs_System_e5838d_bitmap[]; // 働
extern const u32 TextGlyphs_System_e5a699_bitmap[]; // 妙
extern const u32 TextGlyphs_System_e9b9bf_bitmap[]; // 鹿
extern const u32 TextGlyphs_System_e38190_bitmap[]; // ぐ
extern const u32 TextGlyphs_System_e58b95_bitmap[]; // 動
extern const u32 TextGlyphs_System_e5b18b_bitmap[]; // 屋
extern const u32 TextGlyphs_System_e5ae8c_bitmap[]; // 完
extern const u32 TextGlyphs_System_e5bc8f_bitmap[]; // 式
extern const u32 TextGlyphs_System_e5b19e_bitmap[]; // 属
extern const u32 TextGlyphs_System_e695b4_bitmap[]; // 整
extern const u32 TextGlyphs_System_e38191_bitmap[]; // け
extern const u32 TextGlyphs_System_e8b38a_bitmap[]; // 賊
extern const u32 TextGlyphs_System_e6989f_bitmap[]; // 星
extern const u32 TextGlyphs_System_e5908c_bitmap[]; // 同
extern const u32 TextGlyphs_System_e6b091_bitmap[]; // 民
extern const u32 TextGlyphs_System_e8ad98_bitmap[]; // 識
extern const u32 TextGlyphs_System_e5ae98_bitmap[]; // 官
extern const u32 TextGlyphs_System_e686b6_bitmap[]; // 憶
extern const u32 TextGlyphs_System_e79599_bitmap[]; // 留
extern const u32 TextGlyphs_System_e999ba_bitmap[]; // 険
extern const u32 TextGlyphs_System_e38192_bitmap[]; // げ
extern const u32 TextGlyphs_System_e68190_bitmap[]; // 恐
extern const u32 TextGlyphs_System_e6978f_bitmap[]; // 族
extern const u32 TextGlyphs_System_e4bc90_bitmap[]; // 伐
extern const u32 TextGlyphs_System_e5a082_bitmap[]; // 堂
extern const u32 TextGlyphs_System_e9ad82_bitmap[]; // 魂
extern const u32 TextGlyphs_System_e699b4_bitmap[]; // 晴
extern const u32 TextGlyphs_System_e5ba8a_bitmap[]; // 床
extern const u32 TextGlyphs_System_e38193_bitmap[]; // こ
extern const u32 TextGlyphs_System_e7b69a_bitmap[]; // 続
extern const u32 TextGlyphs_System_e58b99_bitmap[]; // 務
extern const u32 TextGlyphs_System_e9a893_bitmap[]; // 験
extern const u32 TextGlyphs_System_e5b08e_bitmap[]; // 導
extern const u32 TextGlyphs_System_e7bdb0_bitmap[]; // 罰
extern const u32 TextGlyphs_System_e38194_bitmap[]; // ご
extern const u32 TextGlyphs_System_e68c9f_bitmap[]; // 挟
extern const u32 TextGlyphs_System_e68a9c_bitmap[]; // 抜
extern const u32 TextGlyphs_System_e8aabf_bitmap[]; // 調
extern const u32 TextGlyphs_System_e5a4a2_bitmap[]; // 夢
extern const u32 TextGlyphs_System_e38195_bitmap[]; // さ
extern const u32 TextGlyphs_System_e58583_bitmap[]; // 元
extern const u32 TextGlyphs_System_e7ab9c_bitmap[]; // 竜
extern const u32 TextGlyphs_System_e784a1_bitmap[]; // 無
extern const u32 TextGlyphs_System_e6ada3_bitmap[]; // 正
extern const u32 TextGlyphs_System_e59ca7_bitmap[]; // 圧
extern const u32 TextGlyphs_System_e69599_bitmap[]; // 教
extern const u32 TextGlyphs_System_e689bf_bitmap[]; // 承
extern const u32 TextGlyphs_System_e38196_bitmap[]; // ざ
extern const u32 TextGlyphs_System_e58e9f_bitmap[]; // 原
extern const u32 TextGlyphs_System_e4bfba_bitmap[]; // 俺
extern const u32 TextGlyphs_System_e6a98b_bitmap[]; // 橋
extern const u32 TextGlyphs_System_e6849f_bitmap[]; // 感
extern const u32 TextGlyphs_System_e8b685_bitmap[]; // 超
extern const u32 TextGlyphs_System_e6b885_bitmap[]; // 清
extern const u32 TextGlyphs_System_e6b49e_bitmap[]; // 洞
extern const u32 TextGlyphs_System_e38197_bitmap[]; // し
extern const u32 TextGlyphs_System_e689b1_bitmap[]; // 扱
extern const u32 TextGlyphs_System_e4beb6_bitmap[]; // 侶
extern const u32 TextGlyphs_System_e6b381_bitmap[]; // 況
extern const u32 TextGlyphs_System_e789b2_bitmap[]; // 牲
extern const u32 TextGlyphs_System_e68b9b_bitmap[]; // 招
extern const u32 TextGlyphs_System_e4b883_bitmap[]; // 七
extern const u32 TextGlyphs_System_e38198_bitmap[]; // じ
extern const u32 TextGlyphs_System_e681a9_bitmap[]; // 恩
extern const u32 TextGlyphs_System_e7949f_bitmap[]; // 生
extern const u32 TextGlyphs_System_e69687_bitmap[]; // 文
extern const u32 TextGlyphs_System_e78b82_bitmap[]; // 狂
extern const u32 TextGlyphs_System_e5ad98_bitmap[]; // 存
extern const u32 TextGlyphs_System_e5b7a6_bitmap[]; // 左
extern const u32 TextGlyphs_System_e99ca7_bitmap[]; // 霧
extern const u32 TextGlyphs_System_e38199_bitmap[]; // す
extern const u32 TextGlyphs_System_e69785_bitmap[]; // 旅
extern const u32 TextGlyphs_System_e995b7_bitmap[]; // 長
extern const u32 TextGlyphs_System_e5adab_bitmap[]; // 孫
extern const u32 TextGlyphs_System_e79b9b_bitmap[]; // 盛
extern const u32 TextGlyphs_System_e8819e_bitmap[]; // 聞
extern const u32 TextGlyphs_System_e5b7ae_bitmap[]; // 差
extern const u32 TextGlyphs_System_e6b8a9_bitmap[]; // 温
extern const u32 TextGlyphs_System_e68f9b_bitmap[]; // 換
extern const u32 TextGlyphs_System_e3819a_bitmap[]; // ず
extern const u32 TextGlyphs_System_e5a4b1_bitmap[]; // 失
extern const u32 TextGlyphs_System_e7b2be_bitmap[]; // 精
extern const u32 TextGlyphs_System_e6b89b_bitmap[]; // 減
extern const u32 TextGlyphs_System_e69887_bitmap[]; // 昇
extern const u32 TextGlyphs_System_e8999c_bitmap[]; // 虜
extern const u32 TextGlyphs_System_e5b08a_bitmap[]; // 尊
extern const u32 TextGlyphs_System_e9a082_bitmap[]; // 頂
extern const u32 TextGlyphs_System_e3819b_bitmap[]; // せ
extern const u32 TextGlyphs_System_e88196_bitmap[]; // 聖
extern const u32 TextGlyphs_System_e98193_bitmap[]; // 道
extern const u32 TextGlyphs_System_e4bdb5_bitmap[]; // 併
extern const u32 TextGlyphs_System_e4ba86_bitmap[]; // 了
extern const u32 TextGlyphs_System_e99fb3_bitmap[]; // 音
extern const u32 TextGlyphs_System_e9b3a5_bitmap[]; // 鳥
extern const u32 TextGlyphs_System_e6908d_bitmap[]; // 損
extern const u32 TextGlyphs_System_e99abc_bitmap[]; // 隼
extern const u32 TextGlyphs_System_e3819c_bitmap[]; // ぜ
extern const u32 TextGlyphs_System_e585b5_bitmap[]; // 兵
extern const u32 TextGlyphs_System_e69d91_bitmap[]; // 村
extern const u32 TextGlyphs_System_e4b88b_bitmap[]; // 下
extern const u32 TextGlyphs_System_e5a3b0_bitmap[]; // 声
extern const u32 TextGlyphs_System_e5aea4_bitmap[]; // 室
extern const u32 TextGlyphs_System_e5a898_bitmap[]; // 娘
extern const u32 TextGlyphs_System_e28a86_bitmap[]; // ⊆
extern const u32 TextGlyphs_System_e3819d_bitmap[]; // そ
extern const u32 TextGlyphs_System_e78fbe_bitmap[]; // 現
extern const u32 TextGlyphs_System_e7a082_bitmap[]; // 砂
extern const u32 TextGlyphs_System_e88888_bitmap[]; // 興
extern const u32 TextGlyphs_System_e58c96_bitmap[]; // 化
extern const u32 TextGlyphs_System_e5b3a0_bitmap[]; // 峠
extern const u32 TextGlyphs_System_e5a180_bitmap[]; // 塀
extern const u32 TextGlyphs_System_e588a4_bitmap[]; // 判
extern const u32 TextGlyphs_System_e28a87_bitmap[]; // ⊇
extern const u32 TextGlyphs_System_e3819e_bitmap[]; // ぞ
extern const u32 TextGlyphs_System_e4b8a1_bitmap[]; // 両
extern const u32 TextGlyphs_System_e8a5bf_bitmap[]; // 西
extern const u32 TextGlyphs_System_e4bb96_bitmap[]; // 他
extern const u32 TextGlyphs_System_e5908d_bitmap[]; // 名
extern const u32 TextGlyphs_System_e58d8a_bitmap[]; // 半
extern const u32 TextGlyphs_System_e4bbae_bitmap[]; // 仮
extern const u32 TextGlyphs_System_e79bb4_bitmap[]; // 直
extern const u32 TextGlyphs_System_e3819f_bitmap[]; // た
extern const u32 TextGlyphs_System_e4bd95_bitmap[]; // 何
extern const u32 TextGlyphs_System_e5a49a_bitmap[]; // 多
extern const u32 TextGlyphs_System_e591bd_bitmap[]; // 命
extern const u32 TextGlyphs_System_e5b9b3_bitmap[]; // 平
extern const u32 TextGlyphs_System_e8aaa0_bitmap[]; // 誠
extern const u32 TextGlyphs_System_e58f8d_bitmap[]; // 反
extern const u32 TextGlyphs_System_e6ad93_bitmap[]; // 歓
extern const u32 TextGlyphs_System_e983b7_bitmap[]; // 郷
extern const u32 TextGlyphs_System_e381a0_bitmap[]; // だ
extern const u32 TextGlyphs_System_e6b288_bitmap[]; // 沈
extern const u32 TextGlyphs_System_e8a880_bitmap[]; // 言
extern const u32 TextGlyphs_System_e6988e_bitmap[]; // 明
extern const u32 TextGlyphs_System_e5a4aa_bitmap[]; // 太
extern const u32 TextGlyphs_System_e5be97_bitmap[]; // 得
extern const u32 TextGlyphs_System_e8aa93_bitmap[]; // 誓
extern const u32 TextGlyphs_System_e6b197_bitmap[]; // 汗
extern const u32 TextGlyphs_System_e796be_bitmap[]; // 疾
extern const u32 TextGlyphs_System_e381a1_bitmap[]; // ち
extern const u32 TextGlyphs_System_e79b9f_bitmap[]; // 盟
extern const u32 TextGlyphs_System_e8b3aa_bitmap[]; // 質
extern const u32 TextGlyphs_System_e8ab8b_bitmap[]; // 請
extern const u32 TextGlyphs_System_e69f84_bitmap[]; // 柄
extern const u32 TextGlyphs_System_e4bea1_bitmap[]; // 価
extern const u32 TextGlyphs_System_e69699_bitmap[]; // 料
extern const u32 TextGlyphs_System_e99fbf_bitmap[]; // 響
extern const u32 TextGlyphs_System_e381a2_bitmap[]; // ぢ
extern const u32 TextGlyphs_System_e5ae89_bitmap[]; // 安
extern const u32 TextGlyphs_System_e5baa7_bitmap[]; // 座
extern const u32 TextGlyphs_System_e8bfb7_bitmap[]; // 迷
extern const u32 TextGlyphs_System_e99990_bitmap[]; // 限
extern const u32 TextGlyphs_System_e5ae9f_bitmap[]; // 実
extern const u32 TextGlyphs_System_e9809d_bitmap[]; // 逝
extern const u32 TextGlyphs_System_e381a3_bitmap[]; // っ
extern const u32 TextGlyphs_System_e58aa0_bitmap[]; // 加
extern const u32 TextGlyphs_System_e6b688_bitmap[]; // 消
extern const u32 TextGlyphs_System_e789b9_bitmap[]; // 特
extern const u32 TextGlyphs_System_e381a4_bitmap[]; // つ
extern const u32 TextGlyphs_System_e58faf_bitmap[]; // 可
extern const u32 TextGlyphs_System_e5808b_bitmap[]; // 個
extern const u32 TextGlyphs_System_e78c9f_bitmap[]; // 猟
extern const u32 TextGlyphs_System_e99689_bitmap[]; // 閉
extern const u32 TextGlyphs_System_e6b889_bitmap[]; // 渉
extern const u32 TextGlyphs_System_e99d92_bitmap[]; // 青
extern const u32 TextGlyphs_System_e381a5_bitmap[]; // づ
extern const u32 TextGlyphs_System_ceb5_bitmap[]; // ε
extern const u32 TextGlyphs_System_e69a97_bitmap[]; // 暗
extern const u32 TextGlyphs_System_e58fa4_bitmap[]; // 古
extern const u32 TextGlyphs_System_e9999b_bitmap[]; // 陛
extern const u32 TextGlyphs_System_e5a7aa_bitmap[]; // 姪
extern const u32 TextGlyphs_System_e79498_bitmap[]; // 甘
extern const u32 TextGlyphs_System_e99d99_bitmap[]; // 静
extern const u32 TextGlyphs_System_e381a6_bitmap[]; // て
extern const u32 TextGlyphs_System_e5868d_bitmap[]; // 再
extern const u32 TextGlyphs_System_e784bc_bitmap[]; // 焼
extern const u32 TextGlyphs_System_e591bc_bitmap[]; // 呼
extern const u32 TextGlyphs_System_e6a188_bitmap[]; // 案
extern const u32 TextGlyphs_System_e7899d_bitmap[]; // 牝
extern const u32 TextGlyphs_System_e381a7_bitmap[]; // で
extern const u32 TextGlyphs_System_e69c80_bitmap[]; // 最
extern const u32 TextGlyphs_System_e7a88e_bitmap[]; // 税
extern const u32 TextGlyphs_System_e6bb85_bitmap[]; // 滅
extern const u32 TextGlyphs_System_e68993_bitmap[]; // 打
extern const u32 TextGlyphs_System_e99787_bitmap[]; // 闇
extern const u32 TextGlyphs_System_e5ab81_bitmap[]; // 嫁
extern const u32 TextGlyphs_System_e59bba_bitmap[]; // 固
extern const u32 TextGlyphs_System_e6af92_bitmap[]; // 毒
extern const u32 TextGlyphs_System_e784a6_bitmap[]; // 焦
extern const u32 TextGlyphs_System_e381a8_bitmap[]; // と
extern const u32 TextGlyphs_System_e5aeb6_bitmap[]; // 家
extern const u32 TextGlyphs_System_e78bac_bitmap[]; // 独
extern const u32 TextGlyphs_System_e6a5ad_bitmap[]; // 業
extern const u32 TextGlyphs_System_e381a9_bitmap[]; // ど
extern const u32 TextGlyphs_System_e5a19e_bitmap[]; // 塞
extern const u32 TextGlyphs_System_e8bfbd_bitmap[]; // 追
extern const u32 TextGlyphs_System_e5ada4_bitmap[]; // 孤
extern const u32 TextGlyphs_System_e889af_bitmap[]; // 良
extern const u32 TextGlyphs_System_e5b180_bitmap[]; // 局
extern const u32 TextGlyphs_System_e7aea1_bitmap[]; // 管
extern const u32 TextGlyphs_System_e5a381_bitmap[]; // 壁
extern const u32 TextGlyphs_System_e5afa1_bitmap[]; // 寡
extern const u32 TextGlyphs_System_e381aa_bitmap[]; // な
extern const u32 TextGlyphs_System_e4bba5_bitmap[]; // 以
extern const u32 TextGlyphs_System_e5a6bb_bitmap[]; // 妻
extern const u32 TextGlyphs_System_e7b0a1_bitmap[]; // 簡
extern const u32 TextGlyphs_System_e5b7b1_bitmap[]; // 己
extern const u32 TextGlyphs_System_e381ab_bitmap[]; // に
extern const u32 TextGlyphs_System_e7979b_bitmap[]; // 痛
extern const u32 TextGlyphs_System_e6839c_bitmap[]; // 惜
extern const u32 TextGlyphs_System_e5aeb0_bitmap[]; // 宰
extern const u32 TextGlyphs_System_e6a5b5_bitmap[]; // 極
extern const u32 TextGlyphs_System_e381ac_bitmap[]; // ぬ
extern const u32 TextGlyphs_System_e4bd8d_bitmap[]; // 位
extern const u32 TextGlyphs_System_e58699_bitmap[]; // 写
extern const u32 TextGlyphs_System_e78e89_bitmap[]; // 玉
extern const u32 TextGlyphs_System_e69e9c_bitmap[]; // 果
extern const u32 TextGlyphs_System_e588a5_bitmap[]; // 別
extern const u32 TextGlyphs_System_e99da2_bitmap[]; // 面
extern const u32 TextGlyphs_System_e9809a_bitmap[]; // 通
extern const u32 TextGlyphs_System_e9878f_bitmap[]; // 量
extern const u32 TextGlyphs_System_e381ad_bitmap[]; // ね
extern const u32 TextGlyphs_System_e6898d_bitmap[]; // 才
extern const u32 TextGlyphs_System_e7aa81_bitmap[]; // 突
extern const u32 TextGlyphs_System_e5b084_bitmap[]; // 射
extern const u32 TextGlyphs_System_e381ae_bitmap[]; // の
extern const u32 TextGlyphs_System_e9a098_bitmap[]; // 領
extern const u32 TextGlyphs_System_e58189_bitmap[]; // 偉
extern const u32 TextGlyphs_System_e69894_bitmap[]; // 昔
extern const u32 TextGlyphs_System_e4bd93_bitmap[]; // 体
extern const u32 TextGlyphs_System_e7a7b0_bitmap[]; // 称
extern const u32 TextGlyphs_System_e68da8_bitmap[]; // 捨
extern const u32 TextGlyphs_System_e6ad8c_bitmap[]; // 歌
extern const u32 TextGlyphs_System_e69585_bitmap[]; // 故
extern const u32 TextGlyphs_System_e381af_bitmap[]; // は
extern const u32 TextGlyphs_System_e58a9b_bitmap[]; // 力
extern const u32 TextGlyphs_System_e59bb2_bitmap[]; // 囲
extern const u32 TextGlyphs_System_e7aba0_bitmap[]; // 章
extern const u32 TextGlyphs_System_e6a8a1_bitmap[]; // 模
extern const u32 TextGlyphs_System_e6b2b3_bitmap[]; // 河
extern const u32 TextGlyphs_System_e8b5a6_bitmap[]; // 赦
extern const u32 TextGlyphs_System_e381b0_bitmap[]; // ば
extern const u32 TextGlyphs_System_e79fb3_bitmap[]; // 石
extern const u32 TextGlyphs_System_e781ab_bitmap[]; // 火
extern const u32 TextGlyphs_System_e5afbe_bitmap[]; // 対
extern const u32 TextGlyphs_System_e7b791_bitmap[]; // 緑
extern const u32 TextGlyphs_System_e7ac91_bitmap[]; // 笑
extern const u32 TextGlyphs_System_e6b996_bitmap[]; // 湖
extern const u32 TextGlyphs_System_e381b1_bitmap[]; // ぱ
extern const u32 TextGlyphs_System_e5a489_bitmap[]; // 変
extern const u32 TextGlyphs_System_e5a794_bitmap[]; // 委
extern const u32 TextGlyphs_System_e7a98d_bitmap[]; // 積
extern const u32 TextGlyphs_System_e6b888_bitmap[]; // 済
extern const u32 TextGlyphs_System_e381b2_bitmap[]; // ひ
extern const u32 TextGlyphs_System_e781bd_bitmap[]; // 災
extern const u32 TextGlyphs_System_e5a881_bitmap[]; // 威
extern const u32 TextGlyphs_System_e78987_bitmap[]; // 片
extern const u32 TextGlyphs_System_e8ab8c_bitmap[]; // 諌
extern const u32 TextGlyphs_System_e5a29f_bitmap[]; // 墟
extern const u32 TextGlyphs_System_e381b3_bitmap[]; // び
extern const u32 TextGlyphs_System_e5b8af_bitmap[]; // 帯
extern const u32 TextGlyphs_System_e69e97_bitmap[]; // 林
extern const u32 TextGlyphs_System_e7b8be_bitmap[]; // 績
extern const u32 TextGlyphs_System_e6af9b_bitmap[]; // 毛
extern const u32 TextGlyphs_System_e381b4_bitmap[]; // ぴ
extern const u32 TextGlyphs_System_e88085_bitmap[]; // 者
extern const u32 TextGlyphs_System_e5be85_bitmap[]; // 待
extern const u32 TextGlyphs_System_e78c9b_bitmap[]; // 猛
extern const u32 TextGlyphs_System_e98284_bitmap[]; // 還
extern const u32 TextGlyphs_System_e7b7a8_bitmap[]; // 編
extern const u32 TextGlyphs_System_e7a8bc_bitmap[]; // 稼
extern const u32 TextGlyphs_System_e381b5_bitmap[]; // ふ
extern const u32 TextGlyphs_System_e8beba_bitmap[]; // 辺
extern const u32 TextGlyphs_System_e6848f_bitmap[]; // 意
extern const u32 TextGlyphs_System_e8b2ac_bitmap[]; // 責
extern const u32 TextGlyphs_System_e7a095_bitmap[]; // 砕
extern const u32 TextGlyphs_System_e8ac9d_bitmap[]; // 謝
extern const u32 TextGlyphs_System_e381b6_bitmap[]; // ぶ
extern const u32 TextGlyphs_System_e7a0a6_bitmap[]; // 砦
extern const u32 TextGlyphs_System_e99693_bitmap[]; // 間
extern const u32 TextGlyphs_System_e8b5a4_bitmap[]; // 赤
extern const u32 TextGlyphs_System_e8bf94_bitmap[]; // 返
extern const u32 TextGlyphs_System_e8bb8a_bitmap[]; // 車
extern const u32 TextGlyphs_System_e6858b_bitmap[]; // 態
extern const u32 TextGlyphs_System_e795aa_bitmap[]; // 番
extern const u32 TextGlyphs_System_e88ab1_bitmap[]; // 花
extern const u32 TextGlyphs_System_e5b1af_bitmap[]; // 屯
extern const u32 TextGlyphs_System_e381b7_bitmap[]; // ぷ
extern const u32 TextGlyphs_System_e7a5ad_bitmap[]; // 祭
extern const u32 TextGlyphs_System_e69893_bitmap[]; // 易
extern const u32 TextGlyphs_System_e8b7a1_bitmap[]; // 跡
extern const u32 TextGlyphs_System_e887a8_bitmap[]; // 臨
extern const u32 TextGlyphs_System_e8998e_bitmap[]; // 虎
extern const u32 TextGlyphs_System_e381b8_bitmap[]; // へ
extern const u32 TextGlyphs_System_e8aa87_bitmap[]; // 誇
extern const u32 TextGlyphs_System_e996a2_bitmap[]; // 関
extern const u32 TextGlyphs_System_e4bebf_bitmap[]; // 便
extern const u32 TextGlyphs_System_e7a681_bitmap[]; // 禁
extern const u32 TextGlyphs_System_e8bcaa_bitmap[]; // 輪
extern const u32 TextGlyphs_System_e69bbf_bitmap[]; // 替
extern const u32 TextGlyphs_System_e381b9_bitmap[]; // べ
extern const u32 TextGlyphs_System_e99aa3_bitmap[]; // 隣
extern const u32 TextGlyphs_System_e982aa_bitmap[]; // 邪
extern const u32 TextGlyphs_System_e58b89_bitmap[]; // 勉
extern const u32 TextGlyphs_System_e7b4b0_bitmap[]; // 細
extern const u32 TextGlyphs_System_e999a5_bitmap[]; // 陥
extern const u32 TextGlyphs_System_e782ba_bitmap[]; // 為
extern const u32 TextGlyphs_System_e88db7_bitmap[]; // 荷
extern const u32 TextGlyphs_System_e381ba_bitmap[]; // ぺ
extern const u32 TextGlyphs_System_e7ad8b_bitmap[]; // 筋
extern const u32 TextGlyphs_System_e58887_bitmap[]; // 切
extern const u32 TextGlyphs_System_e89bae_bitmap[]; // 蛮
extern const u32 TextGlyphs_System_e5809f_bitmap[]; // 借
extern const u32 TextGlyphs_System_e8a8bc_bitmap[]; // 証
extern const u32 TextGlyphs_System_e69ca8_bitmap[]; // 木
extern const u32 TextGlyphs_System_e381bb_bitmap[]; // ほ
extern const u32 TextGlyphs_System_e9bb99_bitmap[]; // 黙
extern const u32 TextGlyphs_System_e795b0_bitmap[]; // 異
extern const u32 TextGlyphs_System_e99b87_bitmap[]; // 雇
extern const u32 TextGlyphs_System_e8838e_bitmap[]; // 胎
extern const u32 TextGlyphs_System_e5bc81_bitmap[]; // 弁
extern const u32 TextGlyphs_System_e9a4a8_bitmap[]; // 館
extern const u32 TextGlyphs_System_e88f93_bitmap[]; // 菓
extern const u32 TextGlyphs_System_e381bc_bitmap[]; // ぼ
extern const u32 TextGlyphs_System_e79bae_bitmap[]; // 目
extern const u32 TextGlyphs_System_e7a7bb_bitmap[]; // 移
extern const u32 TextGlyphs_System_e68ea5_bitmap[]; // 接
extern const u32 TextGlyphs_System_e58d91_bitmap[]; // 卑
extern const u32 TextGlyphs_System_e9a1a7_bitmap[]; // 顧
extern const u32 TextGlyphs_System_e8a9b3_bitmap[]; // 詳
extern const u32 TextGlyphs_System_e381bd_bitmap[]; // ぽ
extern const u32 TextGlyphs_System_e4bf9d_bitmap[]; // 保
extern const u32 TextGlyphs_System_e590a6_bitmap[]; // 否
extern const u32 TextGlyphs_System_e7b6ad_bitmap[]; // 維
extern const u32 TextGlyphs_System_e381be_bitmap[]; // ま
extern const u32 TextGlyphs_System_e8b39e_bitmap[]; // 賞
extern const u32 TextGlyphs_System_e781bc_bitmap[]; // 灼
extern const u32 TextGlyphs_System_e6b699_bitmap[]; // 涙
extern const u32 TextGlyphs_System_e5a683_bitmap[]; // 妃
extern const u32 TextGlyphs_System_e4ba94_bitmap[]; // 五
extern const u32 TextGlyphs_System_e381bf_bitmap[]; // み
extern const u32 TextGlyphs_System_e5b2b8_bitmap[]; // 岸
extern const u32 TextGlyphs_System_e788b5_bitmap[]; // 爵
extern const u32 TextGlyphs_System_e8b2a8_bitmap[]; // 貨
extern const u32 TextGlyphs_System_e59ca8_bitmap[]; // 在
extern const u32 TextGlyphs_System_e8a8ad_bitmap[]; // 設
extern const u32 TextGlyphs_System_e9888d_bitmap[]; // 鈍
extern const u32 TextGlyphs_System_e8b2b8_bitmap[]; // 貸
extern const u32 TextGlyphs_System_e38280_bitmap[]; // む
extern const u32 TextGlyphs_System_e5bdbc_bitmap[]; // 彼
extern const u32 TextGlyphs_System_e98080_bitmap[]; // 退
extern const u32 TextGlyphs_System_e9a19e_bitmap[]; // 類
extern const u32 TextGlyphs_System_e5b7ab_bitmap[]; // 巫
extern const u32 TextGlyphs_System_e38281_bitmap[]; // め
extern const u32 TextGlyphs_System_e8bf91_bitmap[]; // 近
extern const u32 TextGlyphs_System_e68d95_bitmap[]; // 捕
extern const u32 TextGlyphs_System_e682b2_bitmap[]; // 悲
extern const u32 TextGlyphs_System_e7bdaa_bitmap[]; // 罪
extern const u32 TextGlyphs_System_e4bba4_bitmap[]; // 令
extern const u32 TextGlyphs_System_e7af80_bitmap[]; // 節
extern const u32 TextGlyphs_System_e688bb_bitmap[]; // 戻
extern const u32 TextGlyphs_System_e9818e_bitmap[]; // 過
extern const u32 TextGlyphs_System_e8a1a3_bitmap[]; // 衣
extern const u32 TextGlyphs_System_e38282_bitmap[]; // も
extern const u32 TextGlyphs_System_e58685_bitmap[]; // 内
extern const u32 TextGlyphs_System_e8b2a1_bitmap[]; // 財
extern const u32 TextGlyphs_System_e98791_bitmap[]; // 金
extern const u32 TextGlyphs_System_e99a8a_bitmap[]; // 隊
extern const u32 TextGlyphs_System_e6ada9_bitmap[]; // 歩
extern const u32 TextGlyphs_System_e8aaac_bitmap[]; // 説
extern const u32 TextGlyphs_System_e68989_bitmap[]; // 扉
extern const u32 TextGlyphs_System_e38283_bitmap[]; // ゃ
extern const u32 TextGlyphs_System_e88ba5_bitmap[]; // 若
extern const u32 TextGlyphs_System_e79cbc_bitmap[]; // 眼
extern const u32 TextGlyphs_System_e4bd8e_bitmap[]; // 低
extern const u32 TextGlyphs_System_e8a394_bitmap[]; // 裔
extern const u32 TextGlyphs_System_e99a9c_bitmap[]; // 障
extern const u32 TextGlyphs_System_e5909f_bitmap[]; // 吟
extern const u32 TextGlyphs_System_e99baa_bitmap[]; // 雪
extern const u32 TextGlyphs_System_e4be8b_bitmap[]; // 例
extern const u32 TextGlyphs_System_e38284_bitmap[]; // や
extern const u32 TextGlyphs_System_e7b5b6_bitmap[]; // 絶
extern const u32 TextGlyphs_System_e98a80_bitmap[]; // 銀
extern const u32 TextGlyphs_System_e586b7_bitmap[]; // 冷
extern const u32 TextGlyphs_System_e5b2a9_bitmap[]; // 岩
extern const u32 TextGlyphs_System_e981ba_bitmap[]; // 遺
extern const u32 TextGlyphs_System_e5958f_bitmap[]; // 問
extern const u32 TextGlyphs_System_e5819c_bitmap[]; // 停
extern const u32 TextGlyphs_System_e38285_bitmap[]; // ゅ
extern const u32 TextGlyphs_System_e5be8c_bitmap[]; // 後
extern const u32 TextGlyphs_System_e4b88a_bitmap[]; // 上
extern const u32 TextGlyphs_System_e4bba3_bitmap[]; // 代
extern const u32 TextGlyphs_System_e5bcb1_bitmap[]; // 弱
extern const u32 TextGlyphs_System_e8888c_bitmap[]; // 舌
extern const u32 TextGlyphs_System_e4b99d_bitmap[]; // 九
extern const u32 TextGlyphs_System_e38286_bitmap[]; // ゆ
extern const u32 TextGlyphs_System_e7b48b_bitmap[]; // 紋
extern const u32 TextGlyphs_System_e8ac8e_bitmap[]; // 謎
extern const u32 TextGlyphs_System_e5bea1_bitmap[]; // 御
extern const u32 TextGlyphs_System_e68891_bitmap[]; // 我
extern const u32 TextGlyphs_System_e58fb0_bitmap[]; // 台
extern const u32 TextGlyphs_System_e4b888_bitmap[]; // 丈
extern const u32 TextGlyphs_System_e38287_bitmap[]; // ょ
extern const u32 TextGlyphs_System_e5a4a7_bitmap[]; // 大
extern const u32 TextGlyphs_System_e4b8bb_bitmap[]; // 主
extern const u32 TextGlyphs_System_e99680_bitmap[]; // 門
extern const u32 TextGlyphs_System_e78999_bitmap[]; // 牙
extern const u32 TextGlyphs_System_e58b9f_bitmap[]; // 募
extern const u32 TextGlyphs_System_e6829f_bitmap[]; // 悟
extern const u32 TextGlyphs_System_e38288_bitmap[]; // よ
extern const u32 TextGlyphs_System_e58f96_bitmap[]; // 取
extern const u32 TextGlyphs_System_e59f9f_bitmap[]; // 域
extern const u32 TextGlyphs_System_e58588_bitmap[]; // 先
extern const u32 TextGlyphs_System_e7acac_bitmap[]; // 第
extern const u32 TextGlyphs_System_e5a293_bitmap[]; // 墓
extern const u32 TextGlyphs_System_e4b997_bitmap[]; // 乗
extern const u32 TextGlyphs_System_e794bb_bitmap[]; // 画
extern const u32 TextGlyphs_System_e38289_bitmap[]; // ら
extern const u32 TextGlyphs_System_e5ae88_bitmap[]; // 守
extern const u32 TextGlyphs_System_e58d83_bitmap[]; // 千
extern const u32 TextGlyphs_System_e7a4bc_bitmap[]; // 礼
extern const u32 TextGlyphs_System_e9a194_bitmap[]; // 顔
extern const u32 TextGlyphs_System_e882b2_bitmap[]; // 育
extern const u32 TextGlyphs_System_e58697_bitmap[]; // 冗
extern const u32 TextGlyphs_System_e592b2_bitmap[]; // 咲
extern const u32 TextGlyphs_System_e3828a_bitmap[]; // り
extern const u32 TextGlyphs_System_e58da0_bitmap[]; // 占
extern const u32 TextGlyphs_System_e9a198_bitmap[]; // 願
extern const u32 TextGlyphs_System_e6898b_bitmap[]; // 手
extern const u32 TextGlyphs_System_e5ae9a_bitmap[]; // 定
extern const u32 TextGlyphs_System_e9a18c_bitmap[]; // 題
extern const u32 TextGlyphs_System_e3828b_bitmap[]; // る
extern const u32 TextGlyphs_System_e5b89d_bitmap[]; // 帝
extern const u32 TextGlyphs_System_e59f8e_bitmap[]; // 城
extern const u32 TextGlyphs_System_e7a798_bitmap[]; // 秘
extern const u32 TextGlyphs_System_e69aae_bitmap[]; // 暮
extern const u32 TextGlyphs_System_e5aea3_bitmap[]; // 宣
extern const u32 TextGlyphs_System_e5a49c_bitmap[]; // 夜
extern const u32 TextGlyphs_System_e3828c_bitmap[]; // れ
extern const u32 TextGlyphs_System_e88ba6_bitmap[]; // 苦
extern const u32 TextGlyphs_System_e5a0b4_bitmap[]; // 場
extern const u32 TextGlyphs_System_e6af8d_bitmap[]; // 母
extern const u32 TextGlyphs_System_e99ab7_bitmap[]; // 隷
extern const u32 TextGlyphs_System_e8aa9e_bitmap[]; // 語
extern const u32 TextGlyphs_System_e6ae8a_bitmap[]; // 殊
extern const u32 TextGlyphs_System_e4b880_bitmap[]; // 一
extern const u32 TextGlyphs_System_e5ba95_bitmap[]; // 底
extern const u32 TextGlyphs_System_e5b082_bitmap[]; // 専
extern const u32 TextGlyphs_System_e3828d_bitmap[]; // ろ
extern const u32 TextGlyphs_System_e58db1_bitmap[]; // 危
extern const u32 TextGlyphs_System_e99b85_bitmap[]; // 雅
extern const u32 TextGlyphs_System_e78ba9_bitmap[]; // 狩
extern const u32 TextGlyphs_System_e8aaa4_bitmap[]; // 誤
extern const u32 TextGlyphs_System_e58d97_bitmap[]; // 南
extern const u32 TextGlyphs_System_e5969c_bitmap[]; // 喜
extern const u32 TextGlyphs_System_e9878e_bitmap[]; // 野
extern const u32 TextGlyphs_System_e5bbb7_bitmap[]; // 廷
extern const u32 TextGlyphs_System_e9a786_bitmap[]; // 駆
extern const u32 TextGlyphs_System_e8adb7_bitmap[]; // 護
extern const u32 TextGlyphs_System_e4bd9c_bitmap[]; // 作
extern const u32 TextGlyphs_System_e5b79d_bitmap[]; // 川
extern const u32 TextGlyphs_System_e99c8a_bitmap[]; // 霊
extern const u32 TextGlyphs_System_e3828f_bitmap[]; // わ
extern const u32 TextGlyphs_System_e688a6_bitmap[]; // 戦
extern const u32 TextGlyphs_System_e5bc9f_bitmap[]; // 弟
extern const u32 TextGlyphs_System_e7a8ae_bitmap[]; // 種
extern const u32 TextGlyphs_System_e599a8_bitmap[]; // 器
extern const u32 TextGlyphs_System_e8a2ab_bitmap[]; // 被
extern const u32 TextGlyphs_System_e580a3_bitmap[]; // 倣
extern const u32 TextGlyphs_System_e5898a_bitmap[]; // 削
extern const u32 TextGlyphs_System_e5b8b8_bitmap[]; // 常
extern const u32 TextGlyphs_System_e68385_bitmap[]; // 情
extern const u32 TextGlyphs_System_e79fa2_bitmap[]; // 矢
extern const u32 TextGlyphs_System_e59fba_bitmap[]; // 基
extern const u32 TextGlyphs_System_e7a8b2_bitmap[]; // 稲
extern const u32 TextGlyphs_System_e4bc9a_bitmap[]; // 会
extern const u32 TextGlyphs_System_e58c85_bitmap[]; // 包
extern const u32 TextGlyphs_System_e99ba3_bitmap[]; // 難
extern const u32 TextGlyphs_System_e585b7_bitmap[]; // 具
extern const u32 TextGlyphs_System_e68ab5_bitmap[]; // 抵
extern const u32 TextGlyphs_System_e69aa6_bitmap[]; // 暦
extern const u32 TextGlyphs_System_e5a587_bitmap[]; // 奇
extern const u32 TextGlyphs_System_e38292_bitmap[]; // を
extern const u32 TextGlyphs_System_e8a7a3_bitmap[]; // 解
extern const u32 TextGlyphs_System_e6adb4_bitmap[]; // 歴
extern const u32 TextGlyphs_System_e68a9e_bitmap[]; // 択
extern const u32 TextGlyphs_System_e5bdb9_bitmap[]; // 役
extern const u32 TextGlyphs_System_e4baa4_bitmap[]; // 交
extern const u32 TextGlyphs_System_e69da1_bitmap[]; // 条
extern const u32 TextGlyphs_System_e981bf_bitmap[]; // 避
extern const u32 TextGlyphs_System_e6b19d_bitmap[]; // 汝
extern const u32 TextGlyphs_System_e98592_bitmap[]; // 酒
extern const u32 TextGlyphs_System_e38293_bitmap[]; // ん
extern const u32 TextGlyphs_System_e69d96_bitmap[]; // 杖
extern const u32 TextGlyphs_System_e59b9e_bitmap[]; // 回
extern const u32 TextGlyphs_System_e99d9e_bitmap[]; // 非
extern const u32 TextGlyphs_System_e5a0b1_bitmap[]; // 報
extern const u32 TextGlyphs_System_e7b484_bitmap[]; // 約
extern const u32 TextGlyphs_System_e68b93_bitmap[]; // 拓
extern const u32 TextGlyphs_System_e5af84_bitmap[]; // 寄
extern const u32 TextGlyphs_System_e9a696_bitmap[]; // 首
extern const u32 TextGlyphs_System_e4ba8c_bitmap[]; // 二
extern const u32 TextGlyphs_System_e9a39b_bitmap[]; // 飛
extern const u32 TextGlyphs_System_e4beaf_bitmap[]; // 侯
extern const u32 TextGlyphs_System_e58aa3_bitmap[]; // 劣
extern const u32 TextGlyphs_System_e78ab6_bitmap[]; // 状
extern const u32 TextGlyphs_System_e5ae9d_bitmap[]; // 宝
extern const u32 TextGlyphs_System_e58f97_bitmap[]; // 受
extern const u32 TextGlyphs_System_e7a9ba_bitmap[]; // 空
extern const u32 TextGlyphs_System_e5a38a_bitmap[]; // 壊
extern const u32 TextGlyphs_System_e58db0_bitmap[]; // 印
extern const u32 TextGlyphs_System_e5b88c_bitmap[]; // 希
extern const u32 TextGlyphs_System_e8a8b3_bitmap[]; // 訳
extern const u32 TextGlyphs_System_e78388_bitmap[]; // 烈
extern const u32 TextGlyphs_System_e591aa_bitmap[]; // 呪
extern const u32 TextGlyphs_System_e8a382_bitmap[]; // 裂
extern const u32 TextGlyphs_System_e8ba8d_bitmap[]; // 躍
extern const u32 TextGlyphs_System_e58299_bitmap[]; // 備
extern const u32 TextGlyphs_System_e58589_bitmap[]; // 光
extern const u32 TextGlyphs_System_e593a1_bitmap[]; // 員
extern const u32 TextGlyphs_System_e8a897_bitmap[]; // 託
extern const u32 TextGlyphs_System_e5bfab_bitmap[]; // 快
extern const u32 TextGlyphs_System_e58c82_bitmap[]; // 匂
extern const u32 TextGlyphs_System_e585ac_bitmap[]; // 公
extern const u32 TextGlyphs_System_e68fae_bitmap[]; // 揮
extern const u32 TextGlyphs_System_e6818b_bitmap[]; // 恋
extern const u32 TextGlyphs_System_e5b4a9_bitmap[]; // 崩
extern const u32 TextGlyphs_System_e68e88_bitmap[]; // 授
extern const u32 TextGlyphs_System_e680aa_bitmap[]; // 怪
extern const u32 TextGlyphs_System_e59ba0_bitmap[]; // 因
extern const u32 TextGlyphs_System_e7a88b_bitmap[]; // 程
extern const u32 TextGlyphs_System_e68294_bitmap[]; // 悔
extern const u32 TextGlyphs_System_e88289_bitmap[]; // 肉
extern const u32 TextGlyphs_System_e58a9f_bitmap[]; // 功
extern const u32 TextGlyphs_System_e5beae_bitmap[]; // 微
extern const u32 TextGlyphs_System_e68690_bitmap[]; // 憐
extern const u32 TextGlyphs_System_e58ab9_bitmap[]; // 効
extern const u32 TextGlyphs_System_e5bc95_bitmap[]; // 引
extern const u32 TextGlyphs_System_e69797_bitmap[]; // 旗
extern const u32 TextGlyphs_System_e68ab1_bitmap[]; // 抱
extern const u32 TextGlyphs_System_e5a5a2_bitmap[]; // 奢
extern const u32 TextGlyphs_System_e6978b_bitmap[]; // 旋
extern const u32 TextGlyphs_System_e9a3b2_bitmap[]; // 飲
extern const u32 TextGlyphs_System_e697a5_bitmap[]; // 日
extern const u32 TextGlyphs_System_e694be_bitmap[]; // 放
extern const u32 TextGlyphs_System_e69c9f_bitmap[]; // 期
extern const u32 TextGlyphs_System_e6aa84_bitmap[]; // 檄
extern const u32 TextGlyphs_System_e59b9a_bitmap[]; // 囚
extern const u32 TextGlyphs_System_e58e9a_bitmap[]; // 厚
extern const u32 TextGlyphs_System_e696b9_bitmap[]; // 方
extern const u32 TextGlyphs_System_e68b90_bitmap[]; // 拐
extern const u32 TextGlyphs_System_e58fa3_bitmap[]; // 口
extern const u32 TextGlyphs_System_e6b2b9_bitmap[]; // 油
extern const u32 TextGlyphs_System_e7b7b4_bitmap[]; // 練
extern const u32 TextGlyphs_System_e585a5_bitmap[]; // 入
extern const u32 TextGlyphs_System_e59091_bitmap[]; // 向
extern const u32 TextGlyphs_System_e7be8e_bitmap[]; // 美
extern const u32 TextGlyphs_System_e5b188_bitmap[]; // 屈
extern const u32 TextGlyphs_System_e694b9_bitmap[]; // 改
extern const u32 TextGlyphs_System_e7b79a_bitmap[]; // 線
extern const u32 TextGlyphs_System_e591a8_bitmap[]; // 周
