#include "heroes.h"
#include "hero_jobs.h"
#include "debugchapter.h"

#include "constants/iids.h"
#include "constants/jids.h"

const struct UnitInfo DebugBlueUnits[] = {
    {
        .pid = PID_アルフォンス,
        .jid = JID_アルフォンス_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_シャロン,
        .jid = JID_シャロン_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_アンナ,
        .jid = JID_アンナ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = EID_ヴェロニカ,
        .jid = JID_ヴェロニカ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_レギン,
        .jid = JID_レギン_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = EID_ブルーノ,
        .jid = JID_ブルーノ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_神階ピアニー,
        .jid = JID_神階ピアニー_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_セイズ,
        .jid = JID_セイズ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_フィヨルム,
        .jid = JID_フィヨルム_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = PID_神階エイル,
        .jid = JID_神階エイル_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_レティシア,
        .jid = JID_レティシア_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_オッテル,
        .jid = JID_オッテル_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_ファフニール,
        .jid = JID_ファフニール_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_フレイヤ,
        .jid = JID_フレイヤ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_スルト,
        .jid = JID_スルト_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = PID_アシュ,
        .jid = JID_アシュ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = PID_神階アスク,
        .jid = JID_神階アスク_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_リーヴ,
        .jid = JID_リーヴ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_レーギャルン,
        .jid = JID_レーギャルン_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_ダグ,
        .jid = JID_ダグ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_エイトリ,
        .jid = JID_エイトリ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_レーヴァテイン,
        .jid = JID_レーヴァテイン_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_ヘル,
        .jid = JID_ヘル_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_エンブラ,
        .jid = JID_エンブラ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_ネルトゥス,
        .jid = JID_ネルトゥス_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_グスタフ,
        .jid = JID_グスタフ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = PID_ユルグ,
        .jid = JID_ユルグ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = PID_愛の祭ヘンリエッテ,
        .jid = JID_愛の祭ヘンリエッテ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_ロキ,
        .jid = JID_ロキ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_ノート,
        .jid = JID_ノート_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_スカビオサ,
        .jid = JID_スカビオサ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_エルム,
        .jid = JID_エルム_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_ヘルビンディ,
        .jid = JID_ヘルビンディ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_フロージ,
        .jid = JID_フロージ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = PID_神階ルピナス,
        .jid = JID_神階ルピナス_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_グルヴェイグ,
        .jid = JID_グルヴェイグ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = PID_フリーズ,
        .jid = JID_フリーズ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_プルメリア,
        .jid = JID_プルメリア_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_クワシル,
        .jid = JID_クワシル_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = PID_神階ヘイズ,
        .jid = JID_神階ヘイズ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_スラシル,
        .jid = JID_スラシル_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 5,
        .y_move = 5,
    },

    {
        .pid = PID_マークス,
        .jid = JID_マークス_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 5,
        .y_move = 5,
    },

    {
        .pid = PID_スリーズ,
        .jid = JID_スリーズ_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 5,
        .y_move = 5,
    },

    {
        .pid = EID_フード,
        .jid = JID_フード_PROMOTED,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 5,
        .y_move = 5,
    },

    {
    }
};
