#include "heroes.h"
#include "hero_jobs.h"
#include "debugchapter.h"

#include "constants/iids.h"
#include "constants/jids.h"

const struct UnitInfo DebugBlueUnits[] = {
    {
        .pid = PID_アルフォンス,
        .jid = JID_アルフォンス,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_シャロン,
        .jid = JID_シャロン,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_アンナ,
        .jid = JID_アンナ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = EID_ヴェロニカ,
        .jid = JID_ヴェロニカ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_レギン,
        .jid = JID_レギン,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = EID_ブルーノ,
        .jid = JID_ブルーノ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_神階ピアニー,
        .jid = JID_神階ピアニー,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_フィヨルム,
        .jid = JID_フィヨルム,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 0,
        .y_move = 0,
    },

    {
        .pid = PID_神階エイル,
        .jid = JID_神階エイル,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_レティシア,
        .jid = JID_レティシア,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_オッテル,
        .jid = JID_オッテル,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_ファフニール,
        .jid = JID_ファフニール,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_フレイヤ,
        .jid = JID_フレイヤ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = PID_セイズ,
        .jid = JID_セイズ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = EID_スルト,
        .jid = JID_スルト,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = PID_アシュ,
        .jid = JID_アシュ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 1,
        .y_move = 1,
    },

    {
        .pid = PID_神階アスク,
        .jid = JID_神階アスク,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_リーヴ,
        .jid = JID_リーヴ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_レーギャルン,
        .jid = JID_レーギャルン,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_ダグ,
        .jid = JID_ダグ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_エイトリ,
        .jid = JID_エイトリ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_レーヴァテイン,
        .jid = JID_レーヴァテイン,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_ヘル,
        .jid = JID_ヘル,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_エンブラ,
        .jid = JID_エンブラ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 2,
        .y_move = 2,
    },

    {
        .pid = EID_グスタフ,
        .jid = JID_グスタフ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = PID_ユルグ,
        .jid = JID_ユルグ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_ロキ,
        .jid = JID_ロキ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_ノート,
        .jid = JID_ノート,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_スカビオサ,
        .jid = JID_スカビオサ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_エルム,
        .jid = JID_エルム,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_ヘルビンディ,
        .jid = JID_ヘルビンディ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = EID_フロージ,
        .jid = JID_フロージ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 3,
        .y_move = 3,
    },

    {
        .pid = PID_神階ルピナス,
        .jid = JID_神階ルピナス,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_ヴェロニカ洗脳,
        .jid = JID_ヴェロニカ洗脳,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = PID_フリーズ,
        .jid = JID_フリーズ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_プルメリア,
        .jid = JID_プルメリア,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 6,
        .x_move = 6,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_スラシル,
        .jid = JID_スラシル,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 8,
        .x_move = 8,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_グルヴェイグ,
        .jid = JID_グルヴェイグ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 10,
        .x_move = 10,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_ネルトゥス,
        .jid = JID_ネルトゥス,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRESTONE,
            IID_DIVINESTONE,
            IID_DEMONSTONE,
            IID_DARKBREATH,
        },
        .x_load = 12,
        .x_move = 12,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = PID_マークス,
        .jid = JID_マークス,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 14,
        .x_move = 14,
        .y_load = 4,
        .y_move = 4,
    },

    {
        .pid = EID_レティシア洗脳,
        .jid = JID_レティシア洗脳,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 0,
        .x_move = 0,
        .y_load = 5,
        .y_move = 5,
    },

    {
        .pid = PID_スリーズ,
        .jid = JID_スリーズ,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_FIRE,
            IID_LIGHTNING,
            IID_FLUX,
            IID_HEALSTAFF,
        },
        .x_load = 2,
        .x_move = 2,
        .y_load = 5,
        .y_move = 5,
    },

    {
        .pid = EID_フード,
        .jid = JID_フード,
        .pid_lead = PID_アルフォンス,
        .level = DEBUG_BLUE_UNIT_LEVEL,
        .autolevel = DEBUG_BLUE_UNIT_AUTOLEVEL,
        .items = {
            IID_IRONSWORD,
            IID_IRONLANCE,
            IID_IRONAXE,
            IID_IRONBOW,
        },
        .x_load = 4,
        .x_move = 4,
        .y_load = 5,
        .y_move = 5,
    },

    {
    }
};
