name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install python dependencies
      run: apt-get update && apt-get install -y python3-pip && pip3 install numpy

    - name: Build tools
      run: ./build_tools.sh

    - name: Mock base ROM
      run: head -c 8M /dev/urandom > baserom.gba

    - name: Run make
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: linker-mapfile
        path: FEHRR.map
