name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install python dependencies
      run: apt-get update && apt-get install -y python3-pip && pip3 install numpy

    - name: Build tools
      run: ./build_tools.sh

    - name: Download, extract and check base ROM
      env:
        BASEROM_URL: ${{ secrets.BASEROM_URL }}
      run: |
        curl -LO "$BASEROM_URL" && unzip baserom.zip && ./check_baserom.sh

    - name: Run make
      run: make

    - name: Check ROM size
      run: apt-get install -y bc && ./check_rom_size.sh

    - name: Create UPS patch
      uses: actions/setup-go@v5
      with:
        go-version: '1.16'
    - run: git config --global --add safe.directory /__w/FEHRR/FEHRR && go get github.com/rameshvarun/ups && ./create_ups_patch.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ github.repository }}-${{ github.event.repository.pushed_at }}-${{ github.run_id }}-${{ github.sha }}
        path: |
          FEHRR.ups
          FEHRR.map
          FEHRR.png
          FEHRR.updateinfo.txt
          README.md
